//>>built
define("ec/fisa/widget/tsc/EditableOptionsTree","dojo/_base/declare dojo/_base/kernel dojo/dom-construct dojo/_base/array dijit/Tree dijit/Menu ec/fisa/widget/DialogSimple ec/fisa/dwr/Store ec/fisa/dwr/proxy/tsc/MenuEditionAdminControllerDWR dojo/data/ItemFileWriteStore dijit/tree/dndSource ec/fisa/dwr/TreeStoreModel ec/fisa/widget/ConfirmDialog ./_base".split(" "),function(m,f,q,l,n,p){return m("ec.fisa.widget.tsc.EditableOptionsTree",[n],{tabId:"",pageScopeId:"",copyOnly:!0,selfAccept:!1,_selectedNode:null,
showRoot:!1,isForQY:!1,additionalParams:[],dialogIdByItemId:{},newItemsId:[],isDeletedItems:!1,isModifyOption:!1,isNewItem:!1,labelsData:null,selectedItem:null,parentSelectedItem:null,movedItemsIdByOldParent:{},movedItemsId:[],itemData:{},updatedItems:{},domNodes:{},dndParams:[],dndController:"dijit.tree.dndSource",postMixInProperties:function(){this.inherited(arguments);this.store=new ec.fisa.dwr.Store("MenuEditionAdminControllerDWR","viewEditableTransacctions",this.tabId,this.pageScopeId,this.additionalParams,
null);this.store.fastFetchItemByIdentity=!1;this.store.updateMsgsPanel=this.updateMessages;this.store.setCallbackScope(this.store);this.model=new ec.fisa.dwr.TreeStoreModel({childrenAttrs:["items"],labelAttr:"name",query:{},store:this.store,onChildrenChange:f.hitch(this,function(a,c){this.displayOnDropPopup(a,c)}),sendNewItem:f.hitch(this,function(a){this.newItemsId.push(a)}),sendMovedItem:f.hitch(this,function(a,c){if(!0===this.store.getValue(c,"editableTreeItem")){var b=this.movedItemsIdByOldParent[a];
void 0===b&&(b=[],this.movedItemsIdByOldParent[a]=b);b.push(c);this.movedItemsId.push(c)}else delete this.movedItemsId,this.movedItemsIdByOldParent={},this.movedItemsId=[]})});this.dragThreshold=8;this.betweenThreshold=5;this.persist=!1;this.isForQY||(this.dndParams="onDndDrop itemCreator onDndCancel checkAcceptance checkItemAcceptance dragThreshold betweenThreshold deleteSelectedNodes".split(" "))},postCreate:function(){var a=this.store.getAdditionalParams();a[0]=this.getChannelValue();this.store.setAdditionalParams(a);
this.inherited(arguments)},updateMessages:function(a){var c=ec.fisa.controller.utils.getPageController(this.tabId,this.gridStoreId),b=c.globalMessagePanelId;void 0!==b||null!=b?(c.setMessagesPanel(dijit.byId(b)),c.updateMsgsPanel(a)):c.setPenddingMessages(a)},checkAcceptance:function(a,c){return!0},checkItemAcceptance:function(a,c,b){this.leafSwitch=!1;if("before"==b||"after"==b)return!1;a=dijit.byId(a.parentNode.id).item;b=this.tree.store;if("ITEM_QUERY_TEMPLATE"===b.getValue(a,"type")||"BUSINESS_TEMPLATE"===
b.getValue(a,"type")||"BUSINESS_TEMPLATE_CUSTOMIZED"===b.getValue(a,"type"))return!1;if(!0===b.getValue(a,"leaf"))return this.leafSwitch=!0;a=c.tree.selectedItem;c=c.tree.store;return!1===c.getValue(a,"leaf")?!0===c.getValue(a,"editableTreeItem")?!0:!1:!0},deleteSelectedNodes:function(){return!0},getIconClass:function(a){return!a?"itemFolder":!0===this.store.getValue(a,"leaf")?"ITEM_QUERY_TEMPLATE"==this.store.getValue(a,"type")?"qtIconMenu":"itemLeaf":"ITEM_QUERY_TEMPLATE"==this.store.getValue(a,
"type")?"qtIconMenu":"BUSINESS_TEMPLATE"==this.store.getValue(a,"type")||"BUSINESS_TEMPLATE_CUSTOMIZED"==this.store.getValue(a,"type")?"itemLeaf":"itemFolder"},deleteItem:function(a,c){this.isDeletedItems=!0;this.model.deleteItem(a,c)},startup:function(){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){for(var d=b||0,e=this.length;d<e;d++)if(this[d]==a)return d;return-1});MenuEditionAdminControllerDWR.getScreenLabels({callbackScope:this,callback:function(a){this.labelsData=a},errorHandler:f.hitch(this,
this.errorHandler)});if(!this.isForQY){var a=new p;a.addChild(new dijit.MenuItem({iconClass:"dijitIcon dijitIconEdit",type:"M",onClick:f.hitch(this,function(){this.displayModifyItemDialog()})}));a.addChild(new dijit.MenuItem({iconClass:"dijitIcon dijitIconNewTask",type:"AF",onClick:f.hitch(this,function(){var a=this.selectedItem;this.isNewItem=!0;this.displayNewFolderDialog(a)})}));a.addChild(new dijit.MenuItem({iconClass:"dijitIcon dijitIconTask",type:"AU",onClick:f.hitch(this,function(){var a=this.selectedItem;
this.isNewItem=!0;this.displayExternalURLDialog(a)})}));a.addChild(new dijit.MenuItem({iconClass:"dijitIcon dijitIconDelete",type:"D",onClick:f.hitch(this,function(){(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:this.labelsData.yesLabel,cancelDialogLabel:this.labelsData.noLabel,title:this.labelsData.deleteMenuLabel,content:this.labelsData.deleteNodeWarnLabel,acceptAction:f.hitch(this,function(){this.deleteItem(this.selectedItem,this.parentSelectedItem)})})).show()})}));a.bindDomNode(this.id);
a.connect(a,"_openMyself",function(c){var b=dijit.getEnclosingWidget(c.target).lastFocused,d=b.item;if(void 0!==d){c=b.tree.store.getEntryById(d).data;b.tree.selectedItem=d;b.tree.parentSelectedItem=b.getParent().item;var e=b.tree.labelsData;f.forEach(a.getChildren(),function(a){a.set("style","display: block");var b=a.params.type;"M"==b?a.set("label",e.modifyMenuLabel):"AF"==b?a.set("label",e.addFolderMenuLabel):"AU"==b?a.set("label",e.addURLMenuLabel):"D"==b&&a.set("label",e.deleteMenuLabel)});b=
c.type;"MENU_CONTAINER"==b?f.forEach(a.getChildren(),function(a){var b=a.params.type;("M"==b||"D"==b||"AU"==b)&&a.set("style","display: none")}):"ITEM_QUERY_TEMPLATE"==b||"BUSINESS_TEMPLATE"==b||"BUSINESS_TEMPLATE_CUSTOMIZED"==b?f.forEach(a.getChildren(),function(a){"AU"==a.params.type&&a.set("style","display: none")}):c.leaf&&f.forEach(a.getChildren(),function(a){var b=a.params.type;("AF"==b||"AU"==b)&&a.set("style","display: none")})}else f.forEach(a.getChildren(),function(a){a.set("style","display: none")})})}},
displayOnDropPopup:function(a,c){if(this.isDeletedItems)this.isDeletedItems=!1,this.removeNewItemsIdList(c);else if(this.isNewItem)this.isNewItem=!1,this.removeNewItemsIdList(c);else if(this.isModifyOption)this.idModifyOption=!1,this.removeNewItemsIdList(c);else{var b=!1,d=this.movedItemsIdByOldParent[a];void 0!==d&&0<d.length&&(b=!0,delete d,delete this.movedItemsIdByOldParent,this.movedItemsIdByOldParent={});if(!b){var e,b=0;a:for(;b<this.newItemsId.length;b++)for(d=0;d<c.length;d++)if(c[d]==this.newItemsId[b]){e=
this.newItemsId[b];break a}this.removeArr(this.newItemsId,e);var h=!1;f.forEach(this.movedItemsId,function(a){a==e&&(h=!0)});if(h)this.removeArr(this.movedItemsId,e);else if(b=this.store.getEntryById(e).data,!0==b.leaf){for(var g in b)"undefined"!==typeof g&&(d=b[g],null!=d&&(this.itemData[e+"_"+g]=d,"name"==g&&(this.itemData[e+"_nameI18n"]=d)));this.displayItemNodeInformationDialog(b,a)}}}},onClick:function(a){if(!this.isForQY){var c=this.store.getEntryById(a).data;if("MENU_CONTAINER"==c.type){var b=
new ec.fisa.widget.DialogSimple({title:this.labelsData.rootMenuLabel,style:"width: 800px",href:"static/tsc/newMenuFolder.jsp",ioMethod:f.xhrPost,editTreeId:this.id,preventCache:!0,ioArgs:{content:{tabId:this.tabId,pageScopeId:this.pageScopeId,editTreeId:this.id,itemId:a,modify:!1,newFolder:!1,changeMainMenuName:!0}},onCancel:function(){var a=dijit.byId(this.editTreeId);a.isModifyOption=!1;a.isNewItem=!1;a.itemData={};this.destroy()}}),d;for(d in c)if("undefined"!==typeof d){var e=c[d];null!=e&&(this.itemData[a+
"_"+d]=e)}b.show();this.dialogIdByItemId[a]=b.id}}},displayItemNodeInformationDialog:function(a,c){var b=!0,d=!0,e=!1,h="",g=a.type;"ITEM_QUERY_TEMPLATE"==g?(b=!1,h=this.labelsData.addQueryTemplateLabel):"BUSINESS_TEMPLATE"==g?h=this.labelsData.addBusinessTemplateLabel:"BUSINESS_TEMPLATE_CUSTOMIZED"==g?(e=!0,h=this.labelsData.addCustomBusinessLabel):"BUSINESS_TEMPLATE_URL"==g?(b=!1,h=this.labelsData.addURLBusinessLabel):"ITEM_LAYOUT_TEMPLATE"==g&&(d=b=!1,h=this.labelsData.addLayoutTemplateLabel);
b=new ec.fisa.widget.DialogSimple({title:h,style:"width: 800px",href:"static/tsc/menuItemInformation.jsp",ioMethod:f.xhrPost,editTreeId:this.id,itemId:a.id,parentId:c,preventCache:!0,ioArgs:{content:{tabId:this.tabId,pageScopeId:this.pageScopeId,itemId:a.id,editTreeId:this.id,displayParameterField:b,changeParameterFieldType:e,displayRoutineField:d}},onCancel:function(){var a=dijit.byId(this.editTreeId);a.isModifyOption||a.deleteItem(this.itemId,this.parentId);a.isModifyOption=!1;this.destroy()}});
b.show();this.dialogIdByItemId[a.id]=b.id},displayNewFolderDialog:function(a){var c=new ec.fisa.widget.DialogSimple({title:this.labelsData.folderLabel,style:"width: 800px",href:"static/tsc/newMenuFolder.jsp",ioMethod:f.xhrPost,editTreeId:this.id,preventCache:!0,ioArgs:{content:{tabId:this.tabId,pageScopeId:this.pageScopeId,editTreeId:this.id,itemId:a,modify:this.isModifyOption,newFolder:this.isNewItem,changeMainMenuName:!1}},onCancel:function(){var a=dijit.byId(this.editTreeId);a.isModifyOption=!1;
a.isNewItem=!1;this.destroy()}});c.show();this.dialogIdByItemId[a]=c.id},displayModifyItemDialog:function(){this.isModifyOption=!0;var a=this.selectedItem,c=this.store.getEntryById(a).data,b;for(b in c)if("undefined"!==typeof b){var d=c[b];null!=d&&(this.itemData[a+"_"+b]=d)}b=c.type;"EXTERNAL_FOLDER"==b?this.displayNewFolderDialog(a):"EXTERNAL_URL"==b?this.displayExternalURLDialog(a):this.displayItemNodeInformationDialog(c)},displayExternalURLDialog:function(a){var c=new ec.fisa.widget.DialogSimple({title:this.labelsData.externalURLLabel,
style:"width: 800px",href:"static/tsc/externalURL.jsp",ioMethod:f.xhrPost,editTreeId:this.id,preventCache:!0,ioArgs:{content:{tabId:this.tabId,pageScopeId:this.pageScopeId,editTreeId:this.id,itemId:a,modify:this.isModifyOption,newItem:this.isNewItem}},onCancel:function(){var a=dijit.byId(this.editTreeId);a.isModifyOption=!1;a.isNewItem=!1;this.destroy()}});c.show();this.dialogIdByItemId[a]=c.id},removeArr:function(a){for(var c,b=arguments,d=b.length,e;1<d&&a.length;)for(c=b[--d];-1!==(e=a.indexOf(c));)a.splice(e,
1);return a},removeNewItemsIdList:function(a){for(var c=0;c<this.newItemsId.length;c++)for(var b=0;b<a.length;b++)a[b]==this.newItemsId[c]&&this.removeArr(this.newItemsId,a[b])},setItemData:function(a){this.itemData=a},getDomNodeById:function(a){return this._itemNodesMap[a][0].domNode},constructDomNodesArr:function(){this.domNodes={};var a=this._itemNodesMap;this._fillDomNodesArr(a[this.model.root][0],a)},_fillDomNodesArr:function(a,c){var b=this.store.getEntryById(a.params.item);void 0!=b&&(items=
b.data.items);a.setChildItems(items);items&&0<items.length&&l.forEach(items,function(a){this._fillDomNodesArr(c[a][0],c)},this)},getChannelValue:function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);return dijit.byId(a.channelComboId).get("value")},onDndDrop:function(a,c,b){if(!0==this.leafSwitch){if("Over"==this.containerState){var d=this.tree.model,e=this.targetAnchor;this.isDragging=!1;var f=e.getIndexInParent(),g=a.getItem(c[0].id),e=null;if(-1!=l.indexOf(g.type,
"treeNode")){var k=g.data,g=k.item,e=k.getParent().item;d.pasteItem(g,e,e,!1,f,void 0);f=k.getIndexInParent();d.pasteItem(g,e,e,!1,f,void 0)}}}else this.inherited(arguments)}})});
//@ sourceMappingURL=EditableOptionsTree.js.map