//>>built
define("ec/fisa/widget/tsc/MicroRouteTree","dojo/_base/declare dojo/_base/kernel dojo/dom-construct dojo/_base/array dijit/Tree ec/fisa/format/Utils dojo/dom dojo/_base/lang dojo/data/ItemFileWriteStore dojox/grid/DataGrid dijit/form/Button dijit/Menu ec/fisa/dwr/Store ec/fisa/dwr/proxy/UserHomeAdminDWR dojo/data/ItemFileWriteStore dijit/tree/dndSource ec/fisa/dwr/TreeStoreModel ./_base".split(" "),function(q,g,t,u,r,v,w,y,p,z,A,s){return q("ec.fisa.widget.tsc.MicroRouteTree",[r],{tabId:"",pageScopeId:"",
actionId:"",copyOnly:!0,selfAccept:!1,_selectedNode:null,showRoot:!1,controller:"",method:"",elementChildList:null,elementAttributeList:null,gridLayout:null,attrGridData:null,attrGridDataList:null,attrGridStore:null,attrGrid:null,itemData:{},panelAttributes:null,dataTableGeneratedId:null,buttonDataTableId:null,dataTableAttributesMap:null,dndParams:"onDndDrop itemCreator onDndCancel checkAcceptance checkItemAcceptance dragThreshold betweenThreshold deleteSelectedNodes".split(" "),dndController:"dijit.tree.dndSource",
postMixInProperties:function(){this.inherited(arguments);this.store=new ec.fisa.dwr.Store(this.controller,this.method,this.tabId,this.pageScopeId,[],null);this.store.fastFetchItemByIdentity=!1;this.model=new ec.fisa.dwr.TreeStoreModel({childrenAttrs:["items"],labelAttr:"name",query:{},store:this.store,onChildrenChange:g.hitch(this,function(a,e){var b=this.store;0<e.length&&g.forEach(e,function(a){b.setValue(b._entries[a].itemId,"name",b._entries[a].data.name);this.createInitialAttributesTable();g.style(dijit.byId(this.buttonDataTableId).domNode,
{display:"none"})},this)})});this.dragThreshold=8;this.betweenThreshold=5;this.persist=!1;this.elementChildList=[];this.elementAttributeList=[];this.dataTableAttributesMap=[];this.getElementAttributeData();this.checkItemTreeAceptance()},startup:function(){var a=new s;a.addChild(new dijit.MenuItem({iconClass:"dijitIcon dijitIconDelete",type:"D",onClick:g.hitch(this,function(){var a=this.tree.store._entries[this.lastFocused.item],b=!1;a&&"root"==a.data.elementId&&(b=!0);!b&&("IN"==this.actionId||"UP"==
this.actionId)&&(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:"Yes",cancelDialogLabel:"No",title:"Eliminar",content:"Desea Eliminar el Elemento?",acceptAction:g.hitch(this,function(){var a=this.lastFocused.item,b=this.lastFocused.getParent().item;this.deleteItem(a,b)})})).show()})}));a.bindDomNode(this.id)},checkAcceptance:function(a,e){return!0},checkItemAcceptance:function(a,e,b){var f=dijit.getEnclosingWidget(a);a=f.item;var c=this.tree.store;a=c._entries[a].data.elementId;var d=e.tree.selectedItem,
g=c._entries[d];e=null;e=g?g.data.elementId:d.split("_")[2];if("root"==a&&("before"==b||"after"==b))return!1;if("before"==b||"after"==b)a=f.getParent().item,a=c._entries[a].data.elementId;b=!1;f=this.tree.elementChildList;for(x in f)if(a==x){c=f[x];for(j=0;j<c.length;j++)c[j]==e&&(b=!0)}return b},deleteSelectedNodes:function(){return!0},checkItemTreeAceptance:function(){MicroRouteControllerDWR.getMicroRouteElements({callbackScope:this,callback:function(a){this.fillChildListOptions(a)},errorHandler:this.errorHandler})},
fillChildListOptions:function(a){this.elementChildList=a},errorHandler:function(a){alert("errorHandler "+a)},getElementAttributeData:function(){MicroRouteControllerDWR.getAttributesGroupByElement({callbackScope:this,callback:function(a){this.fillElementAttributeList(a)},errorHandler:this.errorHandler})},fillElementAttributeList:function(a){this.elementAttributeList=a},displayOndropAttributesTable:function(a,e){var b=[];for(x in this.elementAttributeList)if(x==a)for(var f=this.elementAttributeList[x],
c=0;c<f.length;c++){var d=f[c].split("_");b.push({id:(c+1).toString(),type:x.toString(),attr:d[0].toString(),widget:"",isLabel:d[1]})}this.attrGridData.items=b;this.attrGridStore=new p({data:this.attrGridData});f=this.tree.store._entries[e];c=dijit.byId(this.dataTableGeneratedId);c.setStore(this.attrGridStore);dijit.byId(this.buttonDataTableId).treeItem=f;c.parentTreeId=this.tree.id;0<b.length?g.style(dijit.byId(this.buttonDataTableId).domNode,{display:"block"}):g.style(dijit.byId(this.buttonDataTableId).domNode,
{display:"none"})},createInitialAttributesTable:function(){this.attrGridData={identifier:"id",label:"type",items:[]};this.attrGridStore=new p({data:this.attrGridData});this.gridLayout="IN"==this.actionId||"UP"==this.actionId?[{name:"Propiedad",field:"attr",editable:!1,width:"40%"},{name:"Valor",field:"widget",width:"60%",editable:!1,cellType:dojox.grid.cells._Widget,widgetClass:dijit.layout.ContentPane,formatter:function(a,b,f){return ec.fisa.format.utils.formatPropertyTextBox(a,b,f,!1)}}]:[{name:"Propiedad",
field:"attr",editable:!1,width:"40%"},{name:"Valor",field:"widget",width:"60%",editable:!1,cellType:dojox.grid.cells._Widget,widgetClass:dijit.form.TextBox,formatter:function(a,b,f){return ec.fisa.format.utils.formatPropertyTextBox(a,b,f,!0)}}];var a=dijit.byId(this.dataTableGeneratedId);a.setStore(this.attrGridStore);a.setStructure(this.gridLayout);a.autoHeight=!0},setDataTableGeneratedId:function(a){this.dataTableGeneratedId=a;this.createInitialAttributesTable()},setButtonDataTableId:function(a){this.buttonDataTableId=
a},onClick:function(a){var e=this.tree.store,b=e._entries[a],f=b.data.properties,c=this.elementAttributeList[b.data.elementId],d=b.updates,k=[];for(attribute in d){var h=attribute.split("_"),l=h[0],h=h[1],n=parseInt(h)+1;"attributeId"==l&&(h={id:n,type:b.data.name,attr:d[attribute],widget:d["attributeValue_".concat(h)],isLabel:d["isLabel_".concat(h)]},k.push(h))}if(0==k.length&&c)for(d=0;d<c.length;d++){var h=c[d].split("_"),l=h[0],n=h[1],m="";null!=f&&(m=f[l],null==m&&(m=""));h={id:(d+1).toString(),
type:a.toString(),attr:l,widget:m,isLabel:n};k.push(h);e.setValue(b.itemId,"attributeId_"+d,l);e.setValue(b.itemId,"attributeValue_"+d,m);e.setValue(b.itemId,"isLabel_"+d,n)}a=dijit.byId(this.dataTableGeneratedId);this.attrGridData.items=k;this.attrGridStore=new p({data:this.attrGridData});a.setStore(this.attrGridStore);null!=this.buttonDataTableId&&(dijit.byId(this.buttonDataTableId).treeItem=b,a.parentTreeId=this.tree.id,0<k.length?g.style(dijit.byId(this.buttonDataTableId).domNode,{display:"block"}):
g.style(dijit.byId(this.buttonDataTableId).domNode,{display:"none"}))},deleteItem:function(a,e){this.isDeletedItems=!0;this.model.deleteItem(a,e);this.createInitialAttributesTable();g.style(dijit.byId(this.buttonDataTableId).domNode,{display:"none"})},getIconClass:function(a){return a&&(a=this.tree.store._entries[a].data.elementId)?a="class_".concat(a):"class_generic"},setItemData:function(a){this.itemData=a}})});
//@ sourceMappingURL=MicroRouteTree.js.map