//>>built
define("ec/fisa/widget/tsc/ProcessRouteTree","dojo/_base/declare dojo/_base/kernel dojo/dom-construct dojo/_base/array dijit/Tree ec/fisa/format/Utils dojo/dom dojo/_base/lang dojo/data/ItemFileWriteStore dojox/grid/DataGrid dijit/form/Button dijit/Menu ec/fisa/dwr/Store ec/fisa/dwr/proxy/UserHomeAdminDWR dojo/data/ItemFileWriteStore dijit/tree/dndSource ec/fisa/dwr/TreeStoreModel ./_base".split(" "),function(q,h,t,u,r,v,w,y,p,z,A,s){return q("ec.fisa.widget.tsc.ProcessRouteTree",[r],{tabId:"",pageScopeId:"",
actionId:"",copyOnly:!0,selfAccept:!1,_selectedNode:null,showRoot:!1,controller:"",method:"",elementChildList:null,elementAttributeList:null,gridLayout:null,attrGridData:null,attrGridDataList:null,attrGridStore:null,attrGrid:null,itemData:{},panelAttributes:null,dataTableGeneratedId:null,buttonDataTableId:null,dataTableAttributesMap:null,dndParams:"onDndDrop itemCreator onDndCancel checkAcceptance checkItemAcceptance dragThreshold betweenThreshold deleteSelectedNodes".split(" "),dndController:"dijit.tree.dndSource",
postMixInProperties:function(){this.inherited(arguments);this.store=new ec.fisa.dwr.Store(this.controller,this.method,this.tabId,this.pageScopeId,[],null);this.store.fastFetchItemByIdentity=!1;this.model=new ec.fisa.dwr.TreeStoreModel({childrenAttrs:["items"],labelAttr:"name",query:{},store:this.store,onChildrenChange:h.hitch(this,function(a,d){var b=this.store;0<d.length&&h.forEach(d,function(a){b.setValue(b._entries[a].itemId,"name",b._entries[a].data.name);this.createInitialAttributesTable();h.style(dijit.byId(this.buttonDataTableId).domNode,
{display:"none"})},this)})});this.dragThreshold=8;this.betweenThreshold=5;this.persist=!1;this.elementChildList=[];this.elementAttributeList=[];this.dataTableAttributesMap=[];this.getElementAttributeData();this.checkItemTreeAceptance()},startup:function(){var a=new s;a.addChild(new dijit.MenuItem({iconClass:"dijitIcon dijitIconDelete",type:"D",onClick:h.hitch(this,function(){var a=this.tree.store._entries[this.lastFocused.item],b=!1;a&&"root"==a.data.elementId&&(b=!0);!b&&("IN"==this.actionId||"UP"==
this.actionId)&&(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:"Yes",cancelDialogLabel:"No",title:"Eliminar",content:"Desea Eliminar el Elemento?",acceptAction:h.hitch(this,function(){var a=this.lastFocused.item,b=this.lastFocused.getParent().item;this.deleteItem(a,b)})})).show()})}));a.bindDomNode(this.id)},checkAcceptance:function(a,d){return!0},checkItemAcceptance:function(a,d,b){var g=!1,e=dijit.getEnclosingWidget(a);a=e.item;var c=this.tree.store;a=c._entries[a].data.elementId;var h=d.tree.selectedItem,
f=c._entries[h];d=null;d=f?f.data.elementId:h.split("_")[2];if(("rule"==a||"root"==a)&&("before"==b||"after"==b))return!1;if("before"==b||"after"==b)a=e.getParent().item,a=c._entries[a].data.elementId;b=this.tree.elementChildList;"rule"==a&&(a="root");for(x in b)if(a==x){e=b[x];for(j=0;j<e.length;j++)e[j]==d&&(g=!0)}return g},deleteSelectedNodes:function(){return!0},checkItemTreeAceptance:function(){ProcessRouteControllerDWR.getProcessRouteElements({callbackScope:this,callback:function(a){this.fillChildListOptions(a)},
errorHandler:this.errorHandler})},fillChildListOptions:function(a){this.elementChildList=a},errorHandler:function(a){alert("errorHandler "+a)},getElementAttributeData:function(){ProcessRouteControllerDWR.getAttributesGroupByElement({callbackScope:this,callback:function(a){this.fillElementAttributeList(a)},errorHandler:this.errorHandler})},fillElementAttributeList:function(a){this.elementAttributeList=a},displayOndropAttributesTable:function(a,d){var b=[];for(x in this.elementAttributeList)if(x==a)for(var g=
this.elementAttributeList[x],e=0;e<g.length;e++){var c=g[e].split("_");b.push({id:(e+1).toString(),type:x.toString(),attr:c[0].toString(),widget:"",isLabel:c[1]})}this.attrGridData.items=b;this.attrGridStore=new p({data:this.attrGridData});g=this.tree.store._entries[d];e=dijit.byId(this.dataTableGeneratedId);e.parentTreeId=this.tree.id;e.setStore(this.attrGridStore);null!=this.buttonDataTableId&&(dijit.byId(this.buttonDataTableId).treeItem=g,0<b.length?h.style(dijit.byId(this.buttonDataTableId).domNode,
{display:"block"}):h.style(dijit.byId(this.buttonDataTableId).domNode,{display:"none"}))},createInitialAttributesTable:function(){this.attrGridData={identifier:"id",label:"type",items:[]};this.attrGridStore=new p({data:this.attrGridData});this.gridLayout="IN"==this.actionId||"UP"==this.actionId?[{name:"Propiedad",field:"attr",editable:!1,width:"150px"},{name:"Valor",field:"widget",width:"250px",editable:!1,cellType:dojox.grid.cells._Widget,widgetClass:dijit.form.TextBox,formatter:function(a,b,g){return ec.fisa.format.utils.formatPropertyTextBox(a,
b,g,!1)}}]:[{name:"Propiedad",field:"attr",editable:!1,width:"150px"},{name:"Valor",field:"widget",width:"250px",editable:!1,cellType:dojox.grid.cells._Widget,widgetClass:dijit.form.TextBox,formatter:function(a,b,g){return ec.fisa.format.utils.formatPropertyTextBox(a,b,g,!0)}}];var a=dijit.byId(this.dataTableGeneratedId);a.setStore(this.attrGridStore);a.setStructure(this.gridLayout);a.autoHeight=!0},setDataTableGeneratedId:function(a){this.dataTableGeneratedId=a;this.createInitialAttributesTable()},
setButtonDataTableId:function(a){this.buttonDataTableId=a},onClick:function(a){var d=this.tree.store,b=d._entries[a],g=b.data.properties,e=this.elementAttributeList[b.data.elementId],c=b.updates,k=[];for(attribute in c){var f=attribute.split("_"),l=f[0],f=f[1],n=parseInt(f)+1;"attributeId"==l&&(f={id:n,type:b.data.name,attr:c[attribute],widget:c["attributeValue_".concat(f)],isLabel:c["isLabel_".concat(f)]},k.push(f))}if(0==k.length&&e)for(c=0;c<e.length;c++){var f=e[c].split("_"),l=f[0],n=f[1],m=
"";null!=g&&(m=g[l],null==m&&(m=""));f={id:(c+1).toString(),type:a.toString(),attr:l,widget:m,isLabel:n};k.push(f);d.setValue(b.itemId,"attributeId_"+c,l);d.setValue(b.itemId,"attributeValue_"+c,m);d.setValue(b.itemId,"isLabel_"+c,n)}a=dijit.byId(this.dataTableGeneratedId);this.attrGridData.items=k;this.attrGridStore=new p({data:this.attrGridData});a.setStore(this.attrGridStore);null!=this.buttonDataTableId&&(dijit.byId(this.buttonDataTableId).treeItem=b,a.parentTreeId=this.tree.id,0<k.length?h.style(dijit.byId(this.buttonDataTableId).domNode,
{display:"block"}):h.style(dijit.byId(this.buttonDataTableId).domNode,{display:"none"}))},deleteItem:function(a,d){this.isDeletedItems=!0;this.model.deleteItem(a,d);this.createInitialAttributesTable();h.style(dijit.byId(this.buttonDataTableId).domNode,{display:"none"})},getIconClass:function(a){return a&&(a=this.tree.store._entries[a].data.elementId)?a="class_".concat(a):"class_generic"},setItemData:function(a){this.itemData=a}})});
//@ sourceMappingURL=ProcessRouteTree.js.map