//>>built
define("ec/fisa/mobile/format/Utils","dojo/_base/kernel dojo/_base/declare dojo/on dojo/date/locale dojo/dom-construct ec/fisa/mobile/format/_base ec/fisa/mobile/widget/Link".split(" "),function(m,p,w,u,v,r,q){p=p("ec.fisa.mobile.format.Utils",null,{JDBCtimestampFormat:"yyyy-MM-dd HH:mm:ss.S",formatQtColumn:function(a,e,c,b,l,k,d,g,f){f=f||{};try{if(isNaN(a)){var h="";null!=c&&(h=c);return h}if(1==a||2==a||3==a){if(null==c)return"";var p=ec.fisa.mobile.format.utils.parseLongDate(c);return u.format(p,
{datePattern:e,selector:"date",locale:m.config.fisaCurrentLocale})}if(4==a||6==a||5==a)return null==c?"":ec.fisa.mobile.format.utils.formatNumber(c,e);if(8==a)return null==c?"":"0"==c?'\x3cinput type\x3d"checkbox" disabled\x3d"true" disabled\x3d"true"  /\x3e':'\x3cinput type\x3d"checkbox" disabled\x3d"true" checked\x3d"checked" /\x3e';if(26==a)return null==c||"0"==c||""==c?"":'\x3cspan class\x3d"qtCellChecked"/\x3e';if(27==a){if(null==c||"0"==c||""==c)return"";var s=m.config.fisaContextPath+"/imageNotFound.jpg";
return'\x3cimg src\x3d"'+(m.config.fisaContextPath+"/fisaImages/"+c)+'"  alt\x3d"'+k+'" title\x3d"'+k+'" onerror\x3d"'+("this.src \x3d '"+s+"'")+'" width\x3d"14" height\x3d"14"  /\x3e'}if(0>a){var n={fakeBtn:{fc:ec.fisa.controller.utils.getPageController(d,g),fisatabid:d,fisapageid:g},fisaScopeSelectedId:b,fisaScopeSelectedAction:l,onClick:function(){this.fakeBtn.fc.executeAction.call(this.fakeBtn,!1,this.fisaScopeSelectedAction,this.fisaScopeSelectedId)}};if(-1==a)return n.title=k||"",n.label=c||
"",h=new q(n);if(-3==a)return n.title=k||"",n.label=e||"",new q(n);if(-2==a)return h=new q(n),s=m.config.fisaContextPath+"/imageNotFound.jpg",v.create("img",{src:e,alt:k,title:k,onerror:"this.src \x3d '"+s+"'",style:{display:"block",margin:"auto"}},h.containerNode),h;if(-4==a){var t={fieldId:f.fieldId,tabId:d,pageScopeId:g,valueToFormat:c,rowIndex:b,colDef:f.colDef,routine:f.routine};return ec.fisa.mobile.format.utils.formatQueryTemplateFieldLink(t)}if(-5==a)return t={fieldId:f.fieldId,tabId:d,pageScopeId:g,
valueToFormat:c,rowIndex:b,gridId:f.colDef.grid.id,colDef:f.colDef,originalValueIndex:f.colDef.grid.originalValueIndex,maskId:e},ec.fisa.format.utils.formatQueryTemplateFieldAliasLink(t)}}catch(r){}return c},parseLongDate:function(a){if(null!=a){var e=a.lastIndexOf(".");0<=e&&a.length>=e+2?a=a.substring(0,e+2):0<=e&&a.length>=e+1&&(a=a.substring(0,e+1)+"0")}return u.parse(a,{datePattern:this.JDBCtimestampFormat,selector:"date",locale:m.config.fisaCurrentLocale})},formatNumber:function(a,e){if(null==
a||""===a||void 0===a)return"";"number"!=typeof a&&(a=number.parse(a,{locale:"en"}));if(isNaN(a))return"";var c="";0>a&&(c="-");var b=0,l=m.config.decimalSeparator,k=m.config.groupSeparator;if(e&&0<e.length){var d=e.indexOf(l);-1<d&&(b=e.substring(d+1).length)}var g=e.split(l),f=b,d=String(Math.abs(a)).split("."),h=d[1]||"";g[1]||options.places?(b=void 0!==b?b:g[1]&&g[1].lastIndexOf("0")+1,b>h.length&&(d[1]=dstring.pad(h,b,"0",!0)),f<h.length&&(d[1]=h.substr(0,f))):d[1]&&d.pop();f=g[0].replace(l,
"");b=f.indexOf("0");-1!=b&&(b=f.length-b,b>d[0].length&&(d[0]=dstring.pad(d[0],b)),-1==f.indexOf("#")&&(d[0]=d[0].substr(d[0].length-b)));g[0].lastIndexOf(k);g=[];for(b=d[0];b;)f=b.length-3,g.push(0<f?b.substr(f):b),b=0<f?b.slice(0,f):"";d[0]=g.reverse().join(k);l=d.join(l);return c+l},formatQueryTemplateFieldLink:function(a){var e=a.valueToFormat;return e&&"0"!==e?new q({fieldId:a.fieldId,fisatabid:a.tabId,fisapageid:a.pageScopeId,rowIndex:a.rowIndex,label:a.valueToFormat,routine:a.routine}):a.valueToFormat}});
r.utils=new p;ec.fisa.mobile.format.utils=r.utils;return p});
//@ sourceMappingURL=Utils.js.map