//>>built
define("ec/fisa/controller/security/ChangeCredentialsController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController dojo/dom-construct ec/fisa/message/ConfirmationPanel ec/fisa/mvc/StatefulModel ./_base ec/fisa/widget/security/Keyboard".split(" "),function(d,f,l,g,e,h,k){return f("ec.fisa.controller.security.ChangeCredentialsController",g,{tabId:null,pageScopeId:null,keyboardId:null,currentPasswordId:null,newPasswordId:null,newPasswordConfirmId:null,breadcrumbId:null,
currentInput:null,keyboard:null,model:null,currentSelectedTxtId:null,data:{},isVirtualKeyboardEnable:!0,constructor:function(a,c){this.tabId=a;this.pageScopeId=c;this.model=new k({})},handleWindowAction:function(a){this.clearPanelMessage();a.dst?(dwr.engine._batchesLength++,ec.fisa.dwr.proxy.standby.show(),document.location.reload(!0),ec.fisa.dwr.proxy.standby.show()):"cnfrm"==a.wAxn?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(a.confirmationDialogTitle,a.aMsgs,this.breadcrumbId,this.tabId,
this.pageId,null,null,!1):"error"==a.wAxn&&this.updateMsgsPanel(a.aMsgs)},setKeyboardWidgetId:function(a){this.keyboardId=a},setCurrentPasswordId:function(a){this.currentPasswordId=a.id;!0==this.isVirtualKeyboardEnable&&(a.set("disabled",!0),a.set("readOnly",!0))},setNewPasswordId:function(a){this.newPasswordId=a.id;!0==this.isVirtualKeyboardEnable&&(a.set("disabled",!0),a.set("readOnly",!0))},setNewPasswordConfirmId:function(a){this.newPasswordConfirmId=a.id;!0==this.isVirtualKeyboardEnable&&(a.set("disabled",
!0),a.set("readOnly",!0))},setModelVal:function(a,c){this.model.setValue([a],c)},setVirtualKeyboardEnable:function(a){a&&"false"===a&&(this.isVirtualKeyboardEnable=!1)},initKeyboard:function(a,c){var b=e.create("div",null,a.domNode);this.keyboard=new ec.fisa.widget.security.Keyboard({tabId:this.tabId,pageScopeId:this.pageScopeId,currentPasswordId:this.currentPasswordId,newPasswordId:this.newPasswordId,newPasswordConfirmId:this.newPasswordConfirmId,currentInput:this.currentInput,data:c,isLogin:!0,
onClick:function(a,c){this.inherited("onClick",arguments);if(null!=this.currentInput){var b=null;"currentPassword"==this.currentInput?b=dijit.byId(this.currentPasswordId):"newPassword"==this.currentInput?b=dijit.byId(this.newPasswordId):"newPasswordConfirm"==this.currentInput&&(b=dijit.byId(this.newPasswordConfirmId));var d=b.get("value");b.set("value",d+"*")}},onClickSpecialBtn:function(a,c){this.inherited("onClickSpecialBtn",arguments);var b=null,d=null;"currentPassword"==this.currentInput?(b=dijit.byId(this.currentPasswordId),
d=this.currentPasswordId):"newPassword"==this.currentInput?(b=dijit.byId(this.newPasswordId),d=this.newPasswordId):"newPasswordConfirm"==this.currentInput&&(b=dijit.byId(this.newPasswordConfirmId),d=this.newPasswordConfirmId);"DELETE"==c&&(b.set("value",""),this._setValueAttr(""),this.setSelectedValueById(d,""))}},b);this.keyboardId=this.keyboard.id;this.keyboard.registrySelectedValue(this.currentPasswordId);this.keyboard.registrySelectedValue(this.newPasswordId);this.keyboard.registrySelectedValue(this.newPasswordConfirmId);
this.keyboard.startup()},setMessagesPanel:function(a){this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId){var c=ec.fisa.controller.utils.findCurrentBreadCrumb(a);c&&(this.breadcrumbId=c.id)}this.updateMsgsPanel(this.initMsgs);delete this.initMsgs},setKeyboardCols:function(a){this.keyboardCols=a},bindToModel:function(a,c){var b=this.data[c];"undefined"===typeof b&&(b="");this.model.appendObject([c],b,a.id,"value",null,!1)},setOnChangeCurrentPassword:function(a){a.on("change",
d.hitch(this,function(a){var b=dijit.byId(this.currentPasswordId);a?(a=dijit.byId(this.keyboardId),!0==this.isVirtualKeyboardEnable&&(a.onChangeSelectedValue(this.currentPasswordId),a.currentInput="currentPassword",this.currentSelectedTxtId=this.currentPasswordId,b.set("disabled",!1),d.removeAttr(b.domNode,"disabled"))):!0==this.isVirtualKeyboardEnable&&b.set("disabled",!0)}),!0)},setOnChangeNewPassword:function(a){a.on("change",d.hitch(this,function(a){var b=dijit.byId(this.newPasswordId);a?(a=dijit.byId(this.keyboardId),
!0==this.isVirtualKeyboardEnable&&(a.onChangeSelectedValue(this.newPasswordId),a.currentInput="newPassword",this.currentSelectedTxtId=this.newPasswordId,b.set("disabled",!1),d.removeAttr(b.domNode,"disabled"))):!0==this.isVirtualKeyboardEnable&&b.set("disabled",!0)}),!0)},setOnChangeNewPasswordConfirm:function(a){a.on("change",d.hitch(this,function(a){var b=dijit.byId(this.newPasswordConfirmId);a?(a=dijit.byId(this.keyboardId),!0==this.isVirtualKeyboardEnable&&(a.onChangeSelectedValue(this.newPasswordConfirmId),
a.currentInput="newPasswordConfirm",this.currentSelectedTxtId=this.newPasswordConfirmId,b.set("disabled",!1),d.removeAttr(b.domNode,"disabled"))):!0==this.isVirtualKeyboardEnable&&b.set("disabled",!0)}),!0)},changeCredentials:function(){var a=dijit.byId(this.keyboardId),c={callbackScope:this};c.callback=this.handleWindowAction;c.errorHandler=this.errorHandler;if(!0==this.isVirtualKeyboardEnable)ChangeCredentialsControllerDWR.changeEncodedCredentials(this.tabId,this.pageScopeId,this.model.getValue(["_currentUsername"]),
a.getSelectedValueById(this.currentPasswordId),this.model.getValue(["_newUsername"]),a.getSelectedValueById(this.newPasswordId),a.getSelectedValueById(this.newPasswordConfirmId),c);else{var a=dijit.byId(this.currentPasswordId).get("value"),b=dijit.byId(this.newPasswordId).get("value"),d=dijit.byId(this.newPasswordConfirmId).get("value");ChangeCredentialsControllerDWR.changeCredentials(this.tabId,this.pageScopeId,this.model.getValue(["_currentUsername"]),a,this.model.getValue(["_newUsername"]),b,d,
c)}},close:function(){ChangeCredentialsControllerDWR.invalidateSession({callbackScope:this,callback:d.hitch(this,function(a){document.location.reload(!0)}),errorHandler:d.hitch(this,this.errorHandler)})},closeCnfrm:function(){ChangeCredentialsControllerDWR.closeCnfrm({callbackScope:this,callback:d.hitch(this,function(a){dijit.byId(this.messagesPanelId).clearAllMessages();this.updateMsgsPanel(a.aMsgs)}),errorHandler:d.hitch(this,this.errorHandler)});document.location.reload(!0)},setConfirmationMessage:function(a){var c=
d.byId("changeCredentialsMsgCntnr"),c=e.create("div",{"class":"fisaConfirmation"},c),c=new h({},c);c.startup();c.update(a)}})});
//@ sourceMappingURL=ChangeCredentialsController.js.map