//>>built
define("ec/fisa/controller/security/ChangePasswordController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController dojo/dom-construct ec/fisa/message/ConfirmationPanel ec/fisa/mvc/StatefulModel ./_base ec/fisa/widget/security/Keyboard".split(" "),function(d,f,l,g,e,h,k){return f("ec.fisa.controller.security.ChangePasswordController",g,{tabId:null,pageScopeId:null,keyboardId:null,currentPasswdId:null,newPasswdId:null,repeatPasswdId:null,breadcrumbId:null,inputPasswdType:null,
keyboard:null,model:null,currentSelectedTxtId:null,isVirtualKeyboardEnable:!0,data:{},constructor:function(a,c){this.tabId=a;this.pageScopeId=c;this.model=new k({})},setVirtualKeyboardEnable:function(a){a&&"false"===a&&(this.isVirtualKeyboardEnable=!1)},handleWindowAction:function(a){this.clearPanelMessage();a.dst?(dwr.engine._batchesLength++,ec.fisa.dwr.proxy.standby.show(),document.location.reload(!0),ec.fisa.dwr.proxy.standby.show()):"cnfrm"==a.wAxn?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(a.confirmationDialogTitle,
a.aMsgs,this.breadcrumbId,this.tabId,this.pageId,null,null,!1):null!=a.GEN_ERROR_PROCESS&&this.updateMsgsPanel(a.aMsgs)},setKeyboardWidgetId:function(a){this.keyboardId=a},setCurrentPasswdId:function(a){this.currentPasswdId=a.id;!0==this.isVirtualKeyboardEnable&&(a.set("disabled",!0),a.set("readOnly",!0))},setNewPasswdId:function(a){this.newPasswdId=a.id;!0==this.isVirtualKeyboardEnable&&(a.set("disabled",!0),a.set("readOnly",!0))},setRepeatPasswdId:function(a){this.repeatPasswdId=a.id;!0==this.isVirtualKeyboardEnable&&
(a.set("disabled",!0),a.set("readOnly",!0))},setModelVal:function(a,c){this.model.setValue([a],c)},initKeyboard:function(a,c){var b=e.create("div",null,a.domNode);this.keyboard=new ec.fisa.widget.security.Keyboard({tabId:this.tabId,pageScopeId:this.pageScopeId,currentPasswdId:this.currentPasswdId,newPasswdId:this.newPasswdId,inputPasswdType:this.inputPasswdType,repeatPasswdId:this.repeatPasswdId,data:c,isLogin:!0,onClick:function(a,c){this.inherited("onClick",arguments);if(null!=this.inputPasswdType){var b=
null,b="currentPasswd"==this.inputPasswdType?dijit.byId(this.currentPasswdId):"newPasswordId"==this.inputPasswdType?dijit.byId(this.newPasswdId):dijit.byId(this.repeatPasswdId),d=b.get("value");b.set("value",d+"*")}},onClickSpecialBtn:function(a,c){this.inherited("onClickSpecialBtn",arguments);var b=null,d=null;"currentPasswd"==this.inputPasswdType?(b=dijit.byId(this.currentPasswdId),d=this.currentPasswdId):"newPasswordId"==this.inputPasswdType?(b=dijit.byId(this.newPasswdId),d=this.newPasswdId):
(b=dijit.byId(this.repeatPasswdId),d=this.repeatPasswdId);"DELETE"==c&&(b.set("value",""),this._setValueAttr(""),this.setSelectedValueById(d,""))}},b);this.keyboardId=this.keyboard.id;this.keyboard.registrySelectedValue(this.currentPasswdId);this.keyboard.registrySelectedValue(this.newPasswdId);this.keyboard.registrySelectedValue(this.repeatPasswdId);this.keyboard.startup()},setMessagesPanel:function(a){this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId){var c=
ec.fisa.controller.utils.findCurrentBreadCrumb(a);c&&(this.breadcrumbId=c.id)}this.updateMsgsPanel(this.initMsgs);delete this.initMsgs},setKeyboardCols:function(a){this.keyboardCols=a},bindToModel:function(a,c){var b=this.data[c];"undefined"===typeof b&&(b="");this.model.appendObject([c],b,a.id,"value",null,!1)},setOnChageCurrentPasswd:function(a){a.on("change",d.hitch(this,function(a){var b=dijit.byId(this.currentPasswdId);a?(this.currentSelectedTxtId=this.currentPasswdId,!0==this.isVirtualKeyboardEnable&&
(a=dijit.byId(this.keyboardId),a.onChangeSelectedValue(this.currentPasswdId),a.inputPasswdType="currentPasswd",b.set("disabled",!1),d.removeAttr(b.domNode,"disabled"))):!0==this.isVirtualKeyboardEnable&&b.set("disabled",!0)}),!0)},setOnChageNewPasswd:function(a){a.on("change",d.hitch(this,function(a){var b=dijit.byId(this.newPasswdId);a?(this.currentSelectedTxtId=this.newPasswdId,!0==this.isVirtualKeyboardEnable&&(a=dijit.byId(this.keyboardId),a.onChangeSelectedValue(this.newPasswdId),a.inputPasswdType=
"newPasswordId",b.set("disabled",!1),d.removeAttr(b.domNode,"disabled"))):!0==this.isVirtualKeyboardEnable&&b.set("disabled",!0)}),!0)},setOnChageRepeatPasswd:function(a){a.on("change",d.hitch(this,function(a){var b=dijit.byId(this.repeatPasswdId);a?(this.currentSelectedTxtId=this.repeatPasswdId,!0==this.isVirtualKeyboardEnable&&(a=dijit.byId(this.keyboardId),a.onChangeSelectedValue(this.repeatPasswdId),a.inputPasswdType="repeatPasswordId",b.set("disabled",!1),d.removeAttr(b.domNode,"disabled"))):
!0==this.isVirtualKeyboardEnable&&b.set("disabled",!0)}),!0)},changePassword:function(a){var c=!1;null!=a&&!0===a&&(c=!0);a={callbackScope:this};a.callback=this.handleWindowAction;a.errorHandler=this.errorHandler;if(!0==this.isVirtualKeyboardEnable){var b=dijit.byId(this.keyboardId);ChangePasswordControllerDWR.changeEncodedPassword(this.tabId,this.pageScopeId,b.getSelectedValueById(this.currentPasswdId),b.getSelectedValueById(this.newPasswdId),b.getSelectedValueById(this.repeatPasswdId),c,a)}else{var b=
dijit.byId(this.currentPasswdId).get("value"),d=dijit.byId(this.newPasswdId).get("value"),e=dijit.byId(this.repeatPasswdId).get("value");ChangePasswordControllerDWR.changePassword(this.tabId,this.pageScopeId,b,d,e,c,a)}},close:function(a){!0==a?ChangePasswordControllerDWR.invalidateSession({callbackScope:this,callback:d.hitch(this,function(a){document.location.reload(!0)}),errorHandler:d.hitch(this,this.errorHandler)}):(ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId),ec.fisa.menu.utils.addEmptyTabAllClosed(d.config.fisaNewTabLabel))},
updateExpiredPasswordMsg:function(a,c){a&&(dijit.byId(this.messagesPanelId).clearAllMessages(),this.updateMsgsPanel([c]))},updateSuccessMsg:function(a){a&&ChangePasswordControllerDWR.generateSuccessMsg({callbackScope:this,callback:d.hitch(this,function(a){dijit.byId(this.messagesPanelId).clearAllMessages();this.updateMsgsPanel(a.aMsgs)}),errorHandler:d.hitch(this,this.errorHandler)})},closeCnfrm:function(){ChangePasswordControllerDWR.closeCnfrm({callbackScope:this,callback:d.hitch(this,function(a){dijit.byId(this.messagesPanelId).clearAllMessages();
this.updateMsgsPanel(a.aMsgs)}),errorHandler:d.hitch(this,this.errorHandler)});document.location.reload(!0)},setConfirmationMessage:function(a){var c=d.byId("changePswMsgCntnr"),c=e.create("div",{"class":"fisaConfirmation"},c),c=new h({},c);c.startup();c.update(a)}})});
//@ sourceMappingURL=ChangePasswordController.js.map