//>>built
define("ec/fisa/controller/security/MachineValidatorController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ./_base ec/fisa/navigation/Utils dojox/mvc dojox/mvc/StatefulModel dijit/form/RadioButton dojox/widget/DialogSimple".split(" "),function(c,f,h,g,k){return f("ec.fisa.controller.security.MachineValidatorController",g,{tabId:null,pageScopeId:null,imagePickerId:null,breadcrumbId:null,userMachineDataGrid:null,model:null,selectedRowItem:null,action:null,
machineDlg:null,data:{},requiredFieldMessage:{},machineListDlg:null,wasMachineListDlg:!1,isEnroll:!1,machineRegLabel:"",machinesRegLabel:"",constructor:function(a,b){this.tabId=a;this.pageScopeId=b;this.model=dojox.mvc.newStatefulModel({data:{}});MachineValidatorControllerDWR.getRequiredFieldMessage({callbackScope:this,callback:function(a){this.requiredFieldMessage=a},errorHandler:c.hitch(this,this.errorHandler)})},handleWindowAction:function(a){dijit.byId(this.messagesPanelId).clearAllMessages();
this.updateMsgsPanel(a.aMsgs);this.cancelMachineInfo();!0==this.wasMachineListDlg&&this.displayMachineList();a.dst&&setTimeout(function(){document.location.reload(!0)},3E3)},loadUserMachineInformation:function(){var a=new ec.fisa.dwr.Store("MachineValidatorControllerDWR","viewUserMachineData",this.tabId,this.pageScopeId,[],null);this.userMachineDataGrid.setStore(a)},bindToModel:function(a,b,d,c){var e=this.data[b];if(void 0===e||null==e)e="","date"==b&&(e=a._componentNode.dropDownDefaultValue);e=
new dojox.mvc.StatefulModel({data:e});this.model.add(b,e);a.set("ref",this.model[b]);a.set("disabled",d);void 0!==c&&a.set("readOnly",c)},saveMachineInfo:function(){var a=[],b="",d="";void 0!=this.model.name&&(b=this.model.name.value);this.validateFields([{field:"CAL_NAME",value:b}])||(void 0!=this.model.identifier&&(d=this.model.identifier.value),a.push(d),a.push(b),b={callbackScope:this},b.callback=this.handleWindowAction,b.errorHandler=this.errorHandler,MachineValidatorControllerDWR.saveUserMachineInformation(this.tabId,
this.pageScopeId,a,this.action,this.isEnroll,b))},setMessagesPanel:function(a){this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId){var b=ec.fisa.controller.utils.findCurrentBreadCrumb(a);b&&(this.breadcrumbId=b.id)}this.updateMsgsPanel(this.initMsgs);delete this.initMsgs},validateFields:function(a){var b={level:{level:4E4}};b.summary=this.requiredFieldMessage.I18N_REQUIRED_FIELDS;c.forEach(a,function(a){if("undefined"===typeof a.value||""==a.value||"-1"==
a.value)b.detail="undefined"!==typeof b.detail?b.detail+" ** "+this.requiredFieldMessage[a.field]:"** "+this.requiredFieldMessage[a.field]},this);return"undefined"!==typeof b.detail?(dijit.byId(this.messagesPanelId).clearAllMessages(),this.updateMsgsPanel([b]),!0):!1},displayMachineInfo:function(a){this.action=a;var b=!1;null!=this.machineListDlg?(this.machineListDlg.onCancel(),this.wasMachineListDlg=!0):this.wasMachineListDlg=!1;if("IN"!=a)if(null!=this.selectedRowItem)this.data.identifier=this.selectedRowItem.identifier,
this.data.name=this.selectedRowItem.name,this.data.date=this.selectedRowItem.date;else{alert("Debe seleccionar una opcion");return}else this.data.identifier="",this.data.name="";"DE"==a&&(b=!0);this.machineDlg=new dojox.widget.DialogSimple({title:this.machineRegLabel,style:"width: 800px",href:"static/security/machineInformation.jsp",preventCache:!0,ioMethod:c.xhrPost,ioArgs:{content:{tabId:this.tabId,pageScopeId:this.pageScopeId,action:this.action,disable:b}}});this.machineDlg.onCancel=c.hitch(this,
function(){this.machineDlg.destroy()});this.machineDlg.show()},formatterDataGridRadioButton:function(a,b,d){if(null!=a){if(0<=b){var f=d.grid.getItem(b);a=new dijit.form.RadioButton({name:"radioBtn",checked:!1});a.onChange=c.hitch(this,function(a){this.selectedRowItem=d.grid.store._entries[f].data});return a}return""}},displayMachineList:function(){this.machineListDlg=new dojox.widget.DialogSimple({title:this.machinesRegLabel,style:"width: 800px",href:"static/security/savedMachineList.jsp",preventCache:!0,
ioMethod:c.xhrPost,ioArgs:{content:{tabId:this.tabId,pageScopeId:this.pageScopeId}}});this.machineListDlg.onCancel=c.hitch(this,function(){this.machineListDlg.destroy();this.machineListDlg=null});this.machineListDlg.show()},cancelMachineInfo:function(){this.machineDlg.onCancel()},close:function(){ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)},setIsEnroll:function(a){this.isEnroll=a}})});
//@ sourceMappingURL=MachineValidatorController.js.map