//>>built
define("ec/fisa/controller/security/SecurityController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect ./_base dojo/dom-geometry dojo/dom-style ec/fisa/controller/Utils ec/fisa/print/Utils dojo/topic ec/fisa/controller/BaseController ec/fisa/navigation/Utils ec/fisa/validation/Utils".split(" "),function(d,e,f,h,k,l,m,n,p,q,r,g){return e("ec.fisa.controller.security.SecurityController",[g],{tabId:null,pageScopeId:null,model:null,data:null,documentData:null,
comboStatusOptions:null,initMsgs:null,breadcrumbId:null,btnsContainer:null,selectDataMap:null,lovData:null,labels:null,contextPath:d.config.fisaContextPath,btActionMode:null,tableRegistry:null,notificationAdditionalsWdgId:null,initLabels:null,btContentPaneId:null,secBeforeListFactor:null,secAfterListFactor:null,subscriptions:null,documentContentPaneWdgId:null,btTabContainerId:null,selectComponentToReload:null,selectIdMap:null,buttonLabel:"Accept",sequenceBtScheduleButtonData:null,skinParameters:null,
data:null,constructor:function(a,b,c){this.tabId=a;this.pageScopeId=b;this.secBeforeListFactor=c.secBeforeListFactor;this.secAfterListFactor=c.secAfterListFactor;this.initLabels=c.initLabels;this.isSequence=c.isSequence;this.btActionMode=c.btActionMode;this.btId=c.btId;this.skinParameters=c.skinParameters;void 0!=c.aMsgs&&(this.initMsgs=c.aMsgs);this.data={};this.verifyBeforeSecurity();delete a;delete b;delete c.initLabels;delete c.secBeforeListFactor;delete c.secAfterListFactor;delete c.isSequence;
delete c.actionId;delete c.skinParameters},mergeObjects:function(a,b){a||(a={});if(b)for(var c in b)a[c]=b[c];return a},destroy:function(){this.notificationAdditionalsWdgId=this.initMsgs=this.tableRegistry=this.lovData=this.model=this.data=null;dojox.lang.functional.forIn(this.subscriptions,function(a,b){a.remove&&f.isFunction(a.remove)&&a.remove()},this)},verifyBeforeSecurity:function(){null!=this.secBeforeListFactor&&(void 0!=this.secBeforeListFactor&&0<this.secBeforeListFactor.length&&"true"!=
this.showConfirmation)&&this.createDialogSecurityFactor(this.secBeforeListFactor)},verifyAfterSecurity:function(a){null!=this.secAfterListFactor&&void 0!=this.secAfterListFactor&&0<this.secAfterListFactor.length?this.createDialogSecurityFactor(this.secAfterListFactor).dlgSuccessEvent=d.hitch(this,function(a,c){this._execActionInternal(a)},a):this._execActionInternal(a)},verifyAfterSecuenceSecurity:function(a,b){null!=this.secAfterListFactor&&void 0!=this.secAfterListFactor&&0<this.secAfterListFactor.length&&
("true"!=this.showDocuments||"true"!=this.showConfirmation)?this.createDialogSecurityFactor(this.secAfterListFactor).dlgSuccessEvent=d.hitch(this,function(a,b,d){this._handleSeqNextActionInternal(a,b)},a,b):this._handleSeqNextActionInternal(a,b)},createDialogSecurityFactor:function(a){var b=ec.fisa.controller.utils.getGlobalModalSize(0.5);b.h+=100;a=new ec.fisa.widget.DialogSecurity({title:this.initLabels.titleSecurityPopup,draggable:!1,wdgtWidth:b.w,wdgtHeight:b.h,tabId:this.tabId,secListFactor:a,
pageScopeId:this.pageScopeId+"sec_pop",style:{width:b.w+"px",height:b.h+"px"},dlgCancelEvent:d.hitch(this,function(a){this.cancelAuthenticationFactorDialog()})});a.show();return a},handleCancelAction:function(){var a=dijit.byId(this.breadcrumbId).selectedChildWidget,b=!1;if(null!=a.postClose&&void 0!=a.postClose&&void 0!=a.postCloseScope&&null!=a.postCloseScope){var c=dijit.byId(a.postCloseScope);a.postClose.apply(c,a.postCloseArgs)}else b=!0;null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):
ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId);null!=a&&(null!=a.postCloseArgs&&void 0!=a.postCloseArgs&&null!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postClose&&void 0!=a.postCloseScope)&&ec.fisa.navigation.utils.closeCurrentBreadCrumb(a.postCloseArgs.btBreadCrumbId);b&&ec.fisa.menu.utils.addEmptyTabAllClosed(d.config.fisaNewTabLabel)},handleWindowAction:function(a){null!=this.fromAgenda&&("true"==this.fromAgenda&&"error"!=a.wAxn)&&(a.wAxn=
"close");if("close"==a.wAxn){a=dijit.byId(this.breadcrumbId).selectedChildWidget;var b=!1;if(null!=a.postClose&&void 0!=a.postClose&&void 0!=a.postCloseScope&&null!=a.postCloseScope){var c=dijit.byId(a.postCloseScope);a.postClose.apply(c,a.postCloseArgs)}else b=!0;null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId);null!=a&&(null!=a.postCloseArgs&&void 0!=a.postCloseArgs&&
null!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postClose&&void 0!=a.postCloseScope)&&ec.fisa.navigation.utils.closeCurrentBreadCrumb(a.postCloseArgs.btBreadCrumbId);b&&ec.fisa.menu.utils.addEmptyTabAllClosed(d.config.fisaNewTabLabel)}else"cnfrm"==a.wAxn?this.handleConfirmationBt(a):"error"==a.wAxn?(this.updateMsgsPanel(a.aMsgs),this.refreshTableRegistry()):"close\x26refresh"==a.wAxn?(ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId),b=ec.fisa.controller.utils.getPageController(a.parentFisaTabId,
a.parentFisaPageScopeId),void 0!=b&&b instanceof CustomBtController&&(a=dijit.byId(b.tableRegistry[a.parentBtId][a.parentEntityId]),void 0!=a&&null!=a&&a.refresh())):"showDlg"==a.wAxn?void 0!=this.isSequence&&null!=this.isSequence&&"true"===this.isSequence?ec.fisa.navigation.utils.templateSequenceDlgShowAction(a.respBtLabels,this.tabId,this.pageScopeId,this.sequenceId):ec.fisa.navigation.utils.templateDlgShowAction(a.respBtLabels,this.tabId,this.pageScopeId,this.btId,this.btActionMode,this.isSequence):
alert("unknown action!")},setMessagesPanel:function(a){this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId){var b=ec.fisa.controller.utils.findCurrentBreadCrumb(a);b&&(this.breadcrumbId=b.id)}this.updateMsgsPanel(this.initMsgs);this.btContentPaneId=a.getParent().getParent().id;delete this.initMsgs},setLabels:function(a){this.labels=a},setBreadcrumb:function(a){this.breadcrumbId=a.id},showMessages:function(a){null!=a&&(this.clearPanelMessage(),this.updateMsgsPanel(a.aMsgs))},
clearPanelMessage:function(){this.messagesPanelId&&dijit.byId(this.messagesPanelId).clearAllMessages()},getSelectedIndex:function(a){var b=-1;a=a.getOptions();for(var c=0,c=0;c<a.length;c++)if(!0===a[c].selected){b=c;break}return b-1},cancelAuthenticationFactorDialog:function(){ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).cancel()}})});
//@ sourceMappingURL=SecurityController.js.map