//>>built
define("ec/fisa/mvc/StatefulModel","dojo/_base/kernel dojo/_base/declare dojo/dom-construct dojo/dom-attr dojo/dom-geometry dojo/dom-style dijit/Tooltip dojox/lang/functional/object dojo/_base/array".split(" "),function(h,k,l,m,n,p,q){return k("ec.fisa.mvc.StatefulModel",null,{_data:null,_fldDta:null,_tt:null,constructor:function(a){null!=a&&(this._data=a);this._tt={}},appendObject:function(a,b,c,d,f,g){a=a||[];var e=null;null==c?(null==this._data&&(this._data={}),e=this._data):(null==this._fldDta&&
(this._fldDta={}),e=this._fldDta);h.forEach(a,function(a){null==e[a]&&(e[a]={});e=e[a]},this);null==c?e._fv=b:(e._cmpId=c,e._cmpProp=d,e._cmpFrmt=f,e._cmpChng=g,dijit.byId(c).set(e._cmpProp,b,g))},removeObject:function(a){a=a||[];if(null==this._containsFld(a)&&null!=this._containsVal(a)&&0<a.length){for(var b=this._data,c=null,d=0;d<a.length-1;d++)a[d]in b&&(c=b,b=b[a[d]]);d=dojox.lang.functional.keys(b);null!=d&&(1<d.length||1==d.length&&null==c?delete b[a[a.length-1]]:delete c[a[a.length-2]])}},
_containsFld:function(a){a=a||[];var b=null;if(0==a.length)return this._fldDta;for(var c=0;c<a.length;c++){if(0==c){if(null==this._fldDta)return null;b=this._fldDta}if(a[c]in b)b=b[a[c]];else return null}return b},_containsVal:function(a){a=a||[];var b=null;if(0==a.length)return this._data;for(var c=0;c<a.length;c++){if(0==c){if(null==this._data)return null;b=this._data}if(a[c]in b)b=b[a[c]];else return null}return b},contains:function(a){return null!=this._containsFld(a)||null!=this._containsVal(a)},
getComponent:function(a){a=this._containsFld(a);return null!=a?dijit.byId(a._cmpId):null},getValue:function(a){var b=this._containsFld(a);if(null!=b)return a=dijit.byId(b._cmpId).get(b._cmpProp),null!=b._cmpFrmt&&(null!=a&&""!=a)&&(a=b._cmpFrmt(a)),a;b=this._containsVal(a);return null!=b?b._fv:null},setValue:function(a,b,c){var d=this._containsFld(a);if(null!=d){a=dijit.byId(d._cmpId);var f=a.get(d._cmpProp);a.set(d._cmpProp,b,c);if(d._cmpChng&&f!=b&&a.onFChange)a.onFChange()}else{d=this._containsVal(a);
if(null==d){d=this._data;c=a||[];for(a=0;a<c.length;a++)c[a]in d||(d[c[a]]={}),d=d[c[a]]}d._fv=b}},setValueDestroyFldData:function(a,b){var c=this._containsFld(a);null!=c&&delete this._fldDta[a];c=this._containsVal(a);if(null==c)for(var c=this._data,d=a||[],f=0;f<d.length;f++)d[f]in c||(c[d[f]]={}),c=c[d[f]];c._fv=b},setMessage:function(a,b,c){a=this._containsFld(a);if(null==a)return!1;if(null!=a)return ec.fisa.format.utils.addToFieldError(a._cmpId,b,c,this._tt),!0},clearAllMessages:function(){dojox.lang.functional.forIn(this._tt,
function(a,b){ec.fisa.format.utils.removeFieldError(b)},this);this._tt={}},toPlainObject:function(){var a=null;if(null!=this._data||null!=this._fldDta)a={},null!=this._data&&dojox.lang.functional.forIn(this._data,function(b,c){a[c]="_fv"in b?b._fv:this.recurseByVal(b)},this),null!=this._fldDta&&dojox.lang.functional.forIn(this._fldDta,function(b,c){if("_cmpId"in b){var d=dijit.byId(b._cmpId);a[c]=d.get(b._cmpProp);null!=b._cmpFrmt&&(null!=a[c]&&""!=a[c])&&(a[c]=b._cmpFrmt(a[c],{format:d.fisaFormat,
formatPattern:d.fisaFormatPattern}))}else a[c]=this.recurseByFld(b,a[c])},this);return a},recurseByVal:function(a){if(null!=a){var b={};dojox.lang.functional.forIn(a,function(a,d){b[d]="_fv"in a?a._fv:this.recurseByVal(a)},this);return b}return null},recurseByFld:function(a,b){if(null!=a){var c=null,c=null==b?{}:b;dojox.lang.functional.forIn(a,function(a,b){if("_cmpId"in a){var g=dijit.byId(a._cmpId);c[b]=g.get(a._cmpProp);null!=a._cmpFrmt&&(null!=c[b]&&""!=c[b])&&(c[b]=a._cmpFrmt(c[b],{format:g.fisaFormat,
formatPattern:g.fisaFormatPattern}))}else c[b]=this.recurseByFld(a,c[b])},this);return c}return null},getComponentsId:function(){var a={};dojox.lang.functional.forIn(this._fldDta,function(b,c){a[c]="_cmpId"in b?b._cmpId:this.recurseByFld(b)},this);return a},recurseGetIdByFld:function(a){if(null!=a){var b={};dojox.lang.functional.forIn(a,function(a,d){b[d]="_cmpId"in a?a._cmpId:this.recurseByFld(a)},this);return b}return null}})});
//@ sourceMappingURL=StatefulModel.js.map