//>>built
define("ec/fisa/layer/nls/Unified_ROOT",{"dojo/cldr/nls/gregorian":{"days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","dateFormatItem-yQQQ":"y QQQ","dateFormatItem-yMEd":"y-MM-dd, E","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["BCE","CE"],"days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"y MMMM d","months-format-wide":"Month1 Month2 Month3 Month4 Month5 Month6 Month7 Month8 Month9 Month10 Month11 Month12".split(" "),"dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"y MMMM d, EEEE","dateFormatItem-Md":"MM-dd","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"y-MM-dd","field-era":"Era","dateFormatItem-yM":"y-MM","months-standAlone-wide":"Month1 Month2 Month3 Month4 Month5 Month6 Month7 Month8 Month9 Month10 Month11 Month12".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-yQQQQ":"y QQQQ","timeFormat-long":"HH:mm:ss z","field-year":"Year","dateFormatItem-yMMM":"y MMM","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour","months-format-abbr":"Month1 Month2 Month3 Month4 Month5 Month6 Month7 Month8 Month9 Month10 Month11 Month12".split(" "),"timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Today","field-day-relative+1":"Tomorrow",
"dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Month1 Month2 Month3 Month4 Month5 Month6 Month7 Month8 Month9 Month10 Month11 Month12".split(" "),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"timeFormat-medium":"HH:mm:ss","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["BCE",
"CE"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Yesterday","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"field-zone":"Zone","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["BCE","CE"],"dateFormatItem-yMMMd":"y MMM d","days-format-narrow":"SMTWTFS".split(""),"days-standAlone-narrow":"SMTWTFS".split(""),
"dateFormatItem-MMM":"LLL","field-month":"Month","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormat-short":"y-MM-dd","field-second":"Second","dateFormatItem-yMMMEd":"y MMM d, E","dateFormatItem-Ed":"d, E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Week","dateFormat-medium":"y MMM d","dayPeriods-format-narrow-pm":"PM","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM"},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Single Sort",indirectSelectionRadio:"Row ${0}, single selection, radio box",ascending:"Click to sort Ascending",indirectSelectionCheckBox:"Row ${0}, multiple selection, check box",selectAll:"Select all",descending:"Click to sort Descending",nestedSort:"Nested Sort",unsorted:"Do not sort this column",sortingState:"${0} - ${1}"},"dijit/_editor/nls/commands":{removeFormat:"Remove Format",
copy:"Copy",paste:"Paste",selectAll:"Select All",insertOrderedList:"Numbered List",insertTable:"Insert/Edit Table",print:"Print",underline:"Underline",foreColor:"Foreground Color",htmlToggle:"HTML Source",formatBlock:"Paragraph Style",newPage:"New Page",insertHorizontalRule:"Horizontal Rule","delete":"Delete",appleKey:"\u2318${0}",insertUnorderedList:"Bullet List",tableProp:"Table Property",insertImage:"Insert Image",superscript:"Superscript",subscript:"Subscript",createLink:"Create Link",undo:"Undo",
fullScreen:"Toggle Full Screen",italic:"Italic",fontName:"Font Name",justifyLeft:"Align Left",unlink:"Remove Link",toggleTableBorder:"Toggle Table Border",viewSource:"View HTML Source",ctrlKey:"ctrl+${0}",fontSize:"Font Size",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',indent:"Indent",redo:"Redo",strikethrough:"Strikethrough",justifyFull:"Justify",justifyCenter:"Align Center",hiliteColor:"Background Color",deleteTable:"Delete Table",outdent:"Outdent",
cut:"Cut",plainFormatBlock:"Paragraph Style",toggleDir:"Toggle Direction",bold:"Bold",tabIndent:"Tab Indent",justifyRight:"Align Right"},"dojox/grid/enhanced/nls/Pagination":{gotoButtonTitle:"Go to a specific page",prevTip:"Previous Page",pageCountIndication:" (${0} pages)",pageStepLabelTemplate:"Page ${0}",descTemplate:"${2} - ${3} of ${1} ${0}",lastTip:"Last Page",all:"All",nextTip:"Next Page",pageSizeLabelTemplate:"${0} items per page",dialogCancel:"Cancel",itemTitle:"items",dialogConfirm:"Go",
firstTip:"First Page",allItemsLabelTemplate:"All items",singularItemTitle:"item",dialogIndication:"Specify the page number",dialogTitle:"Go to Page"},"dojox/form/nls/Uploader":{label:"Select Files..."},"dojo/cldr/nls/currency":{USD_symbol:"US$",CAD_symbol:"CA$",GBP_symbol:"\u00a3",HKD_symbol:"HK$",JPY_symbol:"JP\u00a5",AUD_symbol:"A$",CNY_symbol:"CN\u00a5",EUR_symbol:"\u20ac"},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",nextMessage:"More choices"}});
//@ sourceMappingURL=Unified_ROOT.js.map