//>>built
define("ec/fisa/layer/nls/Unified_en-us",{"dojo/cldr/nls/gregorian":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Su Mo Tu We Th Fr Sa".split(" "),"months-format-narrow":"JFMAMJJASOND".split(""),"quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, M/d/y","dateFormatItem-GyMMMEd":"E, MMM d, y G","dateFormatItem-MMMEd":"E, MMM d",eraNarrow:["B","A"],"days-format-short":"Su Mo Tu We Th Fr Sa".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"MMMM d, y","months-format-wide":"January February March April May June July August September October November December".split(" "),"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, MMMM d, y","dateFormatItem-Md":"M/d","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateFormatItem-yMd":"M/d/y","dayPeriods-format-wide-noon":"noon","field-era":"Era","dateFormatItem-yM":"M/y","months-standAlone-wide":"January February March April May June July August September October November December".split(" "),
"timeFormat-short":"h:mm a","quarters-format-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"h:mm:ss a z","field-year":"Year","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Hour","months-format-abbr":"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),"timeFormat-full":"h:mm:ss a zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"Today","field-day-relative+1":"Tomorrow",
"dateFormatItem-GyMMMd":"MMM d, y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),"timeFormat-medium":"h:mm:ss a","dateFormatItem-Hm":"HH:mm","quarters-standAlone-abbr":["Q1",
"Q2","Q3","Q4"],eraAbbr:["BC","AD"],"field-minute":"Minute","field-dayperiod":"AM/PM","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Yesterday","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} 'at' {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"E, M/d","dateTimeFormat-full":"{1} 'at' {0}","field-day":"Day","days-format-wide":"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
"field-zone":"Time Zone","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"JFMAMJJASOND".split(""),"field-year-relative+-1":"Last year","field-month-relative+-1":"Last month","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["Before Christ","Anno Domini"],"dateFormatItem-yMMMd":"MMM d, y",
"days-format-narrow":"SMTWTFS".split(""),"days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-month":"Month","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","dateFormat-short":"M/d/yy","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second",
"dateFormatItem-yMMMEd":"E, MMM d, y","field-month-relative+0":"This month","field-month-relative+1":"Next month","dateFormatItem-Ed":"d E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Week","dateFormat-medium":"MMM d, y","field-year-relative+0":"This year","field-week-relative+-1":"Last week","field-year-relative+1":"Next year","dayPeriods-format-narrow-pm":"p","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G",
"field-week-relative+0":"This week","field-week-relative+1":"Next week"},"dojox/grid/enhanced/nls/EnhancedGrid":{singleSort:"Single Sort",indirectSelectionRadio:"Row ${0}, single selection, radio box",ascending:"Click to sort Ascending",indirectSelectionCheckBox:"Row ${0}, multiple selection, check box",selectAll:"Select all",descending:"Click to sort Descending",nestedSort:"Nested Sort",unsorted:"Do not sort this column",sortingState:"${0} - ${1}"},"dijit/_editor/nls/commands":{removeFormat:"Remove Format",
copy:"Copy",paste:"Paste",selectAll:"Select All",insertOrderedList:"Numbered List",insertTable:"Insert/Edit Table",print:"Print",underline:"Underline",foreColor:"Foreground Color",htmlToggle:"HTML Source",formatBlock:"Paragraph Style",newPage:"New Page",insertHorizontalRule:"Horizontal Rule","delete":"Delete",appleKey:"\u2318${0}",insertUnorderedList:"Bullet List",tableProp:"Table Property",insertImage:"Insert Image",superscript:"Superscript",subscript:"Subscript",createLink:"Create Link",undo:"Undo",
fullScreen:"Toggle Full Screen",italic:"Italic",fontName:"Font Name",justifyLeft:"Align Left",unlink:"Remove Link",toggleTableBorder:"Toggle Table Border",viewSource:"View HTML Source",ctrlKey:"ctrl+${0}",fontSize:"Font Size",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',indent:"Indent",redo:"Redo",strikethrough:"Strikethrough",justifyFull:"Justify",justifyCenter:"Align Center",hiliteColor:"Background Color",deleteTable:"Delete Table",outdent:"Outdent",
cut:"Cut",plainFormatBlock:"Paragraph Style",toggleDir:"Toggle Direction",bold:"Bold",tabIndent:"Tab Indent",justifyRight:"Align Right"},"dojox/grid/enhanced/nls/Pagination":{gotoButtonTitle:"Go to a specific page",prevTip:"Previous Page",pageCountIndication:" (${0} pages)",pageStepLabelTemplate:"Page ${0}",descTemplate:"${2} - ${3} of ${1} ${0}",lastTip:"Last Page",all:"All",nextTip:"Next Page",pageSizeLabelTemplate:"${0} items per page",dialogCancel:"Cancel",itemTitle:"items",dialogConfirm:"Go",
firstTip:"First Page",allItemsLabelTemplate:"All items",singularItemTitle:"item",dialogIndication:"Specify the page number",dialogTitle:"Go to Page"},"dojox/form/nls/Uploader":{label:"Select Files..."},"dojo/cldr/nls/currency":{HKD_displayName:"Hong Kong Dollar",CHF_displayName:"Swiss Franc",JPY_symbol:"\u00a5",HKD_symbol:"HK$",CAD_displayName:"Canadian Dollar",CNY_displayName:"Chinese Yuan",USD_symbol:"$",AUD_displayName:"Australian Dollar",JPY_displayName:"Japanese Yen",CAD_symbol:"CA$",USD_displayName:"US Dollar",
EUR_symbol:"\u20ac",CNY_symbol:"CN\u00a5",GBP_displayName:"British Pound Sterling",GBP_symbol:"\u00a3",AUD_symbol:"A$",EUR_displayName:"Euro"},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",nextMessage:"More choices"}});
//@ sourceMappingURL=Unified_en-us.js.map