//>>built
define("ec/fisa/mobile/widget/BtController","dijit/_Widget dojo/_base/declare dojo/_base/lang ec/fisa/controller/mobile/BaseController ec/fisa/format/Utils ec/fisa/navigation/Utils dojo/dom-construct ec/fisa/widget/DocumentActions ec/fisa/mvc/StatefulModel dojo/on ec/fisa/controller/custom/QtController ec/fisa/mobile/widget/_MvcMixin ec/fisa/dwr/proxy/EventSequenceActionDWR ec/fisa/widget/DialogSecurity ./_base dojox/lang/functional/object ec/fisa/dwr/proxy/BtControllerDWR ec/fisa/dwr/proxy/EventReportActionDWR ec/fisa/dwr/proxy/RuleFieldSelectorControllerDWR dojox/lang/functional".split(" "),
function(q,u,v,w,z,A,h,B,n,C,D,x,E){var p=u("ec.fisa.mobile.widget.BtController",[q,w,x],{fisatabid:"",fisapageid:"",btId:"",data:null,initData:"",initMsgs:"",selectData:"",selectDataMap:"",lovData:"",btActionMode:"",isSequence:!1,secBeforeListFactor:"",secAfterListFactor:"",initLabels:null,parentConfBtPageScopeId:null,sequenceDontInitiateBt:!1,contextPath:dojo.config.fisaContextPath,saveAsTemplateChckBoxId:null,tableRegistry:null,model:null,notificationAdditionalsWdgId:null,subscriptions:null,selectIdMap:null,
initializer:"",btContentPaneId:"",sequence_mode:"",ftype:"",constructor:function(){this.tableRegistry={};this.model=new n({});this.notificationAdditionalsWdgId=[];this.subscriptions={};this.selectIdMap={}},postMixInProperties:function(){this.inherited(arguments);this.isSequence&&null!=ec.fisa.controller.utils.getPageController(this.fisatabid,this.fisapageid)&&ec.fisa.controller.utils.uninitializeController(this.fisatabid,this.fisapageid);ec.fisa.controller.utils.initPageController(this.fisatabid,
this.fisapageid,this,!0);this.addParamToModel(this,!1);var a=new Function(this.initializer);this.initializer=null;a=a.call();this.data=this.initData=a.initData;this.initMsgs=a.initMsgs;this.selectData=a.selectData;this.selectDataMap=a.selectDataMap;this.lovData=a.lovData;this.btActionMode=a.btActionMode;this.secBeforeListFactor=a.secBeforeListFactor;this.secAfterListFactor=a.secAfterListFactor;a=dijit.byId("viewPort");if(null!=a||void 0!=a)this.btContentPaneId=a.containerNode.children[0].id,a.fisaTabId=
this.fisatabid},copyInitData:function(a,c,b,d,e,g,f,l,k){this.fisatabid=tabId;this.fisapageid=pageScopeId;this.data=this.initData=b;this.initMsgs=d;this.selectDataMap=e;this.lovData=g;this.tableRegistry={};this.model=new n({});this.notificationAdditionalsWdgId=[];this.secBeforeListFactor=f;this.secAfterListFactor=l;this.initLabels=k;this.subscriptions={}},renewInitData:function(a){this.initData=a},loadSelectData:function(a,c){var b=c||!1,d=a["bt-id"],e=a["field-id"],g=[];this.selectDataMap&&(this.selectDataMap[d]&&
this.selectDataMap[d][e].data)&&(d=this.selectDataMap[d][e].data,g[0]={value:"",label:dojo.config.fisaSelectLabel,selected:!0},dojo.forEach(d,function(b,c){g[c+1]={value:""+b[a.valueColumn],label:b[a.labelColum]}},this));b||a.set("options",g);return g},sequenceNextAction:function(a){var c=a.previous_button;dijit.byId(this.messagesPanelId);this.clearPanelMessage();if(a&&a.next_step){var b=a.next_step,d=a.seq_id,e=a["fisa-action-id"],g=a["fisa-bt-id"],f=a.fisatabid,l=a.fisapageid,k=a.is_last_bt;this.isLastBt=
k;var y=a.is_sequence,m=a.has_documents,r=a.show_documents,h=a.accept_button,n=a.has_confirmation_bt,s=a.show_confirmation,t=a.next_button,p=a.sequence_step,q=a.hold_button;this.sequenceMode=a.sequence_mode;this.isSequence=y;this.sequenceId=d;this.nextStep=b;this.fisatabid=f;this.fisapageid=l;this.hasDocuments=m;this.showDocuments=r;this.hasConfirmationBt=n;this.showConfirmation=s;this.previousButton=c;this.actionMode=e;this.sequenceStep=p;a=this.model.toPlainObject();f={callbackScope:this};f.errorHandler=
dojo.hitch(this,this.errorHandler);r&&null==s?q||h||t?(f.callback=this.handleNextSequence,EventSequenceActionDWR.validateDocuments(this.fisatabid,this.fisapageid,d,e,a,f)):ec.fisa.mobile.navigation.utils.navigateSequenceFromDocTo(d,b,this.btContentPaneId,this.fisatabid,this.fisapageid,this.sequenceMode,this.previousButton,"true"):null==r&&s?h?this.sequenceLastAction(d):m?this.sequenceHasDocumentsAction(d,this.previousButton):ec.fisa.mobile.navigation.utils.navigateSequenceTo(d,b,this.btContentPaneId,
this.fisatabid,this.fisapageid,this.sequenceMode,this.previousButton):(f.callback=this.handleNextSequence,m=this._addNotificationValData(),k?EventSequenceActionDWR.validateBtInSequence(this.fisatabid,this.fisapageid,g,d,e,a,!0,t,c,null,this.sequenceMode,m,f):EventSequenceActionDWR.validateBtInSequence(this.fisatabid,this.fisapageid,g,d,e,a,!1,t,c,b,this.sequenceMode,m,f))}},handleNextSequence:function(a){this.handleSeqNextAction(a,this.sequenceId,this.nextStep)},handleSeqNextAction:function(a,c,b){"cnfrm"==
a.wAxn?this.verifyAfterSecuenceSecurity(c,b):"error"==a.wAxn?this.updateMsgsPanel(a.aMsgs):alert("unknown action!")},addControllerRef:function(a){a.fc=this},verifyAfterSecuenceSecurity:function(a,c){this._handleSeqNextActionInternal(a,c)},_handleSeqNextActionInternal:function(a,c){dijit.byId(this.messagesPanelId).clearAllMessages();this.model.clearAllMessages();null==c||"null"==c?this.hasDocuments&&null==this.showDocuments?this.sequenceHasDocumentsAction(a,this.previousButton):this.hasDocuments&&
this.showDocuments&&this.hasConfirmationBt?this.sequenceHasConfirmationAction(a,this.previousButton):this.hasConfirmationBt&&null==this.showConfirmation?this.sequenceHasConfirmationAction(a,this.previousButton):this.sequenceLastAction(a):ec.fisa.navigation.utils.navigateSequenceTo(a,c,this.btContentPaneId,this.fisatabid,this.fisapageid,this.sequenceMode,this.previousButton)},createDialogSecurityFactor:function(a){new SimpleDialog({},h.create("div",{},win.doc.body));var c=ec.fisa.controller.utils.getGlobalModalSize(0.5);
c.h+=100;a=new ec.fisa.widget.DialogSecurity({title:this.initLabels.titleSecurityPopup,draggable:!1,wdgtWidth:c.w,wdgtHeight:c.h,tabId:this.tabId,secListFactor:a,pageScopeId:this.pageScopeId+"sec_pop",style:{width:c.w+"px",height:c.h+"px"},dlgCancelEvent:dojo.hitch(this,function(a){this.handleWindowAction({wAxn:"close"})})});a.show();return a},sequenceLastAction:function(a){var c={callbackScope:this};c.errorHandler=dojo.hitch(this,this.errorHandler);c.callback=this.handleInAction;var b=!1;null!=this.saveAsTemplateChckBoxId&&
!0==dijit.byId(this.saveAsTemplateChckBoxId).get("checked")&&(b=!0);EventSequenceActionDWR.callExecAction(this.fisatabid,this.fisapageid,a,this.sequenceMode,this.actionMode,this.sequenceStep,b,this.templateOverCall,c)},sequenceHasConfirmationAction:function(a,c){var b="",b=dojo.config.fisaContextPath,b=b+"/BUSINESS_TEMPLATE",b=b+"/",b=b+a,b=b+"/FISATabId/",b=b+this.fisatabid,b=b+"/FisaPageScopeId/",b=b+this.fisapageid,b=b+"/REQUEST_SEQUENCE_DRAW_CONFIRMATION/",b=b+"true",b=b+"/SEQUENCE_PRINCIPAL_BT_MODE/",
b=b+this.sequenceMode;c&&(b+="/PREVIOUS_BUTTON_CLICKED/",b+=c);(new dojox.mobile.ContentPane({href:b,ioArgs:"null"},h.create("div",{"class":"mblContentBodyClass"},ec.fisa.mobile.util.buildContentBody.call(this).containerNode))).startup();ec.fisa.controller.utils.resetControllerData(this.fisatabid,this.fisapageid)},sequenceHasDocumentsAction:function(a,c){var b="",b=dojo.config.fisaContextPath,b=b+"/BUSINESS_TEMPLATE",b=b+"/",b=b+a,b=b+"/FISATabId/",b=b+this.fisatabid,b=b+"/FisaPageScopeId/",b=b+this.fisapageid,
b=b+"/REQUEST_SEQUENCE_DRAW_DOCUMENTS/",b=b+"true",b=b+"/SEQUENCE_PRINCIPAL_BT_MODE/",b=b+this.sequenceMode;"true"===c&&(b+="/PREVIOUS_BUTTON_CLICKED/",b+=c);var d={};d.href=b;ec.fisa.navigation.utils.updateCurrentBreadCrumb(d,this.btContentPaneId,this.fisatabid,this.fisapageid)},execAction:function(a){var c=dijit.byId(this.messagesPanelId);null!=c&&c.clearAllMessages();null!=this.model&&this.model.clearAllMessages();if(a&&a["fisa-action-id"]){var c=a["fisa-action-id"],b=a["fisa-bt-id"],d=a.is_sequence;
a=a.template_over_call;this.btId=b;this.btActionMode=c;this.isSequence=d;d={callbackScope:this};d.errorHandler=dojo.hitch(this,this.errorHandler);ec.fisa.widget.utils.resetFocusManager();if("CANCEL"==c||"closeBt"==c)d.callback=this.handleCancelAction,EventActionDWR.executeCommandButtonCancel(this.fisatabid,this.fisapageid,b,d);else if("close"==c)this.handleWindowAction({wAxn:"close"});else{d={callbackScope:this};d.errorHandler=dojo.hitch(this,this.errorHandler);d.callback=this._validateBtCallBack;
var e=this.model.toPlainObject(),g=this._addNotificationValData(),f=!1;null!=this.saveAsTemplateChckBoxId&&!0==dijit.byId(this.saveAsTemplateChckBoxId).get("checked")&&(f=!0);EventActionDWR.executeCommandButtonAction(this.fisatabid,this.fisapageid,b,c,f,a,e,g,d)}}},_validateBtCallBack:function(a){if("cnfrm"==a.wAxn){var c={};c["fisa-action-id"]=a.btAction;c["fisa-bt-id"]=a.btId;this._execActionInternal(c)}else"error"==a.wAxn&&this.updateMsgsPanel(a.aMsgs)},verifyAfterSecurity:function(a){null!=this.secAfterListFactor&&
void 0!=this.secAfterListFactor&&0<this.secAfterListFactor.length?this.createDialogSecurityFactor(this.secAfterListFactor,a["fisa-bt-id"]).dlgSuccessEvent=dojo.hitch(this,function(a,b){this._execActionInternal(a)},a):this._execActionInternal(a)},_execActionInternal:function(a){var c=a["fisa-action-id"];a=a["fisa-bt-id"];var b={callbackScope:this};b.errorHandler=dojo.hitch(this,this.errorHandler);b.callback=this.handleInAction;EventActionDWR.executeValidatedBtAction(this.fisatabid,this.fisapageid,
a,c,b)},handleInAction:function(a){this.model&&(a&&a.ftMsgs&&this.fromAgenda&&"true"!=this.fromAgenda)&&(this.data=a.ftMsgs,dojox.lang.functional.forIn(this.data,function(a,b){this.model.contains([b])&&dojox.lang.functional.forIn(a.dataMessage.fields,function(a,c){this.model.setValue([b,"dataMessage","fields",c,"value"],a.value,!1);this.model.setValue([b,"dataMessage","fields",c,"complement"],a.complement,!1)},this)},this));this.handleWindowAction(a)},handleWindowAction:function(a){null!=this.fromAgenda&&
("true"==this.fromAgenda&&"error"!=a.wAxn)&&(a.wAxn="close");if("close"==a.wAxn){a=!1;if(null!=selectedPane.postClose&&void 0!=selectedPane.postClose&&void 0!=selectedPane.postCloseScope&&null!=selectedPane.postCloseScope){var c=dijit.byId(selectedPane.postCloseScope);selectedPane.postClose.apply(c,selectedPane.postCloseArgs)}else a=!0;null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId);
null!=selectedPane&&(null!=selectedPane.postCloseArgs&&void 0!=selectedPane.postCloseArgs&&null!=selectedPane.postCloseArgs.btBreadCrumbId&&void 0!=selectedPane.postCloseArgs.btBreadCrumbId&&void 0!=selectedPane.postClose&&void 0!=selectedPane.postCloseScope)&&ec.fisa.navigation.utils.closeCurrentBreadCrumb(selectedPane.postCloseArgs.btBreadCrumbId);a&&ec.fisa.menu.utils.addEmptyTabAllClosed(dojo.config.fisaNewTabLabel)}else"cnfrm"==a.wAxn?this.updateMsgsPanel(a.aMsgs):"error"==a.wAxn?this.updateMsgsPanel(a.aMsgs):
"close\x26refresh"==a.wAxn?(ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId),c=ec.fisa.controller.utils.getPageController(a.parentFisaTabId,a.parentFisaPageScopeId),void 0!=c&&c instanceof p&&(a=dijit.byId(c.tableRegistry[a.parentBtId][a.parentEntityId]),void 0!=a&&null!=a&&a.refresh())):"showDlg"==a.wAxn?void 0!=this.isSequence&&null!=this.isSequence&&"true"===this.isSequence?ec.fisa.navigation.utils.templateSequenceDlgShowAction(a.respBtLabels,this.tabId,this.pageScopeId,this.sequenceId):
ec.fisa.navigation.utils.templateDlgShowAction(a.respBtLabels,this.tabId,this.pageScopeId,this.btId,this.btActionMode,this.isSequence):alert("unknown action!")},handleOnChangeComponent:function(a,c,b,d,e,g,f,l,k){this.clearPanelMessage();l=this.model.toPlainObject();var h={callbackScope:{ctrl:this,notifyComboId:d,gridRealRowIndex:k}};h.callback=this.handleCallBackOnChangeComponent;h.errorHandler=dojo.hitch(this,this.errorHandler);EventActionDWR.handleOnChangeComponent(this.fisatabid,this.fisapageid,
a,c,b,l,d,e,g,f,k,h)},handleCallBackOnChangeComponent:function(a){var c=a.aMsgs;"error"==a.wAxn&&(this.ctrl.clearPanelMessage(),this.ctrl.updateMsgsPanel(c));a.wAxn="refresh_dataType";this.ctrl.clearPanelMessage();this.ctrl.updateMsgsPanel(c);a.wAxn="refresh";dojo.hitch(this.ctrl,this.ctrl.handleCallBackBackFieldRoutine(a))},handleCallBackBackFieldRoutine:function(a,c){this.showMessages(a);"refresh"==a.wAxn&&(this.model&&a&&a.msg)&&(affectedFieldData=a.msg,dojox.lang.functional.forIn(affectedFieldData,
function(b,c){if(this.model.contains([c])){var e=null,e="undefined"===typeof b.dataMessage?b:b.dataMessage.fields;dojox.lang.functional.forIn(e,function(b,f){if(null!=b&&!0===b.multivalue){var e=this.tableRegistry[c];null!=e&&(e=e[f],null!=e&&dijit.byId(e).refresh())}else null!=b&&!1===b.multivalue&&(e=!1,void 0!=this.lovData&&void 0!=this.lovData[c]&&void 0!=this.lovData[c][f]?e=!0:a&&(a.priorityChange&&"true"===a.priorityChange)&&(e=!0),this.model.setValue([c,"dataMessage","fields",f,"value"],b.value,
e),this.model.setValue([c,"dataMessage","fields",f,"complement"],b.complement),void 0!=b.enabled&&null!=b.enabled&&this.setFieldModelEnabled(c,f,b.enabled))},this)}},this))},registerTable:function(a){this.tableRegistry[a.btId]||(this.tableRegistry[a.btId]={});var c=this.tableRegistry[a.btId];c[a.entId]||(c[a.entId]=a.id)},addFieldRoutineEvent:function(a,c){var b=a["bt-id"],d=a["field-id"];a.fw=this;"QY"!=c&&"DE"!=c&&(a.attachOnChangeEvent&&v.isFunction(a.attachOnChangeEvent))&&a.attachOnChangeEvent(this,
b,d,c)},showMessages:function(a){null!=a&&(this.clearPanelMessage(),this.updateMsgsPanel(a.aMsgs))},updateNotificationData:function(a,c){null!=this.notificationAdditionalsWdgId&&void 0!=this.notificationAdditionalsWdgId&&dojo.forEach(this.notificationAdditionalsWdgId,dojo.hitch(this,function(b){b.btId==c&&dijit.byId(b.notifWdgId).set("value",a)}))},_addNotificationValData:function(){var a={};null!=this.notificationAdditionalsWdgId&&void 0!=this.notificationAdditionalsWdgId&&dojo.forEach(this.notificationAdditionalsWdgId,
dojo.hitch(this,function(c){var b=c.btId;c=dijit.byId(c.notifWdgId).get("value");null==a[b]&&void 0==a[b]&&(a[b]={});a[b]=c}));return a},showDocument:function(a){var c=dijit.byId(this.messagesPanelId);null!=c&&c.clearAllMessages();null!=this.model&&this.model.clearAllMessages();if(a){var c=a.action_mode,b=a["fisa-bt-id"],d=a.fisatabid,e=a.fisapageid,g={};g.title=a.label;g.href=dojo.config.fisaContextPath+"/pages/static/mobile/documentos/mobile_documentos.jsp";g.ioArgs={content:{btId:b,FisaPageScopeId:e,
actionMode:c,FISATabId:d}};g.ioMethod=dojo.xhrPost;ec.fisa.mobile.navigation.utils.openDocumentBreadCrumb(g)}}});return p});
//@ sourceMappingURL=BtController.js.map