//>>built
define("ec/fisa/mobile/widget/Grid","dijit/_WidgetBase dojo/_base/declare ec/fisa/mobile/widget/RoundRectSwapDataList dojox/mobile/ListItem dojo/dom-construct dojo/_base/array dojox/mobile/SimpleDialog dojox/mobile/Button dojo/_base/window dojo/_base/kernel dojox/mobile/Heading dojox/mobile/CheckBox dojo/number dojo/on dojo/dom-attr dojo/_base/lang dojox/grid/DataGrid ec/fisa/mobile/_base".split(" "),function(t,u,v,z,b,h,w,n,x,l,A,y,q,p,r,s,B){return u("ec.fisa.mobile.Grid",[t],{_input:null,ftype:"qt",
classStyle:"",_dataList:null,structure:null,structureNoHidden:null,selectionMode:"",actions:null,_simpleDialog:null,indexSelected:null,islayout:!1,postMixInProperties:function(){this.inherited(arguments);var d=[],b=0;h.forEach(this.structure,function(a,c){a.hidden||(d[b]=a,a.left=!1,a.right=!1,b++)},this);this.structureNoHidden=d;h.forEach(this.structureNoHidden,function(a,b){b%this.numberColsPerSwap()+1==this.numberColsPerSwap()&&b!=this.structureNoHidden.length&&(a.right=!0);0==b%this.numberColsPerSwap()&&
0!=b&&(a.left=!0)},this);this.independentActions&&s.isString(this.independentActions)&&(this.independentActions=s.getObject(this.independentActions))},buildRendering:function(){this.inherited(arguments);this._dataList=new v({store:null,createListItem:this.createListItem,createTableItem:this.createTableItem,createHeaderListItem:this.createHeaderListItem,select:this.selectionMode,countVisibleColumns:this.countVisibleColumns,numberColumns:this.numberColumns,numberColsPerSwap:this.numberColsPerSwap,nextSwap:this.nextSwap,
previousSwap:this.previousSwap,onSelect:this.onSelect,islayout:this.islayout,onComplete:this.onComplete,pageLength:this.pageLength,paginationLabelBack:this.paginationLabelBack,paginationLabelNext:this.paginationLabelNext,paginationLabelof:this.paginationLabelof,createPagination:this.createPagination,paginationBack:this.paginationBack,paginationNext:this.paginationNext,updateModel:this.updateModel},b.create("div",{},this.domNode));this._dataList.gridId=this.id},createHeaderListItem:function(d,e){var a=
e%this.getParent().numberColsPerSwap(),c=parseInt(q.format(e/this.getParent().numberColsPerSwap(),{round:-1,pattern:"0"}));0==a&&(tr=b.create("tr",{},headerTbody[c]),r.set(tr,"_index",e));a=this.getParent().getActionsSelectables();0==e&&(null!=a&&0<a.length&&!this.islayout)&&b.create("td",{"class":"noContentQtLeft"},tr);d.left&&!this.islayout&&(a=this.id+c+"left",a=b.create("td",{"class":"mblSwapViewLeftTd",rowSpan:1,id:a,valign:"top"},tr),a=new n({"class":"mblBottonSwapLeft","fisa-view-index":c,
fsv:this.swapViewId},a),a.connect(a,"onClick",this.previousSwap),b.create("img",{"class":"mblSwapViewLeftImage",src:l.config.fisaContextPath+"/resources/blank.gif"},a.domNode));b.create("td",{style:"text-align:left;","class":"mobileQtGridHeaderCell",width:d.width},tr).innerHTML=d.name;d.right&&!this.islayout&&(a=this.id+c+"right",a=b.create("td",{"class":"mblSwapViewRightTd",rowSpan:1,id:a,valign:"top"},tr),c=new n({"class":"mblBottonSwapRight","fisa-view-index":c,fsv:this.swapViewId},a),c.connect(c,
"onClick",this.nextSwap),b.create("img",{"class":"mblSwapViewRightImage",src:l.config.fisaContextPath+"/resources/blank.gif"},c.domNode))},createListItem:function(b,e,a){return this.createTableItem(a,b,e)},attachActions:function(b,e){},createTableItem:function(d,e,a){var c=this.getParent().structureNoHidden,g=null;h.forEach(c,function(c,h){var f=h%this.getParent().numberColsPerSwap(),k=parseInt(q.format(h/this.getParent().numberColsPerSwap(),{round:-1,pattern:"0"}));if(0==f&&(g=b.create("tr",{"class":"qtTableTrValue"},
d[k]),r.set(g,"_index",a),f=this.getParent().getActionsSelectables(),null!=f&&0<f.length&&!this.islayout)){var m=b.create("td",{"class":"mblSwapLeftTd",rowSpan:1,valign:"top"},g),f=new y({fisatabid:this.getParent().fisatabid,fisapageid:this.getParent().fisapageid,_index:a,actions:f},b.create("div",null,m));f.connect(f,"onClick",this.onSelect)}c.left&&(!this.islayout&&this.getParent().getActionsSelectables()&&0>=this.getParent().getActionsSelectables().length)&&b.create("td",{"class":"noContentQtLeft"},
g);f=b.create("td",{"class":"mblSwapValueTd"},g);0==a&&c.right?k=b.create("td",{"class":"mblSwapRightTd",rowSpan:1,id:d[k].id+"right",valign:"top"},g):0!=a&&c.right&&(k=l.byId(d[k].id+"right"),k.rowSpan++);k=this.store.getValue(e,c.field);null!=c.formatter?(m=c.formatter(k,a,c),null!=m&&("string"==typeof m?f.innerHTML=m:"object"==typeof m?b.place(m.domNode,f):void 0!=m.domNode?b.place(m.domNode,f):f.innerHTML=k)):null!=k&&(f.innerHTML=k);c.right&&!this.islayout&&b.create("td",{"class":"noContentQtRight"},
g)},this)},createPagination:function(d,e,a){dijit.byId(this.gridId);dijit.byId(this.gridId);dijit.byId(this.gridId);d=b.create("table",{border:0,cellpading:0,cellspacing:0,width:"100%",id:"tablePag_"+a,"class":"qtTableSwapView"},d);d=b.create("tbody",{id:"tbodyPag_"+a},d);var c=b.create("tr",{"class":"qtTableTrValue"},d),g=b.create("td",{className:"qtPaginationBack"},c);d=b.create("td",{className:"qtPaginationInfo"},c);c=b.create("td",{className:"qtPaginationNext"},c);g=b.create("span",{innerHTML:this.paginationLabelBack,
className:"qtPaginationEnable"},g);c=b.create("span",{innerHTML:this.paginationLabelNext,className:"qtPaginationEnable"},c);b.create("span",{innerHTML:a+1+" "+this.paginationLabelof+" "+e,className:"qtPaginationDisable"},d);0==a?(g.className="qtPaginationDisable",p(c,"click",l.hitch(this,this.paginationNext))):(a+1==e?c.className="qtPaginationDisable":(g.className="qtPaginationEnable",p(c,"click",l.hitch(this,this.paginationNext)),c.className="qtPaginationEnable"),p(g,"click",l.hitch(this,this.paginationBack)))},
paginationBack:function(){this.currentPage--;l.hitch(this,this.updateModel(["start"],dijit.byId(this.gridId).pageLength*this.currentPage))},paginationNext:function(){this.currentPage++;l.hitch(this,this.updateModel(["start"],dijit.byId(this.gridId).pageLength*this.currentPage))},updateModel:function(b,e){this.store.callbackScope.model.setValue(b,e);this.query=this.store.callbackScope.model.toPlainObject();this.refresh()},onSelect:function(){var d=ec.fisa.controller.utils.getPageController(this.fisatabid,
this.fisapageid);d.selection={};d.selection.indexSelected=this._index;if(this.checked){this._simpleDialog=new w({closeButton:!0});d.actionsDialogId=this._simpleDialog.get("id");x.body().appendChild(this._simpleDialog.domNode);b.create("div",{"class":"mblSimpleDialogHeader",innerHTML:"Seleccione una acci\x26#243;n."},this._simpleDialog.domNode);var e=b.create("table",{border:0,cellpading:0,cellspacing:0,width:"100%"},this._simpleDialog.domNode),a=b.create("tbody",{},e);h.forEach(this.actions,l.hitch(this,
function(c){var e=b.create("tr",{"class":"mobileQtGridHeader"},a),e=b.create("td",{"class":"mobileQtGridHeaderCell",width:"auto"},e),h=new n({"class":"mblSimpleDialogButton",innerHTML:c.label});h.placeAt(e);h.connect(h,"onClick",l.hitch(d,d.executeAction,!0,c.value,null))}));this._simpleDialog.show();this.checked=!1}},onComplete:function(b,e){this.inherited(arguments);if(!0==this.getParent().hideQTGridIfNoResultsFound&&0==e._totalMatchedItems){var a=ec.fisa.controller.utils.getPageController(this.getParent().fisatabid,
this.getParent().fisapageid);a.unDisplayQTGrid();a.unDisplayMessagesPanel()}!0==this.getParent().hideQTPortletIfNoResultsFound?0<e._totalMatchedItems?(a=ec.fisa.controller.utils.getPageController(this.getParent().fisatabid,this.getParent().fisapageid),a.makeQTPortletVisible()):(a=ec.fisa.controller.utils.getPageController(this.getParent().fisatabid,this.getParent().fisapageid),a.unDisplayQTPortlet()):(a=ec.fisa.controller.utils.getPageController(this.getParent().fisatabid,this.getParent().fisapageid),
a.makeQTPortletVisible())},nextSwap:function(){dijit.byId(this.fsv[this["fisa-view-index"]]).goTo(1)},previousSwap:function(){dijit.byId(this.fsv[this["fisa-view-index"]]).goTo(-1)},countVisibleColumns:function(){return this.getParent().structureNoHidden.length},numberColumns:function(){return this.islayout?0:this.countVisibleColumns()/this.numberColsPerSwap()},numberColsPerSwap:function(){return this.islayout?this.structureNoHidden.length:2},destroy:function(){null!=this._dataList&&(this._dataList.destroy(arguments),
delete this._dataList);this.inherited(arguments)},setQuery:function(b){this._dataList.query=b;null==this._dataList.store&&(this._dataList.store=this.getFisaStore());this._dataList.refresh()},getActionsSelectables:function(){},getActionsNoSelectables:function(){},getFisaStore:function(){}})});
//@ sourceMappingURL=Grid.js.map