//>>built
require({cache:{"url:ec/fisa/mobile/widget/templates/QtController.html":"\x3cdiv\x3e\x3c/div\x3e"}});
define("ec/fisa/mobile/widget/QtController","dijit/_Widget dojo/_base/declare dijit/_Templated dojo/text!./templates/QtController.html ec/fisa/mvc/StatefulModel ec/fisa/controller/mobile/BaseController ec/fisa/mobile/widget/MessagePanel dojox/mobile/SimpleDialog dojo/_base/window dojo/dom-construct dojox/mobile/Button dojo/dom-style ec/fisa/mobile/widget/QtParameterButton ec/fisa/controller/Utils ec/fisa/dwr/proxy/QtControllerDWR ec/fisa/dwr/Store ./_base".split(" "),function(k,l,p,m,h,n,q,r,s,t,
u,g){return l("ec.fisa.mobile.widget.QtController",[k,n],{templateString:m,data:null,parentData:null,parentComplementData:null,model:null,modelComplement:null,selectData:null,selectDataMap:null,fisatabid:"",qtid:"",fisapageid:"",store:null,isForRenderCharts:!1,actionsDialogId:null,initialData:null,ftype:"",isFirstTimePortlet:!0,linkParentFisaTabId:"",linkParentFisaPageScopeId:"",linkParentBtId:"",initialStart:null,initialPageLenght:null,postMixInProperties:function(){this.inherited(arguments);this.model=
new h({});this.modelComplement=new h({});this.model.appendObject(["autoExec"],0,null,null,null,!1);this.model.appendObject(["start"],this.initialStart,null,null,null,!1);this.model.appendObject(["count"],this.initialPageLenght,null,null,null,!1);null==this.parentData&&(this.parentData={});null==this.parentComplementData&&(this.parentComplementData={});this.store=new ec.fisa.dwr.Store("QtControllerDWR","viewData",this.fisatabid,this.qtid,[this.fisapageid],null);ec.fisa.controller.utils.initPageController(this.fisatabid,
this.fisapageid,this,!0);null!=this.initialData&&dojox.lang.functional.forIn(this.initialData,function(a,b){null!=a&&(this.parentData[b]=a)},this);this.store.callbackScope=this},loadSelectData:function(a,b){var c=b||!1,d=a["bt-id"],e=a["field-id"],f=[];this.selectDataMap&&this.selectDataMap[d][e].data&&(d=this.selectDataMap[d][e].data,f[0]={value:"",label:dojo.config.fisaSelectLabel},dojo.forEach(d,function(b,c){f[c+1]={value:""+b[a.valueColumn],label:b[a.labelColum]}},this));c||a.set("options",f);
return f},obtainInitialValue:function(a){a=a["field-id"];var b=null;this.parentData&&this.parentData[a]&&(b=this.parentData[a]);return null==b?"":b},executeAction:function(a,b,c){var d=ec.fisa.controller.utils.getPageController(this.fisatabid,this.fisapageid);d.clearPanelMessage();var e=[];a&&(e[0]=this.selection.indexSelected);null!=c&&(e=[c]);a=this.qtId||d.qtid;c=d.model.toPlainObject();d.linkParentBtId&&""!=d.linkParentBtId&&(c.linkParentBtId=d.linkParentBtId);d={callbackScope:d,callback:d.executeActionCallback,
errorHandler:dojo.hitch(this,this.errorHandler)};0>=e.length?QtControllerDWR.executeAction(this.fisatabid,this.fisapageid,a,null,b,c,null,d):QtControllerDWR.executeAction(this.fisatabid,this.fisapageid,a,e,b,c,null,d)},executeActionCallback:function(a){var b=dijit.byId(this.actionsDialogId);null!=b&&(b.hide(),b.destroy(!1));this.hasToClearMsgs&&(this.clearPanelMessage(),this.model.clearAllMessages());if("error"==a.wAxn)!0===a.refreshResults&&this.searchAfterCloseContentPane(),this.updateMsgsPanel(a.aMsgs);
else if("open"==a.wAxn){a.responseMessages&&(this.updateMsgsPanel(a.responseMessages.aMsgs),this.hasToClearMsgs=!1);b={};b.title=a.dialogName;b.href=a.dialog;if(void 0!=a.transactionDocuments&&null!=a.transactionDocuments){var c=dojo.toJson(a.transactionDocuments);b.ioArgs={content:{transactionDocuments:c,actionMode:a.actionMode,FISATabId:this.tabId}}}b.ioMethod=dojo.xhrPost;ec.fisa.mobile.navigation.utils.openNewBreadCrumb(b)}else"refresh"==a.wAxn?(a.responseMessages&&this.updateMsgsPanel(a.responseMessages.aMsgs),
this.hasToClearMsgs=!1,this.search(!1),this.hasToClearMsgs=!0):"refreshParentBtFtm"==a.wAxn&&(a.wAxn="refresh",a.msg=a.afectedFields,a.priorityChange="true",b=ec.fisa.controller.utils.getPageController(this.linkParentFisaTabId,this.linkParentFisaPageScopeId),b.handleCallBackBackFieldRoutine(a),a.beneficiaryNotificationData&&a.beneficiaryBtId&&b.updateNotificationData(a.beneficiaryNotificationData,a.beneficiaryBtId),this.execCancel(null,this.qtId))},execCancel:function(a,b){var c={callbackScope:this,
errorHandler:dojo.hitch(this,this.errorHandler),callback:this.handleCancelAction};QtControllerDWR.executeCancel(this.tabId,this.pageScopeId,b,c)},handleCancelAction:function(a){"close"==a.wAxn&&(null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.mobile.util.back());this.linkParentFisaTabId&&this.linkParentFisaPageScopeId&&(a=ec.fisa.controller.utils.getPageController(this.linkParentFisaTabId,this.linkParentFisaPageScopeId))&&
(a.selectComponentToReload&&lang.isFunction(a.selectComponentToReload.doForceReloadOptions))&&a.selectComponentToReload.doForceReloadOptions()},updateMsgsPanel:function(a){"QT_PORTLET"===this.ftype&&this.isFirstTimePortlet&&(this.isFirstTimePortlet=!1,a=null);this.inherited(arguments)},handleOnChangeComponent:function(a,b,c,d,e,f,g,h,k){this.clearPanelMessage();c=this.model.toPlainObject();e={callbackScope:{ctrl:this,notifyComboId:d}};e.callback=this.handleCallBackQtOnChangeComponent;e.errorHandler=
dojo.hitch(this,this.errorHandler);EventActionDWR.handleQtOnChangeComponent(this.fisatabid,this.fisapageid,a,b,c,d,f,e)},handleCallBackQtOnChangeComponent:function(a){var b=a.aMsgs;"error"==a.wAxn?(this.ctrl.clearPanelMessage(),this.ctrl.updateMsgsPanel(b)):(null!=a.dataUpdate&&void 0!=a.dataUpdate&&(b=a.dataUpdate,null!=b&&void 0!=b&&dojox.lang.functional.forIn(b,dojo.hitch(this,function(a,b){this.ctrl.updateSelectByOutcome(b,a,this.ctrl)}))),null!=a.qtParams&&void 0!=a.qtParams&&dojox.lang.functional.forIn(a.qtParams,
dojo.hitch(this,function(a,b){this.ctrl.model.setValue([b],a,!1)})),null!=a.complementParams&&void 0!=a.complementParams&&dojox.lang.functional.forIn(a.complementParams,dojo.hitch(this,function(a,b){this.ctrl.modelComplement.setValue([b],a,!1)})))},updateSelectByOutcome:function(a,b,c){a=dijit.byId(c.selectIdMap[a]);c.selectDataMap[a["bt-id"]][a["field-id"]].data=b;a.setControlValue("");a.removeOption(a.getOptions());c.loadSelectData(a)},search:function(a,b){(null==a||!0==a)&&this.messagesPanelId&&
this.clearPanelMessage();var c=this.model.toPlainObject();c.autoExec++;c.sortRequested="0";this.model.setValue(["autoExec"],c.autoExec);!0==b&&(c.calledFromButtonScreenSearch=!0);this.hasToClearMsgs&&this.messagesPanelId&&this.model.clearAllMessages();this.isForRenderCharts?dijit.byId(this.fisaChartId).setQuery(c):dijit.byId(this.qtGridId).setQuery(c)},unDisplayQTGrid:function(){var a=dijit.byId(this.qtGridId).getParent();g.set(a.domNode,"display","none")},unDisplayMessagesPanel:function(){var a=
dijit.byId(this.messagesPanelId);a&&g.set(a.domNode,"display","none")},unDisplayQTPortlet:function(){var a=dijit.byId(this.qtGridId).getParent().getParent().getParent();g.set(a.domNode,"display","none")},makeQTPortletVisible:function(){var a=dijit.byId(this.qtGridId).getParent().getParent().getParent();g.set(a.domNode,"visibility","visible")}})});
//@ sourceMappingURL=QtController.js.map