//>>built
define("ec/fisa/controller/custom/AgendaSupervisorController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ./_base ec/fisa/controller/BaseController ec/fisa/format/Utils dojo/_base/window dojo/dom dojox/mvc dojox/mvc/StatefulModel dojox/lang/functional/object dojo/store/Memory dojo/data/ItemFileReadStore dojo/date/locale ec/fisa/navigation/Utils ec/fisa/dwr/Store ec/fisa/controller/Utils dojox/widget/DialogSimple".split(" "),function(e,f,l,m,g,n,h,k,p,q,r){return f("ec.fisa.controller.custom.AgendaSupervisorController",
[g],{tabId:null,pageScopeId:null,model:null,cmps:null,initData:null,taskTypeList:null,personalizedTaskTypeList:null,priorityList:null,dataGridPriorityList:null,reAssignActionList:null,breadcrumb:null,bindingContentPane:null,agendaDataGrid:null,paneSearcher:null,tabAgendaShow:null,messagesPanel:null,hierarchyDataGrid:null,collaboratorsDataGrid:null,hierarchyList:null,collaboratorList:null,multipleSelectionCollaboratorWidget:null,selectedCollaboratorList:null,hierarchyPopup:null,collaboratorPopup:null,
constructor:function(a,c,b){this.initData=b;b.dateFrom=ec.fisa.format.utils.parseLongDate(b.dateFrom);b.dateTo=ec.fisa.format.utils.parseLongDate(b.dateTo);this.tabId=a;this.pageScopeId=c;this.model={};this.cmps={};this.init(b)},init:function(a){this.taskTypeList=a.taskTypeList;this.priorityList=a.priorityList;this.personalizedTaskTypeList=a.personalizedTaskTypeList;this.reAssignActionList=a.reAssignActionList;this.dataGridPriorityList=a.dataGridPriorityList;this.hierarchyList=a.hierarchyList;delete a.priorityList;
delete a.taskTypeList;delete a.personalizedTaskTypeList;delete a.reAssignActionList;delete a.dataGridPriorityList;delete a.hierarchyList;this.model=dojox.mvc.newStatefulModel({data:a})},setBindingContentPane:function(a){this.bindingContentPane=a},cargarTareas:function(a){this.clearPanelMessage();criteria={taskTypeId:this.model.taskTypeId.value,taskStatusId:this.model.taskStatusId.value,orderByPriority:this.model.orderByPriority.value,dateTo:this.model.dateTo.value,dateFrom:this.model.dateFrom.value,
maxResults:this.model.maxResults.value,personalizedTaskTypeId:this.model.personalizedTaskTypeId.value,collaborators:this.selectedCollaboratorList,authorizationHierarchy:this.model.hierarchyId.value,priority:this.model.priorityId.value};a=new ec.fisa.dwr.Store("AgendaSupervisorControllerDWR","viewData",this.tabId,criteria,[this.model.userDescription.value,this.pageScopeId],null);this.agendaDataGrid.setStore(a)},setTaskStatusId:function(a,c,b){"pendientes"==b?this.model.taskStatusId.value=1:"despachadas"==
b&&(this.model.taskStatusId.value=7)},countTasksByFilter:function(a){a={taskTypeId:this.model.taskTypeId.value,taskStatusId:this.model.taskStatusId.value,orderByPriority:this.model.orderByPriority.value,dateTo:this.model.dateTo.value,dateFrom:this.model.dateFrom.value,maxResults:this.model.maxResults.value,personalizedTaskTypeId:this.model.personalizedTaskTypeId.value};var c={callbackScope:this,callback:function(a){this.totalReg=a}};c.errorHandler=this.errorHandler;AgendaSupervisorControllerDWR.countTasksByCriteria(a,
this.model.userDescription.value,this.tabId,c)},changeUserStatus:function(a,c){this.clearPanelMessage()},_getSelectedTaskIdList:function(){for(var a=this.agendaDataGrid.selection.selected,c=[],b=0,d=0;d<a.length;d++)a[d]&&(c[b++]=this.agendaDataGrid.getItem(d));return c},updateTasksPriority:function(){this.clearPanelMessage();var a=this._getSelectedTaskIdList(),c=this.model.priorityId.value,b={callbackScope:this,callback:function(a){this.showMessages(a);if(null==a||this.isEmpty(a))this.cargarTareas(),
this.agendaDataGrid.rowSelectCell.toggleAllSelection(!1)}};b.errorHandler=e.hitch(this,this.errorHandler);AgendaSupervisorControllerDWR.updateTasksPriorityDWR(a,c,b)},updateSingleTaskPriority:function(a,c){this.clearPanelMessage();var b=[];b[0]=a;var d={callbackScope:this,callback:function(a){this.showMessages(a)}};d.errorHandler=e.hitch(this,this.errorHandler);AgendaSupervisorControllerDWR.updateTasksPriorityDWR(b,c,d)},reAssignTasks:function(){var a=this.model.reAssignActionId.value,c=this._getSelectedTaskIdList(),
b={callbackScope:this,callback:function(a){this.showMessages(a);if(null==a||this.isEmpty(a))this.cargarTareas(),this.agendaDataGrid.rowSelectCell.toggleAllSelection(!1)}};b.errorHandler=e.hitch(this,this.errorHandler);AgendaSupervisorControllerDWR.reAssignTasksDWR(c,a,b)},initComponentData:function(a,c){},setMessagesPanel:function(a){this.messagesPanel=a;this.breadcrumb=this.messagesPanel.getParent().getParent().getParent().getParent().getParent().getParent().getParent()},clearPanelMessage:function(){this.messagesPanel&&
this.messagesPanel.clearAllMessages()},showMessages:function(a){null!=a&&this.updateMsgsPanel(a.aMsgs)},isEmpty:function(a){for(var c in a)if(a.hasOwnProperty(c))return!1;return!0},openHierarchyPopup:function(){this.clearPanelMessage();var a=ec.fisa.controller.utils.getGlobalModalSize(0.5);this.hierarchyPopup=new dojox.widget.DialogSimple({style:"width:"+a.w+"px;",title:"FISA GROUP",href:"./static/agenda/fragment/supervisor-hierarchy-list.jsp",ioArgs:{content:{FISATabId:this.tabId,FisaPageScopeId:this.pageScopeId}},
ioMethod:e.xhrPost});this.hierarchyPopup.show()},loadHierarchyList:function(){var a=new e.data.ItemFileReadStore({data:{identifier:"hierarchyId",items:this.hierarchyList}});this.hierarchyDataGrid.setStore(a)},closeHierarchyPopup:function(){var a=this.hierarchyDataGrid.getItem(this.hierarchyDataGrid.selection.selectedIndex);this.hierarchyPopup.destroy();this.model.hierarchyId.set("value",a.hierarchyId[0]);this.model.hierarchyDescription.set("value",a.description[0])},clearHierarchySelection:function(){this.hierarchyPopup.destroy();
this.model.hierarchyId.set("value","");this.model.hierarchyDescription.set("value","")},openCollaboratorPopup:function(){this.collaboratorList=[];this.clearPanelMessage();var a={callbackScope:this,callback:function(a){this.showMessages(a);a.aMsgs||(this.collaboratorList=a.response_value,a=ec.fisa.controller.utils.getGlobalModalSize(0.7),this.collaboratorPopup=new dojox.widget.DialogSimple({style:"width:"+a.w+"px;",title:"FISA GROUP",href:"./static/agenda/fragment/supervisor-collaborator-list.jsp",
ioArgs:{content:{FISATabId:this.tabId,FisaPageScopeId:this.pageScopeId}},ioMethod:e.xhrPost}),this.collaboratorPopup.show())}};a.errorHandler=e.hitch(this,this.errorHandler);AgendaSupervisorControllerDWR.getSupervisorCollaboratorsByHierarchyIdDWR(this.model.hierarchyId.value,a)},loadCollaboratorList:function(){var a=new e.data.ItemFileReadStore({data:{identifier:"userId",items:this.collaboratorList}});this.collaboratorDataGrid.setStore(a)},closeCollaboratorPopup:function(){var a=this.collaboratorDataGrid.selection.selected;
this.selectedCollaboratorList=[];for(var c=0,b=0;b<a.length;b++)if(a[b]){var d={label:this.collaboratorDataGrid.getItem(b).fullName[0],value:this.collaboratorDataGrid.getItem(b).userId[0],userId:this.collaboratorDataGrid.getItem(b).userId[0]};this.selectedCollaboratorList[c++]=d}this.loadValuesForMultipleSelectionCollaboratorWidget();this.collaboratorPopup.destroy()},loadValuesForMultipleSelectionCollaboratorWidget:function(){if(null!=this.selectedCollaboratorList){for(var a=this.multipleSelectionCollaboratorWidget.get("id"),
a=k.byId(a);a.hasChildNodes();)a.removeChild(a.lastChild);for(var c=0;c<this.selectedCollaboratorList.length;c++){var b=h.doc.createElement("option");b.innerHTML=this.selectedCollaboratorList[c].label;b.value=this.selectedCollaboratorList[c].value;a.appendChild(b)}}}})});
//@ sourceMappingURL=AgendaSupervisorController.js.map