//>>built
define("ec/fisa/controller/custom/BaseSchedulingController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/format/Utils ec/fisa/navigation/Utils dojo/data/ItemFileWriteStore dojo/dom-construct dojox/grid/TreeGrid ec/fisa/mvc/StatefulModel dojox/grid/DataGrid ./_base ec/fisa/dwr/proxy/SchedulingActionDWR".split(" "),function(e,k,n,l,p,q,f,g,r,m,h){return k("ec.fisa.controller.custom.BaseSchedulingController",[l],{tabId:null,pageScopeId:null,model:null,
data:null,breadcrumbId:null,contextPath:e.config.fisaContextPath,repeatId:null,processDate:null,componentCondId:null,btContentPaneId:null,calType:null,mediaData:null,mediaDataSuccessStore:null,mediaDataFailStore:null,constructor:function(a,b,c,d,e){this.tabId=a;this.pageScopeId=b;this.data=c;this.componentCondId=d;this.processDate=c.startDate;this.calType=e;this.model=m({})},initMvc:function(a,b,c){var d=this.data[b];this.model.appendObject([b,"value"],d,a.id,"value",null,!1);this.model.appendObject([b,
"disabled"],c,a.id,"disabled",null,!1);this.model.appendObject([b,"_lastValueReported"],d,a.id,"_lastValueReported",null,!1)},loadRepeatId:function(a){this.repeatId=a;a=dijit.byId(a);a.connect(a,"onChange",e.hitch(this,function(a){this.updateEndDateByRepeat(a)}))},loadFrecuencyId:function(a){this.repeatId=a;a=dijit.byId(a);a.connect(a,"onChange",e.hitch(this,function(a){this.updateFrequency(a)}))},initMediaData:function(a){this.mediaData=a},destroy:function(){null!=this.model&&this.model.clearAllMessages();
this.tableRegistry=this.lovData=this.model=this.data=null},setMessagesPanel:function(a){this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId)this.breadcrumbId=a.getParent().getParent().id;this.updateMsgsPanel(this.initMsgs);this.btContentPaneId=a.getParent().id},updateFrequency:function(a){if(void 0!=a&&null!=a){this.model.setValue(["repeat","disabled"],!1);this.model.setValue(["repeat","value"],"1",!1);var b=this.model.getValue(["startDate","value"]);void 0!=
b&&null!=b&&this.updateEndDate(a,b,1)}else this.model.setValue(["repeat","value"],1,!1),this.model.setValue(["repeat","disabled"],!0),a=this.model.getValue(["startDate","value"]),null!=a&&""!=a||(a=this.processDate,this.model.setValue(["startDate","value"],a,!1)),this.model.setValue(["endDate","value"],a,!1)},updateEndDateByStartDate:function(a){var b=this.model.getValue(["frequency","value"]);void 0!=b&&null!=b?this.updateEndDate(b,a,1):null==b&&(a=this.obtainEndDate(a),this.model.setValue(["endDate",
"value"],a,!1))},updateEndDateByEndDate:function(a){if(null!=a&&""!=a){var b=this.model.getValue(["frequency","value"]),c=this.model.getValue(["startDate","value"]);if(void 0!=b&&null!=b){var d={callbackScope:this};d.errorHandler=e.hitch(this,this.errorHandler);d.callback=this.callBckFnRepeatDwr;SchedulingActionDWR.obtainScheduleRepeatByDates(b,c,a,this.calType,d)}else null==b&&(a=this.obtainEndDate(a),this.model.setValue(["startDate","value"],a,!1))}},callBckFnRepeatDwr:function(a){var b=ec.fisa.controller.utils.getPageController(this.tabId,
this.pageScopeId+"_resourceIn");void 0!==b&&b.clearPanelMessage();this.clearPanelMessage();"cnfrm"==a.wAxn?(a=a.msg,this.model.setValue(["repeat","_lastValueReported"],a[0],!1),this.model.setValue(["repeat","value"],a[0],!1),a=this.obtainEndDate(a[1]),this.model.setValue(["endDate","_lastValueReported"],a,!1),this.model.setValue(["endDate","value"],a,!1)):"error"==a.wAxn&&(void 0!==b?b.updateMsgsPanel(a.aMsgs):this.updateMsgsPanel(a.aMsgs))},updateEndDateByRepeat:function(a){var b=this.model.getValue(["frequency",
"value"]),c=this.model.getValue(["startDate","value"]);void 0!=b&&null!=b&&void 0!=c&&null!=c&&null!=a&&!1==isNaN(a)&&0!=a?this.updateEndDate(b,c,a):(this.model.setValue(["repeat","_lastValueReported"],"1",!1),this.model.setValue(["repeat","value"],"1",!1))},updateEndDate:function(a,b,c){var d={callbackScope:this};d.errorHandler=e.hitch(this,this.errorHandler);d.callback=this.callBckFnEndDateDwr;SchedulingActionDWR.obtainScheduleEndDate(a,b,c,this.calType,d)},callBckFnEndDateDwr:function(a){var b=
ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId+"_resourceIn");void 0!==b&&b.clearPanelMessage();this.clearPanelMessage();"cnfrm"==a.wAxn?(a=this.obtainEndDate(a.msg),this.model.setValue(["endDate","_lastValueReported"],a,!1),this.model.setValue(["endDate","value"],a,!1)):"error"==a.wAxn&&(void 0!==b?b.updateMsgsPanel(a.aMsgs):this.updateMsgsPanel(a.aMsgs))},obtainEndDate:function(a){var b=a;null!=a&&void 0!=a&&"string"==typeof value&&(b=ec.fisa.format.utils.parseLongDate(a));
return b},cancel:function(){ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)},accept:function(){},callBckFnAcceptSchedulingDwr:function(a){if("cnfrm"==a.wAxn)ec.fisa.navigation.utils.showNewBreadCrumbConfirmation("",[a.msg],this.breadcrumbId,this.tabId,this.pageScopeId,"","","");else if("error"==a.wAxn)if(!1==a.errorSchedule){var b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId+"_resourceIn");b.clearPanelMessage();b.updateMsgsPanel(a.aMsgs)}else this.updateMsgsPanel(a.aMsgs)},
isComponentMsg:function(a){return"fieldId"in a&&null!=a.fieldId&&""!=a.fieldId},addComponentMsg:function(a){this.model.setMessage([a.fieldId,"value"],a.fieldMsg,a.origLevel)},initMediaSucessDataGrid:function(a){var b=new f({data:{identifier:"id",items:this.mediaData.success}});this.mediaDataSuccessStore=b;a=g.create("div",null,a.domNode);b=new h({store:b,structure:[{name:"",field:"shortName",width:"250px"},{name:"",field:"value",width:"150px",editable:!1,formatter:function(a,b,e){return ec.fisa.format.utils.formatterMediaNotificationValue(a,
b,e)}}],autoHeight:!0,autoWidth:!0,selectionMode:"none"},a);b.tabId=this.tabId;b.pageScopeId=this.pageScopeId;b.connect(b,"postrender",function(){(null==this.domNode.firstElementChild?this.domNode.children[0]:this.domNode.firstElementChild).style.display="none"});b.startup()},initMediaFailDataGrid:function(a){var b=new f({data:{identifier:"id",items:this.mediaData.fail}});this.mediaDataFailStore=b;a=g.create("div",null,a.domNode);b=new h({store:b,structure:[{name:"",field:"shortName",width:"250px"},
{name:"",field:"value",width:"150px",editable:!1,formatter:function(a,b,e){return ec.fisa.format.utils.formatterMediaNotificationValue(a,b,e)}}],autoHeight:!0,autoWidth:!0},a);b.tabId=this.tabId;b.pageScopeId=this.pageScopeId;b.connect(b,"postrender",function(){(null==this.domNode.firstElementChild?this.domNode.children[0]:this.domNode.firstElementChild).style.display="none"});b.startup()}})});
//@ sourceMappingURL=BaseSchedulingController.js.map