//>>built
define("ec/fisa/controller/custom/BtDocumentController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ./_base dojox/form/Uploader dojo/_base/connect dojox/grid/DataGrid dojo/data/ItemFileWriteStore ec/fisa/widget/OutputText dojo/dom-construct ec/fisa/controller/BaseController dojox/form/uploader/plugins/IFrame ec/fisa/widget/DocumentActions dojox/mvc dojox/mvc/StatefulModel dojo/dom-class dijit/form/TextBox dojox/lang/functional/object ec/fisa/controller/Utils".split(" "),function(d,f,r,s,
t,h,k,l,m,e,n,u,p,v,w,x,q){return f("ec.fisa.controller.custom.BtDocumentController",[n],{tabId:null,model:null,pageScopeId:null,pageTreeGridScopeId:null,data:null,componentFileUploadedText:null,fileUploadedFullPath:null,fileName:null,fileContentType:null,fileLength:null,shortDateFormatTree:null,dialogComponentId:null,keywordStore:null,isLovModal:!0,constructor:function(a,b,c){this.tabId=a;this.pageScopeId=b;this.pageTreeGridScopeId=c;this.inherited(arguments);this.model=dojox.mvc.newStatefulModel({data:{}});
this.keywordStore=[]},setDialogComponent:function(a){a=a.getParent().getParent();this.data=a.data;a.treeGridNodeId=this.data.treeGridNodeId;a.popupPageScopeId=this.pageScopeId;this.dialogComponentId=a.id},setDialogComponentHistory:function(a){this.dialogComponentId=a.getParent().id},initMvc:function(a,b){var c=new dojox.mvc.StatefulModel({data:this.data[b]});this.model.add(b,c);a.set("ref",this.model[b])},_getDataAttr:function(){return this.data},_setDataAttr:function(a){this.data=a},setComponentFileUploadedText:function(a){this.componentFileUploadedText=
a;var b=d.byId("spanFileName");b.style.display="none";a.set("value","");this.data&&!1==this.data.newDocument&&(a.set("value",this.data.fileName),b.style.display="block")},setShortDateFormatTree:function(a){this.shortDateFormatTree=a},documentCallBack:function(a,b,c){a&&(a.status&&"success"==a.status?(c.overlay.innerHTML="success!",c.reset(),this.fisaController.fileUploadedFullPath=a.details.completeFileName,this.fisaController.fileName=a.details.fileName,this.fisaController.fileContentType=a.details.contentType,
this.fisaController.fileLength=a.details.fileLength,this.fisaController.componentFileUploadedText.set("value",a.details.fileName),d.byId("spanFileName").style.display="block"):(a=a.details,this.fisaController.clearPanelMessage(),this.fisaController.updateMsgsPanel(a),c.reset(),c.overlay.innerHTML="error"))},attachDocumentCallBack:function(a){a.fisaController=this;h.connect(a,"onComplete",null,this.documentCallBack)},initDataGrid:function(a,b){var c=e.create("table",{cellpadding:0,cellspacing:10,border:0,
width:"100%"},a.containerNode),g=e.create("tbody",null,c);null!=this.data&&null!=this.data.fisaPopupDocumentKeywords&&d.forEach(this.data.fisaPopupDocumentKeywords,function(a,b){var c=e.create("tr",null,g),d=e.create("td",{width:"40%"},c),c=e.create("td",null,c);e.create("span",null,d).innerHTML=a.keywordName;d=e.create("span",null,c);d=new q({value:null==a.value?"":a.value,"keyword-id":a.id,maxLength:a.maximumLength},d);d.startup();a.cmpid=d.id;this.keywordStore[b]=a},this)},initHistoryGrid:function(a){var b=
dijit.byId(this.dialogComponentId),c=b.labels,b=b.documentHisArray;a=e.create("div",null,a.domNode);if(null==b||0>=b.length)new m({value:c.emptyRowLabel},a);else{var g=[{name:c.auditRecordNumber,field:"recordNumber",width:"100px"},{name:c.auditInputUserId,field:"userName",width:"100px"},{name:c.auditInputDate,field:"iDate",width:"100px",editable:!1,formatter:function(a,b,c){return ec.fisa.format.utils.formatDataGridDate(a,b,c)}},{name:c.auditInstitucion,field:"companyName",width:"100px"},{name:c.treeTableDetailColumn,
field:"description",width:"100px",formatter:function(a,b,c){return ec.fisa.format.utils.formatDataGridHistoryDetail(a,b,c)}},{name:c.optionsColumn,field:"a",width:"100px",cellType:dojox.grid.cells._Widget,editable:!1,widgetClass:p,formatter:function(a,b,c){return ec.fisa.format.utils.formatterDocumentsHistoryOptions(a,b,c)}}],b=new l({data:{identifier:"id",items:b}}),b=new k({store:b,structure:g,autoHeight:!0,autoWidth:!0,selectionMode:"none"},a);b.shortDateFormatTree=this.shortDateFormatTree;b.labels=
c;b.tabIdvar=this.tabId;b.pageScopeIdvar=this.pageTreeGridScopeId;b.contextPath=d.config.fisaContextPath;b.startup()}},popUpCancel:function(){dijit.byId(this.dialogComponentId).hide()},popUpAccept:function(){dijit.byId(this.messagesPanelId).clearAllMessages();var a=this.model.toPlainObject(),b=[];d.forEach(this.keywordStore,function(a,c){var e=d.clone(a),f=dijit.byId(a.cmpid);e.value=f.get("value");delete e.cmpid;b[c]=e},this);a.fisaPopupDocumentKeywords=b;if(!0==this.data.newDocument&&null==this.fileUploadedFullPath)this.updateMsgsPanel([{level:{level:4E4},
summary:this.data.msgErrorNoDocument}]);else{!1==this.data.newDocument&&null==this.fileUploadedFullPath&&(a.fileUploaded=!0);var c={callbackScope:{tabId:this.tabId,pageTreeGridScopeId:this.pageTreeGridScopeId,btDocController:this}};c.errorHandler=d.hitch(this,this.errorHandler);c.callback=this.callBckFnctnDwr;a.fileUploadedFullPath=this.fileUploadedFullPath;a.fileName=this.fileName;a.fileContentType=this.fileContentType;a.fileLength=this.fileLength;a.treeGridNodeId=this.data.treeGridNodeId;DocumentControllerDWR.processReturnPopupDocument(a,
this.tabId,this.pageTreeGridScopeId,c)}},callBckFnctnDwr:function(a){if("success"==a.status){var b=dijit.byId(this.btDocController.dialogComponentId),c=b.treeGrid;c&&(ec.fisa.controller.utils.updateRowTreeGrid(c,a),ec.fisa.controller.utils.getPageController(this.tabId,this.pageTreeGridScopeId).clearPanelMessage());b.destroyRecursive()}else this.btDocController.componentFileUploadedText.set("value",""),d.byId("spanFileName").style.display="none",this.btDocController.updateMsgsPanel(a.details)},setSizeUploadComponents:function(a){a.resize(ec.fisa.controller.utils.getModalSize(0.65))}})});
//@ sourceMappingURL=BtDocumentController.js.map