//>>built
define("ec/fisa/controller/custom/CustomBtController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dijit/focus dojo/aspect ec/fisa/controller/BaseController ec/fisa/format/Utils ec/fisa/widget/Link ec/fisa/navigation/Utils dojo/data/ItemFileWriteStore dojo/dom-construct dojo/dom-geometry dijit/tree/ForestStoreModel dojox/grid/TreeGrid ec/fisa/widget/DocumentActions ec/fisa/mvc/StatefulModel dojo/on ec/fisa/controller/custom/QtController dojo/topic dojo/dom-style dojox/mvc dojox/mvc/StatefulModel ec/fisa/grid/FisaEditableGridDirect ec/fisa/widget/DialogSecurity ./_base ec/fisa/widget/DateTextBox dojox/lang/functional/object ec/fisa/dwr/proxy/BtControllerDWR ec/fisa/dwr/proxy/EventReportActionDWR ec/fisa/dwr/proxy/RuleFieldSelectorControllerDWR dojox/lang/functional ec/fisa/widget/Select ec/fisa/grid/FisaFormGrid".split(" "),
function(e,l,m,q,n,p,r,s,t,u,v,w,x,y,z,A,B,C,D,h,E,F){var k=l("ec.fisa.controller.custom.CustomBtController",[p],{tabId:null,pageScopeId:null,model:null,data:null,documentData:null,comboStatusOptions:null,initMsgs:null,shortDateFormatTree:null,breadcrumbId:null,btnsContainer:null,selectDataMap:null,lovData:null,labels:null,btId:null,actionId:null,contextPath:e.config.fisaContextPath,isDisabled:null,btActionMode:null,tableRegistry:null,treeGridDocuments:null,saveAsTemplateChckBoxId:null,notificationAdditionalsWdgId:null,
initLabels:null,btContentPaneId:null,dateFields:null,secBeforeListFactor:null,secAfterListFactor:null,subscriptions:null,parentConfBtPageScopeId:null,documentContentPaneWdgId:null,btTabContainerId:null,selectComponentToReload:null,selectIdMap:null,buttonLabel:"Accept",sequenceBtScheduleButtonData:null,skinParameters:null,data:null,constructor:function(a,b,c){this.tabId=a;this.pageScopeId=b;this.secBeforeListFactor=c.secBeforeListFactor;this.secAfterListFactor=c.secAfterListFactor;this.initLabels=
c.initLabels;this.isSequence=c.isSequence;this.btActionMode=c.btActionMode;this.btId=c.btId;this.notificationAdditionalsWdgId=[];this.skinParameters=c.skinParameters;void 0!=c.aMsgs&&(this.initMsgs=c.aMsgs);this.data={};this.model=dojox.mvc.newStatefulModel({data:{}});this.verifyBeforeSecurity();delete a;delete b;delete c.initLabels;delete c.secBeforeListFactor;delete c.secAfterListFactor;delete c.isSequence;delete c.actionId;delete c.skinParameters},mergeObjects:function(a,b){a||(a={});if(b)for(var c in b)a[c]=
b[c];return a},destroy:function(){this.notificationAdditionalsWdgId=this.initMsgs=this.tableRegistry=this.lovData=this.model=this.data=null;dojox.lang.functional.forIn(this.subscriptions,function(a,b){a.remove&&m.isFunction(a.remove)&&a.remove()},this)},verifyBeforeSecurity:function(){null!=this.secBeforeListFactor&&(void 0!=this.secBeforeListFactor&&0<this.secBeforeListFactor.length&&"true"!=this.showConfirmation)&&this.createDialogSecurityFactor(this.secBeforeListFactor)},verifyAfterSecurity:function(a){null!=
this.secAfterListFactor&&void 0!=this.secAfterListFactor&&0<this.secAfterListFactor.length?this.createDialogSecurityFactor(this.secAfterListFactor).dlgSuccessEvent=e.hitch(this,function(a,c){this._execActionInternal(a)},a):this._execActionInternal(a)},verifyAfterSecuenceSecurity:function(a,b){null!=this.secAfterListFactor&&void 0!=this.secAfterListFactor&&0<this.secAfterListFactor.length&&("true"!=this.showDocuments||"true"!=this.showConfirmation)?this.createDialogSecurityFactor(this.secAfterListFactor).dlgSuccessEvent=
e.hitch(this,function(a,b,f){this._handleSeqNextActionInternal(a,b)},a,b):this._handleSeqNextActionInternal(a,b)},createDialogSecurityFactor:function(a){var b=ec.fisa.controller.utils.getGlobalModalSize(0.5);b.h+=100;a=new ec.fisa.widget.DialogSecurity({title:this.initLabels.titleSecurityPopup,draggable:!1,wdgtWidth:b.w,wdgtHeight:b.h,tabId:this.tabId,secListFactor:a,pageScopeId:this.pageScopeId+"sec_pop",style:{width:b.w+"px",height:b.h+"px"},dlgCancelEvent:e.hitch(this,function(a){this.cancelAuthenticationFactorDialog()})});
a.show();return a},getComponent:function(a,b){return this.model.getComponent([a,"dataMessage","fields",b,"value"])},addParamToModel:function(a){var b=a["bt-id"],c=a["field-id"],d=null;this.data&&(this.data[b]&&this.data[b].dataMessage)&&(d=this.data[b].dataMessage.fields[c]);null==d?(d={value:"",complement:null},a._fStarted=!0):null==d.value?(d.value="",a._fStarted=!0):""==d.value&&(a._fStarted=!0);var f=!1;a instanceof ec.fisa.grid.FisaEditableGridDirect?f=!0:a instanceof ec.fisa.grid.FisaFormGrid&&
(f=!0);this.model.contains(b)?this.model.contains([b,"dataMessage","fields",c])&&(!0==f?this.model.setValue([b,"dataMessage","fields",c,"multivalueList"],d.value):this.model.setValue([b,"dataMessage","fields",c,"value"],d.value)):(!0==f?this.model.appendObject([b,"dataMessage","fields",c,"multivalueList"],d.value,a.id,"value",null,!1):this.model.appendObject([b,"dataMessage","fields",c,"value"],d.value,a.id,"value",null,!1),f=null,void 0!=d.enabled&&(f=d.enabled),this.model.appendObject([b,"dataMessage",
"fields",c,"enabled"],f,a.id,"enabled",null,!1),a.hasCompl&&this.model.appendObject([b,"dataMessage","fields",c,"complement"],d.complement,a.id,"complement",null,!1));if(a instanceof ec.fisa.widget.Select&&(!0==a.hasBeneficiarySelectionLink||"true"==a.hasBeneficiarySelectionLink))this.selectComponentToReload=a},containsFieldModel:function(a,b){return this.model.contains([a,"dataMessage","fields",b,"value"])},getFieldModel:function(a,b){return this.model.getValue([a,"dataMessage","fields",b,"value"])},
setFieldModelValue:function(a,b,c,d){this.model.setValue([a,"dataMessage","fields",b,"value"],c,d)},setFieldModelEnabled:function(a,b,c){this.model.setValue([a,"dataMessage","fields",b,"enabled"],c)},setFieldModelComplement:function(a,b,c){this.model.setValue([a,"dataMessage","fields",b,"complement"],c)},getFieldModelComplement:function(a,b){return this.model.getValue([a,"dataMessage","fields",b,"complement"])},setIsDisabled:function(a){this.isDisabled=a},addControllerRef:function(a){a.fc=this},handleCancelAction:function(){var a=
dijit.byId(this.breadcrumbId).selectedChildWidget,b=!1;if(null!=a.postClose&&void 0!=a.postClose&&void 0!=a.postCloseScope&&null!=a.postCloseScope){var c=dijit.byId(a.postCloseScope);a.postClose.apply(c,a.postCloseArgs)}else b=!0;null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId);null!=a&&(null!=a.postCloseArgs&&void 0!=a.postCloseArgs&&null!=a.postCloseArgs.btBreadCrumbId&&
void 0!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postClose&&void 0!=a.postCloseScope)&&ec.fisa.navigation.utils.closeCurrentBreadCrumb(a.postCloseArgs.btBreadCrumbId);b&&ec.fisa.menu.utils.addEmptyTabAllClosed(e.config.fisaNewTabLabel)},handleWindowAction:function(a){null!=this.fromAgenda&&("true"==this.fromAgenda&&"error"!=a.wAxn)&&(a.wAxn="close");if("close"==a.wAxn){a=dijit.byId(this.breadcrumbId).selectedChildWidget;var b=!1;if(null!=a.postClose&&void 0!=a.postClose&&void 0!=a.postCloseScope&&
null!=a.postCloseScope){var c=dijit.byId(a.postCloseScope);a.postClose.apply(c,a.postCloseArgs)}else b=!0;null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId);null!=a&&(null!=a.postCloseArgs&&void 0!=a.postCloseArgs&&null!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postCloseArgs.btBreadCrumbId&&void 0!=a.postClose&&void 0!=a.postCloseScope)&&ec.fisa.navigation.utils.closeCurrentBreadCrumb(a.postCloseArgs.btBreadCrumbId);
b&&ec.fisa.menu.utils.addEmptyTabAllClosed(e.config.fisaNewTabLabel)}else"cnfrm"==a.wAxn?this.handleConfirmationBt(a):"error"==a.wAxn?(this.updateMsgsPanel(a.aMsgs),this.refreshTableRegistry()):"close\x26refresh"==a.wAxn?(ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId),b=ec.fisa.controller.utils.getPageController(a.parentFisaTabId,a.parentFisaPageScopeId),void 0!=b&&b instanceof k&&(a=dijit.byId(b.tableRegistry[a.parentBtId][a.parentEntityId]),void 0!=a&&null!=a&&a.refresh())):
"showDlg"==a.wAxn?void 0!=this.isSequence&&null!=this.isSequence&&"true"===this.isSequence?ec.fisa.navigation.utils.templateSequenceDlgShowAction(a.respBtLabels,this.tabId,this.pageScopeId,this.sequenceId):ec.fisa.navigation.utils.templateDlgShowAction(a.respBtLabels,this.tabId,this.pageScopeId,this.btId,this.btActionMode,this.isSequence):alert("unknown action!")},handleConfirmationBt:function(a){var b=a.respBtLabels[0],c=a.aMsgs,d=a.postBtId,f=a.pBtId,g=a.postBtIdDataKey,e=a.principalPostBtIdDataKey,
h=a.parentBtInAuthorization,k=a.showReportModule;a=a.showReportAuto;dijit.byId(this.messagesPanelId).clearAllMessages();this.model.clearAllMessages();null==d?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(b,c,this.breadcrumbId,this.tabId,this.pageScopeId,this.btId,this.btActionMode,this.isSequence,k,a):(b=dijit.byId(this.breadcrumbId),ec.fisa.navigation.utils.showPostBtBreadCrumb(b.params.title,c,this.tabId,this.pageScopeId,d,f,this.btContentPaneId,g,e,this.isSequence,k,a,h,!1))},setMessagesPanel:function(a){this.inherited(arguments);
if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId){var b=ec.fisa.controller.utils.findCurrentBreadCrumb(a);b&&(this.breadcrumbId=b.id)}this.updateMsgsPanel(this.initMsgs);this.btContentPaneId=a.getParent().getParent().id;delete this.initMsgs},setBtId:function(a){this.btId=a},setActionId:function(a){this.actionId=a},setShortDateFormatTree:function(a){this.shortDateFormatTree=a},setLabels:function(a){this.labels=a},setBreadcrumb:function(a){this.breadcrumbId=a.id},setQtDocBreadcrumb:function(a){if(a=
ec.fisa.controller.utils.findCurrentBreadCrumb(a))this.breadcrumbId=a.id},showMessages:function(a){null!=a&&(this.clearPanelMessage(),this.updateMsgsPanel(a.aMsgs))},clearPanelMessage:function(){this.messagesPanelId&&dijit.byId(this.messagesPanelId).clearAllMessages()},getSelectedIndex:function(a){var b=-1;a=a.getOptions();for(var c=0,c=0;c<a.length;c++)if(!0===a[c].selected){b=c;break}return b-1},setBtTabContainerId:function(a){this.btTabContainerId=a;a=dijit.byId(a);a.tabId=this.tabId;a.pageScopeId=
this.pageScopeId;n.around(a,"selectChild",function(a){return function(c){if(this.selectedChildWidget!=c){var d=this.selectedChildWidget.action_mode,f=this.selectedChildWidget["field-id"],g=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);g.clearPanelMessage();null!=g.model&&g.model.clearAllMessages();var h={callbackScope:{btController:g,selectChild:a,arguments:arguments,tabContainer:this}};h.errorHandler=e.hitch(g,g.errorHandler);h.callback=g._updatedFtmLaunchCallBack;g=g.model.toPlainObject();
EventActionDWR.validateBtKeys(g,this.tabId,this.pageScopeId,d,f,h)}}})},cancelAuthenticationFactorDialog:function(){ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).cancel()},_execActionInternal:function(a){var b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);a["fisa-action-id"]&&(this.btActionMode=a["fisa-action-id"]);"IN"==this.btActionMode||"UP"==this.btActionMode?b.save(a):"DE"==this.btActionMode&&b.remove(a)},execAction:function(a){var b={};a?(b["fisa-action-id"]=
a.btAction,b["fisa-bt-id"]=a.btId,b["fisa-parameters"]=a.parameters):(b["fisa-action-id"]=this.btActionMode,b["fisa-bt-id"]=this.btId);a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).validateBtInfo(b);null!=a&&("cnfrm"==a.wAxn?this.verifyAfterSecurity(a):"error"==a.wAxn&&(this.clearPanelMessage(),this.updateMsgsPanel(a.aMsgs)))},bindToModel:function(a,b,c){var d=this.data[b];if(void 0===d||null==d)d="";d=new dojox.mvc.StatefulModel({data:d});this.model.add(b,d);a.set("ref",
this.model[b]);a.set("disabled","true"===c)},_setVisible:function(a){h.set(a.domNode,"display","inline-block")},_setVisiblePanel:function(a){a.style.display="block";h.set(a,"display","block")},_setNotVisible:function(a){h.set(a.domNode,"display","none")},loadNotificationAdditionalsWdgId:function(a,b){this.notificationAdditionalsWdgId.push({btId:b,notifWdgId:a})},updateNotificationData:function(a,b){null!=this.notificationAdditionalsWdgId&&void 0!=this.notificationAdditionalsWdgId&&e.forEach(this.notificationAdditionalsWdgId,
e.hitch(this,function(c){c.btId==b&&dijit.byId(c.notifWdgId).set("value",a)}))},_addNotificationValData:function(){var a={};null!=this.notificationAdditionalsWdgId&&void 0!=this.notificationAdditionalsWdgId&&e.forEach(this.notificationAdditionalsWdgId,e.hitch(this,function(b){var c=b.btId;b=dijit.byId(b.notifWdgId).get("value");null==a[c]&&void 0==a[c]&&(a[c]={});a[c]=b}));return a}});return k});
//@ sourceMappingURL=CustomBtController.js.map