//>>built
define("ec/fisa/controller/custom/PlataformaComercialController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ./_base ec/fisa/controller/BaseController ec/fisa/navigation/Utils ec/fisa/menu/Utils dojo/dom-style dojo/dom-construct dojo/dom-geometry dojox/mvc dojo/on ec/fisa/message/ConfirmationPanel ec/fisa/dwr/proxy/PlataformaComercialDWR ec/fisa/widget/Utils".split(" "),function(e,m,q,r,n,s,p,f,t,u,v,w,x){return m("ec.fisa.controller.custom.PlataformaComercialController",[n,p],{tabId:null,
pageScopeId:null,breadCrumbId:null,msg:null,currentBreadCrumbId:null,btContentPaneId:null,parentPageScopeId:null,initData:null,tabContainerId:null,apellidoPaternoIdTxtBox:null,apellidoMaternoIdTxtBox:null,primerNombreIdTxtBox:null,segundoNombreIdTxtBox:null,juridicoNombreIdText:null,nombreCompletoId:null,agencyTxt:null,executiveTxt:null,sourceTxt:null,clienteNaturalContentPaneId:null,juridicoContentPaneId:null,documentTypeComboId:null,personTypeComboId:null,searchTypeComboId:null,searchTypeLovId:null,
documentNumberTxId:null,borderContainerId:null,juridicoNewButtonId:null,menuBarId:null,menuEnabled:null,titlePaneId:null,labels:null,selectDataMap:null,clientNewButtonId:null,itemDisabled:null,constructor:function(a,b,d,c,e){this.tabId=a;this.pageScopeId=b;this.initData=d;this.labels=c;this.menuEnabled=!1;this.selectDataMap=e},initMenu:function(a){this.menuBarId=a+"menuBarId";this.itemDisabled={};this.updateHorizontalMenu(this.initData.menuItems,a,this.menuBarId,!0);this.findParentMenuItemByHotkey("M_CLIENT");
this.disableMenu()},findParentMenuItemByHotkey:function(a){var b=dijit.byId(this.menuBarId);e.forEach(b.getChildren(),e.hitch(this,function(b){a==b.hotKey&&(this.itemDisabled[a]=b.id)}))},enableMenu:function(){ec.fisa.widget.utils.enableWidget(this.menuBarId);var a=dijit.byId(this.menuBarId);e.forEach(a.getChildren(),e.hitch(this,function(a){ec.fisa.widget.utils.enableWidget(a.id)}))},loadPlatformPersonTypeCombo:function(a){a=dijit.byId(this.personTypeComboId);a.set("options",this.selectDataMap.REQUEST_PLATFORM_PERSON_TYPE);
a.reset()},loadDefaultPlatformDocumentTypeCombo:function(){this.loadPlatformDocumentTypeCombo(1)},loadPlatformDocumentTypeCombo:function(a){var b=dijit.byId(this.documentTypeComboId);b.set("options",this.selectDataMap["REQUEST_PLATFORM_DOCUMENT_TYPE"+a]);b.reset()},loadPlatformSearchTypeCombo:function(){var a=dijit.byId(this.searchTypeComboId);a.set("options",this.selectDataMap.REQUEST_PLATFORM_SEARCH_TYPE);a.reset()},disableMenu:function(){ec.fisa.widget.utils.disableWidget(this.menuBarId);var a=
dijit.byId(this.menuBarId);e.forEach(a.getChildren(),e.hitch(this,function(a){ec.fisa.widget.utils.disableWidget(a.id)}))},addHorizontalMenuItems:function(a,b){null!=b&&e.forEach(b,function(b){var c=b.hotKey;if(null!=b.childrenItems){var g=new dijit.Menu({parentMenu:a,baseClass:"dijitHorizontalSubMenu"}),h=new dijit.PopupMenuItem({label:b.name,popup:g,baseClass:"dijitHorizontalSubMenuItem"});a.addChild(h);f.set(h.arrowWrapper,"visibility","");this.addHorizontalMenuItems(g,b.childrenItems);null!=c&&
(this.itemDisabled[c]=h.id)}else g={onClick:e.hitch(this,function(a){this.menuTreeOnClick(a,null)},b)},g.label=b.name,g.baseClass="dijitHorizontalMenuItem",b=new dijit.MenuItem(g),a.addChild(b),null!=c&&(this.itemDisabled[c]=b.id)},this)},closeTab:function(){},menuTreeOnClick:function(a,b){try{if(null!=a&&(!b||!b.isExpandable)){this.clearPanelMessage();var d=dijit.byId(this.documentTypeComboId).get("value"),c=dijit.byId(this.personTypeComboId).get("value"),g=dijit.byId(this.documentNumberTxId).get("value"),
f=dijit.byId(this.apellidoPaternoIdTxtBox).get("value"),k=dijit.byId(this.apellidoMaternoIdTxtBox).get("value"),l=dijit.byId(this.primerNombreIdTxtBox).get("value"),m=dijit.byId(this.segundoNombreIdTxtBox).get("value");a.customParam=e.toJson({P_PERSON_LEGAL_ID:g,P_PERSON_LEGAL_TYPE:d,P_PERSON_TYPE:c,_AUTO:"1",dataKey:d+"|"+g+"|"+f+"|"+k+"|"+l+"|"+m+"|"+c});a.FISATabId=this.tabId;a.FisaPageScopeId=this.pageScopeId;ec.fisa.menu.utils.loadMenuTabContainer(a,!1,this.tabContainerId,this.tabContainerId+
"inicio",!0)}}catch(n){console.log(n)}},tabIdAdd:function(a){this.tabContainerId=a},apellidoPaternoSet:function(a){this.apellidoPaternoIdTxtBox=a;a=dijit.byId(a);a.textbox.style.textTransform="uppercase";a.connect(a,"onChange",e.hitch(this,function(a){var d=dijit.byId(this.apellidoPaternoIdTxtBox);if(!0!=d.notCallOnChange){this.clearPanelMessage();var c={callbackScope:this};c.errorHandler=e.hitch(this,this.errorHandler);c.callback=this._valueValidationCallBack;PlataformaComercialDWR.valueValidation(d.fid,
a,d.id,c)}d.notCallOnChange=!1}))},apellidoMaternoSet:function(a){this.apellidoMaternoIdTxtBox=a;a=dijit.byId(a);a.textbox.style.textTransform="uppercase";a.connect(a,"onChange",e.hitch(this,function(a){var d=dijit.byId(this.apellidoMaternoIdTxtBox);if(!0!=d.notCallOnChange){this.clearPanelMessage();var c={callbackScope:this};c.errorHandler=e.hitch(this,this.errorHandler);c.callback=this._valueValidationCallBack;PlataformaComercialDWR.valueValidation(d.fid,a,d.id,c)}d.notCallOnChange=!1}))},primerNombreSet:function(a){this.primerNombreIdTxtBox=
a;a=dijit.byId(a);a.textbox.style.textTransform="uppercase";a.connect(a,"onChange",e.hitch(this,function(a){var d=dijit.byId(this.primerNombreIdTxtBox);if(!0!=d.notCallOnChange){this.clearPanelMessage();var c={callbackScope:this};c.errorHandler=e.hitch(this,this.errorHandler);c.callback=this._valueValidationCallBack;PlataformaComercialDWR.valueValidation(d.fid,a,d.id,c)}d.notCallOnChange=!1}))},segundoNombreSet:function(a){this.segundoNombreIdTxtBox=a;a=dijit.byId(a);a.textbox.style.textTransform=
"uppercase";a.connect(a,"onChange",e.hitch(this,function(a){var d=dijit.byId(this.segundoNombreIdTxtBox);if(!0!=d.notCallOnChange){this.clearPanelMessage();var c={callbackScope:this};c.errorHandler=e.hitch(this,this.errorHandler);c.callback=this._valueValidationCallBack;PlataformaComercialDWR.valueValidation(d.fid,a,d.id,c)}d.notCallOnChange=!1}))},agencyTxtSet:function(a){this.agencyTxt=a},executiveTxtSet:function(a){this.executiveTxt=a},sourceTxtSet:function(a){this.sourceTxt=a},juridicoNombreSet:function(a){this.juridicoNombreIdText=
a;a=dijit.byId(a);a.textbox.style.textTransform="uppercase";a.connect(a,"onChange",e.hitch(this,function(a){var d=dijit.byId(this.juridicoNombreIdText);if(!0!=d.notCallOnChange){this.clearPanelMessage();var c={callbackScope:this};c.errorHandler=e.hitch(this,this.errorHandler);c.callback=this._valueValidationCallBack;PlataformaComercialDWR.valueValidation(d.fid,a,d.id,c)}d.notCallOnChange=!1}))},clienteNaturalContentPanetSet:function(a){this.clienteNaturalContentPaneId=a},juridicoContentPaneSet:function(a){this.juridicoContentPaneId=
a;a=dijit.byId(this.juridicoContentPaneId);f.set(a.domNode,"display","none")},_valueValidationCallBack:function(a){"error"==a.wAxn&&(this.updateMsgsPanel(a.aMsgs),a=dijit.byId(a.id),a.notCallOnChange=!0,a.set("value",""))},setPersonTypeComboId:function(a){this.personTypeComboId=a;a=dijit.byId(this.personTypeComboId);a.connect(a,"onChange",e.hitch(this,function(a){this.personTypeChangeCallBack(a);this.resetComponents()}))},setDocumentTypeComboId:function(a){this.documentTypeComboId=a;a=dijit.byId(this.documentTypeComboId);
a.connect(a,"onChange",e.hitch(this,function(a){a=dijit.byId(this.documentTypeComboId);!0!=a.notCallOnChange&&this.resetComponents();a.notCallOnChange=!1}))},personTypeChangeCallBack:function(a){var b=dijit.byId(this.documentTypeComboId);b.removeOption(b.getOptions());this.loadPlatformDocumentTypeCombo(a);var b=dijit.byId(this.clienteNaturalContentPaneId),d=dijit.byId(this.juridicoContentPaneId);"1"==a?(f.set(b.domNode,"display","block"),f.set(d.domNode,"display","none")):(f.set(b.domNode,"display",
"none"),f.set(d.domNode,"display","block"))},setDocumentNumberTxId:function(a){this.documentNumberTxId=a;dijit.byId(a).textbox.style.textTransform="uppercase"},resetComponents:function(){this.clearPanelMessage();dijit.byId(this.documentNumberTxId).set("value","");this.resetComponentsInterno();this.enableComponents(!1);this.closeCurrentTab()},resetComponentsInterno:function(){var a=dijit.byId(this.apellidoPaternoIdTxtBox);if(!0==a.disabled||""!=a.get("value"))a.notCallOnChange=!0;a.set("value","");
a=dijit.byId(this.apellidoMaternoIdTxtBox);if(!0==a.disabled||""!=a.get("value"))a.notCallOnChange=!0;a.set("value","");a=dijit.byId(this.primerNombreIdTxtBox);if(!0==a.disabled||""!=a.get("value"))a.notCallOnChange=!0;a.set("value","");a=dijit.byId(this.segundoNombreIdTxtBox);if(!0==a.disabled||""!=a.get("value"))a.notCallOnChange=!0;a.set("value","");a=dijit.byId(this.juridicoNombreIdText);if(!0==a.disabled||""!=a.get("value"))a.notCallOnChange=!0;a.set("value","");dijit.byId(this.agencyTxt).set("value",
"");dijit.byId(this.executiveTxt).set("value","");dijit.byId(this.sourceTxt).set("value","");this.disableMenu()},enableComponents:function(a){if(!1==a){ec.fisa.widget.utils.disableWidget(this.apellidoPaternoIdTxtBox);ec.fisa.widget.utils.disableWidget(this.apellidoMaternoIdTxtBox);ec.fisa.widget.utils.disableWidget(this.primerNombreIdTxtBox);ec.fisa.widget.utils.disableWidget(this.segundoNombreIdTxtBox);ec.fisa.widget.utils.disableWidget(this.juridicoNombreIdText);a=dijit.byId(this.juridicoNewButtonId);
var b=dijit.byId(this.clientNewButtonId);f.set(a.domNode,"display","none");f.set(b.domNode,"display","none")}else a=dijit.byId(this.personTypeComboId).get("value"),ec.fisa.widget.utils.enableWidget(this.apellidoPaternoIdTxtBox),ec.fisa.widget.utils.enableWidget(this.apellidoMaternoIdTxtBox),ec.fisa.widget.utils.enableWidget(this.primerNombreIdTxtBox),ec.fisa.widget.utils.enableWidget(this.segundoNombreIdTxtBox),ec.fisa.widget.utils.enableWidget(this.juridicoNombreIdText),1==a?(b=dijit.byId(this.clientNewButtonId),
f.set(b.domNode,"display","block")):2==a&&(a=dijit.byId(this.juridicoNewButtonId),f.set(a.domNode,"display","block"))},closeCurrentTab:function(){var a=dijit.byId(this.tabContainerId),b=a.selectedChildWidget;if(b){if(b.onClose)b.onClose();a.removeChild(b);b.destroyRecursive()}},setSearchTypeComboId:function(a){this.searchTypeComboId=a},setSearchTypeLoVId:function(a){this.searchTypeLovId=a},refreshData:function(){this.clearPanelMessage();var a=dijit.byId(this.documentNumberTxId).get("value");if(void 0==
a||null==a||""==a)a=this.generateMsg(this.labels.required,"",4E4),this.resetComponents(),this.updateMsgsPanel(a);else{var b=dijit.byId(this.documentTypeComboId).get("value"),d=dijit.byId(this.personTypeComboId).get("value");this.findCustomerData(a,b,d)}},findCustomerData:function(a,b,d){var c={callbackScope:this};c.errorHandler=e.hitch(this,this.errorHandler);c.callback=this._findCustomerCallBack;PlataformaComercialDWR.findCustomer(a,b,d,this.tabId,this.pageScopeId,c)},_findCustomerCallBack:function(a){"error"==
a.wAxn?(this.resetComponents(),this.updateMsgsPanel(a.aMsgs)):"cnfrm"==a.wAxn&&(void 0!=a.response&&(!0==a.response.newClient?(this.enableComponents(!0),this.resetComponentsInterno()):(this.enableComponents(!1),this.resetComponents(),this.setComponentsValue(a),!1==a.response.disableMenu&&this.enableMenu(),dojox.lang.functional.forIn(this.itemDisabled,function(a,d){ec.fisa.widget.utils.enableWidget(a)},this),null!=a.response.itmDisabled&&0<a.response.itmDisabled.length&&e.forEach(a.response.itmDisabled,
e.hitch(this,function(a){ec.fisa.widget.utils.disableWidget(this.itemDisabled[a])})))),void 0!=a.aMsgs&&null!=a.aMsgs&&this.updateMsgsPanel(a.aMsgs))},clearData:function(){this.resetComponents()},setComponentsValue:function(a){dijit.byId(this.personTypeComboId).set("value",a.CLIENT_TYPE,!1);this.personTypeChangeCallBack(a.CLIENT_TYPE);var b=dijit.byId(this.documentTypeComboId);b.notCallOnChange=!0;b.set("value",a.documentTypeObj,!1);dijit.byId(this.documentNumberTxId).set("value",a.numDocumentObj);
a=a.response;b=dijit.byId(this.apellidoPaternoIdTxtBox);!0==b.disabled&&(b.notCallOnChange=!0);b.set("value",a.lastName);b=dijit.byId(this.apellidoMaternoIdTxtBox);!0==b.disabled&&(b.notCallOnChange=!0);b.set("value",a.secondLastName);b=dijit.byId(this.primerNombreIdTxtBox);!0==b.disabled&&(b.notCallOnChange=!0);b.set("value",a.name);b=dijit.byId(this.segundoNombreIdTxtBox);!0==b.disabled&&(b.notCallOnChange=!0);b.set("value",a.middleName);b=dijit.byId(this.juridicoNombreIdText);!0==b.disabled&&(b.notCallOnChange=
!0);b.set("value",a.lastName);dijit.byId(this.agencyTxt).set("value",a.agency);dijit.byId(this.executiveTxt).set("value",a.executive);dijit.byId(this.sourceTxt).set("value",a.source)},nombreCompletoSet:function(a){this.nombreCompletoId=a},setBorderContainerId:function(a){this.borderContainerId=a},setTitlePaneId:function(a,b,d){dijit.byId(a).watch("open",e.hitch(this,function(c,g,f){c=dijit.byId(a);var k=e.connect(f?c._wipeIn:c._wipeOut,"onEnd",c,e.hitch(this,function(){dijit.byId(this.borderContainerId).resize();
var c=dijit.byId(a);!0===f?c.set("title",b):c.set("title",d);e.disconnect(k)}))}))},clientNewButtonSet:function(a){this.clientNewButtonId=a;a=dijit.byId(this.clientNewButtonId);f.set(a.domNode,"display","none")},juridicoNewButtonSet:function(a){this.juridicoNewButtonId=a;a=dijit.byId(this.juridicoNewButtonId);f.set(a.domNode,"display","none")},updateNewClient:function(){this.clearPanelMessage();var a=dijit.byId(this.personTypeComboId).get("value"),b=dijit.byId(this.documentTypeComboId).get("value"),
d=dijit.byId(this.primerNombreIdTxtBox).get("value"),c=dijit.byId(this.segundoNombreIdTxtBox).get("value"),f=dijit.byId(this.apellidoMaternoIdTxtBox).get("value"),h=dijit.byId(this.apellidoPaternoIdTxtBox).get("value"),k=dijit.byId(this.documentNumberTxId).get("value"),l={callbackScope:this};l.errorHandler=e.hitch(this,this.errorHandler);l.callback=this._updateNewClientCallBack;PlataformaComercialDWR.updateNewClient(k,a,b,d,c,h,f,this.tabId,this.pageScopeId,l)},updateNewJuridico:function(){this.clearPanelMessage();
var a=dijit.byId(this.personTypeComboId).get("value"),b=dijit.byId(this.juridicoNombreIdText).get("value"),d=dijit.byId(this.documentNumberTxId).get("value"),c=dijit.byId(this.documentTypeComboId).get("value"),f={callbackScope:this};f.errorHandler=e.hitch(this,this.errorHandler);f.callback=this._updateNewClientCallBack;PlataformaComercialDWR.updateNewJuridico(d,a,c,b,this.tabId,this.pageScopeId,f)},_updateNewClientCallBack:function(a){"error"==a.wAxn?this.updateMsgsPanel(a.aMsgs):"cnfrm"==a.wAxn&&
(void 0!=a.aMsgs&&null!=a.aMsgs&&this.updateMsgsPanel(a.aMsgs),void 0!=a.response&&(!1==a.response.disableMenu?this.enableMenu():!0==a.response.disableMenu&&this.disableMenu(),dojox.lang.functional.forIn(this.itemDisabled,function(a,d){ec.fisa.widget.utils.enableWidget(a)},this),null!=a.response.itmDisabled&&0<a.response.itmDisabled.length&&e.forEach(a.response.itmDisabled,e.hitch(this,function(a){ec.fisa.widget.utils.disableWidget(this.itemDisabled[a])})),this.enableComponents(!1)))}})});
//@ sourceMappingURL=PlataformaComercialController.js.map