//>>built
define("ec/fisa/controller/custom/QtController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ./_base ec/fisa/controller/BaseController ec/fisa/mvc/StatefulModel dojo/topic dojo/on dojo/dom-style ec/fisa/grid/FisaQtGrid ec/fisa/dwr/proxy/QtControllerDWR dojox/lang/functional/object ec/fisa/format/Utils ec/fisa/navigation/Utils ec/fisa/controller/Utils ec/fisa/widget/DateTextBox dijit/focus".split(" "),function(e,m,l,t,n,q,u,v,h){return m("ec.fisa.controller.custom.QtController",[n],{tabId:null,
pageScopeId:null,parentTabId:null,parentPageScopeId:null,parentBtId:null,parentFieldId:null,parentData:null,parentComplementData:null,model:null,modelComplement:null,qtGridId:null,fisaChartId:null,breadcrumbId:null,selectData:null,lovData:null,hasToClearMsgs:!0,isForRenderCharts:!1,isLovModal:!1,searchButtonId:null,scheduleButtonId:null,qtId:null,selectDataMap:null,publishId:"",subscription:null,reportWdgtId:null,isLovFromEditableGrid:!1,sortSignal:null,linkParentFisaTabId:null,linkParentFisaPageScopeId:null,
linkParentBtId:null,selectIdMap:null,constructor:function(a,b,c,d,f,g,e,p,k,h,l,r,s,m,n){r&&(this.isForRenderCharts=r);s&&(this.isLovFromEditableGrid=s);this.tabId=a;this.pageScopeId=b;this.qtId=f;this.parentTabId=c;this.parentPageScopeId=d;this.parentBtId=g;this.parentFieldId=e;this.parentData={};this.parentComplementData={};!0==m&&(this.isLovModal=!0);this.selectData=p;this.lovData=k;this.model=new q({});this.modelComplement=new q({});this.dojoComponents={};this.initData(h);this.initComplementData(l);
this.model.appendObject(["autoExec"],0,null,null,null,!1);a=n||{};this.selectDataMap=a.selectDataMap||{};this.publishId=this.qtId+"_"+this.tabId+"_"+this.pageScopeId;this.linkParentFisaTabId=a.linkParentFisaTabId||"";this.linkParentFisaPageScopeId=a.linkParentFisaPageScopeId||"";this.linkParentBtId=a.linkParentBtId||"";this.selectIdMap={}},destroy:function(){null!=this.model&&this.model.clearAllMessages();this.parentData=this.dojoComponents=this.modelComplement=this.model=this.data=null;this.subscription&&
(this.subscription.remove&&l.isFunction(this.subscription.remove))&&this.subscription.remove();this.sortSignal&&(this.sortSignal.remove&&l.isFunction(this.sortSignal.remove))&&this.sortSignal.remove()},obtainInitialValue:function(a){a=a["field-id"];var b=null;this.parentData&&this.parentData[a]&&(b=this.parentData[a]);return null==b?"":b},setQtGrid:function(a){this.qtGridId=a.id;a.executeAction=this.executeAction},getComponent:function(a,b){return this.model.getComponent([b])},addParamToModel:function(a){var b=
a["field-id"];if(!this.model.contains(b)){var c=a["bt-id"],d=this.parentData[b],f=null;d?(f=null,f=d.get?d.get("value"):d):f="";this.model.appendObject([b],f,a.id,"value",null,!0);a.hasCompl&&((d=this.parentComplementData[b])||(d=""),this.modelComplement.appendObject([b],d,a.id,"complement",null,!1))}this.dojoComponents[c]||(this.dojoComponents[c]=[]);this.dojoComponents[c].push({fieldId:a["field-id"],component:a.id})},initHoldParams:function(a,b){this.model.appendObject(["APP_ID"],a,null,null,null,
!1);this.model.appendObject(["USER_ID"],b,null,null,null,!1)},containsFieldModel:function(a,b){return this.model.contains([b])},getFieldModel:function(a,b){return this.model.getValue([b])},setFieldModelValue:function(a,b,c,d){this.model.setValue([b],c,void 0==d||null==d?!0:d)},setFieldModelComplement:function(a,b,c){this.modelComplement.setValue([b],c)},getFieldModelComplement:function(a,b){return this.modelComplement.getValue([b])},initSearchBtn:function(a){this.searchButtonId=a.id;a.connect(a,"onClick",
e.hitch(this,this.search,null,!0))},initScheduleBtn:function(a){this.scheduleButtonId=a;a=dijit.byId(a);a.connect(a,"onClick",e.hitch(this,this.scheduleAction))},initData:function(a){if(""!=this.parentTabId&&""!=this.parentPageScopeId){var b=ec.fisa.controller.utils.getPageController(this.parentTabId,this.parentPageScopeId),c=b.lovData[this.parentBtId][this.parentFieldId],d=[];c&&c.input&&0<c.input.length?(e.forEach(c.input,function(a,c){var e=a[0],p=a[1],k=null;this.isLovFromEditableGrid?(k=dijit.byId(b.dojoFromLovId),
k=dijit.byId(k.gridId).model.getValue([e])):(b.containsFieldModel(this.parentBtId,e)||b.addParamToModel({"bt-id":this.parentBtId,"field-id":e,hasCompl:!1,set:function(){}}),k=b.getFieldModel(this.parentBtId,e));this.parentData[p]=null==k?null:k;d.push(e)},this),dojox.lang.functional.forIn(a,function(a,b){for(var c=!1,e=0;e<d.length;e++)if(d[e]==b){c=!0;break}!c&&null!=a&&(this.parentData[b]=a)},this)):dojox.lang.functional.forIn(a,function(a,b){null!=a&&(this.parentData[b]=a)},this)}else dojox.lang.functional.forIn(a,
function(a,b){null!=a&&(this.parentData[b]=a)},this)},initComplementData:function(a){""!=this.parentTabId&&""!=this.parentPageScopeId||dojox.lang.functional.forIn(a,function(a,c){null!=a&&(this.parentComplementData[c]=a)},this)},scheduleAction:function(){var a=this.model.toPlainObject(),a=e.toJson(a);ec.fisa.navigation.utils.showNewBreadCrumbQtScheduling("",this.breadcrumbId,this.tabId,this.pageScopeId,this.qtId,a)},search:function(a,b){if(!0!=this.validate(this)){(null==a||!0==a)&&this.messagesPanelId&&
this.clearPanelMessage();var c=this.model.toPlainObject();c.autoExec++;c.sortRequested="0";this.model.setValue(["autoExec"],c.autoExec);!0==b&&(c.calledFromButtonScreenSearch=!0);this.hasToClearMsgs&&this.messagesPanelId&&this.model.clearAllMessages();if(this.isForRenderCharts)dijit.byId(this.fisaChartId).setQuery(c);else{var d=dijit.byId(this.qtGridId);d.isSearchRequested=!0;d.setQuery(c)}}},hold:function(a,b){this.executeActionCallback({wAxn:"open",dialog:a,dialogName:b})},validate:function(){var a=
!1;if(void 0!=this.model.getComponentsId){var b=this.model.getComponentsId();null!=b&&dojox.lang.functional.forIn(b,function(b,d){var f=dijit.byId(b);void 0!=f&&null!=f&&!1==a&&void 0!=f.hasErrorCmp&&!0===f.hasErrorCmp()&&(a=!0)},this)}b=dijit.byId(this.searchButtonId);null!=b&&void 0!=b&&dijit.focus(b.domNode);return a},findDojoComponent:function(a){var b;dojox.lang.functional.forIn(this.dojoComponents,function(c,d){e.forEach(c,function(c){c.fieldId==a&&(b=c.component)})},this);return b},searchAfterCloseContentPane:function(){var a=
ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),b=a.model.toPlainObject();a.hasToClearMsgs&&a.messagesPanelId&&(a.clearPanelMessage(),a.model.clearAllMessages());a.isForRenderCharts?dijit.byId(a.fisaChartId).setQuery(b):dijit.byId(a.qtGridId).refresh()},executeAction:function(a,b,c){var d=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);d.clearPanelMessage();ec.fisa.widget.utils.resetFocusManager();var f=null;2==arguments.length?f=this.selection.getSelected():
(f=dijit.byId(d.qtGridId).getItem(c),f=[parseInt(f,10)]);var g=d.model.toPlainObject();d.linkParentBtId&&""!=d.linkParentBtId&&(g.linkParentBtId=d.linkParentBtId);var h={callbackScope:d,callback:d.executeActionCallback,errorHandler:e.hitch(d,d.errorHandler)},d=d._getDeselected();0>=f.length?QtControllerDWR.executeAction(this.tabId,this.pageScopeId,a,null,b,g,d,h):QtControllerDWR.executeAction(this.tabId,this.pageScopeId,a,f,b,g,d,h)},executeActionCallback:function(a){dijit.byId(this.messagesPanelId);
this.hasToClearMsgs&&(this.clearPanelMessage(),this.model.clearAllMessages());if("error"==a.wAxn)!0===a.refreshResults&&this.searchAfterCloseContentPane(),this.updateMsgsPanel(a.aMsgs);else if("open"==a.wAxn)if(a.responseMessages&&(this.updateMsgsPanel(a.responseMessages.aMsgs),this.closePopupMsgPanel(),this.hasToClearMsgs=!1),null!=a.dialog&&-1<a.dialog.indexOf("BTRenderWeb/faces/QTReportManager"))a=a.dialog.replace("BTRenderWeb/faces/",e.config.fisaContextPath+"/").replace("?a\x3d","?qtActionTabId\x3d"),
window.open(a+this.tabId);else{var b={};b.title=a.dialogName;b.href=a.dialog;if(void 0!=a.transactionDocuments&&null!=a.transactionDocuments){var c=e.toJson(a.transactionDocuments);b.ioArgs={content:{transactionDocuments:c,actionMode:a.actionMode,FISATabId:this.tabId}}}b.ioMethod=e.xhrPost;ec.fisa.navigation.utils.openNewBreadCrumb(b,this.breadcrumbId)}else"refresh"==a.wAxn?(a.responseMessages&&this.updateMsgsPanel(a.responseMessages.aMsgs),this.hasToClearMsgs=!1,this.search(!1),this.hasToClearMsgs=
!0):"refreshParentBtFtm"==a.wAxn&&(a.beneficiaryNotificationData&&a.beneficiaryBtId&&ec.fisa.controller.utils.getPageController(this.linkParentFisaTabId,this.linkParentFisaPageScopeId).updateNotificationData(a.beneficiaryNotificationData,a.beneficiaryBtId),b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),b={callbackScope:b,callback:b.executeRefreshParentBtFtmCallback,errorHandler:e.hitch(b,b.errorHandler)},QtControllerDWR.executeAfectedFieldsRoutine(this.linkParentFisaTabId,
this.linkParentFisaPageScopeId,this.linkParentBtId,a.afectedFields,b))},executeRefreshParentBtFtmCallback:function(a){"error"==a.wAxn?(!0===a.refreshResults&&this.searchAfterCloseContentPane(),this.updateMsgsPanel(a.aMsgs)):(a.wAxn="refresh",a.msg=a.afectedFields,a.priorityChange="false",ec.fisa.controller.utils.getPageController(this.linkParentFisaTabId,this.linkParentFisaPageScopeId).handleCallBackBackFieldRoutine(a),this.execCancel(null,this.qtId))},setMessagesPanel:function(a){this.inherited(arguments);
this.breadcrumbId=ec.fisa.navigation.utils.obtainParentBreadCrumb(a).id;var b=a.getParent().getParent();b.tabId=this.tabId;b.pageScopeId=this.pageScopeId;b.isQtContentPane=!0},loadSelectData:function(a,b){var c=b||!1,d=a["bt-id"],f=a["field-id"],g=[];this.selectDataMap&&this.selectDataMap[d][f].data&&(d=this.selectDataMap[d][f].data,g[0]={value:"",label:e.config.fisaSelectLabel},e.forEach(d,function(b,c){g[c+1]={value:""+b[a.valueColumn],label:b[a.labelColum]}},this));c||a.set("options",g);return g},
setFisaChart:function(a){this.fisaChartId=a.id;a.tabId=this.tabId;a.pageScopeId=this.pageScopeId;var b=this.model.toPlainObject();a.setInitialQuery(b);a.startUp()},execCancel:function(a,b){var c={callbackScope:this,errorHandler:e.hitch(this,this.errorHandler),callback:this.handleCancelAction};QtControllerDWR.executeCancel(this.tabId,this.pageScopeId,b,c)},handleCancelAction:function(a){"close"==a.wAxn&&(null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):
ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId));this.linkParentFisaTabId&&this.linkParentFisaPageScopeId&&(a=ec.fisa.controller.utils.getPageController(this.linkParentFisaTabId,this.linkParentFisaPageScopeId))&&(a.selectComponentToReload&&l.isFunction(a.selectComponentToReload.doForceReloadOptions))&&a.selectComponentToReload.doForceReloadOptions()},isComponentMsg:function(a){return"fieldId"in a&&null!=a.fieldId&&""!=a.fieldId},addComponentMsg:function(a){this.model.setMessage([a.fieldId],
a.fieldMsg,a.origLevel)},attachOnChangeEvent:function(a){},getSelectedIndex:function(a){var b=-1;a=a.getOptions();for(var c=0;c<a.length;c++)if(!0===a[c].selected){b=c;break}return b-1},fetchSelectOptions:function(a,b,c){this.clearPanelMessage();var d={callbackScope:this,errorHandler:e.hitch(this,this.errorHandler),callback:this.callBackFetchSelectOptions},f=this.model.toPlainObject();QtControllerDWR.loadSelectOptionsData(a,b,c,f,d)},callBackFetchSelectOptions:function(a){var b=a.data,c=a.aMsgs;if(c)this.updateMsgsPanel(c);
else{a=dijit.byId(a.fieldId);var c=a["bt-id"],d=a["field-id"],f=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);f.selectDataMap[c][d].data=b;f.loadSelectData(a);a.set("value","")}},unDisplayQTGrid:function(){var a=dijit.byId(this.qtGridId).getParent();h.set(a.domNode,"display","none")},unDisplayMessagesPanel:function(){var a=dijit.byId(this.messagesPanelId);a&&h.set(a.domNode,"display","none")},unDisplayQTPortlet:function(){var a=dijit.byId(this.qtGridId).getParent().getParent().getParent();
h.set(a.domNode,"display","none")},makeQTPortletVisible:function(){var a=dijit.byId(this.qtGridId).getParent().getParent().getParent();null!=a&&h.set(a.domNode,"visibility","visible")},updateMsgsPanel:function(a){var b=[],c=[];e.forEach(a,function(a,d){a.ftmId==this.qtId&&a.fieldId==this.qtId&&(b.push(d),c.push(a))},this);0<b.length&&(b.reverse(),e.forEach(b,function(b){a.splice(b,1)},this));this.inherited(arguments);if(0<c.length){var d=dijit.byId(this.qtGridId);null!=d&&d.showFooterMessage(c[0].summary)}},
clearPanelMessage:function(){this.inherited(arguments);var a=dijit.byId(this.qtGridId);null!=a&&a.showFooterMessage("")},handleOnChangeComponent:function(a,b,c,d,f,g,h,l,k){this.clearPanelMessage();c=this.model.toPlainObject();f={callbackScope:{ctrl:this,notifyComboId:d}};f.callback=this.handleCallBackQtOnChangeComponent;f.errorHandler=e.hitch(this,this.errorHandler);EventActionDWR.handleQtOnChangeComponent(this.tabId,this.pageScopeId,a,b,c,d,g,f)},handleCallBackQtOnChangeComponent:function(a){var b=
a.aMsgs;"error"==a.wAxn?(this.ctrl.clearPanelMessage(),this.ctrl.updateMsgsPanel(b)):(null!=a.dataUpdate&&void 0!=a.dataUpdate&&(b=a.dataUpdate,null!=b&&void 0!=b&&dojox.lang.functional.forIn(b,e.hitch(this,function(a,b){this.ctrl.updateSelectByOutcome(b,a,this.ctrl)}))),null!=a.qtParams&&void 0!=a.qtParams&&dojox.lang.functional.forIn(a.qtParams,e.hitch(this,function(a,b){this.ctrl.model.setValue([b],a,!1)})),null!=a.complementParams&&void 0!=a.complementParams&&dojox.lang.functional.forIn(a.complementParams,
e.hitch(this,function(a,b){this.ctrl.modelComplement.setValue([b],a,!1)})))},updateSelectByOutcome:function(a,b,c){a=dijit.byId(c.selectIdMap[a]);c.selectDataMap[a["bt-id"]][a["field-id"]].data=b;a.setControlValue("");a.removeOption(a.getOptions());c.loadSelectData(a)},_getDeselected:function(){var a;a=this.qtGridId?(a=dijit.byId(this.qtGridId)._getBySelectionStatus(!1))&&0<a.length?a.toString():null:null;return a}})});
//@ sourceMappingURL=QtController.js.map