//>>built
this.org=this.org||{};org.cometd={};org.cometd.JSON={};org.cometd.JSON.toJSON=org.cometd.JSON.fromJSON=function(e){throw"Abstract";};org.cometd.Utils={};org.cometd.Utils.isString=function(e){return void 0===e||null===e?!1:"string"===typeof e||e instanceof String};org.cometd.Utils.isArray=function(e){return void 0===e||null===e?!1:e instanceof Array};org.cometd.Utils.inArray=function(e,c){for(var a=0;a<c.length;++a)if(e===c[a])return a;return-1};
org.cometd.Utils.setTimeout=function(e,c,a){return window.setTimeout(function(){try{c()}catch(d){e._debug("Exception invoking timed function",c,d)}},a)};org.cometd.Utils.clearTimeout=function(e){window.clearTimeout(e)};
org.cometd.TransportRegistry=function(){var e=[],c={};this.getTransportTypes=function(){return e.slice(0)};this.findTransportTypes=function(a,d,n){for(var f=[],p=0;p<e.length;++p){var g=e[p];!0===c[g].accept(a,d,n)&&f.push(g)}return f};this.negotiateTransport=function(a,d,n,f){for(var p=0;p<e.length;++p)for(var g=e[p],k=0;k<a.length;++k)if(g===a[k]){var m=c[g];if(!0===m.accept(d,n,f))return m}return null};this.add=function(a,d,n){for(var f=!1,p=0;p<e.length;++p)if(e[p]===a){f=!0;break}f||("number"!==
typeof n?e.push(a):e.splice(n,0,a),c[a]=d);return!f};this.find=function(a){for(var d=0;d<e.length;++d)if(e[d]===a)return c[a];return null};this.remove=function(a){for(var d=0;d<e.length;++d)if(e[d]===a)return e.splice(d,1),d=c[a],delete c[a],d;return null};this.clear=function(){e=[];c={}};this.reset=function(){for(var a=0;a<e.length;++a)c[e[a]].reset()}};
org.cometd.Transport=function(){var e,c;this.registered=function(a,d){e=a;c=d};this.unregistered=function(){c=e=null};this._debug=function(){c._debug.apply(c,arguments)};this._mixin=function(){return c._mixin.apply(c,arguments)};this.getConfiguration=function(){return c.getConfiguration()};this.getAdvice=function(){return c.getAdvice()};this.setTimeout=function(a,d){return org.cometd.Utils.setTimeout(c,a,d)};this.clearTimeout=function(a){org.cometd.Utils.clearTimeout(a)};this.convertToMessages=function(a){if(org.cometd.Utils.isString(a))try{return org.cometd.JSON.fromJSON(a)}catch(d){throw this._debug("Could not convert to JSON the following string",
'"'+a+'"'),d;}if(org.cometd.Utils.isArray(a))return a;if(void 0===a||null===a)return[];if(a instanceof Object)return[a];throw"Conversion Error "+a+", typeof "+typeof a;};this.accept=function(a,d,c){throw"Abstract";};this.getType=function(){return e};this.send=function(a,d){throw"Abstract";};this.reset=function(){this._debug("Transport",e,"reset")};this.abort=function(){this._debug("Transport",e,"aborted")};this.toString=function(){return this.getType()}};
org.cometd.Transport.derive=function(e){function c(){}c.prototype=e;return new c};
org.cometd.RequestTransport=function(){function e(d){for(;0<m.length;){var a=m[0],h=a[0],a=a[1];if(h.url===d.url&&h.sync===d.sync)m.shift(),d.messages=d.messages.concat(h.messages),this._debug("Coalesced",h.messages.length,"messages from request",a.id);else break}}function c(d,a){this.transportSend(d,a);a.expired=!1;if(!d.sync){var h=this.getConfiguration().maxNetworkDelay,c=h;!0===a.metaConnect&&(c+=this.getAdvice().timeout);this._debug("Transport",this.getType(),"waiting at most",c,"ms for the response, maxNetworkDelay",
h);var f=this;a.timeout=this.setTimeout(function(){a.expired=!0;var h="Request "+a.id+" of transport "+f.getType()+" exceeded "+c+" ms max network delay",e={reason:h},G=a.xhr;e.httpCode=f.xhrStatus(G);f.abortXHR(G);f._debug(h);f.complete(a,!1,a.metaConnect);d.onFailure(G,d.messages,e)},c)}}function a(a){var d=++p,h={id:d,metaConnect:!1};k.length<this.getConfiguration().maxConnections-1?(k.push(h),c.call(this,a,h)):(this._debug("Transport",this.getType(),"queueing request",d,"envelope",a),m.push([a,
h]))}function d(d,c){var h=org.cometd.Utils.inArray(d,k);0<=h&&k.splice(h,1);if(0<m.length){var h=m.shift(),f=h[0],n=h[1];this._debug("Transport dequeued request",n.id);if(c)this.getConfiguration().autoBatch&&e.call(this,f),a.call(this,f),this._debug("Transport completed request",d.id,f);else{var y=this;this.setTimeout(function(){y.complete(n,!1,n.metaConnect);var a={reason:"Previous request failed"},d=n.xhr;a.httpCode=y.xhrStatus(d);f.onFailure(d,f.messages,a)},0)}}}var n=new org.cometd.Transport,
f=org.cometd.Transport.derive(n),p=0,g=null,k=[],m=[];f.complete=function(a,f,h){if(h){a=a.id;this._debug("Transport",this.getType(),"metaConnect complete, request",a);if(null!==g&&g.id!==a)throw"Longpoll request mismatch, completing request "+a;g=null}else d.call(this,a,f)};f.transportSend=function(a,d){throw"Abstract";};f.transportSuccess=function(a,d,f){if(!d.expired)if(this.clearTimeout(d.timeout),this.complete(d,!0,d.metaConnect),f&&0<f.length)a.onSuccess(f);else a.onFailure(d.xhr,a.messages,
{httpCode:204})};f.transportFailure=function(a,d,f){d.expired||(this.clearTimeout(d.timeout),this.complete(d,!1,d.metaConnect),a.onFailure(d.xhr,a.messages,f))};f.send=function(d,f){if(f){if(null!==g)throw"Concurrent metaConnect requests not allowed, request id\x3d"+g.id+" not yet completed";var h=++p;this._debug("Transport",this.getType(),"metaConnect send, request",h,"envelope",d);h={id:h,metaConnect:!0};c.call(this,d,h);g=h}else a.call(this,d)};f.abort=function(){n.abort();for(var d=0;d<k.length;++d){var a=
k[d];this._debug("Aborting request",a);this.abortXHR(a.xhr)}g&&(this._debug("Aborting metaConnect request",g),this.abortXHR(g.xhr));this.reset()};f.reset=function(){n.reset();g=null;k=[];m=[]};f.abortXHR=function(d){if(d)try{d.abort()}catch(a){this._debug(a)}};f.xhrStatus=function(d){if(d)try{return d.status}catch(a){this._debug(a)}return-1};return f};
org.cometd.LongPollingTransport=function(){var e=new org.cometd.RequestTransport,c=org.cometd.Transport.derive(e),a=!0;c.accept=function(d,c,f){return a||!c};c.xhrSend=function(d){throw"Abstract";};c.transportSend=function(d,c){this._debug("Transport",this.getType(),"sending request",c.id,"envelope",d);var f=this;try{var e=!0;c.xhr=this.xhrSend({transport:this,url:d.url,sync:d.sync,headers:this.getConfiguration().requestHeaders,body:org.cometd.JSON.toJSON(d.messages),onSuccess:function(e){f._debug("Transport",
f.getType(),"received response",e);var m=!1;try{var g=f.convertToMessages(e);0===g.length?(a=!1,f.transportFailure(d,c,{httpCode:204})):(m=!0,f.transportSuccess(d,c,g))}catch(p){f._debug(p),m||(a=!1,e={exception:p},e.httpCode=f.xhrStatus(c.xhr),f.transportFailure(d,c,e))}},onError:function(k,g){a=!1;var r={reason:k,exception:g};r.httpCode=f.xhrStatus(c.xhr);e?f.setTimeout(function(){f.transportFailure(d,c,r)},0):f.transportFailure(d,c,r)}});e=!1}catch(g){a=!1,this.setTimeout(function(){f.transportFailure(d,
c,{exception:g})},0)}};c.reset=function(){e.reset();a=!0};return c};
org.cometd.CallbackPollingTransport=function(){var e=new org.cometd.RequestTransport,e=org.cometd.Transport.derive(e);e.accept=function(c,a,d){return!0};e.jsonpSend=function(c){throw"Abstract";};e.transportSend=function(c,a){for(var d=this,e=0,f=c.messages.length,p=[];0<f;){var g=org.cometd.JSON.toJSON(c.messages.slice(e,e+f));if(2E3<c.url.length+encodeURI(g).length){if(1===f){this.setTimeout(function(){d.transportFailure(c,a,{reason:"Bayeux message too big, max is 2000"})},0);return}--f}else p.push(f),
e+=f,f=c.messages.length-e}var k=c;if(1<p.length){e=0;f=p[0];this._debug("Transport",this.getType(),"split",c.messages.length,"messages into",p.join(" + "));k=this._mixin(!1,{},c);k.messages=c.messages.slice(e,f);k.onSuccess=c.onSuccess;k.onFailure=c.onFailure;for(g=1;g<p.length;++g){var m=this._mixin(!1,{},c),e=f,f=f+p[g];m.messages=c.messages.slice(e,f);m.onSuccess=c.onSuccess;m.onFailure=c.onFailure;this.send(m,a.metaConnect)}}this._debug("Transport",this.getType(),"sending request",a.id,"envelope",
k);try{var r=!0;this.jsonpSend({transport:this,url:k.url,sync:k.sync,headers:this.getConfiguration().requestHeaders,body:org.cometd.JSON.toJSON(k.messages),onSuccess:function(f){var c=!1;try{var e=d.convertToMessages(f);0===e.length?d.transportFailure(k,a,{httpCode:204}):(c=!0,d.transportSuccess(k,a,e))}catch(y){d._debug(y),c||d.transportFailure(k,a,{exception:y})}},onError:function(c,f){var e={reason:c,exception:f};r?d.setTimeout(function(){d.transportFailure(k,a,e)},0):d.transportFailure(k,a,e)}});
r=!1}catch(s){this.setTimeout(function(){d.transportFailure(k,a,{exception:s})},0)}};return e};
org.cometd.WebSocketTransport=function(){function e(){if(!s){s=!0;var d=f.getURL().replace(/^http/,"ws");this._debug("Transport",this.getType(),"connecting to URL",d);try{var a=f.getConfiguration().protocol,c=a?new org.cometd.WebSocket(d,a):new org.cometd.WebSocket(d)}catch(e){throw p=!1,this._debug("Exception while creating WebSocket object",e),e;}k=!1!==f.getConfiguration().stickyReconnect;var g=this,m=null,n=f.getConfiguration().connectTimeout;0<n&&(m=this.setTimeout(function(){m=null;g._debug("Transport",
g.getType(),"timed out while connecting to URL",d,":",n,"ms");var a={code:1E3,reason:"Connect Timeout"};g.webSocketClose(c,a.code,a.reason);g.onClose(c,a)},n));var r=function(d){d=d||{code:1E3};g._debug("WebSocket closing",c,d);s=!1;m&&(g.clearTimeout(m),m=null);if(null!==h&&c!==h)g._debug("Closed Extra WebSocket Connection",c);else g.onClose(c,d)};c.onopen=function(){g._debug("WebSocket opened",c);s=!1;m&&(g.clearTimeout(m),m=null);if(h)f._warn("Closing Extra WebSocket Connections",c,h),g.webSocketClose(c,
1E3,"Extra Connection");else g.onOpen(c)};c.onclose=r;c.onerror=function(){r({code:1002,reason:"Error"})};c.onmessage=function(d){g._debug("WebSocket message",d,c);c!==h&&f._warn("Extra WebSocket Connections",c,h);g.onMessage(c,d)};this._debug("Transport",this.getType(),"configured callbacks on",c)}}function c(d,a,c){var e=org.cometd.JSON.toJSON(a.messages);d.send(e);this._debug("Transport",this.getType(),"sent",a,"metaConnect \x3d",c);var f=e=this.getConfiguration().maxNetworkDelay;c&&(f+=this.getAdvice().timeout,
B=!0);for(var h=this,g=[],m=0;m<a.messages.length;++m)(function(){var c=a.messages[m];c.id&&(g.push(c.id),r[c.id]=this.setTimeout(function(){h._debug("Transport",h.getType(),"timing out message",c.id,"after",f,"on",d);var a={code:1E3,reason:"Message Timeout"};h.webSocketClose(d,a.code,a.reason);h.onClose(d,a)},f))})();this._debug("Transport",this.getType(),"waiting at most",f,"ms for messages",g,"maxNetworkDelay",e,", timeouts:",r)}function a(d,a,f){try{null===d?e.call(this):c.call(this,d,a,f)}catch(h){this.setTimeout(function(){a.onFailure(d,
a.messages,{exception:h})},0)}}var d=new org.cometd.Transport,n=org.cometd.Transport.derive(d),f,p=!0,g=!1,k=!0,m={},r={},s=!1,h=null,B=!1,F=null;n.reset=function(){d.reset();p=!0;g=!1;k=!0;m={};r={};s=!1;h=null;B=!1;F=null};n.onOpen=function(d){this._debug("Transport",this.getType(),"opened",d);h=d;g=!0;this._debug("Sending pending messages",m);for(var a in m){var f=m[a],e=f[0],f=f[1];F=e.onSuccess;c.call(this,d,e,f)}};n.onMessage=function(d,a){this._debug("Transport",this.getType(),"received websocket message",
a,d);for(var c=!1,f=this.convertToMessages(a.data),e=[],h=0;h<f.length;++h){var g=f[h];if((/^\/meta\//.test(g.channel)||void 0!==g.successful)&&g.id){e.push(g.id);var k=r[g.id];k&&(this.clearTimeout(k),delete r[g.id],this._debug("Transport",this.getType(),"removed timeout for message",g.id,", timeouts",r))}"/meta/connect"===g.channel&&(B=!1);"/meta/disconnect"===g.channel&&!B&&(c=!0)}h=!1;for(g=0;g<e.length;++g){var n=e[g],p;for(p in m){var k=p.split(","),s=org.cometd.Utils.inArray(n,k);if(0<=s){h=
!0;k.splice(s,1);n=m[p][0];s=m[p][1];delete m[p];0<k.length&&(m[k.join(",")]=[n,s]);break}}}h&&this._debug("Transport",this.getType(),"removed envelope, envelopes",m);F.call(this,f);c&&this.webSocketClose(d,1E3,"Disconnect")};n.onClose=function(d,a){this._debug("Transport",this.getType(),"closed",d,a);p=k&&g;for(var c in r)this.clearTimeout(r[c]);r={};for(var f in m)c=m[f][0],m[f][1]&&(B=!1),c.onFailure(d,c.messages,{websocketCode:a.code,reason:a.reason});m={};h=null};n.registered=function(a,c){d.registered(a,
c);f=c};n.accept=function(d,a,c){return p&&!!org.cometd.WebSocket&&!1!==f.websocketEnabled};n.send=function(d,c){this._debug("Transport",this.getType(),"sending",d,"metaConnect \x3d",c);for(var f=[],e=0;e<d.messages.length;++e){var g=d.messages[e];g.id&&f.push(g.id)}m[f.join(",")]=[d,c];this._debug("Transport",this.getType(),"stored envelope, envelopes",m);a.call(this,h,d,c)};n.webSocketClose=function(d,a,c){try{d.close(a,c)}catch(f){this._debug(f)}};n.abort=function(){d.abort();if(h){var a={code:1001,
reason:"Abort"};this.webSocketClose(h,a.code,a.reason);this.onClose(h,a)}this.reset()};return n};
org.cometd.Cometd=function(e){function c(b,d){try{return b[d]}catch(a){}}function a(b){return org.cometd.Utils.isString(b)}function d(b){return void 0===b||null===b?!1:"function"===typeof b}function n(b,a){if(window.console){var c=window.console[b];d(c)&&c.apply(window.console,a)}}function f(b){if(b){var d=A[b.channel];d&&d[b.id]&&(delete d[b.id],l._debug("Removed",b.listener?"listener":"subscription",b))}}function p(){for(var b in A){var d=A[b];if(d)for(var a=0;a<d.length;++a){var c=d[a];c&&!c.listener&&
f(c)}}}function g(b){H!==b&&(l._debug("Status",H,"-\x3e",b),H=b)}function k(){return"disconnecting"===H||"disconnected"===H}function m(b,a,c,f,e){try{return a.call(b,f)}catch(g){l._debug("Exception during execution of extension",c,g);b=l.onExtensionException;if(d(b)){l._debug("Invoking extension exception callback",c,g);try{b.call(l,g,c,e,f)}catch(h){l._info("Exception during execution of exception callback in extension",c,h)}}return f}}function r(b){for(var a=0;a<v.length&&!(void 0===b||null===b);++a){var c=
v[a],f=c.extension.outgoing;d(f)&&(c=m(c.extension,f,c.name,b,!0),b=void 0===c?b:c)}return b}function s(b,a){var c=A[b];if(c&&0<c.length)for(var f=0;f<c.length;++f){var e=c[f];if(e)try{e.callback.call(e.scope,a)}catch(g){l._debug("Exception during notification",e,a,g);var h=l.onListenerException;if(d(h)){l._debug("Invoking listener exception callback",e,g);try{h.call(l,g,e,e.listener,a)}catch(k){l._info("Exception during execution of listener callback",e,k)}}}}}function h(b,d){s(b,d);for(var a=b.split("/"),
c=a.length-1,f=c;0<f;--f){var e=a.slice(0,f).join("/")+"/*";f===c&&s(e,d);e+="*";s(e,d)}}function B(){null!==M&&org.cometd.Utils.clearTimeout(M);M=null}function F(b){B();var d=x.interval+w;l._debug("Function scheduled in",d,"ms, interval \x3d",x.interval,"backoff \x3d",w,b);M=org.cometd.Utils.setTimeout(l,b,d)}function y(b,a,c,f){for(var e=0;e<a.length;++e){var g=a[e],h=""+ ++ia;g.id=h;I&&(g.clientId=I);var k=void 0;d(g._callback)&&(k=g._callback,delete g._callback);g=r(g);void 0!==g&&null!==g?(g.id=
h,a[e]=g,k&&(R[h]=k)):a.splice(e--,1)}0!==a.length&&(e=l.getURL(),q.appendMessageTypeToURL&&(e.match(/\/$/)||(e+="/"),f&&(e+=f)),b={url:e,sync:b,messages:a,onSuccess:function(b){try{Y.call(l,b)}catch(a){l._debug("Exception during handling of messages",a)}},onFailure:function(b,a,d){try{d.connectionType=l.getTransport().getType(),S.call(l,b,a,d)}catch(c){l._debug("Exception during handling of failure",c)}}},l._debug("Send",b),t.send(b,c))}function L(b){0<D||!0===K?J.push(b):y(!1,[b],!1)}function G(){var b=
J;J=[];0<b.length&&y(!1,b,!1)}function N(){g("connecting");F(function(){if(!k()){var b={channel:"/meta/connect",connectionType:t.getType()};T||(b.advice={timeout:0});g("connecting");l._debug("Connect sent",b);y(!1,[b],!0,"connect");g("connected")}})}function O(b){b&&(x=l._mixin(!1,{},q.advice,b),l._debug("New advice",x))}function C(b){B();b&&t.abort();I=null;g("disconnected");w=D=0;t=null;0<J.length&&(S.call(l,void 0,J,{reason:"Disconnected"}),J=[])}function P(b,a,c){var e=l.onTransportFailure;if(d(e)){l._debug("Invoking transport failure callback",
b,a,c);try{e.call(l,b,a,c)}catch(f){l._info("Exception during execution of transport failure callback",f)}}}function X(b,a){d(b)&&(a=b,b=void 0);I=null;p();k()?(u.reset(),O(q.advice)):O(l._mixin(!1,x,{reconnect:"retry"}));D=0;K=!0;U=b;Z=a;var c=l.getURL(),e=u.findTransportTypes("1.0",E,c),f=l._mixin(!1,{},U,{version:"1.0",minimumVersion:"1.0",channel:"/meta/handshake",supportedConnectionTypes:e,_callback:a,advice:{timeout:x.timeout,interval:x.interval}});if(!t&&(t=u.negotiateTransport(e,"1.0",E,c),
!t))throw c="Could not find initial transport among: "+u.getTransportTypes(),l._warn(c),c;l._debug("Initial transport is",t.getType());g("handshaking");l._debug("Handshake sent",f);y(!1,[f],!1,"handshake")}function W(){g("handshaking");K=!0;F(function(){X(U,Z)})}function z(b){var a=R[b.id];d(a)&&(delete R[b.id],a.call(l,b))}function Q(b){z(b);h("/meta/handshake",b);h("/meta/unsuccessful",b);!k()&&"none"!==x.reconnect?(w<q.maxBackoff&&(w+=q.backoffIncrement),W()):C(!1)}function $(b){h("/meta/connect",
b);h("/meta/unsuccessful",b);b=k()?"none":x.reconnect;switch(b){case "retry":N();w<q.maxBackoff&&(w+=q.backoffIncrement);break;case "handshake":u.reset();w=0;W();break;case "none":C(!1);break;default:throw"Unrecognized advice action"+b;}}function aa(b){C(!0);z(b);h("/meta/disconnect",b);h("/meta/unsuccessful",b)}function ba(b){var a=A[b.subscription];if(a)for(var d=a.length-1;0<=d;--d){var c=a[d];if(c&&!c.listener){delete a[d];l._debug("Removed failed subscription",c);break}}z(b);h("/meta/subscribe",
b);h("/meta/unsuccessful",b)}function ca(b){z(b);h("/meta/unsubscribe",b);h("/meta/unsuccessful",b)}function da(b){z(b);h("/meta/publish",b);h("/meta/unsuccessful",b)}function ea(b){for(var a=0;a<v.length&&!(void 0===b||null===b);++a){var c=v[q.reverseIncomingExtensions?v.length-1-a:a],e=c.extension.incoming;d(e)&&(c=m(c.extension,e,c.name,b,!1),b=void 0===c?b:c)}if(!(void 0===b||null===b))switch(O(b.advice),b.channel){case "/meta/handshake":if(b.successful)if(I=b.clientId,a=l.getURL(),c=u.negotiateTransport(b.supportedConnectionTypes,
b.version,E,a),null===c)b="Could not negotiate transport with server; client\x3d["+u.findTransportTypes(b.version,E,a)+"], server\x3d["+b.supportedConnectionTypes+"]",a=l.getTransport(),P(a.getType(),null,{reason:b,connectionType:a.getType(),transport:a}),l._warn(b),C(!0);else switch(t!==c&&(l._debug("Transport",t.getType(),"-\x3e",c.getType()),t=c),K=!1,G(),b.reestablish=V,V=!0,z(b),h("/meta/handshake",b),b=k()?"none":x.reconnect,b){case "retry":w=0;N();break;case "none":C(!1);break;default:throw"Unrecognized advice action "+
b;}else Q(b);break;case "/meta/connect":if(T=b.successful)switch(h("/meta/connect",b),b=k()?"none":x.reconnect,b){case "retry":w=0;N();break;case "none":C(!1);break;default:throw"Unrecognized advice action "+b;}else $(b);break;case "/meta/disconnect":b.successful?(C(!1),z(b),h("/meta/disconnect",b)):aa(b);break;case "/meta/subscribe":b.successful?(z(b),h("/meta/subscribe",b)):ba(b);break;case "/meta/unsubscribe":b.successful?(z(b),h("/meta/unsubscribe",b)):ca(b);break;default:void 0===b.successful?
void 0!==b.data?h(b.channel,b):l._warn("Unknown Bayeux Message",b):b.successful?(z(b),h("/meta/publish",b)):da(b)}}function fa(b){if(b=A[b])for(var a=0;a<b.length;++a)if(b[a])return!0;return!1}function ga(b,c){var e={scope:b,method:c};if(d(b))e.scope=void 0,e.method=b;else if(a(c)){if(!b)throw"Invalid scope "+b;e.method=b[c];if(!d(e.method))throw"Invalid callback "+c+" for scope "+b;}else if(!d(c))throw"Invalid callback "+c;return e}function ha(b,a,c,d){a=ga(a,c);l._debug("Adding",d?"listener":"subscription",
"on",b,"with scope",a.scope,"and callback",a.method);a={channel:b,scope:a.scope,callback:a.method,listener:d};c=A[b];c||(c=[],A[b]=c);a.id=c.push(a)-1;l._debug("Added",d?"listener":"subscription",a);a[0]=b;a[1]=a.id;return a}var l=this,ja=e||"default",E=!1,u=new org.cometd.TransportRegistry,t,H="disconnected",ia=0,I=null,D=0,J=[],K=!1,A={},w=0,M=null,v=[],x={},U,Z,R={},V=!1,T=!1,q={protocol:null,stickyReconnect:!0,connectTimeout:0,maxConnections:2,backoffIncrement:1E3,maxBackoff:6E4,logLevel:"info",
reverseIncomingExtensions:!0,maxNetworkDelay:1E4,requestHeaders:{},appendMessageTypeToURL:!0,autoBatch:!1,advice:{timeout:6E4,interval:0,reconnect:"retry"}};this._mixin=function(b,a,d){for(var e=a||{},f=2;f<arguments.length;++f){var g=arguments[f];if(!(void 0===g||null===g))for(var h in g){var k=c(g,h),l=c(e,h);k!==a&&void 0!==k&&(e[h]=b&&"object"===typeof k&&null!==k?k instanceof Array?this._mixin(b,l instanceof Array?l:[],k):this._mixin(b,"object"===typeof l&&!(l instanceof Array)?l:{},k):k)}}return e};
this._warn=function(){n("warn",arguments)};this._info=function(){"warn"!==q.logLevel&&n("info",arguments)};this._debug=function(){"debug"===q.logLevel&&n("debug",arguments)};this._isCrossDomain=function(b){return b&&b!==window.location.host};var Y,S;this.send=L;this.receive=ea;Y=function(b){l._debug("Received",b);for(var a=0;a<b.length;++a)ea(b[a])};S=function(b,a,c){l._debug("handleFailure",b,a,c);c.transport=b;for(b=0;b<a.length;++b){var d=a[b],e={id:d.id,successful:!1,channel:d.channel,failure:c};
c.message=d;switch(d.channel){case "/meta/handshake":var d=e,f=l.getURL(),e=l.getTransport(),g=u.findTransportTypes("1.0",E,f);(f=u.negotiateTransport(g,"1.0",E,f))?(l._debug("Transport",e.getType(),"-\x3e",f.getType()),P(e.getType(),f.getType(),d.failure),Q(d),t=f):(P(e.getType(),null,d.failure),l._warn("Could not negotiate transport; client\x3d["+g+"]"),C(!0),Q(d));break;case "/meta/connect":d=e;T=!1;$(d);break;case "/meta/disconnect":aa(e);break;case "/meta/subscribe":e.subscription=d.subscription;
ba(e);break;case "/meta/unsubscribe":e.subscription=d.subscription;ca(e);break;default:da(e)}}};this.registerTransport=function(b,a,c){if(c=u.add(b,a,c))this._debug("Registered transport",b),d(a.registered)&&a.registered(b,this);return c};this.getTransportTypes=function(){return u.getTransportTypes()};this.unregisterTransport=function(b){var a=u.remove(b);null!==a&&(this._debug("Unregistered transport",b),d(a.unregistered)&&a.unregistered());return a};this.unregisterTransports=function(){u.clear()};
this.findTransport=function(b){return u.find(b)};this.configure=function(b){l._debug("Configuring cometd object with",b);a(b)&&(b={url:b});b||(b={});q=l._mixin(!1,q,b);b=l.getURL();if(!b)throw"Missing required configuration parameter 'url' specifying the Bayeux server URL";var c=/(^https?:\/\/)?(((\[[^\]]+\])|([^:\/\?#]+))(:(\d+))?)?([^\?#]*)(.*)?/.exec(b);b=c[8];var d=c[9];E=l._isCrossDomain(c[2]);q.appendMessageTypeToURL&&(void 0!==d&&0<d.length?(l._info("Appending message type to URI "+b+d+" is not supported, disabling 'appendMessageTypeToURL' configuration"),
q.appendMessageTypeToURL=!1):(c=b.split("/"),d=c.length-1,b.match(/\/$/)&&(d-=1),0<=c[d].indexOf(".")&&(l._info("Appending message type to URI "+b+" is not supported, disabling 'appendMessageTypeToURL' configuration"),q.appendMessageTypeToURL=!1)))};this.init=function(b,a){this.configure(b);this.handshake(a)};this.handshake=function(b,a){g("disconnected");V=!1;X(b,a)};this.disconnect=function(b,a,c){k()||("boolean"!==typeof b&&(c=a,a=b,b=!1),d(a)&&(c=a,a=void 0),a=this._mixin(!1,{},a,{channel:"/meta/disconnect",
_callback:c}),g("disconnecting"),y(!0===b,[a],!1,"disconnect"))};this.startBatch=function(){++D};this.endBatch=function(){--D;if(0>D)throw"Calls to startBatch() and endBatch() are not paired";0===D&&(!k()&&!K)&&G()};this.batch=function(b,a){var c=ga(b,a);this.startBatch();try{c.method.call(c.scope),this.endBatch()}catch(d){throw this._info("Exception during execution of batch",d),this.endBatch(),d;}};this.addListener=function(b,c,d){if(2>arguments.length)throw"Illegal arguments number: required 2, got "+
arguments.length;if(!a(b))throw"Illegal argument type: channel must be a string";return ha(b,c,d,!0)};this.removeListener=function(b){if(!b||!b.channel||!("id"in b))throw"Invalid argument: expected subscription, not "+b;f(b)};this.clearListeners=function(){A={}};this.subscribe=function(b,c,e,f,g){if(2>arguments.length)throw"Illegal arguments number: required 2, got "+arguments.length;if(!a(b))throw"Illegal argument type: channel must be a string";if(k())throw"Illegal state: already disconnected";
d(c)&&(g=f,f=e,e=c,c=void 0);d(f)&&(g=f,f=void 0);var h=!fa(b),l=ha(b,c,e,!1);h&&(h=this._mixin(!1,{},f,{channel:"/meta/subscribe",subscription:b,_callback:g}),L(h));return l};this.unsubscribe=function(b,a,c){if(1>arguments.length)throw"Illegal arguments number: required 1, got "+arguments.length;if(k())throw"Illegal state: already disconnected";d(a)&&(c=a,a=void 0);this.removeListener(b);var e=b.channel;fa(e)||(e=this._mixin(!1,{},a,{channel:"/meta/unsubscribe",subscription:e,_callback:c}),L(e))};
this.resubscribe=function(b,a){b&&!b.listener&&f(b);if(b)return this.subscribe(b.channel,b.scope,b.callback,a)};this.clearSubscriptions=function(){p()};this.publish=function(b,c,e,f){if(1>arguments.length)throw"Illegal arguments number: required 1, got "+arguments.length;if(!a(b))throw"Illegal argument type: channel must be a string";if(/^\/meta\//.test(b))throw"Illegal argument: cannot publish to meta channels";if(k())throw"Illegal state: already disconnected";d(c)?(f=c,c=e={}):d(e)&&(f=e,e={});
var g=this._mixin(!1,{},e,{channel:b,data:c,_callback:f});L(g)};this.getStatus=function(){return H};this.isDisconnected=k;this.setBackoffIncrement=function(b){q.backoffIncrement=b};this.getBackoffIncrement=function(){return q.backoffIncrement};this.getBackoffPeriod=function(){return w};this.setLogLevel=function(b){q.logLevel=b};this.registerExtension=function(b,c){if(2>arguments.length)throw"Illegal arguments number: required 2, got "+arguments.length;if(!a(b))throw"Illegal argument type: extension name must be a string";
for(var e=!1,f=0;f<v.length;++f)if(v[f].name===b){e=!0;break}if(e)return this._info("Could not register extension with name",b,"since another extension with the same name already exists"),!1;v.push({name:b,extension:c});this._debug("Registered extension",b);d(c.registered)&&c.registered(b,this);return!0};this.unregisterExtension=function(b){if(!a(b))throw"Illegal argument type: extension name must be a string";for(var c=!1,e=0;e<v.length;++e){var f=v[e];if(f.name===b){v.splice(e,1);c=!0;this._debug("Unregistered extension",
b);b=f.extension;d(b.unregistered)&&b.unregistered();break}}return c};this.getExtension=function(b){for(var a=0;a<v.length;++a){var c=v[a];if(c.name===b)return c.extension}return null};this.getName=function(){return ja};this.getClientId=function(){return I};this.getURL=function(){if(t&&"object"===typeof q.urls){var a=q.urls[t.getType()];if(a)return a}return q.url};this.getTransport=function(){return t};this.getConfiguration=function(){return this._mixin(!0,{},q)};this.getAdvice=function(){return this._mixin(!0,
{},x)};org.cometd.WebSocket=window.WebSocket;org.cometd.WebSocket||(org.cometd.WebSocket=window.MozWebSocket)};"function"===typeof define&&define.amd&&define("org/cometd",function(){return org.cometd});
//@ sourceMappingURL=cometd.js.map