//>>built
require({cache:{"url:ec/fisa/widget/i18n/templates/I18nOutputText.html":'\x3cdiv data-dojo-attach-point\x3d"multilingual_container_node" class\x3d"${styleClass}"\x3e\n\t\x3ctable cellpadding\x3d"0" cellspacing\x3d"0" border\x3d"0"\x3e\x3ctr\x3e\n\x3ctd\x3e\n\t\x3cdiv style\x3d"float: left;width:225px" data-dojo-attach-point\x3d"_tcn"\x3e\x3c/div\x3e\n\x3c/td\x3e\x3ctd valign\x3d"middle"\x3e\n\t\x3cdiv style\x3d"float: left;" class\x3d"i18nControlBtns" data-dojo-attach-point\x3d"buttons_container_node"\x3e\n\t\t\x3cbutton id\x3d"${id}_collapseLanguagesButton_node" data-dojo-type\x3d"dijit.form.Button"\n\t\t\tdata-dojo-attach-point\x3d"collapseLanguagesButton_node" type\x3d"button"\n\t\t\tdata-dojo-attach-event\x3d"onClick:_toggleCollapsed"\n\t\t\ticonClass\x3d"colapseLanguages" showLabel\x3d"false" \x3e\x3c/button\x3e\n\t\x3c/div\x3e\n\t\x3c/td\x3e\n\t\x3c/tr\x3e\n\t\x3c/table\x3e\n\x3c/div\x3e\n'}});
define("ec/fisa/widget/i18n/I18nOutputText","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_Templated dojo/text!./templates/I18nOutputText.html dijit/form/Button dijit/form/TextBox dojox/lang/functional/object dojo/dom-style dojo/dom-attr dojo/dom dojo/dom-construct dijit/dijit dojo/on ec/fisa/widget/OutputText ./_base".split(" "),function(e,m,n,p,q,s,t,u,g,h,v,k,r,w){return m("ec.fisa.widget.i18n.I18nOutputText",[n,p],{supportedLanguages:[],defaultLanguage:"",supportedLanguagesNumber:0,
tapdFieldLenght:0,translationsDivs:null,translationsTextBoxes:null,isoCodes:null,collapsed:!1,actualTranslations:0,actualValue:"",isARoutineField:!1,routineController:null,routineBtId:null,routineFieldId:null,routineActionMode:null,tabId:"",pageScopeId:"",styleClass:"i18nOutputText",widgetsInTemplate:!0,_fovt:null,autho:!1,oldValue:"",templateString:q,constructor:function(a,c){try{this.supportedLanguages=a,this.defaultLanguage=c,this.translationsDivs=[],this.translationsTextBoxes=[],this.isoCodes=
[]}catch(b){this.logger(b)}},buildRendering:function(){this.inherited(arguments);this.autho&&(g.set(this._tcn,"border","1px solid #FF0000"),this._ov=this.oldValue.split(String.fromCharCode(255)))},destroy:function(){delete this._fovt;delete this.translationsDivs;var a=this.translationsTextBoxes;delete this.translationsTextBoxes;e.forEach(a,function(a){a.destroy(!1)},this);this.inherited(arguments)},logger:function(a){},_createTranslationTextBox:function(a,c,b){var d=e.create("div",{id:this.id+"_"+
a+"_translation"},this._tcn),l=e.create("div",{style:{"float":"left",width:"185px","padding-top":"3px"}},d),f=e.create("div",{},d);h.set(f,"class","i18nOutputTextTranslationTagContainerClass");f=e.create("span",null,f);h.set(f,"class","i18nTextBoxTranslationTagClassImg");k.create("img",{src:e.config.fisaContextPath+"/"+e.config.fisaImages+"/languages/"+a+".png",alt:a,title:a,onerror:this.onerrorCall},f);f=new ec.fisa.widget.OutputText({value:c},a);f.placeAt(l);this.autho&&(null!=this._ov&&this._ov.length>
b&&this._ov[b]!==c)&&(k.create("br",{},l),c=k.create("span",{style:{color:"#FF0000"}},l),c.innerHTML=dojox.html.entities.encode(this._ov[b]),0==b&&(this._fovt=c,this.collapsed&&g.set(c,"display","none")));f.fwId=this.id;this.translationsDivs[b]=d;this.translationsTextBoxes[b]=f;this.isoCodes[b]=a},_init:function(){this.supportedLanguagesNumber=this.supportedLanguages.length},_upLangValue:function(a,c){var b=r.byId(this.fwId);b.actualValue.split(String.fromCharCode(255));var d="";e.forEach(b.isoCodes,
function(a,b){var c=null,c=h.get(this.translationsTextBoxes[b],"value");d+=c;b<this.actualTranslations-1&&(d+=String.fromCharCode(255))},b);b.actualValue=d;b.binding&&b.binding.set("value",b.actualValue)},_setVisible:function(a){g.set(a,"display","block");g.set(a,"float","left")},_setNotVisible:function(a){g.set(a,"display","none")},_getValueAttr:function(){return this.actualValue},_setValueAttr:function(a,c,b){null===a||void 0===a?a="":"string"!=typeof a&&(a=String(a));this.actualValue=a;var d=this.actualValue.split(String.fromCharCode(255));
a=this.oldValue.split(String.fromCharCode(255));if(d.length<a.length){for(c=a.length-1;c>=d.length;c--)a[c-1]=a[c-1]+String.fromCharCode(255)+a[c];this._ov=a.splice(0,d.length)}if(this.translationsTextBoxes.length<d.length)for(a=this.translationsTextBoxes.length;a<=this.supportedLanguages.length;a++)d&&(d[a]&&!this.translationsTextBoxes[a])&&(this._createTranslationTextBox(this.supportedLanguages[a],d[a],a),this.actualTranslations=a+1);0==this.translationsTextBoxes.length&&this._createTranslationTextBox(this.supportedLanguages[0],
"",0);this.translationsTextBoxes&&(e.forEach(this.translationsTextBoxes,function(a,b){a.set("value",d[b])},this),this.collapsed=!1,this._toggleCollapsed())},attachOnChangeEvent:function(a,c,b,d){},_routineEvent:function(){},_collapaseTranslations:function(){try{if(null!=this._fovt&&this._setNotVisible(this._fovt),1<this.translationsDivs.length)for(i=0;i<this.translationsDivs.length;i++)this.isoCodes[i]!=this.defaultLanguage&&this._setNotVisible(this.translationsDivs[i])}catch(a){this.logger(a)}},
_expandTranslations:function(){try{null!=this._fovt&&this._setVisible(this._fovt);for(i=0;i<this.actualTranslations;i++)this._setVisible(this.translationsDivs[i])}catch(a){this.logger(a)}},_toggleCollapsed:function(){this.collapsed?(h.set(this.collapseLanguagesButton_node,"iconClass","colapseLanguages"),this._expandTranslations()):(h.set(this.collapseLanguagesButton_node,"iconClass","expandLanguages"),this._collapaseTranslations());this.collapsed=!this.collapsed}})});
//@ sourceMappingURL=I18nOutputText.js.map