//>>built
define("ec/fisa/controller/transfers/MultipleTransfersController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/controller/custom/CustomBtController dojo/dom-construct dijit/form/CheckBox dojo/dom-geometry dojo/dom-style ec/fisa/widget/SANotificationGridUser ec/fisa/format/Utils ec/fisa/navigation/Utils".split(" "),function(l,n,r,s,p,t,u,q,m){return n("ec.fisa.controller.transfers.MultipleTransfersController",p,{listUserDataGridId:null,tXMDinamicGridId:null,
selectedUsers:null,selectedProds:null,breadcrumbId:null,icons:null,additionalSucessCheckBoxList:[],additionalUnSucessCheckBoxList:[],urlToAdditionalUserPage:null,disableVal:null,breadCrumbAdditionalUser:null,parentBtId:null,additionalUserGridId:null,productSelectValues:null,contentPanelProperties:null,priorityId:null,listSelectFrecuency:{},ownAccountsData:null,listGridData:null,btnBackId:null,btnNextId:null,btnSaveId:null,btnCloseId:null,btnCancelId:null,btnPrintId:null,montoId:"monto",montoIdAux:"monto_aux",
descId:"desc",montoReadId:"montoRead",descReadId:"descRead",accountId:null,accountAmountId:"accountAmount",resumePanelId:null,inputDisabled:null,montoReadId:"montoRead",descReadId:"descRead",chargeId:"charge",totalAmountId:"totalAmount",summaryId:"summary",summarySaveId:"summarySave",isSuccess:"totalSuccess",notificationPanelId:null,constructor:function(a,b,c){this.listGridData={};this.inputDisabled=!1;void 0==c.aMsgs&&(this.selectedUsers=c.selectedUsers,this.selectedProds=c.selectedProds,this.disableVal=
c.disableVal,this.parentBtId=c.parentBtId,this.priorityId=c.priorityId,this.ownAccountsData=c.ownAccountsData);delete c.selectedUsers;delete c.selectedProds;delete c.disableVal;delete c.parentBtId;delete c.priorityId;delete c.ownAccountsData},getSelectedUsers:function(){return this.selectedUsers},getSelectedProds:function(){return this.selectedProds},setTxMDinamicGridId:function(a){this.tXMDinamicGridId=a},getTxMDinamicGrid:function(){return dijit.byId(this.tXMDinamicGridId)},setListProdDataGridId:function(a){this.listProdDataGridId=
a.id},_getSelectedUsers:function(){return this._getSelectedValues(this.listUserDataGridId)},_getSelectedProducts:function(){return this._getSelectedValues(this.listProdDataGridId)},_getSelectedProductsLine:function(){return this._getSelectedValuesProducts(this.listProdDataGridId)},_getSelectedValuesProducts:function(a){a=dijit.byId(gridId);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],l.forEach(a.fisaChecks,function(a){dijit.byId(a).checked&&b.push(null)},this));return b},_getSelectedValues:function(a){a=
dijit.byId(a);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],l.forEach(a.fisaChecks,function(a){a=dijit.byId(a);a.checked&&b.push(a.fval)},this));return b},_getSelectedAllProducts:function(){return this._getAllValues(this.listProdDataGridId)},_getAllValues:function(a){a=dijit.byId(a);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],l.forEach(a.fisaChecks,function(a){a=dijit.byId(a);b.push(a.fval)},this));return b},validateBtInfo:function(a){this.clearPanelMessage();for(var b=!1,c="",e=this.getTxMDinamicGrid().store.getResults(),
g=!1,f=0;f<e.length;f++)"true"===this.listGridData[e[f].data.id][this.isSuccess]&&(g=!0);g||(b=!0,c=this.initLabels.warning6);b?(b=this.generateMsg(c,"",4E4),a.aMsgs=b,a.wAxn="error"):a.wAxn="cnfrm";return a},cancel:function(){EventActionDWR.executeCommandButtonCancel(this.tabId,this.pageScopeId,this.btId,{callbackScope:this,callback:this.handleCancelAction})},remove:function(a){},handleAdditionalSaveAction:function(a){this.contentPanelProperties.destroy()},handleConfirmationBt:function(a){var b=
a.respBtLabels[0],c=a.aMsgs,e=a.postBtId,g=a.pBtId,f=a.postBtIdDataKey,d=a.principalPostBtIdDataKey,h=a.parentBtInAuthorization,k=a.showReportModule;a=a.showReportAuto;dijit.byId(this.messagesPanelId).clearAllMessages();null==e?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(b,c,this.breadcrumbId,this.tabId,this.pageScopeId,this.btId,this.btActionMode,this.isSequence,k,a):(b=dijit.byId(this.breadcrumbId),ec.fisa.navigation.utils.showPostBtBreadCrumb(b.params.title,c,this.tabId,this.pageScopeId,
e,g,this.btContentPaneId,f,d,this.isSequence,k,a,h,!1))},setUrlToAdditionalUserPage:function(a){this.urlToAdditionalUserPage=a},openAdditionalUsersSelection:function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);a.productSelectValues=a._getSelectedProducts();var b={},c=ec.fisa.controller.utils.getGlobalModalSize(0.8);b.href=l.config.fisaContextPath+this.urlToAdditionalUserPage;b.ioArgs={content:{FISATabId:this.tabId,FISAParentPageScopeId:this.pageScopeId,isSelect:this.rowData.checked,
rowId:this.rowData.fval,componentId:this.parentBtId,height:c.h}};b.ioMethod=l.xhrPost;b.style="height:"+c.h+"px;width:700px;overflow: auto;";b.splitter="true";a.contentPanelProperties=new dojox.widget.DialogSimple(b);a.contentPanelProperties.resizeContainerNode=this.resizeNode;a.contentPanelProperties.show();a.resizeNode(a.contentPanelProperties,c)},resizeNode:function(a,b){var c=q.getMarginBox(a.titleNode);m.set(a.containerNode,"height",b.h-c.h-4*c.t+"px");m.set(a.containerNode,"display","block");
m.set(a.containerNode,"overflowY","auto");m.set(a.containerNode,"overflowX","auto")},save:function(a){this.clearPanelMessage();a={callbackScope:this,callback:this.handleSaveAction};var b=this._addNotificationValData();MultipleTransfersControllerDWR.save(this.listGridData,b,this.tabId,this.pageScopeId,a)},next:function(a){this.clearPanelMessage();a=!1;var b="",c=this.getTxMDinamicGrid().store.getResults(),e=dijit.byId(this.accountId).get("value");e&&"-1"==e&&(a=!0,b=this.initLabels.warning3);if(!a)for(var g=
0;g<c.length;g++){var f=c[g].data,d=f.id;this.listGridData[d]&&(this.listGridData[d][this.montoId]&&(f[this.montoId]=this.listGridData[d][this.montoId]),this.listGridData[d][this.descId]&&(f[this.descId]=this.listGridData[d][this.descId]));if(void 0==f[this.descId]||0==f[this.descId].length){a=!0;b=this.initLabels.warning1;break}else if(!(0<f[this.montoId])){a=!0;b=this.initLabels.warning2;break}}a?this.showErrorValidation(b):MultipleTransfersControllerDWR.next(this.listGridData,e,this.tabId,this.pageScopeId,
{callbackScope:this,callback:this.handleNextAction})},back:function(a){this.clearPanelMessage();MultipleTransfersControllerDWR.back(this.listGridData,this.tabId,this.pageScopeId,{callbackScope:this,callback:this.handleBackAction})},handleBackAction:function(a){this.inputDisabled=!1;dijit.byId(this.accountId).set("disabled",this.inputDisabled);a=this.getTxMDinamicGrid();a.isSortable=!0;for(var b=a.store.getResults(),c=0;c<b.length;c++){var e=b[c].data.id;this.listGridData[e]&&(this.listGridData[e][this.montoId]=
this.listGridData[e][this.montoIdAux])}a.layout.setColumnVisibility(7,!0);a.layout.setColumnVisibility(8,!0);a.layout.setColumnVisibility(9,!1);a.layout.setColumnVisibility(10,!1);a.layout.setColumnVisibility(11,!1);a.layout.setColumnVisibility(12,!1);a.layout.setColumnVisibility(13,!1);a.layout.setColumnVisibility(15,!1);a=dijit.byId(this.resumePanelId);b=dijit.byId(this.btnNextId);c=dijit.byId(this.btnBackId);e=dijit.byId(this.btnSaveId);this._setNotVisible(a);this._setNotVisible(c);this._setVisible(b);
this._setNotVisible(e);a=dijit.byId(this.notificationAdditionalsWdgId);l.forEach(a,function(a){a=dijit.byId(a.notifWdgId);this._setVisiblePanel(a.getParent(),"block")},this)},handleNextAction:function(a){this.inputDisabled=!0;dijit.byId(this.accountId).set("disabled",this.inputDisabled);var b=a.errorList,c=a.mapTxM;a=a.totalTxn;var e=this.getTxMDinamicGrid();e.isSortable=!1;for(var g=e.store.getResults(),f=0;f<g.length;f++){var d=g[f].data.id;if(c[d]&&(this.listGridData[d]&&(this.listGridData[d][this.isSuccess]=
c[d][this.isSuccess],this.listGridData[d][this.montoId]=c[d][this.montoId],this.listGridData[d][this.montoReadId]=c[d][this.montoId],this.listGridData[d][this.totalAmountId]=c[d][this.totalAmountId],this.listGridData[d][this.descId]=c[d][this.descId],this.listGridData[d][this.descReadId]=c[d][this.descId],this.listGridData[d][this.chargeId]=c[d][this.chargeId],this.listGridData[d][this.montoIdAux]=c[d][this.montoIdAux],this.listGridData[d][this.summaryId]=""),b[d])){for(var h="",k=0;k<b[d].length;k++)b[d][k][this.summaryId]&&
(h=h+"**"+b[d][k][this.summaryId]);this.listGridData[d]&&(this.listGridData[d][this.summaryId]=h)}}a&&this.setValuesResumePanel(a.accountAmount,a.totalCharge,a.totalDebit);e.layout.setColumnVisibility(7,!1);e.layout.setColumnVisibility(8,!1);e.layout.setColumnVisibility(9,!0);e.layout.setColumnVisibility(10,!0);e.layout.setColumnVisibility(11,!0);e.layout.setColumnVisibility(12,!0);e.layout.setColumnVisibility(13,!0);e.layout.setColumnVisibility(15,!1);b=dijit.byId(this.resumePanelId);c=dijit.byId(this.btnNextId);
a=dijit.byId(this.btnBackId);e=dijit.byId(this.btnSaveId);this._setVisiblePanel(b);this._setNotVisible(c);this._setVisible(a);this._setVisible(e);b=dijit.byId(this.notificationAdditionalsWdgId);l.forEach(b,function(a){a=dijit.byId(a.notifWdgId);this._setNotVisible(a.getParent())},this)},handleSaveAction:function(a){var b=a.mapTxM,c=a.errorList,e=this.getTxMDinamicGrid(),g=e.store.getResults();a=a.totalTxn;for(var f=0;f<g.length;f++){var d=g[f].data,h=d.id,k="";if(c[h])for(var k="",l=0;l<c[h].length;l++)c[h][l][this.summaryId]&&
(k=k+"**"+c[h][l][this.summaryId]);else b[h]&&b[h][this.summaryId]&&(k=b[h][this.summaryId]);d[this.summarySaveId]=k;this.listGridData[h]&&(this.listGridData[h][this.summarySaveId]=k)}a&&this.setValuesResumePanel(a.accountAmount,a.totalCharge,a.totalDebit);e.layout.setColumnVisibility(13,!1);e.layout.setColumnVisibility(14,!0);b=dijit.byId(this.btnNextId);c=dijit.byId(this.btnBackId);e=dijit.byId(this.btnSaveId);g=dijit.byId(this.btnCloseId);a=dijit.byId(this.btnCancelId);f=dijit.byId(this.btnPrintId);
this._setNotVisible(a);this._setNotVisible(b);this._setNotVisible(c);this._setNotVisible(e);this._setVisible(g);this._setVisible(f)},setValuesResumePanel:function(a,b,c){this.model.accountAmount.set("value",a);this.model.totalCharge.set("value",b);this.model.totalDebit.set("value",c)},showErrorValidation:function(a){this.clearPanelMessage();a=this.generateMsg(a,"",4E4);this.updateMsgsPanel(a)},_setVisiblePanel:function(a){a.style="min-width:98%; display: inline-block";m.set(a.domNode,"display","inline-block");
a.resize()}})});
//@ sourceMappingURL=MultipleTransfersController.js.map