//>>built
require({cache:{"url:ec/fisa/widget/rules/templates/RulesComponent.html":'\x3cdiv id\x3d"${id}_rule"\x3e\n\t\x3cdiv data-dojo-attach-point \x3d "_ruleContainer"\x3e\n\t\t\n\t\x3c/div\x3e\n\t\x3cdiv data-dojo-attach-point \x3d "_newRuleLink"\x3e\n\t\t\n\t\x3c/div\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/rules/AuthorizationRule","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_Templated dojo/on dijit/TitlePane ec/fisa/widget/Link dojo/dom-construct dojo/dom-geometry dojo/dom-style ec/fisa/controller/custom/BtController ec/fisa/widget/rules/RulesComponent dojox/widget/DialogSimple dojox/encoding/base64 dojo/text!./templates/RulesComponent.html dojox/lang/functional/object ec/fisa/format/Utils ./_base".split(" "),function(p,s,z,A,B,t,r,f,C,D,E,y,F,G,H){return s("ec.fisa.widget.rules.AuthorizationRule",
[y],{authUserForRule:null,onlyRead:!1,initTableId:null,autAll:"Todos",autAtLeastOne:"Al menos uno",constructor:function(){this.inherited(arguments);this.authUserForRule=[]},postMixInProperties:function(){this.inherited(arguments);this.readOnly=this.onlyRead},postCreate:function(){this.inherited(arguments);ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).setAuthorizationRule(this)},initNewRuleLink:function(){this.onlyRead||(this.newRuleLink=new r({label:this.newRuleLabel}),this.newRuleLink.placeAt(this._newRuleLink),
this.onlyRead||this.newRuleLink.connect(this.newRuleLink,"onClick",p.hitch(this,this.createNewRuleSection)))},createNewRuleSection:function(){var a=new t({title:"Regla"});a.placeAt(this._ruleContainer);var c=this.numberOfRules;this.numberOfRules++;this.rulePaneList[c]=a;return this.initNewConditionSection(a.containerNode,c)},initNewConditionSection:function(a,c){var d=this.createTableRuleId(c),k=this.createTableBodyRuleId(c),b=d+"_auth",e=k+"_auth";this.conditionsArray[c]={};this.numberOfConditionsForRuleIndex[c]=
0;var h=f.create("table",{id:d,rulescompid:this.id,ruleindex:c,cellpadding:"0",cellspacing:"0",border:"0",width:"60%",align:"left"},a),h=f.create("tbody",{id:k,rulescompid:this.id,ruleindex:c},h),b=f.create("table",{id:b,rulescompid:this.id,ruleindex:c,cellpadding:"0",cellspacing:"0",border:"0",width:"40%",align:"right"},a),e=f.create("tbody",{id:e,rulescompid:this.id,ruleindex:c},b),b=f.create("table",{cellpadding:"0",cellspacing:"0",border:"0",width:"100%"},a),b=f.create("tbody",{},b),b=f.create("tr",
{},b),l={};l.tableId=d;l.tBodyId=k;l=this.initNewRuleObject(l);if(!this.onlyRead){k=new r({label:this.newConditionLabel});k.tableId=d;k.ruleObject=l;k.parent=this;this.onlyRead||k.connect(k,"onClick",p.hitch(k,this.showFieldSelector,null));var m=f.create("td",{align:"left"},b);k.placeAt(m);m=new r({label:"Eliminar Regla"});m.tableId=d;m.ruleObject=l;m.parent=this;this.onlyRead||m.connect(m,"onClick",p.hitch(this,this.delRule,c));d=f.create("td",{align:"right"},b);m.placeAt(d);this.links[c]=[m,k]}return{ruleSectionTbody:h,
authSectionTbody:e}},createTableAuthorizationId:function(a){return a+"_auth"},addItem:function(a,c,d,k){var b=null,b=k?k:p.byId(this.createTableAuthorizationId(d.id)),e=new ec.fisa.widget.rules.Condition({rulesComponentId:this.id,fieldType:a,item:c,ruleContainer:d,tabId:this.tabId,pageScopeId:this.pageScopeId});e.placeAt(d);a=e.ruleIndex;k=e.conditionIndex;d=d.rows.length;var h=b.rows.length;e.startup();1==d&&0==h?(h=f.create("tr",{align:"center"},b),d=f.create("tr",{align:"center"},b),e=f.create("td",
{style:"border-top:4px; border-left:4px; solid transparent;color:#1c75bc;padding-top:13px; padding-left:13px"},d),b=f.create("td",{style:"border-top:4px; border-left:4px; solid transparent;color:#1c75bc;padding-top:13px; padding-left:13px"},h),b=f.create("table",{cellpadding:"0",cellspacing:"0",border:"0",width:"65%"},b),b=f.create("tbody",{},b),b=f.create("tr",{"class":"evenFieldBt"},b),tddA4=f.create("div",{},e),tdddA1=f.create("div",{},tddA4),f.create("td",{style:"border-top:4px; border-left:4px; solid transparent;color:#1c75bc;padding-top:13px; padding-left:13px"},
d),h=f.create("td",{"class":"fisaComponentGridHalfLeftCell"},b),d=f.create("td",{"class":"fisaComponentGridHalfRightCell"},b),e=f.create("td",{"class":"fisaComponentGridHalfLeftCell"},b),b=f.create("td",{"class":"fisaComponentGridHalfRightCell"},b),h=f.create("div",{},h),e=f.create("div",{},e),f.create("label",{"class":"fisaLabel",innerHTML:this.autAll},h),f.create("label",{"class":"fisaLabel",innerHTML:this.autAtLeastOne},e),d=f.create("div",{},d),e=f.create("div",{},b),b=new dijit.form.CheckBox({},
d),d=new dijit.form.CheckBox({},e),this.onlyRead?(b.set("disabled",!0),d.set("disabled",!0)):(b.connect(b,"onChange",p.hitch(this,this._setAllChange,b,d)),d.connect(d,"onChange",p.hitch(this,this._setOneChange,b,d))),new dijit.layout.ContentPane({doLayout:"false",style:"height: auto; overflow: auto; width: 450px; display: block; border: 10px;",splitter:"true"},tddA4),e=new ec.fisa.widget.authorization.UserGrid({style:"width: 100%;",autoHeight:"true",label:"Autorizadores",tabId:this.tabId,pageScopeId:this.pageScopeId,
onlyRead:this.onlyRead,selectUsers:c.users,style:"display: block;",isMain:!1},tdddA1),e.startup(),h=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),h.panelInit||h.tempUserGrid.push(e),void 0!=c.approvalType&&("3"==c.approvalType?b.set("checked",!0,!1):d.set("checked",!0,!1)),this.conditionsArray[a][k].usersComponentId=e.id,this.conditionsArray[a][k].approvalTypeComponentId=b.id,this.authUserForRule[a]={userGridId:e.id,approvalTypeId:b.id}):(this.conditionsArray[a][k].usersComponentId=
this.authUserForRule[a].userGridId,this.conditionsArray[a][k].approvalTypeComponentId=this.authUserForRule[a].approvalTypeId);this._fieldSelector.hide()},_getValueAttr:function(){var a={group:[]};a.btId=this.relatedFieldBt;a.fieldId=null;a.operator="AND";a.value=null;a.users=null;a.type=null;for(var c in this.conditionsArray){var d={group:[],btId:null,fieldId:null,operator:"OR",value:null,users:null,type:null};if(!this._isEmpty(this.conditionsArray[c])){for(var f in this.conditionsArray[c]){var b=
{group:null,operator:null,value:[],fieldId:null,btId:null,type:null,users:null};temp=this.conditionsArray[c][f];b.group=[];b.btId=temp.btId;b.fieldId=temp.fieldId;var e=dijit.byId(temp.operatorComponentId);b.operator=e.get("value");var e=dijit.byId(temp.value1ComponentId),h=e.get("value"),e="dijit.form.MultiSelect"==e.declaredClass;if(!0===e)for(var l=0;l<h.length;l++)b.value.push(h[l]);else b.value.push(h);if("7"==b.operator)if(l=dijit.byId(temp.value2ComponentId).get("value"),h=h.length,!1===e)b.value.push(l);
else for(e=0;e<h;e++)b.value.push(l[e]);null==d.users&&(d.users=dijit.byId(temp.usersComponentId).selection.getSelected(),p.byId(temp.approvalTypeComponentId).checked?d.approvalType="3":d.approvalType="1");b.type=temp.fieldType;d.group.push(b)}a.group.push(d)}}return a},_setValueAttr:function(a){var c=a[0],d=a[1],f=a[2];if(!(null==c||null==d||null==f)){this._fieldSelector=new dojox.widget.DialogSimple;for(var b in c.group){var e=c.group[b],h=c.group[b].users,l=c.group[b].approvalType,m=this.createNewRuleSection(),
r=m.ruleSectionTbody,m=m.authSectionTbody,w;for(w in e.group){var g=null,n=e.group[w];if("F"==n.type){var q=d.fields,u;for(u in q)if(q[u].id==n.fieldId){g=q[u];g.value=n.value;g.btId=n.btId;g.operator=n.operator;g.users=h;g.approvalType=l;break}}else if("V"==n.type){var q=d.variables,v;for(v in q)if(q[v].id==n.fieldId){g=q[v];g.value=n.value;g.btId=n.btId;g.operator=n.operator;g.users=h;g.approvalType=l;break}}if(null!=g){q={id:g.id,btId:g.btId,fieldName:g.prompt,value:g.value,operator:g.operator,
users:g.users,approvalType:g.approvalType,conditionEnable:g.conditionEnable,dbDataType:g.dbDataType};a=g.qtId;if(null!=a&&(a=f[a],null!=a)){var s=g.qtDescription,t=g.qtValue,x=[];p.forEach(a,function(a){x.push({label:a["f"+s],value:a["f"+t]})},this);q.qtItems=x}g=p.getAttr(r,"rulescompId");dijit.byId(g).addItem(n.type,q,r,m)}}}c=this._fieldSelector;delete this._fieldSelector;c.destroyRecursive(!1)}},_setOneChange:function(a,c){null==c||null==a||(c.checked?a.set("value",!1,!1):a.set("value",!0,!1))},
_setAllChange:function(a,c){null==a||null==c||(a.checked?c.set("checked",!1,!1):c.set("checked",!0,!1))},delRule:function(a){this.destroyAuthorizationComponents(this.authUserForRule[a]);var c=this.createTableRuleId(a),c=this.createTableAuthorizationId(c);f.destroy(c);delete this.authUserForRule[a];this.inherited(arguments)},destroyAuthorizationComponents:function(a){var c=dijit.byId(a.userGridId);c.destroy(!1);c=dijit.byId(a.approvalTypeId);c.destroy(!1)},destroy:function(){p.forEach(this.authUserForRule,
function(a,c){this.destroyAuthorizationComponents(a)},this);this.inherited(arguments)}})});
//@ sourceMappingURL=AuthorizationRule.js.map