//>>built
require({cache:{"url:ec/fisa/widget/rules/templates/RulesComponent.html":'\x3cdiv id\x3d"${id}_rule"\x3e\n\t\x3cdiv data-dojo-attach-point \x3d "_ruleContainer"\x3e\n\t\t\n\t\x3c/div\x3e\n\t\x3cdiv data-dojo-attach-point \x3d "_newRuleLink"\x3e\n\t\t\n\t\x3c/div\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/rules/RulesComponent","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_Templated dojo/on dijit/TitlePane ec/fisa/widget/Link dojo/dom-construct dojo/dom-geometry dojo/dom-style ec/fisa/controller/custom/BtController dojox/widget/DialogSimple dojox/encoding/base64 dojo/text!./templates/RulesComponent.html ec/fisa/widget/DateTextBox ec/fisa/widget/rules/Condition dojox/lang/functional/object ec/fisa/format/Utils ./_base".split(" "),function(f,v,w,x,B,y,r,g,z,q,C,D,s,
A){return v("ec.fisa.widget.rules.RulesComponent",[w,x],{tabId:"",pageScopeId:"",templateString:A,newRuleLabel:"Nueva Regla",newConditionLabel:"Agregar Nueva Condici\u00f3n",ruleLabel:"Regla",deleteRuleLabel:"Eliminar regla",fieldSelectorTitle:"Seleccione un Campo o Variable",ruleSectionTable:"Table",ruleSectionTbody:"TBody",newRuleLink:null,businessTemplateId:"",fieldId:"",fieldProperties:null,relatedFieldBt:"",operators:null,additionalFieldInfo:null,numberOfRules:0,numberOfConditionsForRuleIndex:null,
links:null,rulePaneList:null,conditionsArray:null,readOnly:!1,comboData:null,rulesData:null,rulesComponentNumber:null,constructor:function(){this.sectionRules=[];this.conditionsArray=[];this.numberOfConditionsForRuleIndex=[];this.links={};this.rulePaneList={}},postMixInProperties:function(){this.inherited(arguments);if(this.fieldProperties){var a=this.fieldProperties.RULE_REF_FIELD;this.fieldProperties=a;this.relatedFieldBt=a[0].value}},postCreate:function(){this.inherited(arguments);this.initNewRuleLink();
if(this.operators){var a=[];dojox.lang.functional.forIn(this.operators,function(b,d){a.push({label:b,value:d})},this);this.operators=a}},initNewRuleLink:function(){var a=this.newRuleLabel;this.readOnly&&(a="");this.newRuleLink=new r({label:a},g.create("div",null,this._newRuleLink));this.readOnly||this.newRuleLink.connect(this.newRuleLink,"onClick",f.hitch(this,this.createNewRuleSection))},createNewRuleSection:function(){var a=new y({title:this.ruleLabel});a.placeAt(this._ruleContainer);a.startup();
var b=this.numberOfRules;this.numberOfRules++;this.rulePaneList[b]=a;return this.initNewConditionSection(a.containerNode,b)},initNewConditionSection:function(a,b){var d=this.createTableRuleId(b),c=this.createTableBodyRuleId(b);this.conditionsArray[b]={};this.numberOfConditionsForRuleIndex[b]=0;var t=g.create("table",{id:d,rulescompid:this.id,ruleindex:b,cellpadding:"0",cellspacing:"0",border:"0"},a),t=g.create("tbody",{id:c,rulescompid:this.id,ruleindex:b},t),h=g.create("table",{cellpadding:"0",cellspacing:"0",
border:"0",width:"100%"},a),h=g.create("tbody",{},h),h=g.create("tr",{},h),l={};l.tableId=d;l.tBodyId=c;var c=this.initNewRuleObject(l),l=g.create("td",{align:"left"},h),e=this.newConditionLabel;this.readOnly&&(e="");l=new r({label:e},g.create("div",null,l));l.tableId=d;l.ruleObject=c;l.parent=this;this.readOnly||l.connect(l,"onClick",f.hitch(l,this.showFieldSelector,null));h=g.create("td",{align:"right"},h);e=this.deleteRuleLabel;this.readOnly&&(e="");h=new r({label:e},g.create("div",null,h));h.tableId=
d;h.ruleObject=c;h.parent=this;this.readOnly||h.connect(h,"onClick",f.hitch(h,this.delRule,b));this.links[b]=[h,l];return t},initNewRuleObject:function(a){var b={};b.tableId=a.tableId;b.tBodyId=a.tBodyId;return b},showFieldSelector:function(a){var b=this.parent,d=null,c=ec.fisa.controller.utils.getPageController(b.tabId,b.pageScopeId);c&&(d=c.getFieldModel(b.businessTemplateId,b.relatedFieldBt));c={};c.href=f.config.fisaContextPath+"/ITEM_RULE_FIELD_SELECTOR/";c.href+=b.businessTemplateId;c.href+=
"/FISATabId/";c.href+=b.tabId;c.href+="/parentFisaPageScopeId/";c.href+=b.pageScopeId;c.href+="/parentBtId/";c.href+=s.encode(ec.fisa.format.utils.toByteArray(b.relatedFieldBt));c.href+="/_parentBtId/parentFieldId/";c.href+=b.fieldId;null!=d&&(c.href+="/btWhereToGetRuleFields/",c.href+=d);c.href+="/parentWidgetId/";c.href+=this.ruleObject.tBodyId;c.href+="/FDK/";null==a?c.href+="_FDK":(c.href+=s.encode(ec.fisa.format.utils.toByteArray("{id:'"+a.id+"',t:'"+a.type+"'}")),c.href+="/_FDK");c.href+="/content.jsp";
c.title=b.fieldSelectorTitle;c.ioArgs={content:{}};c.ioMethod=f.xhrPost;d=ec.fisa.controller.utils.getGlobalModalSize(0.8);c.style="height:"+d.h+"px;width:"+d.w+"px;";b._fieldSelector=new dojox.widget.DialogSimple(c);null!=a&&(c=f.byId(this.ruleObject.tBodyId),f.setAttr(c,"ruleindex",a.ruleindex),f.setAttr(c,"conditionindex",a.conditionindex));b._fieldSelector.tbid=this.ruleObject.tBodyId;b._fieldSelector.connect(b._fieldSelector,"hide",f.hitch(b,function(){var a=f.byId(this._fieldSelector.tbid);
ec.fisa.controller.utils.uninitializeController(f.getAttr(a,"tid"),f.getAttr(a,"psid"));f.removeAttr(a,"tid");f.removeAttr(a,"psid");a=this._fieldSelector;delete this._fieldSelector;a.destroyRecursive(!1)}));b._fieldSelector.show();b._resizeContainerNode(b._fieldSelector,d)},createTableRuleId:function(a){return"rule"+this.id.substring(this.id.lastIndexOf("_")+1)+"_"+this.ruleSectionTable+"_"+a},createTableBodyRuleId:function(a){return"rule"+this.id.substring(this.id.lastIndexOf("_")+1)+"_"+this.ruleSectionTbody+
"_"+a},_resizeContainerNode:function(a,b){var d=z.getMarginBox(a.titleNode);q.set(a.containerNode,"height",b.h-d.h-4*d.t+"px");q.set(a.containerNode,"display","block");q.set(a.containerNode,"overflowY","auto");q.set(a.containerNode,"overflowX","auto")},addItem:function(a,b,d){a=new ec.fisa.widget.rules.Condition({rulesComponentId:this.id,fieldType:a,item:b,ruleContainer:d,tabId:this.tabId,pageScopeId:this.pageScopeId});a.placeAt(d);a.startup();this._fieldSelector.hide()},closeFieldSelector:function(){this._fieldSelector.hide()},
_getValueAttr:function(){return this.rulesComponentNumber},_setValueAttr:function(a,b,d){this.rulesComponentNumber=a},_getRuleValueAttr:function(){var a=this.generateValue();return null!=a&&null==a.errorCode?a:null},_setRuleValueAttr:function(a,b,d){this.rulesData=a},renderRuleComponent:function(){var a=this.rulesData,b=this.additionalFieldInfo,d=this.comboData;if(!(null==a||null==b)){this._fieldSelector=new dojox.widget.DialogSimple;for(var c in a.group){var g=a.group[c],h=this.createNewRuleSection(),
l;for(l in g.group){var e=null,m=g.group[l];if("F"==m.type){var k=b.fields,u;for(u in k)if(k[u].id==m.fieldId){e=k[u];e.value=m.value;e.btId=m.btId;e.operator=m.operator;break}}else if("V"==m.type){var k=b.variables,n;for(n in k)if(k[n].id==m.fieldId){e=k[n];e.value=m.value;e.btId=m.btId;e.operator=m.operator;break}}if(null!=e){var k={id:e.id,btId:e.btId,fieldName:e.prompt,value:e.value,operator:e.operator,conditionEnable:e.conditionEnable,dbDataType:e.dbDataType},p=e.qtId;if(null!=p&&(p=d[p],null!=
p)){var q=e.qtDescription,r=e.qtValue,s=[];f.forEach(p,function(a){s.push({label:a["f"+q],value:a["f"+r]})},this);k.qtItems=s}e=f.getAttr(h,"rulescompId");dijit.byId(e).addItem(m.type,k,h)}}}a=this._fieldSelector;delete this._fieldSelector;a.destroyRecursive(!1)}},generateValue:function(){var a=null;if(null!=this.conditionsArray){var b=[],d;for(d in this.conditionsArray)b.push(d);if(0<b.length)for(var c=0;c<b.length;c++){d=b[c];var f=[],h;for(h in this.conditionsArray[d])f.push(h);if(0<f.length){null==
a&&(a={group:[],operator:"OR",value:null,fieldId:null,btId:null,type:null,users:null});var l={group:[],operator:"AND",value:null,fieldId:null,btId:null,type:null,users:null};a.group.push(l);for(var e=0;e<f.length;e++){var m=this.conditionsArray[d][f[e]],k={group:null,operator:null,value:[],fieldId:null,btId:null,type:null,users:null},g=dijit.byId(m.operatorComponentId);k.operator=g.get("value");var g=dijit.byId(m.value1ComponentId),n=g.get("value"),g="dijit.form.MultiSelect"==g.declaredClass;if(!0===
g)for(c=0;c<n.length;c++)k.value.push(n[c]);else k.value.push(n);if("7"==k.operator){var p=dijit.byId(m.value2ComponentId).get("value"),n=n.length;if(!1===g)k.value.push(p);else for(e=0;e<n;e++)k.value.push(p[e])}k.btId=m.btId;k.type=m.fieldType;k.fieldId=m.fieldId;l.group.push(k)}}}}return a},_setEnabledAttr:function(a){if(null!=a&&this.conditionsArray&&0<this.conditionsArray.length)for(var b=0;b<this.conditionsArray.length;b++)if(this.conditionsArray[b]&&0<this.conditionsArray[b].length)for(var d=
0;d<this.conditionsArray[b][d].length;d++)dijit.byId(this.conditionsArray[b][d].conditionId).enableCondition(a)},_isEmpty:function(a){if(!(void 0==a||null==a))for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},delRule:function(a){var b=this;dojox.lang.functional.forIn(b.conditionsArray[a],function(a){b.destroyRow(a)},this);var d=b.createTableRuleId(a);g.destroy(d);d=b.links[a];d[0].destroy(!1);d[1].destroy(!1);delete b.links[a];b.rulePaneList[a].destroy(!1);delete b.rulePaneList[a];delete b.conditionsArray[a]},
destroyRow:function(a){dijit.byId(a.conditionId).destroyCondition()},destroy:function(){f.forEach(this.conditionsArray,function(a,b){dojox.lang.functional.forIn(a,function(a){this.destroyRow(a)},this)},this);dojox.lang.functional.forIn(this.links,function(a,b){delete a[0].parent;delete a[1].parent;a[0].destroy(!1);a[1].destroy(!1)},this);dojox.lang.functional.forIn(this.rulePaneList,function(a,b){a.destroy(!1)},this);this.newRuleLink.destroy(!1);delete this.newRuleLink;this.inherited(arguments)}})});
//@ sourceMappingURL=RulesComponent.js.map