//>>built
require({cache:{"url:ec/fisa/widget/rules/templates/Rule.html":'\x3cdiv id\x3d"${id}_rule"\x3e\n\t\x3cdiv data-dojo-attach-point \x3d "_ruleContainer"\x3e\n\t\t\n\t\x3c/div\x3e\n\t\x3cdiv data-dojo-attach-point \x3d "_newRuleLink"\x3e\n\t\t\n\t\x3c/div\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/rules/Rule","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_Templated dojo/on dijit/TitlePane ec/fisa/widget/Link dojo/dom-construct dojo/dom-geometry dojo/dom-style ec/fisa/controller/custom/BtController dojox/widget/DialogSimple dojox/encoding/base64 dojo/text!./templates/Rule.html dojox/lang/functional/object ec/fisa/format/Utils ./_base".split(" "),function(m,u,w,x,B,y,r,f,z,q,C,D,t,A){return u("ec.fisa.widget.rules.Rule",[w,x],{tabId:"",pageScopeId:"",templateString:A,
newRuleLabel:"Nueva Regla",newConditionLabel:"Agregar Nueva Condici\u00f3n",fieldSelectorTitle:"Seleccione un Campo o Variable",sectionRules:null,ruleSectionTable:"sTbl",ruleSectionTbody:"sTbd",count:0,businessTemplateId:"",fieldId:"",relatedFieldBt:"",operators:null,fieldProperties:null,_value:null,_sidx:null,_links:null,_panes:null,newRuleLink:null,readOnly:!1,value:null,additionalFieldInfo:null,comboData:null,initialData:null,constructor:function(){this.sectionRules=[];this._value=[];this._sidx=
[];this._links={};this._panes={}},postMixInProperties:function(){this.inherited(arguments);if(this.fieldProperties){var c=this.fieldProperties.RULE_REF_FIELD;this.fieldProperties=c;this.relatedFieldBt=c[0].value}},postCreate:function(){this.inherited(arguments);this.initNewRuleLink();if(this.operators){var c=[];dojox.lang.functional.forIn(this.operators,function(b,e){c.push({label:b,value:e})},this);this.operators=c}},initNewRuleLink:function(){this.newRuleLink=new r({label:this.newRuleLabel},f.create("div",
null,this._newRuleLink));this.readOnly||this.newRuleLink.connect(this.newRuleLink,"onClick",m.hitch(this,this.createNewRuleSection))},createNewRuleSection:function(){var c=new y({title:"Regla"});c.placeAt(this._ruleContainer);c.startup();var b=this.count;this.count++;this._panes["p"+b]=c;return this.initNewConditionSection(c.containerNode,b)},initNewConditionSection:function(c,b){var e=this.createTableRuleId(b),a=this.createTableBodyRuleId(b);this._value["v"+b]={};this._sidx["s"+b]=0;var l=f.create("table",
{id:e,"rule-idx":b,cellpadding:"0",cellspacing:"0",border:"0"},c),l=f.create("tbody",{id:a,"rule-idx":b},l),d=f.create("table",{cellpadding:"0",cellspacing:"0",border:"0",width:"100%"},c),d=f.create("tbody",{},d),d=f.create("tr",{},d),n={};n.tableId=e;n.tBodyId=a;a=this.initNewRuleObject(n);n=f.create("td",{align:"left"},d);n=new r({label:this.newConditionLabel},f.create("div",null,n));n.tableId=e;n.ruleObject=a;n.parent=this;this.readOnly||n.connect(n,"onClick",m.hitch(n,this.showFieldSelector,null));
d=f.create("td",{align:"right"},d);d=new r({label:" Eliminar Regla"},f.create("div",null,d));d.tableId=e;d.ruleObject=a;d.parent=this;this.readOnly||d.connect(d,"onClick",m.hitch(d,this.delRule,b));this._links["l"+b]=[d,n];return l},delRule:function(c){var b=this.parent;dojox.lang.functional.forIn(b._value["v"+c],function(a){b.destroyRow(a)},this);var e=b.createTableRuleId(c);f.destroy(e);e=b._links["l"+c];e[0].destroy(!1);e[1].destroy(!1);delete b._links["l"+c];b._panes["p"+c].destroy(!1);delete b._panes["p"+
c];delete b._value["v"+c]},initNewRuleObject:function(c){var b={};b.tableId=c.tableId;b.tBodyId=c.tBodyId;return b},showFieldSelector:function(c){var b=this.parent,e=null,a=ec.fisa.controller.utils.getPageController(b.tabId,b.pageScopeId);a&&(e=a.getFieldModel(b.businessTemplateId,b.relatedFieldBt));a={};a.href=m.config.fisaContextPath+"/ITEM_RULE_FIELD_SELECTOR/";a.href+=b.businessTemplateId;a.href+="/FISATabId/";a.href+=b.tabId;a.href+="/parentFisaPageScopeId/";a.href+=b.pageScopeId;a.href+="/parentBtId/";
a.href+=t.encode(ec.fisa.format.utils.toByteArray(b.relatedFieldBt));a.href+="/_parentBtId/parentFieldId/";a.href+=b.fieldId;null!=e&&(a.href+="/btWhereToGetRuleFields/",a.href+=e);a.href+="/parentWidgetId/";a.href+=this.ruleObject.tBodyId;a.href+="/FDK/";null==c?a.href+="_FDK":(a.href+=t.encode(ec.fisa.format.utils.toByteArray("{id:'"+c.id+"',t:'"+c.type+"'}")),a.href+="/_FDK");a.href+="/content.jsp";a.title=b.fieldSelectorTitle;a.ioArgs={content:{}};a.ioMethod=m.xhrPost;e=ec.fisa.controller.utils.getGlobalModalSize(0.8);
a.style="height:"+e.h+"px;width:"+e.w+"px;";b._fieldSelector=new dojox.widget.DialogSimple(a);null!=c&&(a=m.byId(this.ruleObject.tBodyId),m.setAttr(a,"val-idx",c.idx),m.setAttr(a,"val-sidx",c.sidx));b._fieldSelector.tbid=this.ruleObject.tBodyId;b._fieldSelector.connect(b._fieldSelector,"hide",m.hitch(b,function(){var a=m.byId(this._fieldSelector.tbid);ec.fisa.controller.utils.uninitializeController(m.getAttr(a,"tid"),m.getAttr(a,"psid"));m.removeAttr(a,"tid");m.removeAttr(a,"psid");a=this._fieldSelector;
delete this._fieldSelector;a.destroyRecursive(!1)}));b._fieldSelector.show();b._resizeContainerNode(b._fieldSelector,e)},createTableRuleId:function(c){return this.id+"_"+this.ruleSectionTable+"_"+c},createTableBodyRuleId:function(c){return this.id+"_"+this.ruleSectionTbody+"_"+c},_resizeContainerNode:function(c,b){var e=z.getMarginBox(c.titleNode);q.set(c.containerNode,"height",b.h-e.h-4*e.t+"px");q.set(c.containerNode,"display","block");q.set(c.containerNode,"overflowY","auto");q.set(c.containerNode,
"overflowX","auto")},addItem:function(c,b,e,a,l){var d=m.byId(e);a=m.getAttr(d,"rule-idx");var n=l=null,p=null,g=null,h=null,k=null;null!=m.getAttr(d,"val-idx")?(l=m.getAttr(d,"val-sidx"),k=this._value["v"+a][l],p=dijit.byId(k.p),n=f.create("div",{},p.domNode.parentNode),p.destroy(!1),delete p,g=dijit.byId(k.o),p=f.create("div",{},g.domNode.parentNode),g.destroy(!1),delete g,h=dijit.byId(k.v),g=f.create("div",{},h.domNode.parentNode),h.destroy(!1),delete h,d=dijit.byId(k.e),h=f.create("div",{},d.domNode.parentNode),
delete d.parent,d.destroy(!1),delete d,d=dijit.byId(k.d),k=f.create("div",{},d.domNode.parentNode),delete d.parent,d.destroy(!1),delete d):(l="i"+this._sidx["s"+a],this._sidx["s"+a]+=1,k=f.create("tr",{id:e+l},d),n=f.create("td",{style:"border-top:4px solid transparent;color:#1c75bc;padding-top:13px"},k),p=f.create("td",{style:"border-top:4px solid transparent;color:#1c75bc;padding-top:13px"},k),g=f.create("td",{style:"border-top:4px solid transparent;color:#1c75bc;padding-top:13px"},k),h=f.create("td",
{style:"border-top:4px solid transparent;color:#1c75bc;padding-top:13px"},k),k=f.create("td",{style:"border-top:4px solid transparent;color:#1c75bc;padding-top:13px"},k),n=f.create("div",{},n),p=f.create("div",{},p),g=f.create("div",{},g),h=f.create("div",{},h),k=f.create("div",{},k));n=new dijit.form.TextBox({value:b.prompt,"val-idx":a,"val-sidx":l,disabled:!0,style:{width:"150px"}},n);d={options:this.operators,"val-idx":a,"val-sidx":l,disabled:this.onlyRead,style:{width:"150px"}};null!=b.operator&&
""!==b.operator&&(d.value=b.operator);null!=b.conditionEnable&&""!==b.conditionEnable&&(d.readOnly="1"==b.conditionEnable);p=new dijit.form.Select(d,p);d=null;d=null==b.o?new dijit.form.TextBox({"val-idx":a,"val-sidx":l,style:{width:"150px"}},g):new dijit.form.Select({options:b.o,"val-idx":a,"val-sidx":l,style:{width:"150px"}},g);null!=b.value&&""!==b.value&&d.set("value",b.value);!0==this.onlyRead&&d.set("disabled","disabled");g=new dijit.form.Button({iconClass:"imgEdit",baseClass:"fisaGridButton",
showLabel:!1},h);g.connect(g,"onClick",m.hitch(g,this.showFieldSelector,{id:b.id,idx:a,sidx:l,type:c}));g.parent=this;g.ruleObject={tBodyId:e};h=new dijit.form.Button({iconClass:"imgDelete",baseClass:"fisaGridButton",showLabel:!1},k);h.connect(h,"onClick",m.hitch(this,this.execDelete,{id:b.id,idx:a,sidx:l,type:c}));h.parent=this;h.ruleObject={tBodyId:e};this._value["v"+a][l]={i:b.id,bt:b.btId,p:n.id,o:p.id,v:d.id,e:g.id,d:h.id,t:c};this._fieldSelector.hide()},execDelete:function(c){var b=c.idx;c=
c.sidx;var e=this.createTableBodyRuleId(b),a=m.byId(e),e=e+c;if(null!=a.rows&&0<a.rows.length)for(var l=0,l=0;l<a.rows.length;l++)if(e==a.rows[l].id){delete this._value["v"+b][c];a.deleteRow(l);break}},destroyRow:function(c){var b=dijit.byId(c.p);b.destroy(!1);b=dijit.byId(c.o);b.destroy(!1);b=dijit.byId(c.v);b.destroy(!1);b=dijit.byId(c.e);delete b.parent;b.destroy(!1);b=dijit.byId(c.d);delete b.parent;b.destroy(!1)},destroy:function(){m.forEach(this._value,function(c,b){dojox.lang.functional.forIn(c,
function(b){this.destroyRow(b)},this)},this);dojox.lang.functional.forIn(this._links,function(c,b){delete c[0].parent;delete c[1].parent;c[0].destroy(!1);c[1].destroy(!1)},this);dojox.lang.functional.forIn(this._panes,function(c,b){c.destroy(!1)},this);this.newRuleLink.destroy(!1);delete this.newRuleLink;this.inherited(arguments)},_getValueAttr:function(){console.debug("_getValueAttr");return this.value},_setValueAttr:function(c,b,e){console.debug("_setValueAttr");this.value=c},_getRuleValueAttr:function(){console.debug("_getRuleValueAttr");
var c=this.generateValue();return null!=c&&null==c.errorCode?c:null},_setRuleValueAttr:function(c,b,e){console.debug("_setRuleValueAttr");this.initialData=c},renderRuleComponent:function(){var c=this.initialData,b=this.additionalFieldInfo,e=this.comboData;if(!(null==c||null==b)){this._fieldSelector=new dojox.widget.DialogSimple;var a,l;for(l in c.group){var d=c.group[l],f=this.createNewRuleSection(),p;for(p in d.group){var g=d.group[p],h=f.id;if("F"==g.type){var k=b.fields,q;for(q in k)if(k[q].id==
g.fieldId){a=k[q];a.value=g.value;a.btId=g.btId;a.operator=g.operator;break}}else if("V"==g.type){var k=b.variables,r;for(r in k)if(k[r].id==g.fieldId){a=k[r];a.value=g.value;a.btId=g.btId;a.operator=g.operator;break}}var k={id:a.id,btId:a.btId,prompt:a.prompt,value:a.value,operator:a.operator,conditionEnable:a.conditionEnable},s=a.qtId;if(null!=s&&(s=e[s],null!=s)){var t=a.qtDescription,u=a.qtValue,v=[];m.forEach(s,function(a){v.push({label:a["f"+t],value:a["f"+u]})},this);k.o=v}h=h.substring(0,
h.lastIndexOf("_"));h=h.substring(0,h.lastIndexOf("_"));dijit.byId(h).addItem(g.type,k,f.id,this.tabId,this.pageScopeId)}}c=this._fieldSelector;delete this._fieldSelector;c.destroyRecursive(!1)}},_isEmpty:function(c){if(!(void 0==c||null==c))for(var b in c)if(c.hasOwnProperty(b))return!1;return!0},generateValue:function(){var c=null;if(null!=this._value){var b=[],e;for(e in this._value)b.push(e);if(0<b.length)for(var c={group:[],operator:"OR",value:null,fieldId:null,btId:null,type:null,users:null},
a=0;a<b.length;a++){e=b[a];var f=[],d;for(d in this._value[e])f.push(d);if(0<f.length){var n={group:[],operator:"AND",value:null,fieldId:null,btId:null,type:null,users:null};c.group.push(n);for(var p=0;p<f.length;p++){var g=this._value[e][f[p]],h={group:null,operator:null,value:[],fieldId:null,btId:null,type:null,users:null},k=dijit.byId(g.o);h.operator=k.get("value");k=dijit.byId(g.v);h.value.push(k.get("value"));h.btId=this.businessTemplateId;h.type=g.t;h.fieldId=g.i;n.group.push(h);if(null==h.operator)return{errorCode:"4"};
if(""==m.string.trim(h.value[0]))return{errorCode:"5"}}}else return{errorCode:"3"}}else return{errorCode:"2"}}else return{errorCode:"1"};return c}})});
//@ sourceMappingURL=Rule.js.map