//>>built
require({cache:{"url:ec/fisa/widget/chart/templates/template.html":'\x3cdiv id\x3d"${id}_chartContainer" style\x3d"display: inline-block;"\x3e\n\t\x3ctable cellspacing\x3d"10" cellpadding\x3d"0" border\x3d"0"\x3e\n\t\t\x3ctr\x3e\n\t\t\t\x3ctd\x3e\x3cdiv id\x3d"${id}_chart" data-dojo-attach-point\x3d"_chartNode" class\x3d"dojoFisaChartDiv"\n\t\t\t\t\tstyle\x3d"width: 600px; height: 400px; float: left;"\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\t\x3ctd\x3e\x3cdiv id\x3d"${id}_legend" data-dojo-attach-point\x3d"_legendNode"\n\t\t\t\t\tstyle\x3d"float: left"\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\x3c/tr\x3e\n\t\x3c/table\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/chart/FisaChart","dojo/dom-construct dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_Templated dojox/charting/Chart dojox/charting/axis2d/Default dojox/charting/widget/Legend dojox/charting/action2d/Tooltip dojox/charting/action2d/Highlight ec/fisa/charting/themes/Dollar ec/fisa/charting/themes/Harmony dojox/charting/plot2d/Pie dojo/store/Observable ec/fisa/dwr/Store dojox/charting/plot2d/Markers dojo/text!ec/fisa/widget/chart/templates/template.html dojox/charting/action2d/Magnify ec/fisa/dwr/StoreSeries ec/fisa/controller/Utils ./_base".split(" "),
function(c,h,k,l,m,n,t,p,f,q,u,v,g,w,x,e,r,s){return k("ec.fisa.widget.chart.FisaChart",[l,m],{tabId:"",qtId:"",pagescopeId:"",chartDesign:"",chartStyle:"",chartType:"",qtForLabels:"",parentFisaTabId:"",parentFisaPageScopeId:"",parentBtId:"",parentFieldId:"",plotType:{},xAxis:{},yAxis:{},series:[],theme:null,chartInstance:null,dimensionColumn:null,measureColum:null,measurementColumns:[],availableThemes:{dollar:dojox.charting.themes.FisaDollar,harmony:dojox.charting.themes.FisaHarmony},templateString:r,
store:{},query:{},legend:null,_childChartNode:null,_childLegendNode:null,_processLabels:!1,labels:[],format:4,numericFormat:h.config.fisaNumericPattern,constructor:function(){},postCreate:function(){this.inherited(arguments)},startUp:function(){var a=this._initChartConfig();this.plotType=a.plotType;this.xAxis=a.xAxis;this.yAxis=a.yAxis;this.theme=a.theme;this._init()},_init:function(){this._childChartNode=c.create("div",{style:{width:"600px",height:"400px","float":"left"}},this._chartNode);var a=
new n(this._childChartNode);this.chartInstance=a;this._processTheme();a.addPlot("default",this.plotType);this._procesAxis(this.xAxis);this._procesAxis(this.yAxis);this._addSeries();this._addHighlight();this._addTooltip()},_addSeries:function(){if(this.plotType.type==g){this.store=new ec.fisa.dwr.Store("QtControllerDWR","viewData",this.tabId,this.qtId,[this.pagescopeId],null);var a=this,b=this.chartInstance,d=new ec.fisa.dwr.StoreSeries(this.store,{query:this.query,fisaUpdateLegend:this._addLegend,
fisaUpdateLegendScope:this,tabId:this.tabId,pageScopeId:this.pagescopeId,refreshAxisLabels:!1,measureColum:this.measureColum,dimensionColum:this.dimensionColumn},function(b){var d={};d.y=b[a.measureColum];d.text=b[a.dimensionColumn];var c=ec.fisa.format.utils.formatNumber(b[a.measureColum],a.numericFormat);d.tooltip=b[a.dimensionColumn]+" : "+c;d.legend=b[a.dimensionColumn]+" : "+c;return d});b.addSeries("Data",d)}else this.plotType.type==e&&(this.store=new ec.fisa.dwr.Store("QtControllerDWR","viewData",
this.tabId,this.qtId,[this.pagescopeId],null),b=this.chartInstance,a=this,d=new ec.fisa.dwr.StoreSeries(this.store,{query:this.query,fisaUpdateLegend:this._addLegend,fisaUpdateLegendScope:this,tabId:this.tabId,pageScopeId:this.pagescopeId,measureColum:this.measureColum,dimensionColum:this.dimensionColumn,refreshAxisLabels:!0},function(b){return b[a.measureColum]}),b.addSeries("Data",d))},_procesAxis:function(a){var b=this.chartInstance;a&&a.axisData?b.addAxis(a.axisName,a.axisData):a&&b.addAxis(a.axisName)},
_processTheme:function(){var a=this.chartInstance;this.theme&&a.setTheme(this.availableThemes[this.theme])},_addLegend:function(){this._childLegendNode=c.create("div",{style:{"float":"left"}},this._legendNode);this.legend=new p({chart:this.chartInstance,horizontal:!1},this._childLegendNode)},_addTooltip:function(){var a=this.chartInstance;if(this.plotType.type==e){var b={text:function(a){return a.run.source.labels[a.x].text+" : "+a.y}};new f(a,"default",b)}else new f(a,"default"),b={scale:1.05},new s(a,
"default",b)},_addHighlight:function(){new q(this.chartInstance,"default")},_initChartConfig:function(){var a={};"1"==this.chartType?this._pieChartConfig(a):"3"==this.chartType&&this._lineChartConfig(a);return a},_pieChartConfig:function(a){a.plotType={type:g,radius:130,startAngle:-10,labelOffset:-20,labelStyle:"columns",htmlLabels:!0,font:"normal bold 7pt Tahoma"};a.theme=this._getTheme(this.chartStyle);this._processLabels=!1},_lineChartConfig:function(a){var b=this;a.plotType={type:e,font:"normal normal 8pt Tahoma"};
a.xAxis={axisName:"x",axisData:{fixLower:"major",fixUpper:"major",natural:!0,majorTickStep:5,labelFunc:function(a){var c=" ";if(a=b.labels[a])c=a.text;return c},maxLabelSize:45,trailingSymbol:"\u2026",rotation:15}};a.yAxis={axisName:"y",axisData:{vertical:!0,fixLower:"major",fixUpper:"major",includeZero:!0}};a.theme=this._getTheme(this.chartStyle);this._processLabels=!0},_getTheme:function(a){return 1==a?"dollar":"harmony"},setQuery:function(a){this.query=a;this.chartInstance.destroy();this.legend.destroy(!1);
c.destroy(this._childChartNode);this._init()},setInitialQuery:function(a){this.query=a}})});
//@ sourceMappingURL=FisaChart.js.map