//>>built
require({cache:{"url:ec/fisa/widget/templates/DateTextBox.html":'\x3cdiv\x3e\n\t\x3cdiv dojoType\x3d"dijit.form.DateTextBox" baseClass\x3d"${dateTextboxBaseClass}" data-dojo-attach-point\x3d"_componentNode" openOnClick\x3d"false" ${_readOnlyExp} tabIndex\x3d"${_tabIndex}"\x3e\x3c/div\x3e\n\x3c/div\x3e',"url:ec/fisa/widget/DateTextBox.conf":"{\n\tfisaClassic:{\n\t\ttextCharWidth:9,\n\t\tdefaultVisualSize:20\n\t},\n\tfisaDesert:{\n\t\ttextCharWidth:9,\n\t\tdefaultVisualSize:20\n\t}\n\n}"}});
define("ec/fisa/widget/DateTextBox","dijit/form/DateTextBox dojo/_base/declare dojo/date dojo/number dojo/_base/lang ec/fisa/format/Utils ec/fisa/widget/Utils dojo/date/locale dijit/_Widget dijit/_Templated dojo/text!ec/fisa/widget/DateTextBox.conf dojo/text!ec/fisa/widget/templates/DateTextBox.html ec/fisa/controller/Utils ./_base".split(" "),function(q,f,e,g,h,r,s,k,l,m,n,p){dojo.config.fisaDateExp=/[0-9\-]+/g;dojo.config.fisaDateTypeExp=/[dmyDMY]/g;dojo.config.fisaDateFullExp=/[0-9\-]+[dmyDMY]/g;
return f("ec.fisa.widget.DateTextBox",[l,m],{fisaFormat:0,fisaFormatPattern:dojo.config.fisaShortDatePattern,minDate:"",maxDate:"",widgetsInTemplate:!0,readOnly:!1,_readOnlyExp:"",_destroyOnRemove:!0,templateString:p,_componentNode:null,dateTextboxBaseClass:"",inputInvalidLabel:"",widgetVisualConfig:dojo.fromJson(n),visualSize:-1,parentEditableGrid:!1,entityMrId:null,gridRealRowIndex:null,tabIndexField:null,_tabIndex:0,fieldId:null,gridId:null,_destroyOnRemove:!0,postMixInProperties:function(){this.inherited(arguments);
!0===this.readOnly&&(this._readOnlyExp="disabled\x3d'disabled'");this.dateTextboxBaseClass=this.baseClass;this.baseClass="";null!=this.tabIndexField&&(this._tabIndex=this.tabIndexField)},destroy:function(){ec.fisa.widget.utils.destroyMultiregisterWidget(this);this.inherited(arguments)},buildRendering:function(){this.inherited(arguments);this._componentNode.constraints||(this._componentNode.constraints={});this._componentNode.constraints.datePattern=this.fisaFormatPattern;this._componentNode.constraints.selector=
"date";this.minDate&&""!=this.minDate&&(this._componentNode.constraints.min=this.minDate);this.maxDate&&""!=this.maxDate&&(this._componentNode.constraints.max=this.maxDate);this._componentNode._refreshState=this._refreshState;this._componentNode._fisaAddDate=this._fisaAddDate;this._componentNode._resetComponentErrorStatus=this._resetComponentErrorStatus;var a=this["fisa-tab-id"],b=this["fisa-page-scope-id"];this._componentNode.btId=this["bt-id"];this._componentNode.notifyComboId=this["notify-combo-id"];
this._componentNode.fieldId=this["field-id"];this._componentNode.fisaTabId=a;this._componentNode.fisaPageScopeId=b;this._componentNode.validator=this.validator;this._componentNode._validatorInterno=this._validatorInterno;this._componentNode._internalOnChange=this._internalOnChange;this._componentNode._routineEvent=this._routineEvent;this._componentNode.handleErrorMsg=this.handleErrorMsg;this._componentNode.inputInvalidLabel=this.inputInvalidLabel;this._componentNode._notificationEvent=this._notificationEvent;
this._componentNode.isARoutineField=!1;this._componentNode.hasError=!1;this._componentNode.parentEditableGrid=this.parentEditableGrid;this._componentNode.gridRealRowIndex=this.gridRealRowIndex;this._componentNode.entityMrId=this.entityMrId;a=null;a=0<=this.visualSize?this.visualSize:this.widgetVisualConfig[dojo.config.fisaTheme].defaultVisualSize;a++;a*=this.widgetVisualConfig[dojo.config.fisaTheme].textCharWidth;!0==this.parentEditableGrid&&null!=this.tdParentWidth&&a<this.tdParentWidth&&(a=this.tdParentWidth-
10);this._componentNode.domNode.style.width=a+"px"},_setValueAttr:function(a,b,c){var d=null;if(null!=a)"string"!=typeof a?this._componentNode.set("value",a,b,c):(d=""!=a?ec.fisa.format.utils.parseLongDate(a):null,this._componentNode.setByCode=!0,this._componentNode.set("value",d,b,c));else if(null!=this._componentNode.get("value")&&(this._componentNode.value=null,this._componentNode.onChange&&h.isFunction(this._componentNode.onChange)))this._componentNode.onChange()},_getValueAttr:function(){var a=
this._componentNode.get("value");null!=a&&(a=ec.fisa.format.utils.formatLongDate(a));return a},_refreshState:function(){this.inherited(arguments)},_fisaAddDate:function(a){var b=new String(a),b=b.replace(dojo.config.fisaDateTypeExp,"");a=new String(a);a=a.toLowerCase();a=a.replace(dojo.config.fisaDateExp,"");var c="day";"m"==a?c="month":"y"==a&&(c="year");return e.add(new Date,c,g.parse(b))},_setEnabledAttr:function(a){null!=a&&(a?ec.fisa.widget.utils.enableWidget(this._componentNode):ec.fisa.widget.utils.disableWidget(this._componentNode))},
_getEnabledAttr:function(){return ec.fisa.widget.utils.isEnabled(this._componentNode)},displayMessage:function(a){},hasErrorCmp:function(){return this._componentNode.hasError},attachOnChangeEvent:function(a,b,c,d){this._componentNode.isARoutineField=!0;this._componentNode.routineBtId=b;this._componentNode.routineFieldId=c;this._componentNode.routineActionMode=d},_internalOnChange:function(){if(null!=this.notifyComboId&&void 0!=this.notifyComboId||!0==this.isARoutineField){var a=ec.fisa.controller.utils.getPageController(this.fisaTabId,
this.fisaPageScopeId);void 0!=a&&null!=a&&a.handleOnChangeComponent(this.fieldId,this.btId,this.routineActionMode,this.notifyComboId,this.isARoutineField,null,this.parentEditableGrid,this.entityMrId,this.gridRealRowIndex)}},validator:function(a,b){var c=this._validatorInterno(a,b);this.hasError=!c;!1===this.focused&&!0==c&&!0==this.tobeChanged&&(!0!=this.setByCode||void 0==this.setByCode)&&this._internalOnChange();this.setByCode=!1;return!0},_validatorInterno:function(a,b){this.tobeChanged=!0;if(!0!==
this.focused){var c=ec.fisa.controller.utils.getPageController(this.fisaTabId,this.fisaPageScopeId),d=null;if(null==a||""==a)return this._resetComponentErrorStatus(),this._oldValue===a&&(this.tobeChanged=!1),this._oldValue=a,!0;void 0!=c.messagesPanelId&&null!=c.messagesPanelId&&dijit.byId(c.messagesPanelId).clearAllMessages();if("string"==typeof a){if(0==a.search(dojo.config.fisaDateFullExp))return this._lastValueReported=d=this._fisaAddDate(a),this._setValueAttr(d),this.tobeChanged=!1,!0;d=k.parse(a,
{datePattern:this.constraints.datePattern,selector:this.constraints.selector,locale:dojo.config.fisaCurrentLocale})}if(!0==this._isInvalidDate(d))return this.handleErrorMsg(),!1;if(this._oldValue===a)return this.tobeChanged=!1,!0;this._oldValue=a;if(this.dropDown&&null!=this.dropDown.value){if(!e.compare(this.dropDown.value,d,this._selector))return!0;this.dropDown.destroyRecursive();delete this.dropDown}}return!0},handleErrorMsg:function(){var a={summary:this.inputInvalidLabel+" "+this.displayedValue,
detail:"",level:{level:4E4}},b=ec.fisa.controller.utils.getPageController(this.fisaTabId,this.fisaPageScopeId);b.updateMsgsPanel([a]);b instanceof ec.fisa.controller.custom.BtController&&this.getParent().set("value","",!1)},_resetComponentErrorStatus:function(){this.hasError=!1}})});
//@ sourceMappingURL=DateTextBox.js.map