//>>built
require({cache:{"url:ec/fisa/widget/templates/EnhancedDateTextBox.html":'\x3cdiv\x3e\n\t\x3cdiv dojoType\x3d"dijit.form.DateTextBox" baseClass\x3d"${dateTextboxBaseClass}" data-dojo-attach-point\x3d"_componentNode" openOnClick\x3d"false" tabIndex\x3d"${_tabIndex}"\x3e\x3c/div\x3e\n\x3c/div\x3e',"url:ec/fisa/widget/DateTextBox.conf":"{\n\tfisaClassic:{\n\t\ttextCharWidth:9,\n\t\tdefaultVisualSize:20\n\t},\n\tfisaDesert:{\n\t\ttextCharWidth:9,\n\t\tdefaultVisualSize:20\n\t}\n\n}"}});
define("ec/fisa/widget/EnhancedDateTextBox","dijit/_Widget dijit/_Templated dijit/form/DateTextBox dojo/_base/declare ec/fisa/format/Utils ec/fisa/widget/Utils ec/fisa/widget/EnhancedCalendar dojo/date/locale dojo/_base/lang dijit/_HasDropDown dojo/date dojo/number dojo/text!ec/fisa/widget/DateTextBox.conf dojo/text!ec/fisa/widget/templates/EnhancedDateTextBox.html ./_base ./DateTextBox".split(" "),function(g,h,u,m,v,w,n,p,e,q,l,r,s,t){return m("ec.fisa.widget.EnhancedDateTextBox",[g,h],{minDate:"",
maxDate:"",_destroyOnRemove:!0,_oldValue:null,datesToDisable:[],visualSize:-1,tabIndexField:null,_tabIndex:0,daysOfWeekDisable:[],fisaFormat:1,fisaFormatPattern:dojo.config.fisaShortDatePattern,valueInitialCalendar:null,inputInvalidLabel:"",gridId:null,widgetVisualConfig:dojo.fromJson(s),skipValidation:!1,widgetsInTemplate:!0,templateString:t,_componentNode:null,dateTextboxBaseClass:"",parentEditableGrid:!1,gridRealRowIndex:null,entityMrId:null,fieldId:null,startup:function(){this.inherited(arguments)},
postMixInProperties:function(){this.inherited(arguments);this.dateTextboxBaseClass=this.baseClass;this.baseClass="";null!=this.tabIndexField&&(this._tabIndex=this.tabIndexField)},destroy:function(){ec.fisa.widget.utils.destroyMultiregisterWidget(this);this.inherited(arguments)},buildRendering:function(){this.inherited(arguments);this._componentNode.constraints||(this._componentNode.constraints={});delete this._componentNode.constraints.min;delete this._componentNode.constraints.max;this._componentNode.constraints.datePattern||
(this._componentNode.constraints.datePattern=this.fisaFormatPattern);this._componentNode.constraints.selector||(this._componentNode.constraints.selector="date");this.minDate&&""!=this.minDate&&(this._componentNode.constraints.minDate=this.minDate);this.maxDate&&""!=this.maxDate&&(this._componentNode.constraints.maxDate=this.maxDate);this.datesToDisable&&(this._componentNode.constraints.datesToDisable=this.datesToDisable);this.daysOfWeekDisable&&(this._componentNode.constraints.daysOfWeekDisable=this.daysOfWeekDisable);
var a=this["fisa-tab-id"],c=this["fisa-page-scope-id"],b=this["bt-id"],d=this["field-id"];this._componentNode.fisaTabId=a;this._componentNode.fisaPageScopeId=c;this._componentNode.btId=b;this._componentNode.fieldId=d;this._componentNode.notifyComboId=this["notify-combo-id"];this._componentNode.btController=ec.fisa.controller.utils.getPageController(a,c);this._componentNode.popupClass=n;this._componentNode._oldValue=this._oldValue;this._componentNode.valueInitialCalendar=this.valueInitialCalendar;
this._componentNode.inputInvalidLabel=this.inputInvalidLabel;this._componentNode.skipValidation=this.skipValidation;this._componentNode.validator=this.validator;this._componentNode._validatorInterno=this._validatorInterno;this._componentNode._routineEvent=this._routineEvent;this._componentNode._internalOnChange=this._internalOnChange;this._componentNode._notificationEvent=this._notificationEvent;this._componentNode._fisaAddDate=this._fisaAddDate;this._componentNode._handleValidatorAction=this._handleValidatorAction;
this._componentNode.handleErrorMsg=this.handleErrorMsg;this._componentNode.openDropDown=this.openDropDown;this._componentNode._handleDropDownAction=this._handleDropDownAction;this._componentNode._resetComponentErrorStatus=this._resetComponentErrorStatus;this._componentNode.isARoutineField=!1;this._componentNode.parentEditableGrid=this.parentEditableGrid;this._componentNode.entityMrId=this.entityMrId;this._componentNode.gridRealRowIndex=this.gridRealRowIndex;a=null;a=0<=this.visualSize?this.visualSize:
this.widgetVisualConfig[dojo.config.fisaTheme].defaultVisualSize;a*=this.widgetVisualConfig[dojo.config.fisaTheme].textCharWidth;!0==this.parentEditableGrid&&null!=this.tdParentWidth&&a<this.tdParentWidth&&(a=this.tdParentWidth-10);this._componentNode.domNode.style.width=a+"px"},_fisaAddDate:function(a){var c=new String(a),c=c.replace(dojo.config.fisaDateTypeExp,"");a=new String(a);a=a.toLowerCase();a=a.replace(dojo.config.fisaDateExp,"");var b="day";"m"==a?b="month":"y"==a&&(b="year");return l.add(new Date,
b,r.parse(c))},attachOnChangeEvent:function(a,c,b,d){this._componentNode.isARoutineField=!0;this._componentNode.routineBtId=c;this._componentNode.routineFieldId=b;this._componentNode.routineActionMode=d},_internalOnChange:function(){if(null!=this.notifyComboId&&void 0!=this.notifyComboId||!0==this.isARoutineField){var a=ec.fisa.controller.utils.getPageController(this.fisaTabId,this.fisaPageScopeId);void 0!=a&&null!=a&&a.handleOnChangeComponent(this.fieldId,this.btId,this.routineActionMode,this.notifyComboId,
this.isARoutineField,null,this.parentEditableGrid,this.entityMrId,this.gridRealRowIndex)}},validator:function(a,c){var b=this._validatorInterno(a,c);this.hasError=!b;!1===this.focused&&(!0==b&&!0==this.tobeChanged)&&((!0!=this.setByCode||void 0==this.setByCode)&&this._internalOnChange(),this.setByCode=!1);return b},_validatorInterno:function(a,c){this.tobeChanged=!0;if(!0===this.focused)return!0;if(!0==this.skipValidation)return this.skipValidation=!1,!0;void 0!=this.btController.messagesPanelId&&
null!=this.btController.messagesPanelId&&dijit.byId(this.btController.messagesPanelId).clearAllMessages();var b=null;if(null==a||""==a)return this._resetComponentErrorStatus(),this._oldValue===a&&(this.tobeChanged=!1),this._oldValue=a,!0;if("string"==typeof a){if(0==a.search(dojo.config.fisaDateFullExp))return this._lastValueReported=b=this._fisaAddDate(a),this._setValueAttr(b),this.tobeChanged=!1,!0;b=p.parse(a,{datePattern:this.constraints.datePattern,selector:this.constraints.selector,locale:"en"})}if(!0==
this._isInvalidDate(b))return this.handleErrorMsg(),!1;if(this._oldValue===a)return this.tobeChanged=!1,!0;this._oldValue=a;if(this.dropDown&&null!=this.dropDown.value){if(!l.compare(this.dropDown.value,b,this._selector))return!0;this.dropDown.destroyRecursive();delete this.dropDown}var d=this.btId,f=this.fieldId,e=this.fisaTabId,g=this.fisaPageScopeId,k={callbackScope:this};k.errorHandler=dojo.hitch(this.btController,this.btController.errorHandler);k.callback=this._handleValidatorAction;var h=this.btController.model.toPlainObject();
EventActionDWR.verifyDateFieldTextProperty(e,g,d,f,b,h,k);this.tobeChanged=!1;return!0},handleErrorMsg:function(){this.btController.updateMsgsPanel([{summary:this.inputInvalidLabel+" "+this.displayedValue,detail:"",level:{level:4E4}}]);this.skipValidation=!0;this._oldValue="";this.set("value",null)},_handleValidatorAction:function(a){var c=!0;null!=a&&null!=a.calIsValidValue?(c=a.calIsValidValue,!1===c?this.handleErrorMsg():((!0!=this.setByCode||void 0==this.setByCode)&&this._internalOnChange(),this.setByCode=
!1)):"enhanceDateNoProperty"==a.wAxn&&((!0!=this.setByCode||void 0==this.setByCode)&&this._internalOnChange(),this.setByCode=!1);return c},openDropDown:function(a){this.disabled=!0;this.dropDown&&this.dropDown.destroy();a=this.btId;var c=this.fieldId,b=this.fisaTabId,d=this.fisaPageScopeId,f={callbackScope:this};f.errorHandler=dojo.hitch(this.btController,this.btController.errorHandler);f.callback=this._handleDropDownAction;var e=this.btController.model.toPlainObject();EventActionDWR.verifyDateFieldProperty(b,
d,a,c,e,f)},_setValueAttr:function(a,c,b){var d=null;if(null!=a)"string"!=typeof a?this._componentNode.set("value",a,c,b):(d=""!=a?ec.fisa.format.utils.parseLongDate(a):null,this._componentNode.setByCode=!0,this._componentNode.set("value",d,c,b));else if(null!=this._componentNode.get("value")&&(this._componentNode.value=null,this._componentNode.onChange&&e.isFunction(this._componentNode.onChange)))this._componentNode.onChange()},_getValueAttr:function(){var a=this._componentNode.get("value");null!=
a&&(a=ec.fisa.format.utils.formatLongDate(a));return a},_handleDropDownAction:function(a){this.constraints.minDate=null;this.constraints.maxDate=null;this.constraints.datesToDisable=null;this.constraints.daysOfWeekDisable=null;if("enhanceDatePropertyEvaluate"==a.wAxn){var c=a.enhancedCalVal;this.constraints.minDate=c.minDate;this.constraints.maxDate=c.maxDate;this.constraints.datesToDisable=dojo.fromJson(c.datesToDisable);this.constraints.daysOfWeekDisable=c.daysOfWeekDisable.split(",")}var c=e.isString(this.popupClass)?
e.getObject(this.popupClass,!1):this.popupClass,b=this,d=this.get("value");this.valueInitialCalendar=this.constraints.minDate?ec.fisa.format.utils.parseLongDate(this.constraints.minDate.concat(" 00:00:00.0")):this.dropDownDefaultValue;this.dropDown=new c({onChange:function(a){b.set("value",a,!0)},id:this.id+"_popup",dir:b.dir,lang:b.lang,value:d,currentFocus:!this._isInvalidDate(d)?d:this.valueInitialCalendar,constraints:b.constraints,filterString:b.filterString,datePackage:b.datePackage,constraints:b.constraints});
q.prototype.openDropDown.apply(this,arguments);this.disabled=!1},_setEnabledAttr:function(a){null!=a&&(a?ec.fisa.widget.utils.enableWidget(this._componentNode):ec.fisa.widget.utils.disableWidget(this._componentNode))},_getEnabledAttr:function(){return ec.fisa.widget.utils.isEnabled(this._componentNode)},_resetComponentErrorStatus:function(){this.hasError=!1}})});
//@ sourceMappingURL=EnhancedDateTextBox.js.map