//>>built
require({cache:{"url:ec/fisa/widget/templates/NotificationBTSelection.html":'\x3cdiv  data-dojo-attach-point\x3d"_tcn"\x3e\x3c/div\x3e\n\t\t\t',"url:ec/fisa/widget/TextBox.conf":"{\n\tfisaClassic:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20\n\t},\n\tfisaDesert:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20\n\t}\n\n}"}});
define("ec/fisa/widget/NotificationBTSelection","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_Templated dojo/text!./templates/NotificationBTSelection.html dojo/regexp dijit/form/Button dijit/form/TextBox dijit/form/ValidationTextBox dojox/lang/functional/object dojo/dom-style dojo/dom-attr dojo/dom dojo/dom-construct dijit/dijit dojo/on dijit/focus dojo/text!ec/fisa/widget/TextBox.conf ec/fisa/widget/Utils ec/fisa/format/Utils dojo/string dijit/form/Select ./_base".split(" "),function(e,
l,m,n,p,r,s,t,u,v,f,w,x,c,h,y,z,q){return l("ec.fisa.widget.NotificationBTSelection",[m,n],{tapdFieldLenght:0,notificationMaxLength:0,requestedAction:"",tabId:"",pageScopeId:"",styleClass:"notificationReceiverSelection",widgetsInTemplate:!0,readOnly:!1,_disabledExp:"",_connections:null,_destroyOnRemove:!0,parentEditableGrid:!1,gridId:"",gridSelectedRowIndex:null,parentType:"",visualSize:20,templateString:p,notificationMeansList:null,labelDest:"",labelNewBeneficiario:"",invalidValue:"",emailRegex:null,
numberRegex:null,textBoxConfig:e.fromJson(q),notificationDataVO:null,btController:null,arrayIdTextBox:[],ta:null,constructor:function(a,b){try{this.emailRegex="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",this.numberRegex="^[0-9]+$",this.tapdFieldLenght=a.tapdFieldLenght||0,this.requestedAction=a.requestedAction||"",this.ref=a.ref,this._connections=[],this.arrayIdTextBox=[]}catch(d){this.logger("No se pudo ejecutar el constructor"),this.logger(d)}},postMixInProperties:function(){!0==
this.readOnly&&(this._disabledExp="disabled\x3d'disabled'")},buildRendering:function(){this.inherited(arguments);this._init()},destroy:function(){this.inherited(arguments)},logger:function(a){},_createNotification:function(a,b,d){var k=null;if(null==b)a=c.create("table",{"class":"fisaComponentGrid"},this._tcn),k=c.create("tbody",{},a);else{d=c.create("tr",{"class":1==d?"evenFieldBt":"oddFieldBt"},b);b=c.create("td",{"class":"fisaComponentGridLeftCell"},d);b=c.create("div",{},b);d=c.create("td",{"class":"fisaComponentGridRightCell"},
d);d=c.create("div",{},d);var g=null,g=0<=this.visualSize?this.visualSize:this.textBoxConfig[e.config.fisaTheme].defaultVisualSize,g=this.textBoxConfig[e.config.fisaTheme].textCharWidth*g,f={value:a.currentValue,maxLength:this.notificationMaxLength,size:this.visualSize,title:a.contactMediaShortName+" "+this.titlelabeltext};c.create("label",{"class":"fisaLabel",innerHTML:a.contactMediaShortName,title:a.contactMediaShortName+" "+this.titlelabeltext},b);b=new h.form.ValidationTextBox(f,d);b.domNode.style.width=
g+"px";b.set("required",!1);b.set("trim",!0);b.mediaDataVO=a;"SMS"==a.contactMediaId?b.set("regExp",this.numberRegex):"MAIL"==a.contactMediaId&&b.set("regExp",this.emailRegex);b.tabId=this.tabId;b.pageScopeId=this.pageScopeId;b.invalidValue=this.invalidValue;b.connect(b,"onChange",function(a){this.mediaDataVO.currentValue=a;a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);null!=a&&!0==this.dontClearPanelMsg&&(ec.fisa.format.utils.removeFieldError(this.id),this.dontClearPanelMsg=
!1);this.isValid()||(null!=a&&ec.fisa.format.utils.addToFieldError(this.id,this.invalidValue,{level:4E4},null),this.set("value","",!1),this._lastValueReported="",this.dontClearPanelMsg=!0,this.mediaDataVO.currentValue="")});this.arrayIdTextBox.push(b.id)}return k},_init:function(){this.notificationMaxLength=this.tapdFieldLenght},_setVisible:function(a){f.set(a,"display","block")},_setNotVisible:function(a){f.set(a,"display","none")},_getValueAttr:function(){var a=[];e.forEach(this.arrayIdTextBox,
function(b){b=h.byId(b).mediaDataVO;a.push(b)});return a},_setValueAttr:function(a,b,d){this.notificationDataVO=a;if(null!=a.listContactMediaDataVOs&&void 0!=a.listContactMediaDataVOs){null==this.ta||void 0==this.ta?this.ta=this._createNotification(null,null,null):(e.empty(this.ta),this.arrayIdTextBox.length=0);var c=1;e.forEach(a.listContactMediaDataVOs,e.hitch(this,function(a){this._createNotification(a,this.ta,c);a=!0;1==c&&(c=0,a=!1);!0==a&&0==c&&(c=1)}))}},updateRowHeight:function(){null!=this.gridSelectedRowIndex&&
h.byId(this.gridId).scroller.rowHeightChanged(this.gridSelectedRowIndex,!0)}})});
//@ sourceMappingURL=NotificationBTSelection.js.map