//>>built
require({cache:{"url:ec/fisa/widget/templates/NumberTextBox.html":'\x3cdiv\x3e\n\t\x3cdiv dojoType\x3d"dijit.form.NumberTextBox" baseClass\x3d"${textboxBaseClass}" data-dojo-attach-point\x3d"_componentNode" ${_readOnlyExp} ${_maxLengthExp} tabIndex\x3d"${_tabIndex}"\x3e\x3c/div\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/NumberTextBox","dojo/_base/declare dojo/number dijit/form/NumberTextBox ec/fisa/widget/Utils dijit/_Widget dijit/_Templated dojo/regexp dojo/_base/lang dojo/text!./templates/NumberTextBox.html dojo/dom-attr dojo/has dojo/_base/sniff dojo/string".split(" "),function(d,f,p,g,h,k,q,r,l,m,n){dojo.config.fisaDecimalExp=/[-\+\d\.]/g;dojo.config.fisaDecimalTypeExp=/[mMtT]/g;return d("ec.fisa.widget.NumberTextBox",[h,k],{_fStarted:!0,baseClass:"",widgetsInTemplate:!0,readOnly:!1,maxLength:-1,
maskall:!1,password:!1,_readOnlyExp:"",_maxLengthExp:"",_type:"",factor:1,tabId:"",_tabIndex:0,_destroyOnRemove:!0,pageScopeId:"",btId:"",fieldId:"",decimalSeparator:dojo.config.decimalSeparator,groupSeparator:dojo.config.groupSeparator,currencyFormat:dojo.config.fisaDefaultCurrency,numericFormat:dojo.config.fisaNumericPattern,templateString:l,_componentNode:null,textboxBaseClass:"",noValidInputLabel:"Valor fuera de rango ",postMixInProperties:function(){!0===this.readOnly&&(this._readOnlyExp="disabled\x3d'disabled'");
0<=this.maxLength&&(this._maxLengthExp="maxLength\x3d"+this.maxLength);if(this.maskall||this.password)this._type="password";null!=this.tabindex&&(this._tabIndex=this.tabindex)},buildRendering:function(){this.inherited(arguments);this._componentNode.textbox.style.textAlign="right";g.setAcceptOnlyNumeric(this._componentNode,!1);this._componentNode._setBlurValue=this._setBlurValue;this._componentNode.format=this.format;this._componentNode.parse=this.parse;this._componentNode.parser=this.parser;this._componentNode._getStringValueInEN_USLocale=
this._getStringValueInEN_USLocale;this._componentNode._fisaConvertAmount=this._fisaConvertAmount;this._componentNode._cleanSeparators=this._cleanSeparators;this._componentNode._clearErrorMsg=this._clearErrorMsg;this._componentNode.handleErrorMsg=this.handleErrorMsg;this._componentNode.decimalSeparator=this.decimalSeparator;this._componentNode.groupSeparator=this.groupSeparator;this._componentNode._refreshState=this._refreshState;this._componentNode._onFocus=this._onFocus;this._componentNode.validate=
this.validate;this._componentNode.isInRange=this.isInRange;this._componentNode._numberParser=this._numberParser;this._componentNode.numericFormat=this.numericFormat;this._componentNode.tabId=this.tabId;this._componentNode.pageScopeId=this.pageScopeId;this._componentNode.btId=this.btId;this._componentNode.fieldId=this.fieldId;this._componentNode.noValidInputLabel=this.noValidInputLabel;this._componentNode.connect(this._componentNode,"onChange",dojo.hitch(this,this._onChangeInterno))},startup:function(){this.inherited(arguments);
dojo.removeAttr(this.domNode,"tabindex");n("ie")&&(this._componentNode.textbox.tabIndex=parseInt(this.tabIndex),m.set(this._componentNode.textbox,"tabindex",parseInt(this.tabIndex)))},format:function(a,b){var c=b.pattern;void 0==c&&(c=this.numericFormat);return ec.fisa.format.utils.formatNumber(a,c)},_onChangeInterno:function(a){if(void 0!=this.onChange)this.onChange(a)},parse:function(a,b){a&&0<a.length&&(a=dojo.string.trim(a));return void 0===a||null==a||""==a?NaN:v=this.parser(a)},parser:function(a){a=
this._cleanSeparators(a);return this._numberParser(a)},_setBlurValue:function(){if(!1==this.focused){this._clearErrorMsg();this.factor=1;var a=this.textbox.value,b=null;null!=a&&""!=a&&(b="string"==typeof a?this._getStringValueInEN_USLocale(a):a);isNaN(b)||null==b?this.set("value",null):this.isInRange(b,this.factor)?this.set("value",this._numberParser(b,this.factor)):(this.set("value",null),this.handleErrorMsg(b))}else return!1},_refreshState:function(){},_getValueAttr:function(){var a=this._componentNode.get("value");
return isNaN(a)?"":""+a},_onFocus:function(){},validate:function(a){},_setValueAttr:function(a,b,c){c=null;null!=a&&""!=a&&(c=this._numberParser(a));this._componentNode.set("value",c,b);"boolean"===typeof b&&!b&&(this._componentNode._pendingOnChange=!1,this._componentNode._lastValueReported=c)},_getStringValueInEN_USLocale:function(a){var b=null;a=this._cleanSeparators(a);return b=-1!=a.search(dojo.config.fisaDecimalTypeExp)?this._fisaConvertAmount(a):a},_fisaConvertAmount:function(a){var b=new String(a),
b=b.replace(dojo.config.fisaDecimalTypeExp,"");a=new String(a);a=a.replace(dojo.config.fisaDecimalExp,"");a=a.toLowerCase();this.factor=1;"m"==a?this.factor=1E6:"t"==a&&(this.factor=1E3);return b},_cleanSeparators:function(a){a=a.replace(RegExp("\\"+this.groupSeparator,"g"),"");return a=a.replace(this.decimalSeparator,".")},_getConstraintsAttr:function(a){return this._componentNode.get("constraints")},_setConstraintsAttr:function(a){this._componentNode.set("constraints",a)},_setEnabledAttr:function(a){null!=
a&&(a?ec.fisa.widget.utils.enableWidget(this._componentNode):ec.fisa.widget.utils.disableWidget(this._componentNode))},_getEnabledAttr:function(){return ec.fisa.widget.utils.isEnabled(this._componentNode)},isInRange:function(a,b){var c=!0,e=this._numberParser(a,b),d=this.constraints.min;if(e>this.constraints.max||e<d)c=!1;return c},_numberParser:function(a,b){b||(b=1);return f.parse(a,{locale:"en"})*b},_clearErrorMsg:function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);
null!=a&&void 0!=a&&(a.model.clearAllMessages(),void 0!=a.messagesPanelId&&null!=a.messagesPanelId&&dijit.byId(a.messagesPanelId).clearAllMessages())},handleErrorMsg:function(a){a=this.noValidInputLabel+"["+this.constraints.max+", "+this.constraints.min+"] : "+a;a={fieldId:this.fieldId,fieldMsg:a,detail:"",summary:a,level:{level:4E4},origLevel:{level:4E4}};var b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);b instanceof ec.fisa.controller.custom.BtController&&(a.ftmId=this.btId);
b.updateMsgsPanel([a])}})});
//@ sourceMappingURL=NumberTextBox.js.map