//>>built
require({cache:{"url:ec/fisa/widget/templates/OutputTextComplement.html":'\x3cdiv\x3e\n\x3ctable border\x3d"0" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\n\t\x3ctbody\x3e\n\t\t\x3ctr\x3e\n\t\t\t\x3ctd valign\x3d"middle" \x3e\n\t\t\t\t\x3cdiv id\x3d"${id}_textBox" data-dojo-attach-point\x3d"_componentNode" style\x3d"word-wrap:break-word;" class\x3d"${styleClass}"\n\t\t\t\t\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\t\x3ctd\x3e\x26nbsp;\x3c/td\x3e\n\t\t\t\x3ctd\x3e\n\t\t\t\x3cdiv id\x3d"${id}_complement" data-dojo-attach-point\x3d"_complementNode"\n\t\t\t\tdojoType\x3d"ec.fisa.widget.OutputText"\n\t\t\t\tstyle\x3d"color: blue; white-space: nowrap;"\n\t\t\t\tbaseClass\x3d"${complementBaseClass}"\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\x3c/tr\x3e\n\t\x3c/tbody\x3e\n\x3c/table\x3e\n\x3c/div\x3e\n',
"url:ec/fisa/widget/TextBox.conf":"{\n\tfisaClassic:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20\n\t},\n\tfisaDesert:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20\n\t}\n\n}"}});
define("ec/fisa/widget/OutputTextComplement","dijit/_Widget dijit/_Templated dojo/_base/declare dojo/number dojo/keys dijit/form/TextBox ec/fisa/widget/Utils dojo/text!ec/fisa/widget/templates/OutputTextComplement.html dojo/text!ec/fisa/widget/TextBox.conf ec/fisa/widget/OutputText ./_base".split(" "),function(c,d,e,h,k,l,m,f,g){return e("ec.fisa.widget.OutputTextComplement",[c,d],{readOnly:!0,title:"",style:"",textboxBaseClass:"dijitTextBox",complementBaseClass:"fisaOutputTextComplement",hasCompl:!0,
widgetsInTemplate:!0,_complementNode:null,_componentNode:null,_cmpType:"dijit.form.TextBox",password:!1,value:"",format:0,numeric:!1,textBoxConfig:dojo.fromJson(g),tasasFormat:dojo.config.interestRateFormat,porcentajeFormat:dojo.config.percentageFormat,currencyFormat:dojo.config.fisaDefaultCurrency,numericFormat:dojo.config.fisaNumericPattern,templateString:f,styleClass:"",_destroyOnRemove:!0,postMixInProperties:function(){this.inherited(arguments);this.styleClass&&(this.complementBaseClass=this.styleClass)},
postCreate:function(){this.inherited(arguments);this._valueSetter(this.value)},buildRendering:function(){this.inherited(arguments);var a=null,a=0<=this.visualSize?this.visualSize:this.textBoxConfig[dojo.config.fisaTheme].defaultVisualSize;this._componentNode.style.width=this.textBoxConfig[dojo.config.fisaTheme].textCharWidth*a+"px";if(4==this.format||5==this.format||6==this.format||this.numeric)this._componentNode.style.textAlign="right"},destroy:function(){this.inherited(arguments)},_getRefCmplAttr:function(){return this._complementNode.get("ref")},
_setRefCmplAttr:function(a){this._complementNode.set("ref",a)},_setBindingAttr:function(a){this._componentNode.set("binding",a)},_getValueAttr:function(){return this._componentNode.innerHTML},_setValueAttr:function(a,b,c){this._valueSetter(a)},_valueSetter:function(a){!0==this.password&&(a=this._maskValue(a));this._componentNode.innerHTML=null==a||""==a?"":!0==this.password?a:1==this.format||2==this.format||3==this.format?this.formatDatebyFormatId(a,this.format):4==this.format?this.formatNumber(a,
{pattern:this.numericFormat}):5==this.format?this.formatNumber(a,{pattern:this.tasasFormat}):6==this.format?this.formatNumber(a,{pattern:this.porcentajeFormat}):a},formatNumber:function(a,b){return ec.fisa.format.utils.formatNumber(a,b.pattern)},formatDatebyFormatId:function(a,b){return ec.fisa.format.utils.formatDateByFormatId(a,b)},_maskValue:function(a){var b;null!=a&&""!=a&&(b=a.replace(/./g,"*"));return b},_getComplementAttr:function(){return this._complementNode.get("value")},_setComplementAttr:function(a,
b,c){this._complementNode.set("value",a)},_maskValue:function(a){var b="";null!=a&&""!=a&&(b=a.replace(/./g,"*"));return b}})});
//@ sourceMappingURL=OutputTextComplement.js.map