//>>built
define("ec/fisa/widget/PaymentDynamicGrid","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/connect dijit/_Widget dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ec/fisa/grid/EnhancedGrid dijit/form/CheckBox ec/fisa/widget/Link dijit/form/Select dijit/form/TextBox ec/fisa/widget/OutputTextComplement".split(" "),function(f,h,p,q,r,s,t,k,u,l,v,m,w){return h("ec.fisa.widget.PaymentDynamicGrid",[k],{selectButtonLabel:"Activar Env\u00edo",tabId:"",pageScopeId:"",parentFisaPageScopeId:"",
parentBtId:"",parentFieldId:"",parentWidgetId:"",onlyRead:!1,labelNumber:"",selectionMode:"none",_onSelectionUpdate:!1,fsv:null,labelProduct:"",labelFormat:"",labelFrecuency:"",selectWidth:"180px",readWidth:"12%",readWidthSummary:"20%",txtWidth:"105",montoId:"monto",montoIdAux:"monto_aux",montoReadId:"montoRead",chargeId:"charge",totalAmountId:"totalAmount",summaryId:"summary",summarySaveId:"summarySave",contractId:"contract",descId:"desc",disabledId:"disabledId",contractReadId:"contractReadId",descReadId:"descRead",
isSortable:!0,postMixInProperties:function(){this.inherited(arguments);this.autoHeight=!0;this.selectable="true";this.fisaEditableGrid=!0;var b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);b.skinParameters&&(this.readWidth=this.txtWidth=this.selectWidth="10%");var a=[];a.push({name:"id",field:"id",width:"auto",hidden:!0,sortable:this.isSortable});a.push({name:"Id Transacci\u00f3n",field:"transactionType",width:"auto",hidden:!0,sortable:this.isSortable,noresize:!0});a.push({name:b.initLabels.transactionName,
field:"transactionName",width:"10%",sortable:this.isSortable,noresize:!0,headerstyle:"text-align:left"});a.push({name:b.initLabels.companyName,field:"companyName",width:"1%",hidden:!0,sortable:this.isSortable,noresize:!0});a.push({name:b.initLabels.serviceName,field:"serviceName",width:"8%",sortable:this.isSortable,noresize:!0,headerstyle:"text-align:left"});a.push({name:b.initLabels.contract,field:"outAccount",width:"10%",sortable:this.isSortable,noresize:!0,headerstyle:"text-align:left"});a.push({name:b.initLabels.amount,
field:this.montoIdAux,width:this.selectWidth,widgetClass:ec.fisa.widget.NumberTextBox,sortable:!1,hidden:!1,noresize:!0,formatter:f.hitch(this,function(a,c,d){return!0===this.store.getValue(d.grid.getItem(c),this.disabledId)?this.formatterGridReadTextBox(a,c,d,b):this.formatterGridNumberTextBoxAux(a,c,d,b)}),headerstyle:"text-align:left"});a.push({name:b.initLabels.desc,field:this.descId,width:this.selectWidth,widgetClass:dijit.form.TextBox,sortable:this.isSortable,noresize:!0,formatter:f.hitch(this,
function(a,c,d){return this.formatterGridTextBox(a,c,d,b)}),headerstyle:"text-align:left"});a.push({name:b.initLabels.desc,field:this.descReadId,width:this.readWidth,hidden:!0,widgetClass:ec.fisa.widget.OutputTextComplement,sortable:this.isSortable,noresize:!0,formatter:f.hitch(this,function(a,c,d){return this.formatterGridReadTextBox(a,c,d,b)}),headerstyle:"text-align:left"});a.push({name:b.initLabels.amount,field:this.montoId,width:this.selectWidth,widgetClass:ec.fisa.widget.NumberTextBox,sortable:this.isSortable,
hidden:!0,noresize:!0,formatter:f.hitch(this,function(a,c,d){return this.formatterGridNumberTextBox(a,c,d,b)}),headerstyle:"text-align:right"});a.push({name:b.initLabels[this.chargeId],field:this.chargeId,width:this.readWidth,hidden:!0,widgetClass:ec.fisa.widget.OutputTextComplement,sortable:this.isSortable,noresize:!0,formatter:f.hitch(this,function(a,c,d){return this.formatterGridReadNumberTextBox(a,c,d,b)}),headerstyle:"text-align:right"});a.push({name:b.initLabels[this.totalAmountId],field:this.totalAmountId,
width:this.readWidth,hidden:!0,widgetClass:ec.fisa.widget.OutputTextComplement,sortable:this.isSortable,noresize:!0,formatter:f.hitch(this,function(a,c,d){return this.formatterGridReadNumberTextBox(a,c,d,b)}),headerstyle:"text-align:right"});a.push({name:b.initLabels[this.summaryId],field:this.summaryId,width:this.readWidthSummary,hidden:!1,widgetClass:ec.fisa.widget.OutputTextComplement,sortable:this.isSortable,noresize:!0,formatter:f.hitch(this,function(a,c,d){return this.formatterGridReadTextBox(a,
c,d,b)}),headerstyle:"text-align:left"});a.push({name:b.initLabels[this.summarySaveId],field:this.summarySaveId,width:this.readWidthSummary,hidden:!0,widgetClass:ec.fisa.widget.OutputTextComplement,sortable:this.isSortable,noresize:!0,formatter:f.hitch(this,function(a,c,d){return this.formatterGridReadTextBox(a,c,d,b)}),headerstyle:"text-align:left"});this.fisaTextBoxAcc=[];this.fisaTextBoxDesc=[];this.structure=[a];this.store=new ec.fisa.dwr.Store("MultiplePaymentsControllerDWR","viewDataTransactions",
this.tabId,this.pageScopeId,[],null)},startup:function(){this.inherited(arguments);ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).setTxMDinamicGridId(this.id)},formatterGridLink:function(b,a,e,c){b=b.split("-");b={checked:"true"===b[0],fval:b[1]};if(b.checked||e.fReadOnly)disabled=b.readOnly=!0;if(0<=a){var d=new l({label:c.labelsData.addUsersTo,title:c.labelsData.addUsersTo});d.set("enabled",this.fisaChecksValues[a]);d.onClick=c.openAdditionalUsersSelection;d.rowData=b;d.fisaRowItem=
e;d.field=e.field;d.parentBtId=c.parentBtId;d.tabId=c.tabId;d.pageScopeId=c.pageScopeId;d.urlToAdditionalUserPage=c.urlToAdditionalUserPage;d.breadCrumbId=c.breadcrumbId;e.grid.fisaLinks[a]=d.id;return d}},formatterGridNumberTextBox:function(b,a,e,c){e.sortable=this.isSortable;b=e.grid.getItem(a);void 0==c.listGridData[b]&&(c.listGridData[b]={});a=20;try{a=f.byId(e.id).offsetWidth/c.skinParameters.tbtextCharWidth-2}catch(d){console.log(d)}return new ec.fisa.widget.OutputTextComplement({format:"4",
value:c.listGridData[b][this.montoId],baseClass:"textboxBaseClass",complementBaseClass:"fisaOutputText",visualSize:a})},formatterGridNumberTextBoxAux:function(b,a,e,c){var d=e.grid.getItem(a);void 0==c.listGridData[d]&&(c.listGridData[d]={});var g=!1;b&&(g=b.disabledId);if(g){a=20;try{a=f.byId(e.id).offsetWidth/c.skinParameters.tbtextCharWidth-2}catch(n){console.log(n)}return new ec.fisa.widget.OutputTextComplement({format:"4",value:b,baseClass:"textboxBaseClass",complementBaseClass:"fisaOutputText",
visualSize:a})}b=new ec.fisa.widget.NumberTextBox({value:b,maxLength:8,baseClass:"dijit dijitReset dijitInline dijitLeft dijitTextBox dijitNumberTextBox"});b.grid={};b.grid.tabId=this.tabId;b.grid.pageScopeId=this.pageScopeId;b.rowGridItem=d;b.name=this.montoIdAux;b.idx=a;b.connect(b,"onChange",function(a){if(this!=window){var b=ec.fisa.controller.utils.getPageController(this.grid.tabId,this.grid.pageScopeId);b.listGridData[this.rowGridItem].id=d;b.listGridData[this.rowGridItem][this.name]=""!=a||
0>a?a:0}});return b},formatterGridTextBox:function(b,a,e,c){e.sortable=this.isSortable;var d=e.grid.getItem(a);void 0==c.listGridData[d]&&(c.listGridData[d]={});b=20;try{b=f.byId(e.id).offsetWidth-40}catch(g){console.log(g)}c=new m({value:c.listGridData[d][e.field],readOnly:c.inputDisabled,maxLength:30,style:"width: "+b+"px;",baseClass:"dijitTextBox"});c.grid={};c.grid.tabId=this.tabId;c.grid.pageScopeId=this.pageScopeId;c.rowGridItem=d;c.name=e.field;c.idx=a;c.connect(c,"onChange",function(a){if(this!=
window&&""!=a){var b=ec.fisa.controller.utils.getPageController(this.grid.tabId,this.grid.pageScopeId);b.listGridData[this.rowGridItem].id=d;b.listGridData[this.rowGridItem][this.name]=a}});return c},formatterGridReadNumberTextBox:function(b,a,e,c){e.sortable=this.isSortable;b=e.grid.getItem(a);void 0==c.listGridData[b]&&(c.listGridData[b]={});a=20;try{a=f.byId(e.id).offsetWidth/c.skinParameters.tbtextCharWidth-2}catch(d){console.log(d)}return new ec.fisa.widget.OutputTextComplement({format:"4",value:c.listGridData[b][e.field],
baseClass:"textboxBaseClass",complementBaseClass:"fisaOutputText",visualSize:a})},formatterGridReadTextBox:function(b,a,e,c){e.sortable=this.isSortable;a=e.grid.getItem(a);void 0==c.listGridData[a]&&(c.listGridData[a]={});null==c.listGridData[a][e.field]&&(c.listGridData[a][e.field]=b);return new ec.fisa.widget.OutputTextComplement({value:c.listGridData[a][e.field],baseClass:"textboxBaseClass",complementBaseClass:"fisaOutputText"})},canSort:function(){return!1}})});
//@ sourceMappingURL=PaymentDynamicGrid.js.map