//>>built
define("ec/fisa/widget/SANotificationGridProduct","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/connect dijit/_Widget dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ec/fisa/grid/EnhancedGrid dijit/form/CheckBox ec/fisa/widget/Link dijit/form/Select".split(" "),function(h,l,q,r,s,t,u,m,n,p,k){return l("ec.fisa.widget.SANotificationGridProduct",[m],{selectButtonLabel:"Activar Env\u00edo",tabId:"",pageScopeId:"",parentFisaPageScopeId:"",parentBtId:"",parentFieldId:"",parentWidgetId:"",
onlyRead:!1,labelNumber:"",selectionMode:"none",_onSelectionUpdate:!1,fsv:null,labelProduct:"",labelFormat:"",labelFrecuency:"",selectWidth:"180px",labelNotifyTo:"",postMixInProperties:function(){this.inherited(arguments);this.autoHeight=!0;var d=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);d.skinParameters&&(this.selectWidth=d.skinParameters.stextCharWidth*d.skinParameters.sdefaultVisualSize+"px");var e=[],f={name:this.selectButtonLabel,field:"slctd",width:"100px",styles:"text-align: center;",
widgetClass:dijit.form.CheckBox,formatter:function(a,c,b){a=a.split("-");void 0==b.grid.fisaChecksValues[c]&&(b.grid.fisaChecksValues[c]="true"===a[0],b.grid.fisaUserSelect[c]="true"===a[0]);a={checked:b.grid.fisaChecksValues[c],fval:a[1],fvalLine:a[2]};b.fReadOnly&&(a.readOnly=!0);a=new n(a);a.gridId=b.grid.id;b.grid.fisaChecks[c]=a.id;a.onChange=function(a){var b=dijit.byId(this.gridId),d=b.getItemIndex(this.fval),e=b.fisaSelectFormat[d],f=b.fisaSelectFrecuency[d],d=dijit.byId(b.fisaLinks[d]),e=
dijit.byId(e),f=dijit.byId(f);e.set("disabled",!a);f.set("disabled",!a);a||(e.set("value","-1"),f.set("value","-1"));d.set("enabled",a);b.fisaChecksValues[c]=a};return a}};this.onlyRead?f.fReadOnly=!0:this.fisaChecks=[];e.push(f);e.push({name:this.labelNumber,field:"cta",width:"auto"});e.push({name:this.labelProduct,field:"prd",width:"auto"});e.push({name:this.labelFormat,field:"format",width:this.selectWidth,styles:"text-align: center;",widgetClass:dijit.form.Select,formatter:h.hitch(this,function(a,
c,b){return this.formatterGridFormatCombo(a,c,b,d)})});e.push({name:this.labelFrecuency,field:"frecuency",width:this.selectWidth,styles:"text-align: center;",widgetClass:dijit.form.Select,formatter:h.hitch(this,function(a,c,b){return this.formatterGridFrecuencyCombo(a,c,b,d)})});e.push({name:this.labelNotifyTo,field:"slctd",width:"auto",styles:"text-align: center;",widgetClass:ec.fisa.widget.Link,formatter:h.hitch(this,function(a,c,b){return this.formatterGridLink(a,c,b,d)})});this.fisaLinks=[];this.fisaSelectFormat=
[];this.fisaSelectFrecuency=[];this.fisaChecksValues=[];this.fisaUserSelect=[];this.structure=[e];this.store=new ec.fisa.dwr.Store("StatementAccountControllerDWR","viewDataProds",this.tabId,this.pageScopeId,d.getSelectedProds(),null)},startup:function(){this.inherited(arguments);ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).setListProdDataGridId(this)},formatterGridLink:function(d,e,f,a){d=d.split("-");d={checked:"true"===d[0],fval:d[1]};if(d.checked||f.fReadOnly)d.readOnly=
!0;if(0<=e){var c=new p({label:a.labelsData.addUsersTo,title:a.labelsData.addUsersTo});c.set("enabled",this.fisaChecksValues[e]);c.onClick=a.openAdditionalUsersSelection;c.rowData=d;c.fisaRowItem=f;c.field=f.field;c.parentBtId=a.parentBtId;c.tabId=a.tabId;c.pageScopeId=a.pageScopeId;c.urlToAdditionalUserPage=a.urlToAdditionalUserPage;c.breadCrumbId=a.breadcrumbId;f.grid.fisaLinks[e]=c.id;return c}},formatterGridFormatCombo:function(d,e,f,a){var c=d.split("-");d=c[0];var b=c[1];if(0<=e){var g=a.selectedFormat[d],
c=!1;void 0===g&&(g="-1",c=!0);b=new k({baseClass:"dijit dijitReset dijitInline dijitLeft dijitDownArrowButton dijitSelectFixedWidth dijitValidationTextBoxFixedWidth dijitSelect dijitValidationTextBox",options:a.formatListData[b],value:g});b.set("disabled",c);b.gridId=f.grid.id;b.productId=d;b.tabId=a.tabId;b.pageScopeId=a.pageScopeId;b.onChange=function(a){ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).selectedFormat[this.productId]=a};f.grid.fisaSelectFormat[e]=b.id;return b}},
formatterGridFrecuencyCombo:function(d,e,f,a){var c=d.split("-");d=c[0];var b=c[1];if(0<=e){var g=a.selectedFrecuency[d],c=!1;void 0===g&&(g="-1",c=!0);b=new k({baseClass:"dijit dijitReset dijitInline dijitLeft dijitDownArrowButton dijitSelectFixedWidth dijitValidationTextBoxFixedWidth dijitSelect dijitValidationTextBox",options:a.frecuencyListData[b],value:g});b.set("disabled",c);b.gridId=f.grid.id;b.productId=d;b.tabId=a.tabId;b.pageScopeId=a.pageScopeId;b.onChange=function(a){dijit.byId(this.gridId);
ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).selectedFrecuency[this.productId]=a};f.grid.fisaSelectFrecuency[e]=b.id;return b}}})});
//@ sourceMappingURL=SANotificationGridProduct.js.map