//>>built
require({cache:{"url:ec/fisa/widget/templates/Select.html":'\x3cdiv\x3e\n\t\x3cdiv data-dojo-attach-point\x3d"_componentNode"\x3e\x3c/div\x3e\n\x3c/div\x3e\n',"url:ec/fisa/widget/Select.conf":"{\n\tfisaClassic:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20,\n\t\tselectorWidth:30,\n\t\tgridOffset:30\n\t},\n\tfisaDesert:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20,\n\t\tselectorWidth:30,\n\t\tgridOffset:30\n\t}\n\n}"}});
define("ec/fisa/widget/Select","dijit/_Widget dijit/_Templated dojo/_base/declare dojo/_base/kernel dijit/form/Select dojo/_base/lang dojo/text!./templates/Select.html dojo/topic dojo/_base/array dojo/text!ec/fisa/widget/Select.conf ec/fisa/controller/Utils ec/fisa/widget/Utils ./_base".split(" "),function(g,h,k,d,l,f,m,q,n,p){return k("ec.fisa.widget.Select",[g,h],{readOnlyValue:!1,tabId:"",pageScopeId:"",hasFieldRoutineOrPolicy:!1,actionModeReq:"QY",parentGridId:null,gridId:"",qtId:"",fieldId:"",
valueColumn:0,labelColum:1,textBoxConfig:d.fromJson(p),visualSize:0,ioParametters:null,publishId:"",templateString:m,isARoutineField:!1,maxHeight:-1,parentEditableGrid:!1,entityMrId:null,tabIndexField:null,_tabIndex:0,gridRealRowIndex:null,tdParentWidth:null,CCYDependentFields:null,hasBeneficiarySelectionLink:null,_destroyOnRemove:!0,postMixInProperties:function(){this.inherited(arguments);var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);null==this.parentGridId&&(this.value=
a.obtainInitialValue(this));this.options=a.loadSelectData(this,!0);"string"==typeof this.ioParametters&&(this.ioParametters=eval(this.ioParametters))},startup:function(){this.inherited(arguments);var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),b=a.selectIdMap;if(null!=b&&void 0!=b){var c=this["field-id"];!0==this.parentEditableGrid&&(void 0!=this.gridRealRowIndex&&null!=this.gridRealRowIndex)&&(c=c+"|"+this.gridRealRowIndex);b[c]=this.id}null==this.parentGridId&&a.addParamToModel(this);
!0==this.hasFieldRoutineOrPolicy&&(a.addFieldRoutineEvent(this,this.actionModeReq),this._fStarted=!0);!0===this.readOnlyValue&&this._componentNode.set("disabled",this.readOnlyValue);null!=this.CCYDependentFields&&(b=this.get("value"),null!=b&&""!=b&&a.formatCCYRelatedField(this["bt-id"],this,!1));a=this._componentNode;a.connect(a,"onChange",d.hitch(this,this._execChange));!0===this.parentEditableGrid?(a=this.tdParentWidth,null!=a&&d.style(this._componentNode.containerNode,"width",a-this.textBoxConfig[d.config.fisaTheme].selectorWidth+
"px")):0<this.visualSize&&(a=this.widthCompCalc-this.textBoxConfig[d.config.fisaTheme].selectorWidth,0<a&&(a=this.widthCompCalc-this.textBoxConfig[d.config.fisaTheme].selectorWidth,d.style(this._componentNode.containerNode,"width",a+"px")))},attachOnChangeEvent:function(a,b,c,e){this.isARoutineField=!0;this.routineBtId=b;this.routineFieldId=c;this.routineActionMode=e},_execChange:function(){var a=this["notify-combo-id"],b=this["bt-id"],c=this["field-id"],e=ec.fisa.controller.utils.getPageController(this.tabId,
this.pageScopeId);e.clearPanelMessage();void 0!=e&&null!=e&&e.handleOnChangeComponent(c,b,this.routineActionMode,a,this.isARoutineField,e.getSelectedIndex(this),this.parentEditableGrid,this.entityMrId,this.gridRealRowIndex)},buildRendering:function(){this.inherited(arguments);null!=this.tabIndexField&&(this._tabIndex=this.tabIndexField);var a={"bt-id":this["bt-id"],"qt-id":this["qt-id"],"field-id":this["field-id"],tabId:this.tabId,pageScopeId:this.pageScopeId,options:this.options,ioParametters:this.ioParametters,
tabIndex:this._tabIndex};null!=this.value&&(a.value=this.value);if(0<this.visualSize){var b=this.textBoxConfig[d.config.fisaTheme].textCharWidth*this.visualSize+5;this.widthCompCalc=b;a.style={width:b+"px"}}a.maxHeight=this.maxHeight;this._componentNode=new l(a,this._componentNode);this._componentNode.findOutputParameters=this.findOutputParameters;this._componentNode.findComplemenParams=this.findComplemenParams;this._componentNode.findParametersbByType=this.findParametersbByType;this._componentNode._loadChildren=
this._loadChildren},destroy:function(){this.subscription&&(this.subscription.remove&&f.isFunction(this.subscription.remove))&&this.subscription.remove();ec.fisa.widget.utils.destroyMultiregisterWidget(this);this.inherited(arguments)},_setEnabledAttr:function(a){null!=a&&(a?ec.fisa.widget.utils.enableWidget(this._componentNode):ec.fisa.widget.utils.disableWidget(this._componentNode))},_getEnabledAttr:function(){return ec.fisa.widget.utils.isEnabled(this._componentNode)},verifyReloadOptionsNeeded:function(a,
b){var c=this.findInputParameters();this.verifyMyInParamChange(c,a)&&(this._componentNode.set("value",null),this._componentNode.removeOption(this._componentNode.options),ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).fetchSelectOptions(this.id,this["qt-id"],c,this["bt-id"]))},doForceReloadOptions:function(){var a=this.findInputParameters();this._componentNode.removeOption(this._componentNode.options);ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).reloadSelectOptions(this.id,
this["qt-id"],a,this["bt-id"],this["field-id"],this.tabId,this.pageScopeId)},findParametersbByType:function(a){var b=[];d.forEach(this.ioParametters,function(c,e,d){c.typeParameter==a&&b.push(c)},this);return b},findInputParameters:function(){return this.findParametersbByType("0")},findOutputParameters:function(){return this.findParametersbByType("1")},findComplemenParams:function(){return this.findParametersbByType("2")},verifyMyInParamChange:function(a,b){var c=!1;d.forEach(a,function(a,d,f){b["field-id"]==
a.parameterFieldId&&(a.value=b.get("value"),c=!0)},this);return c},_setValueAttr:function(a,b,c){null==a&&(a="");this._componentNode.set("value",a+"",b,c)},_getValueAttr:function(){return this._componentNode.get("value")},getOptions:function(a){return this._componentNode.getOptions(a)},addOption:function(a){this._componentNode.addOption(a)},removeOption:function(a){void 0!=a&&0<a.length&&(a=f.clone(a),""==a[0].value&&a.splice("0","1"),this._componentNode.removeOption(a))},updateOption:function(a){this._componentNode.updateOption(a)},
_setOptionsAttr:function(a){this._componentNode.set("options",a)},_loadChildren:function(a){if(!0===a)if(this.dropDown&&delete this.dropDown.focusedChild,this.options.length)this.inherited(arguments);else{n.forEach(this._getChildren(),function(a){a.destroyRecursive()});var b=new MenuItem({label:"\x26#160;"});this.dropDown.addChild(b)}else this._updateSelection();this._isLoaded=!1;this._childrenLoaded=!0;this._loadingStore||(this._lastValueReported=this.value,this._setValueAttr(this.value))},setControlValue:function(a){this._componentNode._lastValueReported=
"";this._componentNode.set("value",a,!0)}})});
//@ sourceMappingURL=Select.js.map