//>>built
require({cache:{"url:ec/fisa/widget/TextBox.conf":"{\n\tfisaClassic:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20\n\t},\n\tfisaDesert:{\n\t\ttextCharWidth:11,\n\t\ttextCharHeight:17,\n\t\tdefaultVisualSize:20\n\t}\n\n}","url:ec/fisa/widget/templates/TextBox.html":'\x3cdiv class\x3d"fisaTextBox"\x3e\n\x3ctable border\x3d"0" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\n\t\x3ctbody\x3e\n\t\t\x3ctr\x3e\n\t\t\t\x3ctd\x3e\n\t\t\t\x3cdiv id\x3d"${id}_textBox" data-dojo-attach-point\x3d"_componentNode" type\x3d"${_type}" \n\t\t\t\tdojoType\x3d"${_cmpType}" data-dojo-props\x3d\'${_dojoProps}\' tabIndex\x3d"${_tabIndex}"\n\t\t\t\t${_maxLengthExp}  title\x3d"${title}" tabId\x3d\'${tabId}\' pageScopeId\x3d\'${pageScopeId}\'\n\t\t\t\t${_baseClassExp}\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\t\x3ctd\x3e\x26nbsp;\x3c/td\x3e\n\t\t\t\x3ctd\x3e\n\t\t\t\x3cdiv id\x3d"${id}_complement" data-dojo-attach-point\x3d"_complementNode"\n\t\t\t\tdojoType\x3d"ec.fisa.widget.OutputText"\n\t\t\t\tbaseClass\x3d"${complementBaseClass}"\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\x3c/tr\x3e\n\t\x3c/tbody\x3e\n\x3c/table\x3e\n\x3c/div\x3e\n'}});
define("ec/fisa/widget/TextBox","dijit/_Widget dijit/_Templated dojo/_base/declare dojo/number dojo/on dojo/keys dijit/form/TextBox ec/fisa/widget/NumberTextBox ec/fisa/widget/Utils dojo/text!./templates/TextBox.html dojo/text!ec/fisa/widget/TextBox.conf dojo/topic dojo/dom-attr ec/fisa/widget/OutputText ec/fisa/controller/Utils ./_base ec/fisa/dwr/proxy/EventActionDWR".split(" "),function(f,g,h,m,n,p,q,r,e,k,l,s,t){return h("ec.fisa.widget.TextBox",[f,g],{readOnlyValue:!1,_readOnlyExp:"",maxLength:-1,
_maxLengthExp:"",_dojoProps:"trim:true",numeric:!1,title:"",style:"",format:0,textboxBaseClass:"dijitTextBox",complementBaseClass:"fisaOutputTextComplement",showComplement:!0,hasCompl:!0,widgetsInTemplate:!0,gridSelectedRowIndex:null,_complementNode:null,_componentNode:null,_cmpType:"",maskall:!1,password:!1,textTransform:"",parentEditableGrid:!1,gridId:"",_type:"text",_numeric:!1,tabId:"",pageScopeId:"",btId:"",fieldId:"",visualSize:-1,isARoutineField:!1,tabIndexField:null,_tabIndex:0,gridRealRowIndex:null,
tdParentWidth:null,textBoxConfig:dojo.fromJson(l),onChangeAttached:!1,templateString:k,tasasFormat:dojo.config.interestRateFormat,porcentajeFormat:dojo.config.percentageFormat,numericFormat:dojo.config.fisaNumericPattern,currencyFormat:dojo.config.fisaDefaultCurrency,inputConstraint:"",javaScriptValidator:"",additionalInfo:"",_destroyOnRemove:!0,customMsgParent:!1,postMixInProperties:function(){this.inherited(arguments);4==this.format||5==this.format||6==this.format?(this.textboxBaseClass+=" dijitNumberTextBox",
this._baseClassExp="textboxBaseClass\x3d'"+this.textboxBaseClass+"'",this._cmpType="ec.fisa.widget.NumberTextBox",this._numeric=!0):(this._baseClassExp="baseClass\x3d'"+this.textboxBaseClass+"'",this._cmpType="dijit.form.TextBox");0<=this.maxLength&&(this._maxLengthExp="maxLength\x3d'"+this.maxLength+"'");if(this.maskall||this.password)this._type="password";this._dojoProps="1"==this.textTransform?this._dojoProps+", uppercase:true ":"2"==this.textTransform?this._dojoProps+", lowercase:true ":"3"==
this.textTransform?this._dojoProps+", propercase:true ":"";null!=this.tabIndexField&&(this._tabIndex=this.tabIndexField)},buildRendering:function(){this.inherited(arguments);this._componentNode.btId=this.btId||this["bt-id"];this._componentNode.fieldId=this.fieldId||this["field-id"];var a=null;4==this.format?(this._componentNode._componentNode.set("constraints",{pattern:this.numericFormat}),a=this._componentNode._componentNode):5==this.format?(this._componentNode._componentNode.set("constraints",{pattern:this.tasasFormat}),
a=this._componentNode._componentNode):6==this.format?(this._componentNode._componentNode.set("constraints",{pattern:this.porcentajeFormat}),a=this._componentNode._componentNode):this.numeric&&(this._componentNode.textbox.style.textAlign="right",e.setAcceptOnlyNumeric(this._componentNode,!0));null!=a&&(a.btId=this.btId||this["bt-id"],a.fieldId=this.fieldId||this["field-id"]);"1"==this.textTransform?this._componentNode.textbox.style.textTransform="uppercase":"2"==this.textTransform?this._componentNode.textbox.style.textTransform=
"lowercase":"3"==this.textTransform&&(this._componentNode.textbox.style.textTransform="capitalize");var a=null,a=0<=this.visualSize?this.visualSize:this.textBoxConfig[dojo.config.fisaTheme].defaultVisualSize,a=this.textBoxConfig[dojo.config.fisaTheme].textCharWidth*a,b=this.getComponentNode();!0==this.parentEditableGrid&&null!=this.tdParentWidth&&a<this.tdParentWidth&&(a=this.tdParentWidth-10);b.domNode.style.width=a+"px";null!=this.inputConstraint&&""!=this.inputConstraint&&e.inputConstraint(this._componentNode,
this.inputConstraint);this.parentEditableGrid&&(this._complementNode.domNode.parentNode.style.display="none");this._complementNode._componentNode.style.display="none"},startup:function(){this.inherited(arguments);if(!0===this.readOnlyValue)this.getComponentNode().set("disabled",this.readOnlyValue);else{var a=this.getComponentNode();a.connect(a,"onChange",dojo.hitch(this,this._execChange));this.onChangeAttached=!0}},destroy:function(){ec.fisa.widget.utils.destroyMultiregisterWidget(this);this.inherited(arguments)},
_getRefAttr:function(){return this._componentNode.get("ref")},_setRefAttr:function(a){this._componentNode.set("ref",a)},_getRefCmplAttr:function(){return this._complementNode.get("ref")},_setRefCmplAttr:function(a){this._complementNode.set("ref",a)},_getBindingAttr:function(){return this._componentNode.get("binding")},_setBindingAttr:function(a){this._componentNode.set("binding",a)},_getValueAttr:function(){var a=this._componentNode.get("value");if(1==this.format||2==this.format||3==this.format)a=
this.getStrDatebyFormatId(a,this.format);return a},_setValueAttr:function(a,b,c){if(1==this.format||2==this.format||3==this.format)a=this.formatDatebyFormatId(a,this.format);this._componentNode.set("value",a,b,c);"boolean"===typeof b&&(!b&&!this.numeric)&&(this._componentNode._pendingOnChange=!1,this._componentNode._lastValueReported=a)},_getComplementAttr:function(){return this._complementNode.get("value")},_setComplementAttr:function(a,b,c){this.showComplement&&(this._complementNode._componentNode.style.display=
"block",this._complementNode.set("value",a))},attachOnChangeEvent:function(a,b,c,d){!0==this._fStarted&&(this._componentNode._fStarted=!0,delete this._fStarted);this.isARoutineField=!0;this.routineBtId=b;this.routineFieldId=c;this.routineActionMode=d;!1==this.onChangeAttached&&(a=this.getComponentNode(),a.connect(a,"onChange",dojo.hitch(this,this._execChange)),this.onChangeAttached=!0)},getComponentNode:function(){var a=this._componentNode;if(4==this.format||5==this.format||6==this.format)a=a._componentNode;
return a},_execChange:function(){var a=this["field-id"],b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);if(!0==b.applyValidator(this)){var c=this["notify-combo-id"];if(null!=c&&void 0!=c||!0==this.isARoutineField){var d=this["bt-id"];void 0!=b&&null!=b&&b.handleOnChangeComponent(a,d,this.routineActionMode,c,this.isARoutineField,null,this.parentEditableGrid,this.entityMrId,this.gridRealRowIndex)}}},_setEnabledAttr:function(a){null!=a&&(this._numeric?this._componentNode.set("enabled",
a):a?ec.fisa.widget.utils.enableWidget(this._componentNode):ec.fisa.widget.utils.disableWidget(this._componentNode))},_getEnabledAttr:function(){return this._numeric?this._componentNode.get("enabled"):ec.fisa.widget.utils.isEnabled(this._componentNode)},formatDatebyFormatId:function(a,b){return ec.fisa.format.utils.formatDateByFormatId(a,b)},getStrDatebyFormatId:function(a,b){return ec.fisa.format.utils.getStrDatebyFormatId(a,b)},getParentMsgComponent:function(){return this.customMsgParent?this.domNode.parentNode.parentNode.parentNode.parentNode.parentNode:
this.domNode.parentNode},getBeneficiaryNode:function(){if(this.customMsgParent){var a,b=this.domNode.parentNode.parentNode.children[1].childNodes;void 0!==b&&dojox.lang.functional.forIn(b,dojo.hitch(this,function(b){void 0!=b&&(null!=b&&void 0!=b.id&&null!=b.id&&""!=b.id)&&(a=b.id)}));return dijit.byId(a)}return this.domNode}})});
//@ sourceMappingURL=TextBox.js.map