//>>built
define("ec/fisa/dwr/Store",["dojo/_base/kernel","dojo/_base/declare","dojo/data/util/filter","ec/fisa/dwr/proxy/Engine","ec/fisa/dwr/Cache"],function(e,k){return k("ec.fisa.dwr.Store",null,{autoIdPrefix:"",_clientCache:!1,_currentQuery:null,_executedQueries:null,controller:null,method:null,tabId:null,gridStoreId:null,callbackScope:null,constructor:function(a,b,c,d,f,e){this._executedQueries=[];this.autoIdPrefix="_auto_"+Math.floor(1E5*Math.random())+"_";this.controller=a||this.controller;this.method=
b||this.method;this.tabId=c||this.tabId;this.gridStoreId=d||this.gridStoreId;if(null==this.controller||"string"!=typeof this.controller)throw Error("contoller is null or not a string");if(null==this.method||"string"!=typeof this.method)throw Error("method is null or not a string");a=e&&e.subscribe?this:null;this._clientCache=e&&void 0!==e.cache?e.cache:!1;this.dwrCache=new ec.fisa.dwr.Cache(this.controller,this.method,this.tabId,this.gridStoreId,f,a);this._entries={};this._updated={};this._nextLocalId=
0;this.$dwrByRef=this.fastFetchItemByIdentity=!0},getFeatures:function(){return{"dojo.data.api.Write":!0,"dojo.data.api.Notification":!0,"dojo.data.api.Identity":!0,"dojo.data.api.Read":!0}},_getAttributeValue:function(a,b,c){var d=this._entries[a];if(null==d&&(d=this._updated[a],null==d))throw Error("non item passed to _getAttributeValue() from ["+arguments.callee.caller+"]: "+a);if("$id"==b)return d.$id;if("$label"==b)return d.$label;var f=d.updates[b];void 0===f&&(f=d.data[b]);void 0===f&&(f=c);
return f},getValue:function(a,b,c){a=this._getAttributeValue(a,b,c);return e.isArray(a)?null:a},getValues:function(a,b){var c=this._getAttributeValue(a,b,[]);return e.isArray(c)?c:[c]},getAttributes:function(a){a=this._entries[a];if(null==a)throw Error("non item passed to getAttributes()");var b=["$id","$label"],c;for(c in a.data)"function"!=typeof a.data[c]&&b.push(c);return b},hasAttribute:function(a,b){return void 0!==this._getAttributeValue(a,b,void 0)},containsValue:function(a,b,c){a=this._getAttributeValue(a,
b,void 0);var d=!1;e.forEach(a,function(a){a==c&&(d=!0)});return d},isItem:function(a){return e.isString(a)&&null!=this._entries[a]},isItemLoaded:function(a){a=this._entries[a];return null!=a&&null!=a.data},loadItem:function(a){return!0},_complete:function(a,b,c){var d=a.scope||e.global;e.isFunction(a.onBegin)&&a.onBegin.call(d,b,a);e.isFunction(a.onItem)&&e.forEach(c,function(b){a.aborted||a.onItem.call(d,b.$id,a)});if(e.isFunction(a.onComplete)&&!a.aborted)if(e.isFunction(a.onItem))a.onComplete.call(d,
null,a);else{var f=[];e.forEach(c,function(a){f.push(a.$id)});a.onComplete.call(d,f,a)}},fetch:function(a){a.aborted=!1;this._currentQuery=a.query;if(this._clientCache){var b=this.getResults(),c=this.isCached(a,b);if(null!=c)return c=void 0===c.found?c._totalMatchedItems:c.found,b=this.clientSideFetch(a,b),this._complete(a,c,this.clientSidePaging(a,b)),a}return this._fetch(a)},isCached:function(a,b){void 0===a.start&&(a.start=0);void 0===a.count&&(a.count=1);for(var c=0;c<this._executedQueries.length;c++){var d=
this._executedQueries[c];if(!1!==this.querySuperSet(d,a)){var f=this.clientSideFetch({start:0,count:Infinity,query:a.query,queryOptions:a.queryOptions},b).length;if(a.start+a.count<=f)return delete d.found,d;var e=this.clientSideFetch({start:0,count:Infinity,query:d.query,queryOptions:d.queryOptions},b).length;if(d._totalMatchedItems<=e)return d.found=f,d}}return null},containedInterval:function(a,b,c,d){return a>c||b!=Number.POSITIVE_INFINITY&&b<d?!1:!0},querySuperSet:function(a,b){if(a.query==b.query)return{};
if(!(b.query instanceof Object&&(!a.query||"object"==typeof a.query)))return!1;var c=e.mixin({},b.query),d;for(d in a.query)if(c[d]==a.query[d])delete c[d];else if(!("string"==typeof a.query[d]&&e.data.util.filter.patternToRegExp(a.query[d]).test(c[d])))return!1;return c},getResults:function(){var a=[],b;for(b in this._entries)a.push(this._entries[b]);return a},clientSideFetch:function(a,b){var c;if(a.query){c=[];for(var d=0;d<b.length;d++){var f=b[d];f&&this.matchesQuery(f,a)&&c.push(b[d])}}else c=
b;return c},matchesQuery:function(a,b){var c=!1;b.queryOptions&&b.queryOptions.ignoreCase&&(c=b.queryOptions.ignoreCase);for(var d in b.query){var f=b.query[d],g=this.getValue(a.$id,d),h="string"==typeof f&&(null!=f.match(/[\*\.]/)||c);if(h=h?!e.data.util.filter.patternToRegExp(f,c).test(g):g!=f)return!1}return!0},clientSidePaging:function(a,b){var c=a.start||0;return c||a.count?b.slice(c,c+(a.count||b.length)):b},_fetch:function(a){a=a||{};var b=this,c=a.queryOptions?a.queryOptions:{deep:!1,ignoreCase:!1};
"undefined"==typeof c.deep&&(c.deep=!1);"undefined"==typeof c.ignoreCase&&(c.ignoreCase=!1);this.dwrCache.viewRegion({count:Number.POSITIVE_INFINITY==a.count?-1:a.count,start:Number.POSITIVE_INFINITY==a.start?0:a.start,query:a.query,sort:a.sort,queryOptions:c},{callback:function(c){var f=a.abort;a.abort=function(){a.aborted=!0;e.isFunction(f)&&f.call(a)};b._executedQueries.push(a);if(null==c)a._totalMatchedItems=0,b._complete(a,a._totalMatchedItems,[]);else{e.forEach(c.items.viewedMatches,b._importItem,
b);a._totalMatchedItems=c.items.totalMatchCount;this.updateMsgsPanel&&this.updateMsgsPanel(c.msgs);if(null!=this.reportWdgtId&&void 0!=this.reportWdgtId){var g=dijit.byId(this.reportWdgtId);null!=g&&void 0!=g&&(g=g._format_button,null!=g&&void 0!=g&&(0==c.items.totalMatchCount?e.setAttr(g,"disabled",!0):e.setAttr(g,"disabled",!1),dijit.focus(g.domNode)))}b._complete(a,c.items.totalMatchCount,c.items.viewedMatches);b.callbackScope&&b.callbackScope.qtGridId&&(c=dijit.byId(b.callbackScope.qtGridId))&&
e.isFunction(c.correctWidth)&&c.correctWidth()}},errorHandler:function(b,c){dwr.engine._postHook&&dwr.engine._postHook();if(e.isFunction(a.onError))a.onError(c,a)},callbackScope:this.callbackScope});return a},close:function(a){this._entries={};this._updated={};this.dwrCache.unsubscribe({exceptionHandler:function(a,c){console.error(c)}})},getLabel:function(a){try{return this._getAttributeValue(a,"$label")}catch(b){return"Item was deleted"}},getLabelAttributes:function(a){if(!this.isItem(a))throw Error("non item passed to getLabelAttributes()");
return["$label"]},getIdentity:function(a){try{return this._getAttributeValue(a,"$id")}catch(b){return null}},getIdentityAttributes:function(a){if(!this.isItem(a))throw Error("non item passed to getIdentityAttributes()");return["$id"]},fetchItemByIdentity:function(a){var b=a.scope||e.global,c=a.identity.toString(),d=this;this.fastFetchItemByIdentity?e.isFunction(a.onItem)&&a.onItem.call(b,c):this.dwrCache.viewItem(c,{callback:function(c){c.updates={};c.isDeleted=!1;c.isDirty=!1;c.$id=c.itemId;d._entries[c.$id]=
c;delete d._updated[c.$id];e.isFunction(a.onItem)&&a.onItem.call(b,c.$id)},exceptionHandler:function(c,d){e.isFunction(a.onError)&&a.onError.call(b,d)}});return a},_importItem:function(a){a.updates={};a.isDeleted=!1;a.isDirty=!1;a.$id=a.itemId;a.$label=a.label;this._entries[a.$id]=a;delete this._updated[a.$id]},itemRemoved:function(a,b){var c=this.getLabel(b);delete this._entries[b];delete this._updated[b];e.isFunction(this.onDelete)&&(console&&console.log&&console.log("Firing onDelete(",b,",",c,
")"),this.onDelete(b))},itemAdded:function(a,b){if(void 0===this._entries[b.itemId]){this._importItem(b);var c=1==this.clientSideFetch({start:0,count:Infinity,query:this._currentQuery,queryOptions:{ignoreCase:!0}},[this._entries[b.$id]]).length;e.isFunction(this.onNew)&&c&&(console&&console.log&&console.log("Firing onNew(",b.itemId,", null)"),this.onNew(b.itemId,null))}},itemChanged:function(a,b,c){this._updated[b.itemId]&&console&&console.log&&console.log("Warning server changes to "+b.itemId+" override local changes");
this._importItem(b);var d=this;e.isFunction(this.onSet)&&e.forEach(c,function(a){var c=d._getAttributeValue(b.itemId,a);console&&console.log&&console.log("Firing onSet(",b.itemId,a,c,b.data[a],")");d.onSet(b.itemId,a,c,b.data[a])})},onSet:function(a,b,c,d){console&&console.log&&console.log("Original onSet function called")},onNew:function(a,b){console&&console.log&&console.log("The store has been notified of an item ["+a+"] creation. Are you interested?")},onDelete:function(a){console&&console.log&&
console.log("Original onDelete function called")},newItem:function(a,b){var c={itemId:-1,$id:this.autoIdPrefix+this._nextLocalId++,data:a,$label:"",isDeleted:!1,isDirty:!0,updates:a};this._entries[c.$id]=c;this._updated[c.$id]=c;if(e.isFunction(this.onNew))this.onNew(c.$id,null);return c.$id},deleteItem:function(a){var b=this._entries[a];if(null==b)throw Error("non item passed to deleteItem(): "+a);delete this._entries[b.$id];b.isDeleted=!0;this._updated[b.$id]=b;if(e.isFunction(this.onDelete))this.onDelete(b.$id)},
setValue:function(a,b,c){if(void 0===c)throw Error("value is undefined");if(!b)throw Error("attribute is undefined");a=this._entries[a];if(null==a)throw Error("non item passed to setValue()");a.updates[b]=c;a.data[b]=c;a.isDirty=!0;this._updated[a.$id]=a;if(e.isFunction(this.onSet))this.onSet(a.$id,b,a.data[b],c)},setValues:function(a,b,c){if(!e.isArray(c))throw Error("value is not an array");if(!b)throw Error("attribute is undefined");a=this._entries[a];if(null==a)throw Error("non item passed to setValues()");
a.updates[b]=c;a.data[b]=c;a.isDirty=!0;this._updated[a.$id]=a;if(e.isFunction(this.onSet))this.onSet(a.$id,b,a.data[b],c)},unsetAttribute:function(a,b){if(!b)throw Error("attribute is undefined");var c=this._entries[a];if(null==c)throw Error("non item passed to unsetAttribute()");c.updates[b]=null;c.isDirty=!0;this._updated[c.$id]=c;if(e.isFunction(this.onSet))this.onSet(c.$id,b,c.data[b],null)},save:function(a){var b=[],c=this._updated;this._updated={};for(var d in c){var f=c[d];if(f.isDeleted)b.push({itemId:d,
attribute:"$delete",newValue:null});else for(var g in f.updates)b.push({itemId:d,attribute:g,newValue:f.updates[g]})}0<b.length?this.dwrCache.update(b,{callback:function(){c=null;if(a.onComplete)a.onComplete()},exceptionHandler:function(b,d){this._updated=e.mixin(this._updated,c);if(a.onError)a.onError(d)},scope:a.scope}):console&&console.log&&console.log("No updates to process")},getEntryById:function(a){var b=this._entries[a];if(null==b&&(b=this._updated[a],null==b))throw Error("doesn't exist item with id: "+
a);return b},revert:function(){for(var a in this._entries){var b=this._entries[a];b.isDeleted=!1;b.isDirty=!1;b.updates={}}this._updated={};return!0},isDirty:function(a){a=this._entries[a];if(null==a)throw Error("non item passed to isDirty()");return a.isDirty},clearCache:function(){this._executedQueries=[]},destroy:function(){var a=this.dwrCache;delete this.dwrCache;a.destroy();delete this.callbackScope;delete this._executedQueries;delete this._entries;delete this._currentQuery;delete this._clientCache},
setCallbackScope:function(a){this.callbackScope=a||{}},getAdditionalParams:function(){return this.dwrCache.doGetAdditionalParameters()},setAdditionalParams:function(a){this.dwrCache.additionalParams=a}})});
//@ sourceMappingURL=Store.js.map