//>>built
define("ec/fisa/controller/tsc/ChannelAppOptionController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/format/Utils ec/fisa/navigation/Utils dojo/data/ItemFileWriteStore dojo/dom-construct dijit/tree/ForestStoreModel dijit/Tree dijit/Menu dijit/tree/dndSource dojox/mvc ec/fisa/mvc/StatefulModel ec/fisa/widget/ConfirmDialog ec/fisa/widget/tsc/AvailableOptionsTree ec/fisa/widget/tsc/EditableOptionsTree ec/fisa/controller/custom/QtController dojo/dom-style".split(" "),
function(h,n,r,p,s,t,u,m,v,w,x,y,z,q,A,B,C,D,l){return n("ec.fisa.controller.tsc.ChannelAppOptionController",p,{tabId:null,pageScopeId:null,parentTabId:null,isDelete:!1,parentPageScopeId:null,mainOptionsData:null,editableOptionsData:null,treeData:null,editableOptionsTree:null,breadcrumbId:null,model:null,dialogId:null,data:{},dialogIdByItemId:{},scheduleList:null,parameterList:null,channelList:null,newItemId:null,identifierId:null,editableTreeId:null,availableTreeId:null,executeSaveTree:!0,channelComboId:null,
channelComboValue:null,requiredFieldMessage:null,globalMessagePanelId:null,combo:null,supportedLanguages:[],languageCode:null,componentsNames:"nameI18n parameter schedule routine relatedURL leaf".split(" "),constructor:function(a,b){this.tabId=a;this.pageScopeId=b;this.model=new q({});MenuEditionAdminControllerDWR.loadComboOptionsOptions(this.tabId,{callbackScope:this,callback:function(a){delete a.tabId;this.fillComboOptions(a)},errorHandler:h.hitch(this,this.errorHandler)});MenuEditionAdminControllerDWR.getRequiredFieldMessage({callbackScope:this,
callback:function(a){this.requiredFieldMessage=a},errorHandler:h.hitch(this,this.errorHandler)})},fillComboOptions:function(a){this.scheduleList=a.scheduleList;this.parameterList=a.parameterList;this.channelList=a.channelList;delete a.scheduleList;delete a.parameterList;delete a.channelList},setEditableOptionsId:function(a){this.editableTreeId=a.id},setAvailableOptionsId:function(a){this.availableTreeId=a},setChannelComboId:function(a){this.channelComboId=a;this.combo=dijit.byId(a);this.combo.connect(this.combo,
"onChange",h.hitch(this,this.setChannelId))},setAvailableMenuData:function(a){this.mainOptionsData=a},setEditableMenuData:function(a){this.editableOptionsData=a},deleteEditTree:function(a){(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:this.labelsData.yesLabel,cancelDialogLabel:this.labelsData.noLabel,title:this.labelsData.deleteMenuLabel,content:this.labelsData.deleteWarnLabel,acceptAction:h.hitch(this,this.deleteEditTreeCnfrm,a)})).show()},deleteEditTreeCnfrm:function(a){var b={callbackScope:this};
b.callback=this.handleWindowAction;b.errorHandler=this.errorHandler;MenuEditionAdminControllerDWR.deleteMenu(this.tabId,this.pageScopeId,a,b)},saveEditTree:function(){var a=dijit.byId(this.channelComboId);this.channelComboValue=a.getValue();a={field:"ADM_CHANNEL",value:a.getValue()};this.validateFields([a],!0)||(this.executeSaveTree=!0,a={scope:this},a.onComplete=this.onSaveComplete,a.onError=h.hitch(this,this.errorHandler),dijit.byId(this.editableTreeId).store.save(a))},onSaveComplete:function(a){this.executeSaveTree=
!1;a={callbackScope:this.scope};a.callback=this.scope.handleWindowAction;a.errorHandler=h.hitch(this.scope,this.scope.errorHandler);MenuEditionAdminControllerDWR.saveEditableTree(this.scope.tabId,this.scope.pageScopeId,this.scope.channelComboValue,a)},handleWindowAction:function(a){var b=null,c=null;"cnfrm"==a.wAxn?(b=this.tabId,c=this.pageScopeId):(b=this.parentTabId,c=this.parentPageScopeId);b=ec.fisa.controller.utils.getPageController(b,c);b.clearPanelMessage();b.updateMsgsPanel(a.aMsgs);"cnfrm"==
a.wAxn&&ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(a.confirmationDialogTitle,a.aMsgs,this.breadcrumbId,this.tabId,this.pageId,null,null,!1)},bindToModel:function(a,b,c){var d;void 0!==typeof c&&null!=c&&(d=dijit.byId(c).itemData[b]);"undefined"===typeof d&&(d="");this.model.appendObject([b],d,a.id,"value",null,!0)},addNewFolder:function(a,b){var c=a+"_nameI18n",d=this.model.getValue([c]);if(!this.validateFields([{field:"CAL_NAME",value:d}])){var e=dijit.byId(b);e.model.newItem({name:ec.fisa.controller.utils.getCurrentTranslation(d,
this.languageCode,this.supportedLanguages),nameI18n:d,type:"EXTERNAL_FOLDER",isLeaf:!1,editableTreeItem:!0},a,e.lastFocused.getChildren().length);d=e.dialogIdByItemId[a];e.itemData={};this.model.removeObject([c]);dijit.byId(d).destroy()}},changeFolderName:function(a,b){var c=a+"_nameI18n",d=this.model.getValue([c]);if(!this.validateFields([{field:"CAL_NAME",value:d}])){var e=dijit.byId(b),f=e.store;f.setValue(a,"name",ec.fisa.controller.utils.getCurrentTranslation(d,this.languageCode,this.supportedLanguages));
f.setValue(a,"nameI18n",d);d=e.dialogIdByItemId[a];e.itemData={};this.model.removeObject([c]);e.isModifyOption=!1;dijit.byId(d).destroy()}},saveItemInformation:function(a,b){var c=dijit.byId(b),d=c.store,e=d.getEntryById(a);if(!e)return alert("entry doesn't exist");var e=e.data,f=!1,h="-1",k="-1",f={field:"CAL_NAME",value:this.model.getValue([a+"_nameI18n"])};!0==this.model.contains([a+"_schedule"])&&(h=this.model.getValue([a+"_schedule"]));var g=e.type;"ITEM_LAYOUT_TEMPLATE"!=g?(h={field:"ADM_SCHEDULE",
value:h},!0==this.model.contains([a+"_parameter"])&&(k=this.model.getValue([a+"_parameter"])),k={field:"ADM_PARAMETER",value:k},"ITEM_QUERY_TEMPLATE"==g||"BUSINESS_TEMPLATE_URL"==g?f=this.validateFields([f,h]):"EXTERNAL_URL"==g?(g={field:"ADM_URL",value:this.model.getValue([a+"_relatedURL"])},f=this.validateFields([g,f])):f="BUSINESS_TEMPLATE_CUSTOMIZED"==g?this.validateFields([f,h]):this.validateFields([f,h,k])):(g={field:"ADM_IDENTIFIER",value:this.model.getValue([a+"_relatedURL"])},f=this.validateFields([g,
f]));if(!1===f){for(f=0;f<this.componentsNames.length;f++)g=this.componentsNames[f],k=this.model.getValue([a+"_"+g]),void 0!==typeof k&&null!=k&&(e[g]=k,d.setValue(a,g,k),"nameI18n"==g&&(k=ec.fisa.controller.utils.getCurrentTranslation(k,this.languageCode,this.supportedLanguages),e.name=k,d.setValue(a,"name",k))),this.model.removeObject([a+"_"+g]);d.setValue(a,"leaf",e.leaf);d.setValue(a,"editableTreeItem",!0);d=c.dialogIdByItemId[a];c.itemData={};c.isModifyOption=!1;dijit.byId(d).destroy()}},cancelItemInformation:function(a,
b){var c=dijit.byId(b).dialogIdByItemId[a];dijit.byId(c).onCancel()},saveExternalURLInformation:function(a,b){var c={field:"ADM_URL",value:this.model.getValue([a+"_relatedURL"])},d={field:"CAL_NAME",value:this.model.getValue([a+"_nameI18n"])};this.validateFields([c,d])||(c=dijit.byId(b),c.model.newItem({name:ec.fisa.controller.utils.getCurrentTranslation(this.model.getValue([a+"_nameI18n"]),this.languageCode,this.supportedLanguages),nameI18n:this.model.getValue([a+"_nameI18n"]),routine:this.model.getValue([a+
"_routine"]),relatedURL:this.model.getValue([a+"_relatedURL"]),type:"EXTERNAL_URL",leaf:!0,editableTreeItem:!0},a,c.lastFocused.getChildren().length),d=c.dialogIdByItemId[a],c.itemData={},this.model.removeObject([a+"_nameI18n",a+"_routine",a+"_relatedURL"]),dijit.byId(d).destroy())},findAvailableTree:function(){var a=this.model.getValue(["availableValuePattern"]),b="",c=dijit.byId(this.availableTreeId),d=null;null==c.modelAllTree&&(c.modelAllTree=c.model);d=c.modelAllTree;"undefined"!==typeof a&&
null!=a&&""!=a?(b=d.findTreeItem(a,"id"),b=this.setFoundNodesIdsAsString(b)):a="";var e=m.create("div",{},c.domNode.parentNode),a={tabId:c.tabId,pageScopeId:c.pageScopeId,additionalParams:[c.getChannelValue(),"isTreeFinder",b,a],style:"overflow: visible;"};c.destroyRecursive(!1);c=new ec.fisa.widget.tsc.AvailableOptionsTree(a,e);this.availableTreeId=c.id;""!=b&&(c.autoExpand=!0);c.modelAllTree=d},findEditablebleTree:function(){var a=this.model.getValue(["editableValuePattern"]),b=null,c=dijit.byId(this.editableTreeId);
c.constructDomNodesArr();"undefined"!==typeof a&&(null!=a&&""!=a)&&(a=c.model.findTreeItem(a,"id"),b=this.setFoundNodesIdsAsString(a));if(""!=b&&null!=b){var a=b.split("#"),b=c._itemNodesMap,d;for(d in b){var e=c.getDomNodeById(d);l.set(e,"display","none");for(var f=0;f<a.length;f++)if(""!=a[f]&&d==a[f]){l.set(e,"display","");b[d][0].expand();break}}}else if(""==b)for(d in b=c._itemNodesMap,b)e=c.getDomNodeById(d),l.set(e,"display","none");else for(d in b=c._itemNodesMap,b)e=c.getDomNodeById(d),l.set(e,
"display","")},validateFields:function(a,b){var c={level:{level:4E4}};c.summary=this.requiredFieldMessage.I18N_REQUIRED_FIELDS;h.forEach(a,function(a){if("undefined"===typeof a.value||""==a.value||"-1"==a.value||"-1000"==a.value)c.detail="undefined"!==typeof c.detail?c.detail+" ** "+this.requiredFieldMessage[a.field]:"** "+this.requiredFieldMessage[a.field]},this);if("undefined"!==typeof c.detail){var d=null;void 0!==b&&b?(d=dijit.byId(this.globalMessagePanelId),this.setMessagesPanel(d,b)):d=dijit.byId(this.messagesPanelId);
d.clearAllMessages();this.updateMsgsPanel([c]);return!0}return!1},close:function(){ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)},setMessagesPanel:function(a,b){void 0!==b&&!0===b&&(this.globalMessagePanelId=a.id);this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId)this.breadcrumbId=ec.fisa.controller.utils.findCurrentBreadCrumb(a);this.updateMsgsPanel(this.initMsgs);delete this.initMsgs},setChannelId:function(a){this.clearPanelMessage();
this.reloadAvailableTree();this.reloadEditableTree()},reloadAvailableTree:function(){var a=dijit.byId(this.availableTreeId),b=m.create("div",{},a.domNode.parentNode),c={tabId:a.tabId,pageScopeId:a.pageScopeId,additionalParams:[a.getChannelValue(),"isReloadTree"],style:"overflow: visible;"};a.destroyRecursive(!1);b=new ec.fisa.widget.tsc.AvailableOptionsTree(c,b);this.availableTreeId=b.id;a.modelAllTree=b.model;b.startup()},reloadEditableTree:function(){var a=dijit.byId(this.editableTreeId),b=m.create("div",
{},a.domNode.parentNode),c={tabId:a.tabId,pageScopeId:a.pageScopeId,additionalParams:[a.getChannelValue(),"isReloadTree"],style:"overflow: visible;"};a.destroyRecursive(!1);b=new ec.fisa.widget.tsc.EditableOptionsTree(c,b);this.editableTreeId=b.id;a.modelAllTree=b.model;b.startup()},setSelectedChannelValue:function(a,b){!0==b&&a.set("selected","selected")},setParentTabId:function(a){this.parentTabId=a},setParentPageScopeId:function(a){this.parentPageScopeId=a},setSupportedLanguages:function(a){this.supportedLanguages=
a},setLanguageCode:function(a){this.languageCode=a},setFoundNodesIdsAsString:function(a){for(var b="",c=0;c<a.length;c++)for(var d=a[c],e=0;e<d.length;e++){var f=d[e];-1==b.indexOf(f)&&(b=b+f+"#")}return b}})});
//@ sourceMappingURL=ChannelAppOptionController.js.map