//>>built
define("ec/fisa/controller/tsc/MicroRouteBuilderController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/dom-construct ec/fisa/controller/BaseController dojox/mvc dojox/mvc/StatefulModel ec/fisa/format/Utils dojo/data/ItemFileWriteStore ./_base ec/fisa/grid/FisaQtGrid ec/fisa/dwr/proxy/QtControllerDWR dojox/lang/functional/object ec/fisa/widget/DateTextBox dijit/layout/AccordionContainer dojo/dnd/Source dojo/data/ItemFileWriteStore dijit/tree/TreeStoreModel dijit/tree/ForestStoreModel dijit/Tree dijit/tree/dndSource dijit/registry dijit/form/TextBox dojox/grid/DataGrid dojox/grid/cells dojox/grid/cells/dijit dojo/currency dijit/Editor dojox/grid/cells dijit/form/CurrencyTextBox".split(" "),
function(h,k,m,n,l,p,q,r,s){return k("ec.fisa.controller.tsc.MicroRouteBuilderController",l,{tabId:null,pageScopeId:null,parentTabId:null,parentPageScopeId:null,parentBtId:null,parentFieldId:null,parentData:null,model:null,modelComplement:null,qtGridId:null,fisaChartId:null,mainOptionsData:null,treeData:null,mainRouteTreeId:null,attributesTableId:null,gridLayout:null,attrGridData:null,attrGridDataList:null,attrGridStore:null,attrGrid:null,elementAttributeList:null,buttonId:null,model:null,microRouteObjectData:null,
data:{},constructor:function(a,b,c,e,g,f){this.tabId=a;this.pageScopeId=b;this.parentTabId=c;this.parentPageScopeId=e;this.parentBtId=g;this.parentFieldId=f;this.mainOptionsData={identifier:"id",label:"name",items:[]};this.model=dojox.mvc.newStatefulModel({data:{}});this.initData()},initData:function(){this.elementAttributeList=[]},setMainRouteTreeId:function(a){this.mainRouteTreeId=a.id},setMicroRouteObjectData:function(a){this.microRouteObjectData=a},setRouteAttributesTableId:function(a){this.attributesTableId=
a.id;dijit.byId(this.mainRouteTreeId).setDataTableGeneratedId(this.attributesTableId)},getElementAttributeData:function(){MicroRouteControllerDWR.findAllElementAttributesWithParent({callbackScope:this,callback:function(a){this.fillElementAttributeList(a)},errorHandler:this.errorHandler})},saveItemInformation:function(a){for(var b=dijit.byId(this.attributesTableId),c=dijit.byId(b.parentTreeId),b=b.store,e=a.data.elementId,g="",e=e.concat("( "),f=0;f<b._arrayOfAllItems.length;f++){var d=b._arrayOfAllItems[f];
null!=d.widget&&""!=d.widget&&(c.store.setValue(a.itemId,"attributeId_"+f,d.attr[0]),c.store.setValue(a.itemId,"attributeValue_"+f,d.widget),c.store.setValue(a.itemId,"isLabel_"+f,d.isLabel[0]),g=g.concat(d.attr[0]+"TPT"+d.widget+"TAT"),c.store.setValue(a.itemId,"attrArray",g),"1"==d.isLabel&&(e=e.concat(d.attr[0].concat(" [ "+d.widget+" ] ")),e=e.concat("  "),c.store.setValue(a.itemId,"name",e.toString().concat(" )"))))}},saveMainRouteTree:function(){var a={scope:this};a.onComplete=this.onSaveComplete;
a.onError=this.errorHandler;var b=dijit.byId(this.mainRouteTreeId);b.store.dwrCache.additionalParams.push(this.model._microRouteName.value);b.store.dwrCache.additionalParams.push(this.model._microRouteDescription.value);b.store.dwrCache.additionalParams.push(this.model._microRouteId.value);b.store.save(a)},deleteMainRouteTree:function(){(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:"Eliminar",cancelDialogLabel:"Cancelar",title:"Eliminar Ruta",content:"Desea eliminar la ruta actual?",acceptAction:h.hitch(this,
function(){var a={callbackScope:this};a.callback=this.handleWindowAction;a.errorHandler=this.errorHandler;MicroRouteControllerDWR.deleteCurrentMicroRoute(this.tabId,this.pageScopeId,a);ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)})})).show()},cancelMicroRoute:function(a){null!=a&&"true"==a?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)},setMessagesPanel:function(a){this.inherited(arguments);
if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId)this.breadcrumbId=a.getParent().getParent().getParent().id;this.updateMsgsPanel(this.initMsgs);this.btContentPaneId=a.getParent().getParent().id;delete this.initMsgs},onSaveComplete:function(a){ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.scope.breadcrumbId)},bindToModel:function(a,b,c){dijit.byId(this.mainRouteTreeId);c=this.bindDataRoute()[b];"undefined"===typeof c&&(c="");c=new dojox.mvc.StatefulModel({data:c});this.model.add(b,
c);a.set("ref",this.model[b])},bindDataRoute:function(){var a={};null!=this.microRouteObjectData&&(a._microRouteName=this.microRouteObjectData[0],a._microRouteDescription=this.microRouteObjectData[1],a._microRouteId=this.microRouteObjectData[2]);return a},setButtonId:function(a){this.buttonId=a.id;dijit.byId(this.mainRouteTreeId).setButtonDataTableId(this.buttonId)},fillElementAttributeList:function(a){this.elementAttributeList=a},setAttributesTableProperties:function(){},errorHandler:function(a){alert("errorHandler "+
a)},destroy:function(){}})});
//@ sourceMappingURL=MicroRouteBuilderController.js.map