//>>built
define("ec/fisa/controller/tsc/ProcessRouteBuilderController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/dom-construct ec/fisa/controller/BaseController dojox/mvc dojox/mvc/StatefulModel ec/fisa/format/Utils dojo/data/ItemFileWriteStore ec/fisa/mvc/StatefulModel ./_base ec/fisa/grid/FisaQtGrid ec/fisa/dwr/proxy/QtControllerDWR dojox/lang/functional/object ec/fisa/widget/DateTextBox ec/fisa/controller/Utils dijit/layout/AccordionContainer dojo/dnd/Source dojo/data/ItemFileWriteStore dijit/tree/TreeStoreModel dijit/tree/ForestStoreModel dijit/Tree dijit/tree/dndSource dijit/registry dijit/form/TextBox dojox/grid/DataGrid dojox/grid/cells dojox/grid/cells/dijit dojo/currency dijit/Editor dojox/grid/cells dijit/form/CurrencyTextBox".split(" "),
function(h,k,n,p,l,q,r,s,t,m){return k("ec.fisa.controller.tsc.ProcessRouteBuilderController",l,{tabId:null,pageScopeId:null,parentTabId:null,parentPageScopeId:null,parentBtId:null,parentFieldId:null,actionId:null,parentData:null,model:null,model2:null,modelComplement:null,qtGridId:null,fisaChartId:null,mainOptionsData:null,treeData:null,mainRouteTreeId:null,attributesTableId:null,gridLayout:null,attrGridData:null,attrGridDataList:null,attrGridStore:null,attrGrid:null,elementAttributeList:null,buttonId:null,
model:null,processRouteObjectData:null,data:{},initData:null,lovData:null,initDataFT:null,processDefinitionId:null,contentPanel:null,breadcrumbId:null,constructor:function(a,b,c,d,f,g,e,h,k,l){this.tabId=a;this.pageScopeId=b;this.parentTabId=c;this.parentPageScopeId=d;this.parentBtId=f;this.parentFieldId=g;this.actionId=e;this.mainOptionsData={identifier:"id",label:"name",items:[]};this.model2=dojox.mvc.newStatefulModel({data:{}});this.elementAttributeList=[];this.initData=h;this.lovData=k;this.data=
l;this.model=new m({data:this.initData})},setMainRouteTreeId:function(a){this.mainRouteTreeId=a.id},setRouteAttributesTableId:function(a){this.attributesTableId=a.id;dijit.byId(this.mainRouteTreeId).setDataTableGeneratedId(this.attributesTableId)},getElementAttributeData:function(){ProcessRouteControllerDWR.findAllElementAttributesWithParent({callbackScope:this,callback:function(a){this.fillElementAttributeList(a)},errorHandler:this.errorHandler})},saveItemInformation:function(a){for(var b=dijit.byId(this.attributesTableId),
c=dijit.byId(b.parentTreeId),b=b.store,d=a.data.elementId,f="",d=d.concat("( "),g=0;g<b._arrayOfAllItems.length;g++){var e=b._arrayOfAllItems[g];null!=e.widget&&""!=e.widget&&(c.store.setValue(a.itemId,"attributeId_"+g,e.attr[0]),c.store.setValue(a.itemId,"attributeValue_"+g,e.widget),c.store.setValue(a.itemId,"isLabel_"+g,e.isLabel[0]),f=f.concat(e.attr[0]+"TPT"+e.widget+"TAT"),c.store.setValue(a.itemId,"attrArray",f),"1"==e.isLabel&&(d=d.concat(e.attr[0].concat(" [ "+e.widget+" ] ")),d=d.concat("  "),
c.store.setValue(a.itemId,"name",d.toString().concat(" )"))))}},saveMainRouteTree:function(){var a={scope:this};a.onComplete=this.onSaveMainRouteComplete;a.onError=this.errorHandler;var b=dijit.byId(this.mainRouteTreeId);b.store.dwrCache.additionalParams.push(this.model2._processRouteName.value);b.store.dwrCache.additionalParams.push(this.model2._processRouteDescription.value);b.store.dwrCache.additionalParams.push(this.model2._internalProcessId.value);b.store.dwrCache.additionalParams.push(this.model2._processRouteId.value);
b.store.save(a)},onSaveMainRouteComplete:function(a){ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.scope.breadcrumbId);"IN"==this.scope.actionId&&ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.scope.breadcrumbId)},bindToModel:function(a,b,c){c=dijit.byId(this.mainRouteTreeId);null!=this.attributesTableId&&c.setDataTableGeneratedId(this.attributesTableId);dijit.byId(this.mainRouteTreeId);c=this.bindDataRoute()[b];"undefined"===typeof c&&(c="");c=new dojox.mvc.StatefulModel({data:c});this.model2.add(b,
c);a.set("ref",this.model2[b])},bindDataRoute:function(){var a={};null!=this.processRouteObjectData&&(a._processRouteName=this.processRouteObjectData[0],a._processRouteDescription=this.processRouteObjectData[1],a._internalProcessId=this.processRouteObjectData[2],a._processRouteId=this.processRouteObjectData[3]);return a},setProcessRouteObjectData:function(a){this.processRouteObjectData=a},setButtonId:function(a){this.buttonId=a.id;dijit.byId(this.mainRouteTreeId).setButtonDataTableId(this.buttonId)},
addParamToModel:function(a){var b=a["bt-id"],c=a["field-id"],d=null;this.data&&(this.data[b]&&this.data[b].dataMessage)&&(d=this.data[b].dataMessage.fields[c]);null==d?(d={value:"",complement:null},a._fStarted=!0):null==d.value&&(d.value="",a._fStarted=!0);"EFP-TTSC_PROCESS_ROUTE-PROCESS_ID"===c&&(this.processDefinitionId=d.value);if(this.model.contains(b))this.model.contains([b,"dataMessage","fields",c])&&this.model.setValue([b,"dataMessage","fields",c,"value"],d.value);else{var f=null;a instanceof
ec.fisa.widget.DateTextBox&&(f=ec.fisa.format.utils.formatLongDate);this.model.appendObject([b,"dataMessage","fields",c,"value"],d.value,a.id,"value",f,!0);f=null;void 0!=d.enabled&&(f=d.enabled);this.model.appendObject([b,"dataMessage","fields",c,"enabled"],f,a.id,"enabled",null,!1);a.hasCompl&&this.model.appendObject([b,"dataMessage","fields",c,"complement"],d.complement,a.id,"complement",null,!1)}},containsFieldModel:function(a,b){return this.model.contains([a,"dataMessage","fields",b,"value"])},
getFieldModel:function(a,b){return this.model.getValue([a,"dataMessage","fields",b,"value"])},setFieldModelValue:function(a,b,c){this.model.setValue([a,"dataMessage","fields",b,"value"],c)},setFieldModelEnabled:function(a,b,c){this.model.setValue([a,"dataMessage","fields",b,"enabled"],c)},setFieldModelComplement:function(a,b,c){this.model.setValue([a,"dataMessage","fields",b,"complement"],c)},getFieldModelComplement:function(a,b){return this.model.getValue([a,"dataMessage","fields",b,"complement"])},
handleCallBackBackFieldRoutine:function(a,b){this.showMessages(a)},showMessages:function(a){null!=a&&this.updateMsgsPanel(a.aMsgs)},goToNewProcessRoute:function(a){this.processDefinitionId=this.getFieldModel("EFP_TSC_PRR_NFIS0000","EFP-TTSC_PROCESS_ROUTE-PROCESS_ID");this.callNewProcessRouteDialog()},openNewProcessRouteDialog:function(){this.contentPanel=new dojox.widget.DialogSimple({title:"Nueva Ruta de Proceso",href:"./static/tsc/newProcessRouteBuilder.jsp?",ioArgs:{content:{FISATabId:this.tabId,
FisaPageScopeId:this.pageScopeId}},ioMethod:h.xhrPost});this.contentPanel.set("dimensions",[400,200]);this.contentPanel.layout();this.contentPanel.show()},callNewProcessRouteDialog:function(){var a={callbackScope:this,callback:function(a){var c={title:"Nueva Ruta de Proceso",iconClass:"breadcrumbIcon"};c.href=a.nextUrl;c.postClose=this.refresh;c.postCloseScope=this.id;c.postCloseArgs=[this.tabId];a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);ec.fisa.navigation.utils.openNewBreadCrumb(c,
a.breadcrumbId)}};a.errorHandler=this.errorHandler;ProcessRouteControllerDWR.getNewProcessRoutePage(this.tabId,this.pageScopeId,this.actionId,this.processDefinitionId,a)},setMessagesPanel:function(a){this.inherited(arguments);if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId)this.breadcrumbId=a.getParent().getParent().getParent().id;this.updateMsgsPanel(this.initMsgs);this.btContentPaneId=a.getParent().getParent().id;delete this.initMsgs},cancelProcessRoute:function(a){null!=a&&"true"==
a?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)},deleteMainRouteTree:function(){(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:"Eliminar",cancelDialogLabel:"Cancelar",title:"Eliminar Ruta",content:"Desea eliminar la ruta actual?",acceptAction:h.hitch(this,function(){var a={callbackScope:this};a.callback=this.handleWindowAction;a.errorHandler=this.errorHandler;ProcessRouteControllerDWR.deleteCurrentProcessRoute(this.tabId,
this.pageScopeId,a);ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)})})).show()},fillElementAttributeList:function(a){this.elementAttributeList=a},setAttributesTableProperties:function(){},errorHandler:function(a){alert("errorHandler "+a)},destroy:function(){}})});
//@ sourceMappingURL=ProcessRouteBuilderController.js.map