//>>built
define("ec/fisa/controller/tsc/TranslatorController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/format/Utils dojo/_base/window dojo/dom dojox/mvc ec/fisa/mvc/StatefulModel dojox/lang/functional/object dojo/store/Memory dojo/data/ItemFileReadStore dojo/date/locale ec/fisa/navigation/Utils ec/fisa/dwr/Store dojox/widget/DialogSimple ec/fisa/controller/Utils ec/fisa/widget/Utils".split(" "),function(f,k,g,l,n,p,q,r,m,s){return k("ec.fisa.controller.tsc.TranslatorController",
l,{tiMappingId:null,dropAreaSource:null,dropAreaTarget:null,controllerList:null,handlerPropertiesDataGrid:null,data:null,tabId:null,pageScopeId:null,model:null,cmps:null,initData:null,breadcrumb:null,bindingContentPane:null,sourceTargetDataGrid:null,propertiesDataGrid:null,paneSearcher:null,messagesPanel:null,translatorInstanceId:null,translatorName:null,translatorDesc:null,translatorId:null,translatorSource:null,translatorTarget:null,local:null,contentPanel:null,contentPanelProperties:null,breadcrumbId:null,
initMsgs:null,lovData:null,validador:null,sourceQtId:null,targetQtId:null,sourceComponent:null,targetComponent:null,propertiesName:null,propertiesValor:null,disabled:null,actionId:null,buttonTiMapping:null,requiredFieldMessage:null,proNameList:null,priorityId:null,sourceType:null,targetType:null,expression:null,sourceBTApplyTo:null,isBTSource:!1,targetBTApplyTo:null,comboSourceApplyToId:null,comboTargetApplyToId:null,hasMappings:null,constructor:function(a,b,d,c,e){this.initData=d;this.tabId=a;this.pageScopeId=
b;this.model={};this.cmps={};this.initMsgs=[];this.data=e;this.lovData=c;this.init(d);this.buttonTiMapping=!1},init:function(a){this.disabled=a.disabled;this.translatorId=a.translatorId;this.sourceQtId=a.sourceQtId;this.targetQtId=a.targetQtId;this.validador=a.validador;this.actionId=a.actionId;this.requiredFieldMessage=a.requiredFieldMessage;this.sourceType=a.sourceType;this.targetType=a.targetType;this.hasMappings=a.hasMappings;"1"==this.sourceType&&(this.isBTSource=!0);delete a.translatorId;delete a.sourceQtId;
delete a.targetQtId;delete a.validador;delete a.disabled;delete a.actionId;delete a.requiredFieldMessage;delete a.targetType;delete a.sourceType;delete a.hasMappings;this.model=new m({data:a})},validarTiMapping:function(){this.buttonTiMapping=!1},cargarTareas:function(a,b,d,c){this.clearPanelMessage();a=null;a=new ec.fisa.dwr.Store("TranslatorControllerDWR","viewData",this.tabId,this.pageScopeId,[b,d,c],null);this.sourceTargetDataGrid.setStore(a)},cargarTareasProperties:function(a,b){this.clearPanelMessage();
var d=null,d=new ec.fisa.dwr.Store("TranslatorControllerDWR","viewDataProperties",this.tabId,this.pageScopeId,[],null);this.propertiesDataGrid.setStore(d)},saveDropArea:function(){this.processApplyToValues();var a=null,b=null;null==this.sourceBTApplyTo&&(this.sourceBTApplyTo="1");null==this.targetBTApplyTo&&(this.targetBTApplyTo="1");var d=dojox.lang.functional.keys(this.dropAreaSource.selection),c=dojox.lang.functional.keys(this.dropAreaSource.map),e=d[0];0<c.length&&f.forEach(c,function(b){b==e&&
(a=this.dropAreaSource.map[e].data.id)},this);var d=dojox.lang.functional.keys(this.dropAreaTarget.selection),c=dojox.lang.functional.keys(this.dropAreaTarget.map),h=d[0];0<c.length&&f.forEach(c,function(a){a==h&&(b=this.dropAreaTarget.map[h].data.id)},this);d={callbackScope:this,callback:function(d){this.clearPanelMessage();if("error"==d.wAxn){var c=this.messagesPanelId;this.messagesPanelId=this.mappingMessagesPanelId;this.updateMsgsPanel(d.aMsgs);this.messagesPanelId=c}else this.cargarTareas(this.tabId,
a,b,"true")}};d.errorHandler=this.errorHandler;null!=a&&null!=b?("COMMONS|EXPRESSION"==a&&(a=a+"|"+this.expression),TranslatorControllerDWR.saveHomeLayout(this.tabId,this.pageScopeId,[a,b,"true",this.translatorInstanceId,this.translatorId,this.sourceType,this.targetType,this.sourceBTApplyTo,this.targetBTApplyTo],d)):alert("Ingresar valores para proceder a agregar")},deleteRegistro:function(){var a=this.sourceTargetDataGrid.selection.getSelected(),b={callbackScope:this,callback:function(a){this.clearPanelMessage();
this.cargarTareas(this.tabId,null,null,"true")}};b.errorHandler=this.errorHandler;TranslatorControllerDWR.deleteHomeLayout(this.tabId,this.pageScopeId,a,b)},destroy:function(){this.inherited(arguments);delete this.dropAreaSource;delete this.dropAreaTarget},bindDropAreaSource:function(a){this.dropAreaSource=a},bindDropAreaTarget:function(a){this.dropAreaTarget=a},openTiMapping:function(){this.processApplyToValues();if("1"==this.sourceType){var a={field:"Campos de origen se aplican a",value:this.sourceBTApplyTo};
if(this.validateFields([a]))return}if("1"==this.targetType&&(a={field:"Campos de destino se aplican a",value:this.targetBTApplyTo},this.validateFields([a])))return;a={title:"Mapping",iconClass:"breadcrumbIcon",href:"./static/tsc/fragment/tiMapping.jsp"};a.ioArgs={content:{FISATabId:this.tabId,FisaPageScopeId:this.pageScopeId,actionId:this.actionId,showSourceApplyTo:this.verifyShowApplyTo(this.sourceType),showTargetApplyTo:this.verifyShowApplyTo(this.targetType)}};a.ioMethod=f.xhrPost;var b=ec.fisa.controller.utils.getPageController(this.tabId,
this.pageScopeId);ec.fisa.navigation.utils.openNewBreadCrumb(a,b.breadcrumbId)},closeTiMapping:function(){var a={callbackScope:this,callback:function(a){this.clearPanelMessage();ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)}};a.errorHandler=this.errorHandler;TranslatorControllerDWR.cancelTiMapping(this.tabId,this.pageScopeId,a)},closeTI:function(a){a={callbackScope:this,callback:function(a){this.clearPanelMessage();null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):
ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)}};a.errorHandler=this.errorHandler;TranslatorControllerDWR.cancelTI(this.tabId,this.pageScopeId,a)},saveTI:function(a){this.processApplyToValues();if(!this.validateFields([{field:"_Id",value:this.translatorInstanceId},{field:"_Transformador",value:this.translatorId}])){if("1"==this.sourceType&&(a={field:"Campos de origen se aplican a",value:this.sourceBTApplyTo},this.validateFields([a]))||"1"==this.targetType&&(a={field:"Campos de destino se aplican a",
value:this.targetBTApplyTo},this.validateFields([a])))return;TranslatorControllerDWR.saveTranslatorInstance(this.tabId,this.pageScopeId,[this.translatorInstanceId,this.translatorName,this.translatorDesc,this.translatorId,this.translatorSource,this.translatorTarget,this.local,this.sourceBTApplyTo,this.targetBTApplyTo],{callbackScope:this,callback:function(a){a.validadorId?this.showMessages(a):(this.clearPanelMessage(),null!=this.isSequence&&"true"==this.isSequence?ec.fisa.navigation.utils.closeSequenceBreadCrumb(this.breadcrumbId):
ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId))}})}},saveTiMapping:function(){var a={callbackScope:this,callback:function(a){this.clearPanelMessage();ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId);var d=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);d.hasMappings=a.hasMappings;d.processHasMappings()}};a.errorHandler=this.errorHandler;TranslatorControllerDWR.saveTiMapping(this.tabId,this.pageScopeId,a)},setMessagesPanel:function(a){this.inherited(arguments);
if("undefined"===typeof this.breadcrumbId||null==this.breadcrumbId)this.breadcrumbId=a.getParent().getParent().getParent().id;this.updateMsgsPanel(this.initMsgs);this.btContentPaneId=a.getParent().getParent().id;delete this.initMsgs},addParamToModel:function(a){var b=a["bt-id"],d=a["field-id"],c=null;this.data&&(this.data[b]&&this.data[b].dataMessage)&&(c=this.data[b].dataMessage.fields[d]);null==c?(c={value:"",complement:null},a._fStarted=!0):null==c.value&&(c.value="",a._fStarted=!0);this.disabled&&
(a.set("disabled",this.disabled),c.enabled=!1);if("EFP-TTSC_TRANSLATOR_INSTANCE-TRANSLATOR_INSTANCE_ID"===d)"UP"===this.actionId&&(a.set("disabled",this.disabled),c.enabled=!1),this.translatorInstanceId=c.value;else if("EFP-TTSC_TRANSLATOR_INSTANCE-NAME"===d)this.translatorName=c.value;else if("EFP-TTSC_TRANSLATOR_INSTANCE-DESCRIPTION"===d)this.translatorDesc=c.value;else if("EFP-TTSC_TRANSLATOR_INSTANCE-TRANSLATOR_ID"===d)"UP"===this.actionId&&(a.set("disabled",this.disabled),c.enabled=!1),this.translatorId=
c.value;else if("EFP-TTSC_TRANSLATOR_INSTANCE-LOCAL"===d)this.local=c.value;else if("EFP-TTSC_TRANSLATOR_INSTANCE-SOURCE"===d)this.translatorSource=c.value,this.sourceComponent=a,null==this.translatorSource&&(a.set("disabled",!0),c.enabled=!1),!this.disabled&&(null!=this.translatorSource&&0!=this.translatorSource.length&&null!=this.translatorTarget&&0!=this.translatorTarget.length)&&(this.buttonTiMapping=!0);else if("EFP-TTSC_TRANSLATOR_INSTANCE-TARGET"===d)this.translatorTarget=c.value,this.targetComponent=
a,null==this.translatorTarget&&(a.set("disabled",!0),c.enabled=!1),!this.disabled&&(null!=this.translatorSource&&0!=this.translatorSource.length&&null!=this.translatorTarget&&0!=this.translatorTarget.length)&&(this.buttonTiMapping=!0);else if("EFP-TTSC_TRANSLATOR_INSTANCE-SOURCE_APPLIES_TO"==d){if("1"==this.sourceType&&(null==c.value||""==c.value||"undefined"==typeof c.value))c.value="1";this.sourceBTApplyTo=c.value;this.processHasMappings()}else if("EFP-TTSC_TRANSLATOR_INSTANCE-TARGET_APPLIES_TO"==
d){if("1"==this.targetType&&(null==c.value||""==c.value||"undefined"==typeof c.value))c.value="1";this.targetBTApplyTo=c.value;this.processHasMappings()}if(this.model.contains(b))this.model.contains([b,"dataMessage","fields",d])&&this.model.setValue([b,"dataMessage","fields",d,"value"],c.value,!1);else{var e=null;a instanceof ec.fisa.widget.DateTextBox&&(e=ec.fisa.format.utils.formatLongDate);this.model.appendObject([b,"dataMessage","fields",d,"value"],c.value,a.id,"value",e,!0);e=null;void 0!=c.enabled&&
(e=c.enabled);this.model.appendObject([b,"dataMessage","fields",d,"enabled"],e,a.id,"enabled",null,!1);a.hasCompl&&this.model.appendObject([b,"dataMessage","fields",d,"complement"],c.complement,a.id,"complement",null,!1)}},containsFieldModel:function(a,b){return this.model.contains([a,"dataMessage","fields",b,"value"])},getFieldModel:function(a,b){return this.model.getValue([a,"dataMessage","fields",b,"value"])},setFieldModelValue:function(a,b,d){this.model.setValue([a,"dataMessage","fields",b,"value"],
d,!1);"EFP-TTSC_TRANSLATOR_INSTANCE-TRANSLATOR_ID"===b?(this.translatorId=d,this.updateTranslatorId()):"EFP-TTSC_TRANSLATOR_INSTANCE-SOURCE"===b?(this.translatorSource=d,null!=this.translatorSource&&(0!=this.translatorSource.length&&null!=this.translatorTarget&&0!=this.translatorTarget.length)&&(this.buttonTiMapping=!0)):"EFP-TTSC_TRANSLATOR_INSTANCE-TARGET"===b&&(this.translatorTarget=d,null!=this.translatorSource&&(0!=this.translatorSource.length&&null!=this.translatorTarget&&0!=this.translatorTarget.length)&&
(this.buttonTiMapping=!0))},setFieldModelEnabled:function(a,b,d){this.model.setValue([a,"dataMessage","fields",b,"enabled"],d,!1)},setFieldModelComplement:function(a,b,d){this.model.setValue([a,"dataMessage","fields",b,"complement"],d)},getFieldModelComplement:function(a,b){return this.model.getValue([a,"dataMessage","fields",b,"complement"])},updateTranslatorId:function(){var a=this.sourceComponent["bt-id"],b=this.sourceComponent["field-id"],d=this.targetComponent["bt-id"],c=this.targetComponent["field-id"],
e={callbackScope:this,callback:function(e){this.clearPanelMessage();this.sourceComponent["qt-id"]=e.sourceQtId;this.targetComponent["qt-id"]=e.targetQtId;this.sourceType=e.sourceType;this.targetType=e.targetType;"1"==this.sourceType?(ec.fisa.widget.utils.enableWidget(this.comboSourceApplyToId),this.setFieldModelEnabled(a,b,!0)):(ec.fisa.widget.utils.disableWidget(this.comboSourceApplyToId),this.setFieldModelValue("EFP_TSC_TIS_NFIS0000","EFP-TTSC_TRANSLATOR_INSTANCE-SOURCE_APPLIES_TO",""));"1"==this.targetType?
(ec.fisa.widget.utils.enableWidget(this.comboTargetApplyToId),this.setFieldModelEnabled(a,b,!0)):(ec.fisa.widget.utils.disableWidget(this.comboTargetApplyToId),this.setFieldModelValue("EFP_TSC_TIS_NFIS0000","EFP-TTSC_TRANSLATOR_INSTANCE-TARGET_APPLIES_TO",""));e.hasQtSource&&(this.sourceComponent.set("disabled",!1),this.setFieldModelEnabled(a,b,!0));e.hasQtTarget&&(this.targetComponent.set("disabled",!1),this.setFieldModelEnabled(d,c,!0));this.cargarTareasProperties(this.tabId,null);this.setFieldModelValue("EFP_TSC_TIS_NFIS0000",
"EFP-TTSC_TRANSLATOR_INSTANCE-SOURCE","");this.setFieldModelValue("EFP_TSC_TIS_NFIS0000","EFP-TTSC_TRANSLATOR_INSTANCE-TARGET","")}};e.errorHandler=this.errorHandler;TranslatorControllerDWR.updateTranslatorId(this.tabId,this.pageScopeId,this.translatorId,null,e)},bindToModel:function(a,b,d){var c=this.data[b];if(void 0===c||null==c)c="";new dojox.mvc.StatefulModel({data:c});a.set("ref",this.model[b]);a.set("disabled",d)},saveProperties:function(){var a={callbackScope:this,callback:function(a){this.clearPanelMessage();
this.contentPanelProperties.destroy();this.cargarTareasProperties(this.tabId,!0)}};a.errorHandler=this.errorHandler;null!=this.propertiesName&&0<this.propertiesName.length&&null!=this.propertiesValor&&0<this.propertiesValor.length?"-1"!=this.propertiesName?TranslatorControllerDWR.saveProperties(this.tabId,this.pageScopeId,this.propertiesName,this.propertiesValor,[this.translatorInstanceId,this.translatorId],a):alert("Seleccionar un nombre de propiedad para continuar..."):alert("Ingresar valores para proceder a agregar")},
eliminarProperties:function(){var a=this.propertiesDataGrid.selection.getSelected(),b={callbackScope:this,callback:function(a){this.cargarTareasProperties(this.tabId,!0)}};b.errorHandler=this.errorHandler;TranslatorControllerDWR.eliminarProperties(this.tabId,this.pageScopeId,a,b)},openTiProperties:function(){this.clearPanelMessage();if(!(null!=this.translatorInstanceId&&0==this.translatorInstanceId.length||null!=this.translatorId&&0==this.translatorId.length)){var a={callbackScope:this,callback:function(a){this.proNameList=
a.proNameList;this.priorityId=a.priorityId;this.contentPanelProperties=new dojox.widget.DialogSimple({title:"Transformador Properties",href:"./static/tsc/fragment/tiProperties.jsp",ioArgs:{content:{FISATabId:this.tabId,FisaPageScopeId:this.pageScopeId}},ioMethod:f.xhrPost});this.contentPanelProperties.show()}};a.errorHandler=this.errorHandler;TranslatorControllerDWR.getComboPropertiesName(null,this.translatorId,this.tabId,a)}},closeTiProperties:function(){this.contentPanelProperties.destroy();this.clearPanelMessage()},
deshabilitar:function(a){this.disabled&&component.set("disabled",this.disabled)},handleCallBackBackFieldRoutine:function(a,b){this.showMessages(a)},showMessages:function(a){null!=a&&this.updateMsgsPanel(a.aMsgs)},validateFields:function(a){var b={level:{level:4E4}};b.summary=this.requiredFieldMessage.I18N_REQUIRED_FIELDS;f.forEach(a,function(a){if("undefined"===typeof a.value||""==a.value||"-1"==a.value)b.detail="undefined"!==typeof b.detail?b.detail+" * "+this.requiredFieldMessage[a.field]:"* "+
a.field},this);return"undefined"!==typeof b.detail?(dijit.byId(this.messagesPanelId).clearAllMessages(),this.updateMsgsPanel([b]),!0):!1},limpiarTranslator:function(){var a={callbackScope:this,callback:function(a){this.clearPanelMessage();this.cargarTareasProperties(this.tabId,null);this.setFieldModelValue("EFP_TSC_TIS_NFIS0000","EFP-TTSC_TRANSLATOR_INSTANCE-SOURCE","");this.setFieldModelValue("EFP_TSC_TIS_NFIS0000","EFP-TTSC_TRANSLATOR_INSTANCE-TARGET","")}};a.errorHandler=this.errorHandler;TranslatorControllerDWR.limpiarTranslator(this.tabId,
this.pageScopeId,a)},onBlurExpression:function(a){this.expression=a.get("value")},processApplyToValues:function(){var a=dijit.byId(this.comboSourceApplyToId);a&&g.isFunction(a.get)&&(this.sourceBTApplyTo=a.get("value"));if((a=dijit.byId(this.comboTargetApplyToId))&&g.isFunction(a.get))this.targetBTApplyTo=a.get("value")},initApplyToOptions:function(a,b){a.set("options",this._getListOfOptions());this[b]=a.get("id")},_getListOfOptions:function(){var a=[];a[0]={value:"",label:f.config.fisaSelectLabel,
selected:!0};a[1]={value:"1",label:"Aplicaci\u00f3n"};a[2]={value:"2",label:"BT"};return a},getLabel:function(a,b){var d="",c=this._getListOfOptions();a&&""!=a&&f.forEach(c,function(b,c){a==b.value&&(d=b.label)});b.set("value",d);return d},verifyShowApplyTo:function(a){return"1"==a},processHasMappings:function(){hasMappings=this.hasMappings;("IN"==this.actionId||"UP"==this.actionId)&&"1"==this.sourceType&&!1==hasMappings?ec.fisa.widget.utils.enableWidget(this.comboSourceApplyToId):ec.fisa.widget.utils.disableWidget(this.comboSourceApplyToId);
("IN"==this.actionId||"UP"==this.actionId)&&"1"==this.targetType&&!1==hasMappings?ec.fisa.widget.utils.enableWidget(this.comboTargetApplyToId):ec.fisa.widget.utils.disableWidget(this.comboTargetApplyToId)},setMappingMessagesPanel:function(a){this.mappingMessagesPanelId=a.id}})});
//@ sourceMappingURL=TranslatorController.js.map