//>>built
define("ec/fisa/navigation/Utils","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/xhr dojo/on ec/fisa/navigation/_base dojox/widget/DialogSimple ec/fisa/layout/ContentPane ec/fisa/widget/ConfirmDialog ec/fisa/widget/ConfirmTemplateDialog dojo/dom-geometry dojo/dom-style dojo/dom-construct ec/fisa/controller/Utils".split(" "),function(m,s,z,A,u,t,n,B,v,w,x,r,y){s=s("ec.fisa.navigation.Utils",null,{createNewFisaTab:function(a,b,c,d,k){var h=dijit.byId("tabContainer"),l=0,e=0;m.forEach(h.getChildren(),
function(a){0==a.id.indexOf("TAB_"+b,0)&&(l+=1);a.tabCount>e&&(e=a.tabCount)});var f={preload:!0};f.id="TAB_"+b+"_"+l;f.tabCount=e+1;0==l?(f.href=c+"\x26tabId\x3d"+(e+1),f.title=a):(f.href=c+"\x26tabId\x3d"+(e+1),f.title=a+" ("+(l+1)+")");f.closable=!0;var p=new dojox.layout.ContentPane(f,m.doc.createElement("div"));h.addChild(p);h.selectChild(p);p.startup();d&&(a=m.dijit.byId(d),h.fisaTableStoreToAnswer=a,h.fisaStoreToAnswer=a.store,h.fisaIndexesToAnswer=k,h.fisaAction=function(){p.close()})},closeTab:function(a){EventActionDWR.closeTab(a,
{callbackScope:this,callback:ec.fisa.controller.utils.clearControllers})},closeCurrentTab:function(){var a=dijit.byId("tabContainer"),b=a.selectedChildWidget;if(b){if(b.onClose)b.onClose();a.removeChild(b);b.destroyRecursive()}},closeTabFromBreadCrumb:function(a){var b=a.getParent();b.getChildren();b.removeChild(a);EventActionDWR.closeTab(a.tabId)},openNewBreadCrumb:function(a,b){a.preventCache=!0;a.iconClass="breadcrumbIcon";var c=new ec.fisa.layout.ContentPane(a),d=dijit.byId(b);d.addChild(c);d.selectedChildWidget.controlButton.set("disabled",
!0);d.selectedChildWidget.controlButton.oldOnClick=d.selectedChildWidget.controlButton.onClick;d.selectedChildWidget.controlButton.onClick=function(){};d.selectChild(c)},updateCurrentBreadCrumb:function(a,b,c,d){b=dijit.byId(b);b.ioArgs=a.ioArgs;b.setHref(a.href);ec.fisa.controller.utils.resetControllerData(c,d)},closeCurrentBreadCrumb:function(a){var b=dijit.byId(a);a=ec.fisa.navigation.utils.removeChildBreadCrumb(a);null==a||!0===a.isHome?ec.fisa.navigation.utils.closeTabFromBreadCrumb(b):!0===
a.isQtContentPane?ec.fisa.controller.utils.getPageController(a.tabId,a.pageScopeId).searchAfterCloseContentPane():a.getChildren()[0]&&(a.getChildren()[0].selectedChildWidget&&!0===a.getChildren()[0].selectedChildWidget.isQtContentPane)&&(b=a.getChildren()[0].selectedChildWidget.tabId,a=a.getChildren()[0].selectedChildWidget.pageScopeId,ec.fisa.controller.utils.getPageController(b,a).searchAfterCloseContentPane())},closeSequenceBreadCrumb:function(a){var b=dijit.byId(a);a=ec.fisa.navigation.utils.removeChildBreadCrumb(a);
!0===a.isHome?ec.fisa.navigation.utils.closeTabFromBreadCrumb(b):!0===a.isQtContentPane?ec.fisa.controller.utils.getPageController(a.tabId,a.pageScopeId).searchAfterCloseContentPane():ec.fisa.navigation.utils.closeSequenceBreadCrumb(b)},removeChildBreadCrumb:function(a){a=dijit.byId(a);var b=a.selectedChildWidget;a.removeChild(b);b.destroyRecursive(!1);var b=a.getChildren(),c=null;0<b.length&&(c=b[b.length-1],c.controlButton.set("disabled",!1),c.controlButton.onClick=c.controlButton.oldOnClick,delete c.controlButton.oldOnClick,
a.selectChild(c));return c},showMsgCloseCurrentBreadCrumb:function(a,b,c){a=this.openCntFisaDlg(a,b);a.closeCurrentBreadCrumb=this.closeCurrentBreadCrumb;a.breadcrumbId=c;u(a,"hide",function(){var a=dijit.byId(c).selectedChildWidget;if(a.postClose){var b=ec.fisa.controller.utils.getPageController(a.postCloseArgs[0],a.postCloseArgs[1]);a.postClose.apply(b,a.postCloseArgs);scp=null}this.closeCurrentBreadCrumb(this.breadcrumbId);this.destroyRecursive()});a.resize({w:250,h:150});a.show()},showNewBreadCrumbConfirmation:function(a,
b,c,d,k,h,l,e){this.showNewBreadCrumbConfirmation(a,b,c,d,k,h,l,e,null,null)},showNewBreadCrumbConfirmation:function(a,b,c,d,k,h,l,e,f,p){var n;n=""+m.config.fisaContextPath;var q={};q.title=a;q.iconClass="breadcrumbIcon";q.href=n+"/pages/static/bt/btConfirmation.jsp";q.closeArgs=[c,b];q.ioArgs={content:{tabId:d,pageScopeId:k,btId:h,btCalledActionMode:l,isSequence:e,showReportModule:f,showReportAuto:p}};ec.fisa.navigation.utils.openNewBreadCrumb(q,c)},showNewDialogAdditionalCm:function(a,b,c,d){a=
ec.fisa.controller.utils.getGlobalModalSize(0.8);var k;k=""+m.config.fisaContextPath;var h={};h.title=d;h.href=k+"/pages/static/tsc/notification/fragment/additionalPersonContactMedia.jsp";h.resizeOnLoad=!1;h.executeScripts=!0;h.ioArgs={content:{tabId:b,pageScopeId:c}};h.ioMethod=m.xhrPost;h.style="height:"+a.h-70+"px;width:500px;overflow: auto;";b=new n(h);r.set(b.closeButtonNode,"display","none");b.show();this.resizeNode(b,a);return b.id},resizeNode:function(a,b){var c=x.getMarginBox(a.titleNode);
r.set(a.containerNode,"height",b.h-c.h-4*c.t-85+"px");r.set(a.containerNode,"display","block");r.set(a.containerNode,"overflowY","auto");r.set(a.containerNode,"overflowX","auto")},showNewReportBreadCrumb:function(a,b,c,d,k,h,l){var e;e=""+m.config.fisaContextPath;var f={};f.title=a;f.iconClass="breadcrumbIcon";f.href=e+k;f.ioArgs={content:{tabId:c,btPageScopeId:d,responseShowNextReportButton:h,responseShowEndReportButton:l}};f.ioMethod=m.xhrPost;ec.fisa.navigation.utils.openNewBreadCrumb(f,b)},showNewBreadCrumbQtScheduling:function(a,
b,c,d,k,h){var l;l=""+m.config.fisaContextPath;l+="/SCHEDULE_QT_FILTER";l+="/";l+="ITEM_QUERY_TEMPLATE";l+="/";l+=k;l+="/FISATabId/";l+=c;l+="/REQUEST_HIDE_BUTTON_BAR/true";k={};k.title=a;k.href=l;k.ioArgs={content:{parentTabId:c,parentPageScopeId:d,parentBreadCrumbId:b,scheduleInitialQtParams:h}};k.ioMethod=m.xhrPost;ec.fisa.navigation.utils.openNewBreadCrumb(k,b)},showPostBtBreadCrumb:function(a,b,c,d,k,h,l,e,f,p,n,q,r,s){var g;g=""+m.config.fisaContextPath;g+="/BUSINESS_TEMPLATE";g+="/";g+=k;null!=
h&&(void 0!=h&&""!=h)&&(g+="/",g+="POST_SECUENCE_ID",g+="/",g+=h);g+="/FISATabId/";g+=c;g+="/actionMode/QY";g+="/FDK/";g+=e;g+="/_FDK";g+="/BT_SHOW_CONFIRMATION_BT/";g+="true";null!=p&&void 0!=p&&(g+="/REQUEST_IS_SEQUENCE/",g+=p);g+="/POST_PBT_FDK/";g+=f;g+="/parentBtInAuthorization/";g+=r;g+="/isConfirmationBt/";g+="true/index.jsp";h={};h.title=a;h.iconClass="breadcrumbIcon";h.href=g;!1==s?(h.ioArgs={content:{msgPostBreadCrumb:m.toJson(b),showReportModule:n,showReportAuto:q,btPageScopeId:d}},ec.fisa.navigation.utils.updateCurrentBreadCrumb(h,
l,c,d)):(h.ioArgs={content:{msgPostBreadCrumb:encodeURIComponent(m.toJson(b)),tabId:c,pageScopeId:d,btPageScopeId:d,btId:k,isSequence:p,showReportModule:n,showReportAuto:q}},ec.fisa.navigation.utils.openNewBreadCrumb(h,l))},openFisaDialog:function(a,b,c,d){a={callbackScope:{titleDlg:a,hrefString:b,data:c,treeGrid:d}};a.errorHandler=m.hitch(this,this.errorHandler);a.callback=this.callBckObjOpenPopup;DocumentControllerDWR.processLaunchPopupDocument(c.actionId,c.tabId,c.pageScopeId,c.btId,c.id[0],a)},
openCntFisaDlg:function(a,b){var c=new n({title:a,content:b,preload:!0,preventCache:!0,draggable:!1});c.show();return c},openHrefFisaDlg:function(a,b,c){a=new n({title:a,href:b,preload:!0,preventCache:!0,ioArgs:c});a.show();return a},openHrefFisaDlgPopupUnique:function(a,b,c,d){a=new n({id:a,title:b,href:c,preload:!0,preventCache:!0,ioArgs:d});a.connect(a,"onHide",function(a){this.destroyRecursive(!1)});a.show();return a},callBckObjOpenPopup:function(a){a.treeGridNodeId=this.data.id[0];var b=new n({title:this.titleDlg,
href:this.hrefString,ioArgs:{content:{tabId:this.data.tabId,btId:this.data.btId,actionId:this.data.actionId,pageScopeIdDocument:this.data.pageScopeId}},ioMethod:m.xhrPost});b.treeGrid=this.treeGrid;b.tabId=this.data.tabId;b.data=a;b.show();b.connect(b,"hide",function(){var a={callbackScope:this};a.errorHandler=m.hitch(this,this.errorHandler);a.callback=ec.fisa.navigation.utils.callBckHideDialogHandler;DocumentControllerDWR.undoCancelUploadDocument(this.treeGridNodeId,this.treeGrid.tabIdvar,this.treeGrid.pageScopeIdvar,
a)})},callBckHideDialogHandler:function(a){"success"==a.status?(ec.fisa.controller.utils.uninitializeController(this.tabId,this.popupPageScopeId),this.destroyRecursive()):ec.fisa.controller.utils.getPageController(this.tabId,this.popupPageScopeId).updateMsgsPanel(a.details)},switchVisibility:function(a){var b=m.byId(a);a=b;b.domNode&&(a=b.domNode);var b=a.style,c="none";"none"==b.display&&(c="");b.display=c;return a},undoTreeGridAction:function(a,b,c){a=new v({acceptDialogLabel:a.acceptButton,cancelDialogLabel:a.cancelButton,
title:a.infoTitle,content:a.treeTableUndoMessage,acceptAction:this._undoDialogActin});a.callBckFnctnDwr=this.callBckFnctnDwr;a.errorHandler=m.hitch(this,this.errorHandler);a.rowItemData=c;a.treeGrid=b;a.show()},templateDlgShowAction:function(a,b,c,d,k,h){var l={};l["fisa-action-id"]=k;l["fisa-bt-id"]=d;l.is_sequence=h;this._templateDlgShowAction(a,b,c,function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);this.callerCmp.template_over_call="New";a.execAction(this.callerCmp)},
function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);this.callerCmp.template_over_call="OverWrite";a.execAction(this.callerCmp)},l)},templateSequenceDlgShowAction:function(a,b,c,d){this._templateDlgShowAction(a,b,c,function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);a.templateOverCall="New";a.sequenceLastAction(d)},function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);a.templateOverCall="OverWrite";
a.sequenceLastAction(d)},{})},_templateDlgShowAction:function(a,b,c,d,k,h){a=new w({acceptDialogLabel:a.New,cancelDialogLabel:a.Cancel,overWriteDialogLabel:a.PLANTILLA_OVERWRITE,title:a.PLANTILLA_CONFIRM,content:a.PLANTILLA_DUPLICATE,acceptAction:d,overWriteAction:k});a.errorHandler=m.hitch(this,this.errorHandler);a.callerCmp=h;a.tabId=b;a.pageScopeId=c;a.show()},_undoDialogActin:function(){var a={callbackScope:{treeGrid:this.treeGrid}};a.errorHandler=m.hitch(this,this.errorHandler);a.callback=this.callBckFnctnDwr;
DocumentControllerDWR.undoDocument(this.rowItemData.id[0],this.treeGrid.tabIdvar,this.treeGrid.pageScopeIdvar,a)},callBckFnctnDwr:function(a){"success"==a.status&&this.treeGrid&&ec.fisa.controller.utils.updateRowTreeGrid(this.treeGrid,a)},historyTreeGridAction:function(a,b){var c={callbackScope:{treeGrid:a}};c.errorHandler=m.hitch(this,this.errorHandler);c.callback=this.callBckFnctnHistoryDwr;DocumentControllerDWR.processLaunchShowHistory(b.id[0],a.tabIdvar,a.pageScopeIdvar,c)},callBckFnctnHistoryDwr:function(a){if("success"==
a.status){var b=a.details;a=a.labels;var c=m.config.fisaContextPath,d=new n({title:a.treeDocHistory,href:c+"/pages/static/documents/document_history.jsp",ioArgs:{content:{tabId:this.treeGrid.tabIdvar,btId:this.treeGrid.btIdvar,actionId:this.treeGrid.actionIdvar,pageScopeIdDocument:this.treeGrid.pageScopeIdvar}},ioMethod:m.xhrPost});d.documentHisArray=b;d.labels=a;d.contextPath=c;d.show()}},obtainParentBreadCrumb:function(a){for(;"dijit.layout.TabContainer"!=a.declaredClass;)if(a.getParent())a=a.getParent();
else break;a&&(a.finner&&"true"===a.finner&&a.getParent())&&(a=this.obtainParentBreadCrumb(a.getParent()));return a},obtainBtTitle:function(a,b){for(var c=b||!1,d=null,k=a;"dijit.layout.TabContainer"!=k.declaredClass;)if(k.getParent())k=k.getParent();else break;void 0!=k&&null!=k&&(k=m.query(".btTitle",k.domNode),null!=k&&0<k.length&&(d=c?k[0]:k[k.length-1]));return d},navigateSequenceTo:function(a,b,c,d,k,h,l){this.navigateSequenceFromDocTo(a,b,c,d,k,h,l,"false")},navigateSequenceFromDocTo:function(a,
b,c,d,k,h,l,e){var f="",f=m.config.fisaContextPath,f=f+"/BUSINESS_TEMPLATE",f=f+"/",f=f+a,f=f+"/btSequenceStep/",f=f+b,f=f+"/FISATabId/",f=f+d,f=f+"/FisaPageScopeId/",f=f+k,f=f+"/SEQUENCE_PRINCIPAL_BT_MODE/",f=f+h;"true"===l&&(f+="/PREVIOUS_BUTTON_CLICKED/",f+=l);"true"===e&&(f+="/COMING_BACK_FROM_DOC/",f+=e);a={};a.href=f;ec.fisa.navigation.utils.updateCurrentBreadCrumb(a,c,d,k)},navigateToSchedulePage:function(a,b,c,d,k,h,l){var e;e=""+m.config.fisaContextPath;e+="/SCHEDULE_FILTER";e+="/";e+="BUSINESS_TEMPLATE";
e+="/";e+=b;e+="/FISATabId/";e+=c;e+="/FDK/";e+=k;e+="/_FDK";e+="/actionMode/QY";e+="/";e+="REQUEST_SCHEDULE_FILTER_BT";e+="/";e+=a;e+="/REQUEST_HIDE_BUTTON_BAR/true";e+="/index.jsp";a={};a.title=d;a.iconClass="breadcrumbIcon";a.href=e;ec.fisa.navigation.utils.updateCurrentBreadCrumb(a,h,c,l)},openChat:function(){var a=dijit.byId("chatCP"),b=m.config.fisaChatUsername,c=m.config.fisaSessionId,d=m.config.fisaDojoRootUrl;null==a&&("1"==m.config.fisaFinalUser?(a=m.config.modulePaths.chat+"/pages/client.jsp?username\x3d"+
b+"\x26fisaSessionId\x3d"+encodeURIComponent(c),a=new dojox.layout.ContentPane({id:"chatCP",href:a,doLayout:!1,style:"width:31em; right:auto;"},y.create("div",{},m.byId("copyright"))),a.startup(),a._onShow()):(a=m.config.modulePaths.chat+"/pages/manageClients.jsp",window.open(a+"?operator\x3d"+b+"\x26fisaSessionId\x3d"+encodeURIComponent(c)+"\x26fisaDojoRootUrl\x3d"+d,b,"menubar\x3d0,resizable\x3d1,width\x3d600,height\x3d350")))},hideChat:function(){m.query("#chatCP").style("display","none")},closeChat:function(){var a=
dijit.byId("chatCP");null!=a&&a.destroyRecursive(!1)}});t.utils=new s;ec.fisa.navigation.utils=t.utils;return s});
//@ sourceMappingURL=Utils.js.map