//>>built
define("ec/fisa/grid/FisaNonEditableGrid","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ec/fisa/grid/EnhancedGrid dijit/form/Button ec/fisa/dwr/Store ec/fisa/grid/enhanced/plugins/NePagination dojox/grid/enhanced/plugins/IndirectSelection ec/fisa/controller/Utils ec/fisa/grid/Utils ./_base".split(" "),function(e,f,h,k,l,g,m,n,p){return f("ec.fisa.grid.FisaNonEditableGrid",[g],{newButtonLabel:"",editButtonLabel:"",deleteButtonLabel:"",queryButtonLabel:"",
selectButtonLabel:"Seleccionar",block:null,entId:"",btId:"",openBtId:"",tabId:"",pageScopeId:"",keys:{},pKeyStr:"",fKeyStr:"",btPos:-1,pageLength:null,postMixInProperties:function(){this.inherited(arguments);this.pKeyStr=e.toJson(this.keys.PK);this.fKeyStr=e.toJson(this.keys.FK);this.store=new ec.fisa.dwr.Store("BtControllerDWR","viewMultivalueData",this.tabId,this.pageScopeId,[this["fisa-bt-id"],this.btId,this.entId,this.pKeyStr]);this.store.callbackScope=ec.fisa.controller.utils.getPageController(this.tabId,
this.pageScopeId);var a={newBlocked:this.block.n,editBlocked:this.block.e,deleteBlocked:this.block.d,queryBlocked:this.block.q,onNewExecute:this.execNew,onEditExecute:this.execEdit,onDeleteExecute:this.execDelete,onQueryExecute:this.execQuery},b={headerSelector:!1,width:"64px",name:this.selectButtonLabel,styles:"text-align: center;"};this.plugins?(this.plugins.fisaNePagination=a,this.plugins.indirectSelection=b):this.plugins={fisaNePagination:a,indirectSelection:b}},buildRendering:function(){this.inherited(arguments);
ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).registerTable(this)},getPostFTM:function(){return ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).model.toPlainObject()},getSelectedIndex:function(){var a=this.fisaNePagination.plugin,b=a.currentPage();null==b?b=0:b--;return b*a.currentPageSize()+this.selection.selectedIndex},execNew:function(){var a={callbackScope:this.grid,callback:this.grid.handleCB},b=ec.fisa.controller.utils.getPageController(this.grid.tabId,
this.grid.pageScopeId);dijit.byId(b.messagesPanelId).clearAllMessages();b.model.clearAllMessages();ec.fisa.widget.utils.resetFocusManager();BtControllerDWR.execNEGridNew(this.grid.openBtId,this.grid.entId,null,this.grid.btId,this.grid.pKeyStr,this.grid.fKeyStr,this.grid.btPos,this.grid.tabId,this.grid.pageScopeId,this.grid.getPostFTM(),a)},execEdit:function(){var a={callbackScope:this.grid,callback:this.grid.handleCB},b=this.grid.selection.getFirstSelected(),c=this.grid.getSelectedIndex(),d=ec.fisa.controller.utils.getPageController(this.grid.tabId,
this.grid.pageScopeId);dijit.byId(d.messagesPanelId).clearAllMessages();d.model.clearAllMessages();ec.fisa.widget.utils.resetFocusManager();BtControllerDWR.execNEGridEdit(this.grid.openBtId,this.grid.entId,b,c,this.grid.btId,this.grid.pKeyStr,this.grid.fKeyStr,this.grid.btPos,this.grid.tabId,this.grid.pageScopeId,this.grid.getPostFTM(),a)},execDelete:function(){var a={callbackScope:this.grid,callback:this.grid.handleCB},b=this.grid.selection.getFirstSelected(),c=this.grid.getSelectedIndex(),d=ec.fisa.controller.utils.getPageController(this.grid.tabId,
this.grid.pageScopeId);dijit.byId(d.messagesPanelId).clearAllMessages();d.model.clearAllMessages();ec.fisa.widget.utils.resetFocusManager();BtControllerDWR.execNEGridDelete(this.grid.openBtId,this.grid.entId,b,c,this.grid.btId,this.grid.pKeyStr,this.grid.fKeyStr,this.grid.btPos,this.grid.tabId,this.grid.pageScopeId,this.grid.getPostFTM(),a)},execQuery:function(){var a={callbackScope:this.grid,callback:this.grid.handleCB},b=this.grid.selection.getFirstSelected(),c=this.grid.getSelectedIndex(),d=ec.fisa.controller.utils.getPageController(this.grid.tabId,
this.grid.pageScopeId);dijit.byId(d.messagesPanelId).clearAllMessages();d.model.clearAllMessages();ec.fisa.widget.utils.resetFocusManager();BtControllerDWR.execNEGridQuery(this.grid.openBtId,this.grid.entId,b,c,this.grid.btId,this.grid.pKeyStr,this.grid.fKeyStr,this.grid.btPos,this.grid.tabId,this.grid.pageScopeId,this.grid.getPostFTM(),a)},handleCB:function(a){if("open"==a.wAxn){var b={};b.title=a.dialogName;b.iconClass="breadcrumbIcon";b.href=a.dialog;b.postClose=this.refresh;b.postCloseScope=this.id;
b.postCloseArgs=[this.tabId];var c=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);ec.fisa.navigation.utils.openNewBreadCrumb(b,c.breadcrumbId)}else"refresh"==a.wAxn?this.refresh():"error"==a.wAxn&&(c=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),c.updateMsgsPanel(a.aMsgs));"error"!=a.wAxn&&a.msg&&(a.wAxn="refresh",c=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),c.handleCallBackBackFieldRoutine(c.removeCurrentMRFromOutcome(a,
this)))},refresh:function(){this.setQuery(this.query,this.queryOptions)},canSort:function(a){return!1}})});
//@ sourceMappingURL=FisaNonEditableGrid.js.map