//>>built
define("ec/fisa/grid/FisaFormGrid","dojo/_base/kernel dojo/_base/declare dijit/_Widget dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ec/fisa/grid/EnhancedGrid dijit/form/Button ec/fisa/dwr/Store ec/fisa/grid/enhanced/plugins/Pagination dojox/lang/functional ec/fisa/grid/Utils dojo/dom-style dojo/on dojo/dom ec/fisa/grid/RowActions ec/fisa/controller/Utils ./_base".split(" "),function(d,e,l,m,n,f,p,q,r,s,g,c,h,k){return e("ec.fisa.grid.FisaFormGrid",[f],{_dataGridStore:null,newButtonLabel:"",
editButtonLabel:"",deleteButtonLabel:"",selectButtonLabel:"Seleccionar",block:null,tabId:"",pageScopeId:"",tabIndexField:null,entId:"",btId:"",addNewButton:null,btPos:-1,keys:{},pKeyStr:"",fKeyStr:"",model:null,complementModel:null,fisaEditableGrid:!0,fisaEditableDirectGrid:!0,hasComboInside:!1,pageLength:null,handle:null,constructor:function(){this.addNewButton=!1},postMixInProperties:function(){this.inherited(arguments);this.pKeyStr=d.toJson(this.keys.PK);this.fKeyStr=d.toJson(this.keys.FK);this.store=
new ec.fisa.dwr.Store("BtControllerDWR","viewEditableMultivalueDataDirect",this.tabId,this.pageScopeId,[this["fisa-bt-id"],this.btId,this.entId,this.pKeyStr]);this.store.onNew=this.handleNew;this.store.onSet=this.handleSet;!1===this.addNewButton&&(this.block.n=!0);var a={newBlocked:this.block.n,onNewExecute:this.execNew,tabIndexField:this.tabIndexField};this.plugins?this.plugins.fisaPagination=a:this.plugins={fisaPagination:a}},postCreate:function(){this.inherited(arguments);this.store.fisaEditableGridId=
this.id;this.hadle=h(this,"stylerow",function(a){var b=d.query("tr",a.node);this.defineTrClass(b[0],a);this.defineTrClass(b[1],a);d.query(".dojoxGridRowTable",a.node).forEach(function(a){c.set(a,"width","100%")});b=d.query(".fisaComponentGridLeftCell",a.node);b.forEach(function(a){c.set(a,"width","40%")});b=d.query(".fisaComponentGridRightCell",a.node);b.forEach(function(a){c.set(a,"width","60%")});a.customStyles="width:100%;border:none;"})},defineTrClass:function(a,b){a&&(a.className=!0==b.odd?"oddFieldBt":
"evenFieldBt")},doKeyEvent:function(a){},handleSet:function(){},handleNew:function(a,b){},execNew:function(){var a=dijit.byId(this.fisaEditableGridId),b={callbackScope:a,callback:a.handleNewCB},c=ec.fisa.controller.utils.getPageController(a.tabId,a.pageScopeId);dijit.byId(c.messagesPanelId).clearAllMessages();c.model.clearAllMessages();BtControllerDWR.execEDirectGridNew(a.entId,null,a.btId,a.pKeyStr,a.fKeyStr,a.btPos,a.tabId,a.pageScopeId,a.getPostFTM(),b)},handleNewCB:function(a){"refresh"==a.wAxn?
(null==this.model&&(this.model=[]),null==this.complementModel&&(this.complementModel=[]),g.newRowDataDirect(a,this,!1),this.refresh(),a.record&&(this.store.newItem(a.record),this.lastPage())):"error"==a.wAxn&&ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).updateMsgsPanel(a.aMsgs)},handleDeleteCB:function(a){},getPostFTM:function(){return ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId).model.toPlainObject()},refresh:function(){this.setQuery(this.query,
this.queryOptions)},canSort:function(a){return!1},_getValueAttr:function(){var a=[];null!=this.model&&d.forEach(this.model,function(b){b=b.toPlainObject();var c={};dojox.lang.functional.forIn(b,function(a,b){c[b]={value:a}});a.push(c)});return a},_setValueAttr:function(a,b,c){},startup:function(){this.inherited(arguments);this.correctWidth()},_resize:function(){this.inherited(arguments);c.set(this.viewsHeaderNode,"display","none")},destroy:function(){this.inherited(arguments);this.handle&&this.handle.remove()},
correctWidth:function(){var a=k.byId(this.id);c.set(a,"min-width","100%");c.set(a,"margin","auto");c.set(a,"width","100%");this.hideMasterViewBorders()},hideMasterViewBorders:function(){var a=d.query(".dojoxGridMasterView",this.id);c.set(a[0],"border","none");c.set(a[0],"border-bottom-left-radius","");c.set(a[0],"border-bottom-right-radius","")},_onFetchComplete:function(){this.inherited(arguments)}})});
//@ sourceMappingURL=FisaFormGrid.js.map