//>>built
define("ec/fisa/grid/FisaQtGrid","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/connect dijit/_Widget dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ec/fisa/grid/EnhancedGrid dijit/form/Button ec/fisa/dwr/Store ec/fisa/grid/enhanced/plugins/QtPagination dojox/grid/enhanced/plugins/IndirectSelection ec/fisa/controller/custom/QtController dojo/topic dojo/dom dojo/dom-style dojo/dom-geometry ./_base".split(" "),function(g,q,h,v,w,x,y,r,z,A,B,C,D,E,s,d,t){return q("ec.fisa.grid.FisaQtGrid",
[r],{_dataGridStore:null,execButtonLabel:"Ejecutar",selectButtonLabel:"Seleccionar",closeButtonLabel:"Cerrar",tabId:"",pageScopeId:"",qtId:"",actions:null,islov:!1,parentFisaTabId:"",parentFisaPageScopeId:"",parentBtId:"",parentFieldId:"",pageLength:null,parentType:"",parentWidgetId:"",hasSelectionActions:!1,hasSelection:!1,hideQTGridIfNoResultsFound:!1,hideQTPortletIfNoResultsFound:!1,isFinalUser:null,showPagination:!0,realIndexSelectedArray:null,lovInfoMode:!1,originalValueIndex:-1,substitutionFdk:"",
postCreate:function(){this._setActionsAttr(this.actions);this.connect(this.selection,"addToSelection",this._addToSelection);this.connect(this.selection,"deselect",this._deselect);this.selection.getSelected=this._getSelected;this.realIndexSelectedArray=[];this.inherited(arguments)},canSort:function(a){var b=!1,c=this.structure[0];null!=c&&void 0!=c&&(a=ec.fisa.format.utils.absNumber(a),a-=1,this.hasSelection&&(a-=1),c=c[a],void 0!=c&&c.sortable&&(b=!0));return b},postMixInProperties:function(){this.inherited(arguments);
var a={showAddButton:!1,options:this.actions,onExecute:this._execAction,islov:this.islov,onSelect:this._returnSelectedRow,isFinalUser:this.isFinalUser},b;b=!0===this.hasSelectionActions||!0===this.islov?{headerSelector:!1,width:"105px",name:this.selectButtonLabel,styles:"text-align: center;"}:!1;"1"==this.isFinalUser&&("single"==this.selectionMode&&!0!=this.islov)&&(b=!1);!0==this.lovInfoMode&&(b=!1,a.lovInfoMode=!0,a.onClose=this._onClose);this.keepSelection=!0;a.indirectSelectionVar=b;this.hasSelection=
!1!==b;this.plugins?(this.showPagination&&(this.plugins.fisaQtPagination=a),this.plugins.indirectSelection=b):this.plugins=this.showPagination?{fisaQtPagination:a,indirectSelection:b}:{indirectSelection:b};this.store=new ec.fisa.dwr.Store("QtControllerDWR","viewData",this.tabId,this.qtId,g.hitch(this,this._defineAditionalParameters),null);this.store.callbackScope=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId)},startup:function(){this.query=ec.fisa.controller.utils.getPageController(this.tabId,
this.pageScopeId).model.toPlainObject();this.correctWidth()},_getSelected:function(){for(var a=[],b=0,c=this.grid.realIndexSelectedArray.length;b<c;b++)this.grid.realIndexSelectedArray[b]&&a.push(b);return a},_deselect:function(a){a=ec.fisa.grid.utils.obtainInitialViewableMrIndex(this)+parseInt(a,10);this.realIndexSelectedArray[a]=!1},_addToSelection:function(a){"single"==this.selectionMode&&(this.realIndexSelectedArray=[]);a=ec.fisa.grid.utils.obtainInitialViewableMrIndex(this)+parseInt(a);this.realIndexSelectedArray[a]=
!0},correctWidth:function(){var a=s.byId(this.id),b=d.getComputedStyle(a),c=d.get(a,"width"),e=d.get(a,"height"),c={w:parseInt(c,10)-2,h:e};t.setContentSize(a,c,b)},_execAction:function(){this.grid.executeAction(this.grid.qtId,this.select.get("value"))},_returnSelectedRow:function(){var a=this.grid.selection.getSelected();if(0<a.length){var b=this.grid.parentFisaTabId,c=this.grid.parentBtId,e=this.grid.parentFieldId,k=this.grid.parentType,p=this.grid.parentFisaPageScopeId,f=ec.fisa.controller.utils.getPageController(b,
p),u=f.btActionMode,l=ec.fisa.controller.utils.getPageController(this.grid.tabId,this.grid.pageScopeId),l={callbackScope:this.grid,callback:this.grid._getSelectedRowCallback,errorHandler:g.hitch(l,l.errorHandler)},d=null,h=null,n=f.model.toPlainObject(),m=null,m=this.grid.parentWidgetId?dijit.byId(this.grid.parentWidgetId):f.getComponent(c,e);f instanceof ec.fisa.controller.custom.QtController&&(h=n,n=null,d=this["action-lov"]);f.clearPanelMessage();f=null;m.parentEditableGrid&&(f=m.entityMrId);QtControllerDWR.getSelectedRow(this.grid.tabId,
this.grid.pageScopeId,b,p,this.grid.qtId,a[0],c,e,k,u,h,n,d,f,m.hasFieldRoutineOrPolicy,l)}},_getSelectedRowCallback:function(a){var b=dijit.byId(this.parentWidgetId);if(!0===b.parentEditableGrid){var c=dijit.byId(b.gridId),e=ec.fisa.controller.utils.getPageController(this.parentFisaTabId,this.parentFisaPageScopeId),k=this.parentFieldId,e=e.lovData[this.parentBtId][k],d=null,f=null;!0==c.fisaEditableDirectGrid?(d=c.model[b.gridRealRowIndex],f=c.complementModel[b.gridRealRowIndex]):(d=c.model,f=c.complementModel);
g.forEach(e.output,function(b,c){d.setValue([b[0]],a.selectedRow[b[1]],!1)},this);g.forEach(e.complement,function(b,c){f.setValue([k+"--CMPLMNT"],a.selectedRow[b[0]],!1)},this)}b._executeAutoLovCallback(a);dijit.byId(this.parentBtId+"_"+this.parentFieldId+"_fisaLov").closeF()},_onClose:function(){dijit.byId(this.grid.parentBtId+"_"+this.grid.parentFieldId+"_fisaLov").closeF()},_setActionsAttr:function(a){a&&h.isString(a)&&(g.deprecated("ec.fisa.grid.FisaQtGrid.set('actions', 'objVar')","use dojox.grid._Grid.set('actions', objVar) instead",
"2.0"),a=h.getObject(a));this.actions=a},setActions:function(a){g.deprecated("ec.fisa.grid.FisaQtGrid.setActions(obj)","use dojox.grid._Grid.set('actions', obj) instead.","2.0");this._setActionsAttr(a)},executeAction:function(a,b){},_storeLayerFetch:function(a){var b=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);b.hasToClearMsgs&&b.messagesPanelId&&b.clearPanelMessage();this.inherited(arguments)},sort:function(){this.query.sortRequested="1";this.inherited(arguments)},_onFetchComplete:function(a,
b){this.inherited(arguments);if(!0==this.hideQTGridIfNoResultsFound&&0==b._totalMatchedItems){var c=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);c.unDisplayQTGrid();c.unDisplayMessagesPanel()}!0==this.hideQTPortletIfNoResultsFound?0<b._totalMatchedItems?(c=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),c.makeQTPortletVisible()):(c=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId),c.unDisplayQTPortlet()):(c=ec.fisa.controller.utils.getPageController(this.tabId,
this.pageScopeId),c.makeQTPortletVisible());if("single"==this.selectionMode||!0===this.isSearchRequested)delete this.isSearchRequested,null!=this.selection&&this.selection.deselectAll&&this.selection.deselectAll(),this.realIndexSelectedArray=[];"multiple"==this.selectionMode&&this.preSelect(a)},showFooterMessage:function(a){this._messagesId&&(g.byId(this._messagesId).innerHTML=a)},preSelect:function(a){for(var b=this.structure[0].length,c=0;c<=a.length-1;c++){var e=this.getItemIndex(a[c]),d=this.getItem(e),
d=this.store.getValue(d,b+"");if("boolean"==typeof d)this.selection.setSelected(e,d);else break}},_getBySelectionStatus:function(a){for(var b=[],c=0,d=this.realIndexSelectedArray.length;c<d;c++)this.realIndexSelectedArray[c]==a&&b.push(c);return b},_defineAditionalParameters:function(){var a=[];a.push(this.pageScopeId);if("multiple"==this.selectionMode){var b=this._getBySelectionStatus(!1);b&&a.push(b.toString());(b=this._getBySelectionStatus(!0))&&a.push(b.toString())}return a}})});
//@ sourceMappingURL=FisaQtGrid.js.map