//>>built
require({cache:{"url:ec/fisa/grid/templates/RowActionsDirect.html":'\x3ctable border\x3d"0" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\n\t\x3ctbody\x3e\n\t\t\x3ctr\x3e\n\t\t\t\x3ctd\x3e\n\t\t\t\t\x3cdiv id\x3d"${id}_delete" data-dojo-attach-point\x3d"_deleteComponent"\n\t\t\t\t data-dojo-type\x3d"dojox.form.BusyButton" iconClass\x3d"imgDelete" tabIndex\x3d"${_tabIndex}"\n\t\t\t\t  baseClass\x3d"fisaGridButton" showLabel\x3d"false" title\x3d"${delete_title}"\x3e\x3c/div\x3e\n\t\t\t\x3c/td\x3e\n\t\t\x3c/tr\x3e\n\t\x3c/tbody\x3e\n\x3c/table\x3e'}});
define("ec/fisa/grid/RowActionsDirect","dijit/_Widget dijit/_Templated dojo/_base/declare dojo/text!./templates/RowActionsDirect.html dojo/dom-style dojo/html dojo/on dojo/_base/connect dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ec/fisa/controller/Utils dojox/form/BusyButton".split(" "),function(l,m,n,p,s,t,u,g,q,r){return n("ec.fisa.grid.RowActionsDirect",[l,m,q,r],{widgetsInTemplate:!0,_deleteComponent:null,data:null,rowIndex:null,viewRowIndex:null,tabId:null,gridId:null,pageScopeId:null,
editBlocked:!1,deleteBlocked:!1,actionMode:"",delete_title:"",deleteHandle:null,tabIndex:null,_tabIndex:0,templateString:p,constructor:function(){},postMixInProperties:function(){this.inherited(arguments);null!=this.tabIndex&&(this._tabIndex=this.tabIndex)},postCreate:function(){this.inherited(arguments);this.deleteHandle=this.connect(this._deleteComponent,"onClick",this._onClickDelete);this._deleteComponent.fautoexec=!0;this.changeBehavior()},changeBehavior:function(){var a=this.data%10;4==a?this._deleteComponent.domNode.style.display=
this.deleteBlocked?"none":"":5==a?this._deleteComponent.domNode.style.display="block":6==a?(this.hideAllButtons(),this._addComponent.domNode.style.display=""):7==a?(this.hideAllButtons(),this._editComponent.domNode.style.display="",g.disconnect(this.editHandle)):8==a?(this.hideAllButtons(),this._deleteComponent.domNode.style.display="",g.disconnect(this.deleteHandle)):this._deleteComponent.domNode.style.display="none"},hideAllButtons:function(){this._deleteComponent.domNode.style.display="none"},
_onClickDelete:function(){var a=dijit.byId(this.gridId);1==a.pageLength-(a.pageLength*a.getTotalPageNum()-a.getTotalRowCount())&&(a.doLastPage=!0);null!=a.model&&null!=a.model[this.rowIndex]&&this._execAction(BtControllerDWR.execEDirectGridDelete,null,a,null)},_execAction:function(a,c,b,e){var h=b.getItem(this.rowIndex),k={callbackScope:this,callback:this._handleEditResponse},f=ec.fisa.controller.utils.getPageController(b.tabId,b.pageScopeId);f.clearPanelMessage();f=f.model.toPlainObject();null==
e?a(b.entId,h,this.rowIndex,this.viewRowIndex,b.btId,f,this.actionMode,b.pKeyStr,b.fKeyStr,b.btPos,b.tabId,b.pageScopeId,c,k):a(b.entId,h,this.rowIndex,this.viewRowIndex,b.btId,f,this.actionMode,b.pKeyStr,b.fKeyStr,b.btPos,b.tabId,b.pageScopeId,c,e,k)},_handleEditResponse:function(a){var c=dijit.byId(this.gridId);if("delete"==a.wAxn){if(void 0!=a.multiregisterSize&&null!=a.multiregisterSize){var b=c.getItem(this.viewRowIndex);if(null!=c.store.getEntryById(b)&&(b=c.store.getEntryById(b).data,void 0!=
b&&null!=b)){var c=dijit.byId(this.gridId),e=ec.fisa.controller.utils.getPageController(c.tabId,c.pageScopeId);dojox.lang.functional.forIn(b,function(a,b){if(void 0!=this.selectIdMap&&null!=this.selectIdMap){var c=this.rowActionScope.rowIndex;if(void 0!=this.selectIdMap[b+"|"+c]){delete this.selectIdMap[b+"|"+c];for(var d=c+1;d<this.multiregisterSize;d++){var e=this.selectIdMap[b+"|"+d];void 0!=e&&null!=e&&(this.selectIdMap[b+"|"+(d-1)]=e)}d=this.multiregisterSize-1;delete this.selectIdMap[b+"|"+
d]}}if(void 0!=this.btSelectDataMap&&null!=this.btSelectDataMap&&void 0!=this.btSelectDataMap[b+"|"+c]){delete this.btSelectDataMap[b+"|"+c];for(d=c+1;d<this.multiregisterSize;d++)c=this.btSelectDataMap[b+"|"+d],void 0!=c&&null!=c&&(this.btSelectDataMap[b+"|"+(d-1)]=c);d=this.multiregisterSize-1;delete this.btSelectDataMap[b+"|"+d]}},{rowActionScope:this,selectIdMap:e.selectIdMap,multiregisterSize:a.multiregisterSize,btSelectDataMap:e.selectDataMap[c.btId]})}}c.model.splice(this.rowIndex,1);c.refresh()}else"error"==
a.wAxn&&ec.fisa.controller.utils.getPageController(a.FISATabId,a.FisaPageScopeId).updateMsgsPanel(a.aMsgs)},activateComponents:function(){this.activateCmp(this._deleteComponent)},activateCmp:function(a){"none"!=a.domNode.style.display&&a.cancel()},_getTabIdAttr:function(){return this.tabId},_setTabIdAttr:function(a){this.tabId=a},_getPageScopeIdAttr:function(){return this.pageScopeId},_setPageScopeIdAttr:function(a){this.pageScopeId=a},removeCurrentMRFromOutcome:function(a,c){null!=a.msg&&(a.msg[c.btId]&&
a.msg[c.btId][c.entId])&&delete a.msg[c.btId][c.entId];return a}})});
//@ sourceMappingURL=RowActionsDirect.js.map