//>>built
define("ec/fisa/controller/tsc/notification/NotificationAdditionalTransactionController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/controller/custom/CustomBtController ec/fisa/format/Utils ec/fisa/navigation/Utils dojo/dom-construct dojox/mvc dojox/mvc/StatefulModel ec/fisa/mvc/StatefulModel dojo/dom-style ec/fisa/grid/EnhancedGrid dojo/data/ItemFileWriteStore dijit/tree/ForestStoreModel dojox/grid/TreeGrid dijit/form/CheckBox ec/fisa/widget/tsc/MixedCheckBox ec/fisa/dwr/Store dojox/grid/EnhancedGrid ec/fisa/grid/enhanced/plugins/Pagination dojox/lang/functional ec/fisa/dwr/proxy/tsc/NotificationAdditionalTransactionControllerDWR".split(" "),
function(g,h,q,r,n,s,t,k,u,v,p,w,l,m){return h("ec.fisa.controller.tsc.NotificationAdditionalTransactionController",n,{tabId:null,pageScopeId:null,model:null,modelDestinatario:null,data:{},accountAccessDataGrid:null,treeGridPrivileges:null,treegridId:null,breadcrumbId:null,icons:null,labelsData:null,requiredFieldMessage:null,priorityId:null,notificationMeansList:null,meansDataGrid:null,listUserDataGrid:null,receiverData:null,roleId:null,roleName:null,destPanelId:null,selectUsers:null,newNotificationMeansList:null,
additionalDataGridId:null,additionalDataGridIdCm:null,additionalDataStore:null,deletedItems:null,lastIdNumber:null,emailRegex:null,numberRegex:null,messagesPanelIdCm:null,idAdditionalDlg:null,constructor:function(a,b,c){this.setLabelsData(this.initLabels);this.icons=c.icons;this.deletedItems=[];this.emailRegex="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";this.numberRegex="^[0-9]+$";void 0==c.aMsgs&&(this.model={},this.modelDestinatario={},this.init(c))},
init:function(a){this.priorityId=a.priorityId;this.notificationMeansList=a.notificationMeansList;this.receiverData=a.receiverData;this.selectUsers=a.selectUsers;delete a.priorityId;delete a.notificationMeansList;delete a.receiverData;delete a.selectUsers;this.data=a;this.model=dojox.mvc.newStatefulModel({data:{}});this.modelDestinatario=new p({data:{}})},handleWindowAction:function(a){dijit.byId(this.messagesPanelId).clearAllMessages();if("cnfrm"==a.wAxn)ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(a.confirmationDialogTitle,
a.aMsgs,this.breadcrumbId,this.tabId,this.pageId,null,null,!1);else if(void 0!=a.aMsgs&&"20000"==a.aMsgs[0].level.level||void 0!=a.wAxn&&"close"==a.wAxn)this.updateMsgsPanel(a.aMsgs),ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId)},bindToModel:function(a,b,c){var d=this.data[b];if(void 0===d||null==d)d="";d=new dojox.mvc.StatefulModel({data:d});this.model.add(b,d);a.set("ref",this.model[b]);a.set("disabled",c)},processValue:function(a,b){},setLabelsData:function(a){this.labelsData=
a},validateBtInfo:function(a){this.clearPanelMessage();var b="",c=dijit.byId(this.additionalDataGridId),d=g.fromJson(c.store._getNewFileContentString()).items,e=!1;g.some(d,function(a){if(null==a.name||void 0==a.name||""===a.name)b=c.labels.emptyName,e=!0;if(null==a.tipo||void 0==a.tipo||!0===ec.fisa.format.utils.isObjectEmpty(a.tipo))b=c.labels.emptyCm,e=!0;a.tipo=g.toJson(a.tipo)},this);var f=this.generateMsg(b,"",4E4);!1===e?(a.wAxn="cnfrm",a.items=d):(a.aMsgs=f,a.wAxn="error");return a},save:function(a){var b=
{callbackScope:this};b.callback=this.handleWindowAction;b.errorHandler=g.hitch(this,this.errorHandler);NotificationAdditionalTransactionControllerDWR.saveAdditionalPersonNotifiableInformation(this.tabId,this.pageScopeId,this._addNotificationValData(),a.items,b)},deleteRoleInformation:function(){(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:this.labelsData.yesLabel,cancelDialogLabel:this.labelsData.noLabel,title:this.labelsData.deleteMenuLabel,content:this.labelsData.deleteWarnLabel,acceptAction:g.hitch(this,
function(){var a={callbackScope:this};a.callback=this.handleWindowAction;a.errorHandler=this.errorHandler;NotificationAdditionalTransactionControllerDWR.deleteUserRoleInfo(this.tabId,this.pageScopeId,a)})})).show()},cancel:function(){this.handleWindowAction({wAxn:"close"})},setMessagesPanelContactMedia:function(a){this.inherited(arguments);this.messagesPanelIdCm=a.id},addParamToModel:function(a){var b=a["bt-id"],c=a["field-id"],d=null;this.data&&(this.data[b]&&this.data[b].dataMessage)&&(d=this.data[b].dataMessage.fields[c]);
null==d?(d={value:"",complement:null},a._fStarted=!0):null==d.value&&(a._fStarted=!0);this.disabled&&(a.set("disabled",this.disabled),d.enabled=!1);if("EFP-MCN-CHM-NOTIFICATION"===c){var e=[],f;for(f in this.notificationMeansList)"AGENDA"!=this.notificationMeansList[f].value&&e.push({label:this.notificationMeansList[f].label,selected:this.notificationMeansList[f].selected,value:this.notificationMeansList[f].value});d.value=[this.receiverData,e,this.priorityId,!0]}else d.value="";this.notificationId=
a.id;this.modelDestinatario.contains(b)?this.modelDestinatario.contains([b,"dataMessage","fields",c])&&this.modelDestinatario.setValue([b,"dataMessage","fields",c,"value"],d.value):(this.modelDestinatario.appendObject([b,"dataMessage","fields",c,"value"],d.value,a.id,"value",null,!1),e=null,void 0!=d.enabled&&(e=d.enabled),this.modelDestinatario.appendObject([b,"dataMessage","fields",c,"enabled"],e,a.id,"enabled",null,!1),a.hasCompl&&this.modelDestinatario.appendObject([b,"dataMessage","fields",c,
"complement"],d.complement,a.id,"complement",null,!1))},containsFieldModel:function(a,b){return this.modelDestinatario.contains([a,"dataMessage","fields",b,"value"])},getFieldModel:function(a,b){return this.modelDestinatario.getValue([a,"dataMessage","fields",b,"value"])},setFieldModelValue:function(a,b,c){this.modelDestinatario.setValue([a,"dataMessage","fields",b,"value"],c)},setFieldModelEnabled:function(a,b,c){this.modelDestinatario.setValue([a,"dataMessage","fields",b,"enabled"],c)},setFieldModelComplement:function(a,
b,c){this.modelDestinatario.setValue([a,"dataMessage","fields",b,"complement"],c)},getFieldModelComplement:function(a,b){return this.modelDestinatario.getValue([a,"dataMessage","fields",b,"complement"])},cargarTareasListUser:function(a,b){this.clearPanelMessage();var c=null,c=new ec.fisa.dwr.Store("NotificationTransactionControllerDWR","viewDataUsers",this.tabId,this.pageScopeId,[],null);this.listUserDataGrid.setStore(c);g.forEach(this.selectUsers,function(a,b){this.listUserDataGrid.selection.addToSelection(this.listUserDataGrid.getItemIndex(a))},
this);this.listUserDataGrid.render()},initDataGrid:function(a,b){var c=[{noscroll:!0,cells:[{name:b.userName,field:"name",width:"auto",formatter:function(a,b,c){return ec.fisa.format.utils.formatterAdditionalUsersName(a,b,c)}},{name:b.contactMedia,field:"tipo",width:"auto",formatter:function(a,b,c){return ec.fisa.format.utils.formatterAdditionalUsersLink(a,b,c)}},{name:b.options,field:"",width:"90px",styles:"text-align: center;",formatter:function(a,b,c){return ec.fisa.format.utils.formatterAdditionalUsersOptions(a,
b,c)}}]}],d={identifier:"id",items:this.receiverData};this.lastIdNumber=this.receiverData.length;this.additionalDataStore=d=new m({data:d,hierarchical:!1});var e=k.create("div",null,a.domNode),f={onNewExecute:g.hitch(this,this.execNew),hidePaginationNumber:!0},c=new l({store:d,structure:c,autoHeight:!0,style:{width:"50%",margin:"auto"},newButtonLabel:b.labelNew,selectable:"true",fisaEditableGrid:!0,plugins:{fisaPagination:f}},e);c.doKeyEvent=function(a){};c.tabId=this.tabId;c.labels=b;c.pageScopeId=
this.pageScopeId;c.breadCrumbId=this.breadcrumbId;c.startup();this.additionalDataGridId=c.id},execNew:function(){this.additionalDataStore.newItem({id:this.lastIdNumber,recipientId:null,tipo:{},name:""});this.lastIdNumber++},initDataGridContactMedia:function(a,b){var c=[{name:b.contactMedia,field:"contactMedia",width:"auto",editable:!1},{name:b.labelData,field:"name",width:"200px",editable:!1,formatter:function(a,b,c){return ec.fisa.format.utils.formatterAdditionalCmData(a,b,c)}}],d=dijit.byId(this.additionalDataGridId),
d=d.selectedRowGridItem.tipo[0],e=[],f=0;g.forEach(this.notificationMeansList,function(a){-1!=a.value&&(a={id:f,name:"",contactMedia:a.value},e.push(a),f++)});dojox.lang.functional.forIn(d,function(a,b){g.forEach(e,function(c){c.contactMedia==b&&(c.name=a)})},this);var d=new m({data:{identifier:"id",items:e},hierarchical:!1}),h=k.create("div",null,a.domNode),d=new l({store:d,structure:c,autoHeight:!0,selectable:"true",fisaEditableGrid:!0},h);d.tabId=this.tabId;d.labels=b;d.pageScopeId=this.pageScopeId;
d.numberRegex=this.numberRegex;d.emailRegex=this.emailRegex;d.startup();this.additionalDataGridIdCm=d.id},cancelUserContactMedia:function(){this.clearPanelMessageCm();dijit.byId(this.idAdditionalDlg).destroy()},saveUserContactMedia:function(){if(!1!=dijit.byId(this.messagesPanelIdCm).messagesPanelEmpty()){this.clearPanelMessageCm();var a=dijit.byId(this.additionalDataGridIdCm),a=g.fromJson(a.store._getNewFileContentString()).items,b={};g.forEach(a,function(a){null!=a.name&&(void 0!=a.name&&""!=a.name)&&
(b[a.contactMedia]=a.name)});dijit.byId(this.additionalDataGridId).selectedRowGridItem.tipo[0]=b;dijit.byId(this.idAdditionalDlg).destroy()}},updateMsgsPanelCm:function(a){if(a){var b=dijit.byId(this.messagesPanelIdCm);b&&b.update(a,this.isComponentMsg,this.addComponentMsg,this)}},clearPanelMessageCm:function(){this.messagesPanelIdCm&&dijit.byId(this.messagesPanelIdCm).clearAllMessages()}})});
//@ sourceMappingURL=NotificationAdditionalTransactionController.js.map