//>>built
define("ec/fisa/controller/tsc/notification/StatementAccountController","dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/controller/custom/CustomBtController dojo/dom-construct dijit/form/CheckBox dojo/dom-geometry dojo/dom-style ec/fisa/widget/SANotificationGridUser ec/fisa/format/Utils ec/fisa/navigation/Utils ./_base".split(" "),function(l,s,t,p,q,u,r,e){return l("ec.fisa.controller.tsc.notification.StatementAccountController",p,{listUserDataGridId:null,listProdDataGridId:null,
selectedUsers:null,selectedProds:null,breadcrumbId:null,icons:null,labelsData:null,additionalSucessCheckBoxList:[],additionalUnSucessCheckBoxList:[],urlToAdditionalUserPage:null,disableVal:null,breadCrumbAdditionalUser:null,parentBtId:null,additionalUserGridId:null,productSelectValues:null,contentPanelProperties:null,priorityId:null,formatListData:null,selectedFormat:null,listSelectFormat:{},frecuencyListData:null,selectedFrecuency:null,listSelectFrecuency:{},constructor:function(a,b,c){this.setLabelsData(this.initLabels);
void 0==c.aMsgs&&(this.selectedUsers=c.selectedUsers,this.selectedProds=c.selectedProds,this.disableVal=c.disableVal,this.parentBtId=c.parentBtId,this.formatListData=c.formatListData,this.selectedFormat=c.selectedFormat,this.frecuencyListData=c.frecuencyListData,this.selectedFrecuency=c.selectedFrecuency,this.priorityId=c.priorityId);delete c.selectedUsers;delete c.selectedProds;delete c.disableVal;delete c.parentBtId;delete c.formatListData;delete c.selectedFormat;delete c.priorityId;delete c.frecuencyListData;
delete c.selectedFrecuency},getSelectedUsers:function(){return this.selectedUsers},getSelectedProds:function(){return this.selectedProds},setListUserDataGridId:function(a){this.listUserDataGridId=a.id},setListProdDataGridId:function(a){this.listProdDataGridId=a.id},_getSelectedUsers:function(){return this._getSelectedValues(this.listUserDataGridId)},_getSelectedProducts:function(){return this._getSelectedValues(this.listProdDataGridId)},_getSelectedProductsLine:function(){return this._getSelectedValuesProducts(this.listProdDataGridId)},
_getSelectedValuesProducts:function(a){a=dijit.byId(gridId);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],dojo.forEach(a.fisaChecks,function(a){dijit.byId(a).checked&&b.push(null)},this));return b},_getSelectedValues:function(a){a=dijit.byId(a);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],dojo.forEach(a.fisaChecks,function(a){a=dijit.byId(a);a.checked&&b.push(a.fval)},this));return b},_getSelectedAllProducts:function(){return this._getAllValues(this.listProdDataGridId)},_getAllValues:function(a){a=
dijit.byId(a);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],dojo.forEach(a.fisaChecks,function(a){a=dijit.byId(a);b.push(a.fval)},this));return b},validateBtInfo:function(a){this.clearPanelMessage();for(var b="",c=!0,d=this._getSelectedProducts(),h=dijit.byId(this.listProdDataGridId),e={},k={},f=0;f<d.length;f++){var g=h.getItemIndex(d[f]),m=dijit.byId(h.fisaSelectFormat[g]),n=dijit.byId(h.fisaSelectFrecuency[g]);if("-1"==m.get("value")){c=!1;b=this.labelsData.warning1;break}else e[d[f]]=m.get("value");
if("-1"==n.get("value")){c=!1;b=this.labelsData.warning1;break}else k[d[f]]=n.get("value");if(h.fisaChecksValues[g]!=h.fisaUserSelect[g]){c=!1;b=this.labelsData.warning2;break}}b=this.generateMsg(b,"",4E4);this.listSelectFormat=e;this.listSelectFrecuency=k;c?a.wAxn="cnfrm":(a.aMsgs=b,a.wAxn="error");return a},cancel:function(){EventActionDWR.executeCommandButtonCancel(this.tabId,this.pageScopeId,"",{callbackScope:this,callback:this.handleCancelAction})},remove:function(a){},handleSaveAction:function(a){"cnfrm"==
a.wAxn?this.handleConfirmationBt(a):"error"==a.wAxn&&this.updateMsgsPanel(a.aMsgs)},handleAdditionalSaveAction:function(a){this.contentPanelProperties.destroy()},handleConfirmationBt:function(a){var b=a.respBtLabels[0],c=a.aMsgs,d=a.postBtId,e=a.pBtId,l=a.postBtIdDataKey,k=a.principalPostBtIdDataKey,f=a.parentBtInAuthorization,g=a.showReportModule;a=a.showReportAuto;dijit.byId(this.messagesPanelId).clearAllMessages();null==d?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(b,c,this.breadcrumbId,
this.tabId,this.pageScopeId,this.btId,this.btActionMode,this.isSequence,g,a):(b=dijit.byId(this.breadcrumbId),ec.fisa.navigation.utils.showPostBtBreadCrumb(b.params.title,c,this.tabId,this.pageScopeId,d,e,this.btContentPaneId,l,k,this.isSequence,g,a,f,!1))},setLabelsData:function(a){this.labelsData=a},setUrlToAdditionalUserPage:function(a){this.urlToAdditionalUserPage=a},openAdditionalUsersSelection:function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);a.productSelectValues=
a._getSelectedProducts();var b={},c=ec.fisa.controller.utils.getGlobalModalSize(0.8);b.title=a.labelsData.addUsersTo;b.href=dojo.config.fisaContextPath+this.urlToAdditionalUserPage;b.ioArgs={content:{FISATabId:this.tabId,FISAParentPageScopeId:this.pageScopeId,isSelect:this.rowData.checked,rowId:this.rowData.fval,componentId:this.parentBtId,height:c.h}};b.ioMethod=dojo.xhrPost;b.style="height:"+c.h+"px;width:700px;overflow: auto;";b.splitter="true";a.contentPanelProperties=new dojox.widget.DialogSimple(b);
a.contentPanelProperties.resizeContainerNode=this.resizeNode;a.contentPanelProperties.show();a.resizeNode(a.contentPanelProperties,c)},resizeNode:function(a,b){var c=r.getMarginBox(a.titleNode);e.set(a.containerNode,"height",b.h-c.h-4*c.t+"px");e.set(a.containerNode,"display","block");e.set(a.containerNode,"overflowY","auto");e.set(a.containerNode,"overflowX","auto")},initAdditionalUsersGrid:function(a,b,c,d){this.additionalSucessCheckBoxList=[];this.additionalUnSucessCheckBoxList=[];b=new ec.fisa.dwr.Store("StatementAccountControllerDWR",
"viewDataUsers",this.tabId,this.pageScopeId,[b,c],null);a=q.create("div",null,a.domNode);a=new ec.fisa.widget.SANotificationGridUser({style:"width: 100%;",autoWidth:"true",tabId:this.tabId,pageScopeId:this.pageScopeId,onlyRead:this.disableVal,label:this.labelsData.addUserLabel,labelRole:this.labelsData.labelRole,selectButtonLabel:this.labelsData.selectButtonLabel,selectProducts:this.productSelectValues,store:b},a);this.additionalUserGridId=a.id;a.startup()},cancelAdditionalUser:function(a,b,c){dijit.byId(this.listProdDataGridId);
this._getSelectedValues(a);this.contentPanelProperties.destroy()},saveAdditionalUser:function(a,b,c){b=dijit.byId(this.listProdDataGridId);a=dijit.byId(this.additionalUserGridId);a=this._getSelectedValues(a.id);var d=b.getItemIndex(c);b.fisaUserSelect[d]=0!=a.length?!0:!1;b=dijit.byId(b.fisaChecks[d]).fvalLine;d={callbackScope:this};d.callback=dojo.hitch(this,this.handleAdditionalSaveAction);d.errorHandler=this.errorHandler;StatementAccountControllerDWR.saveUserProductSelected(this.tabId,this.pageScopeId,
a,c,b,d)},openWarning:function(){this.clearPanelMessage();this.contentPanelProperties=new dojox.widget.DialogSimple({title:"Warning",href:"./static/tsc/notification/fragment/accountUserWarning.jsp",ioArgs:{content:{FISATabId:this.tabId,FisaPageScopeId:this.pageScopeId}},ioMethod:dojo.xhrPost});this.contentPanelProperties.show()},actionWarning:function(a){this.clearPanelMessage();this.contentPanelProperties.destroy();"true"===a&&this.save()},save:function(a){a=this._getSelectedProducts();var b={callbackScope:this,
callback:this.handleSaveAction};StatementAccountControllerDWR.save(this._addNotificationValData(),this._getSelectedAllProducts(),a,this.listSelectFormat,this.listSelectFrecuency,this.tabId,this.pageScopeId,b)}})});
//@ sourceMappingURL=StatementAccountController.js.map