//>>built
define("ec/fisa/menu/Utils","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/window dojo/dom-construct dojo/dom-style dojo/dom-geometry dojo/on ec/fisa/menu/_base ec/fisa/layout/ContentPane dijit/layout/AccordionContainer dijit/layout/BorderContainer ec/fisa/widget/Link ec/fisa/widget/VerticalMenuLink dojox/fx dojo/fx dojo/aspect ec/fisa/widget/IFrame ec/fisa/controller/Utils dijit/PopupMenuBarItem dijit/MenuBar dijit/MenuItem".split(" "),function(f,s,y,z,m,q,u,t,v,C,A,B,r,D,p,w,E){s=s("ec.fisa.menu.Utils",
null,{dynamicMenuCurrentLevel:0,levelsItemMap:{},levelBackParentItem:{},updatePreferentialOptions:function(a){var b=f.byId("menuOptions"),d=[];f.forEach(b.children,function(a){var b=f.getAttr(a,"fisa-link-id");null!=b&&(dijit.byId(b).destroy(!1),d.push(a))},this);for(var c=0;c<d.length;c++){var e=d[c];d[c]=null;m.destroy(e)}null!=a&&null!=a.options&&(f.forEach(a.options,function(a,c){var d=m.create("div",{"class":"userMenuContainerMiddleItem"},b,c),e=m.create("table",{cellpadding:"0",cellspacing:"0",
border:"0"},d),n=m.create("tbody",{},e),e=null,e=m.create("tr",{},n),n=null,x=m.create("td",{},e),n=m.create("td",{},e),e=null;m.create("div",{},x);x=null;e=m.create("div",{},n);n=null;e=new r({"class":"userMenuContainerMiddleItemLink",label:a.label},e);f.setAttr(d,"fisa-link-id",e.id);e.item=a;a.name=a.label;e.connect(e,"onClick",function(){ec.fisa.menu.utils.menuTreeOnClick(this.item,{})})},this),b=null)},updateLocalCurrency:function(a){null!=a&&(f.config.fisaDefaultCurrency=a)},updateRoles:function(a,
b){if(null==b){var d=dijit.byId("selectCompany");a+=d.get("value")}f.xhrGet({url:a,preventCache:!0,handleAs:"json",load:this.updateRolesData,error:function(a){window.location.replace(f.config.fisaContextPath+"/duplicate_session_error.jsp?fisaLanguajeParam\x3d"+f.config.fisaLanguajeParam)}})},updateRolesData:function(a){var b=dijit.byId("selectRole"),d=b.options.length;ec.fisa.menu.utils.updatePreferentialOptions(a.prefs);ec.fisa.menu.utils.updateLocalCurrency(a.prefs);f.forEach(a.items,function(c,
e){if(0==e){for(var g=!1,f=-1,l=0;l<d;l++)if(b.options[l].value==a.value){g=!0;f=l;break}g||b.addOption(c);b.set("value",c.value);for(l=g=0;l<d;l++)l==f?g++:b.removeOption(b.options[g])}else b.addOption(c)},this)},updateRolesDataMenu:function(a,b,d,c,e,g){this.updateRolesData(a);ec.fisa.menu.utils.menuLoad(b,e,!0,d);a=dijit.byId("selectRole");this._containerId=d;this._url=c;this._typeMenu=e;this._contextPath=g;setTimeout(f.hitch(a,"connect",a,"onChange",ec.fisa.menu.utils.updateMenu),1E3)},updateMenu:function(a){f.xhrGet({url:ec.fisa.menu.utils._url+
"\x26roleId\x3d"+a,preventCache:!0,handleAs:"json",load:function(a){ec.fisa.menu.utils.menuLoad(a,ec.fisa.menu.utils._typeMenu,!0,ec.fisa.menu.utils._containerId)},error:function(a){window.location.replace(f.config.fisaContextPath+"/duplicate_session_error.jsp?fisaLanguajeParam\x3d"+f.config.fisaLanguajeParam)}})},clearTabs:function(){var a=dijit.byId("tabContainer"),b=a.getChildren();f.forEach(b,function(b){0<a.getIndexOfChild(b)&&a.closeChild(b)},this)},menuLoad:function(a,b,d,c){ec.fisa.menu.utils.clearTabs();
if(d){var e=a.home;null==e&&(e={itemType:"DIRECT_LINK"});ec.fisa.menu.utils.updateHomeTab(e)}c=dijit.byId(c);var e=a.items,g=a.sort;g&&!0==g&&(e=a.items.slice(0).sort(function(a,b){return a.name<b.name?-1:a.name>b.name?1:0}));if("tree"==b){var h=dijit.byId("leftAccordion");null!=h&&h.destroyRecursive(!1);h=new A({id:"leftAccordion",name:"leftAccordion"});c.attr("content",h);f.forEach(e,function(a,b){var c=new dijit.layout.ContentPane({title:a.name,id:a.id,iconClass:"fisaTabIcon menuGroupIcon"});0!=
b&&c.connect(c,"onShow",ec.fisa.menu.utils.updateSubMenuTree);c.advChilds=a.childrenItems;h.addChild(c);0==b&&(ec.fisa.menu.utils.updateSubMenuTree.call(c),h.selectedChildWidget=c)});h.startup()}else"slide"==b?ec.fisa.menu.utils.updateNavigateMenu(e,c.id):"horizontal"==b&&ec.fisa.menu.utils.updateHorizontalMenu(e,c.id,"topMenu");d&&(ec.fisa.menu.utils.menuItems=a.items)},updateNavigateMenu:function(a,b){var d=dijit.byId("homePanel"),d=m.create("tr",{},m.create("tbody",{},m.create("table",{border:0,
cellpadding:0,cellspacing:0},d.domNode))),c=new r({region:"leading",baseClass:"backmenuWidget",labelClass:"backmenu"},m.create("div",{},m.create("td",{"class":"homePanelLeft"},d)));new r({region:"leading",labelClass:"icnhome",onClick:function(){ec.fisa.menu.utils.loadItems(b,a,c.id,!0,null,!0)}},m.create("div",{},m.create("td",{"class":"homePanelRight"},d)));d=null;ec.fisa.menu.utils.loadItems(b,a,c.id,!0,null,!0)},loadItems:function(a,b,d,c,e,g){var h=new B({gutters:!1}),l=dijit.byId(a);l.destroyDescendants(!1);
l.set("content",h);var k=dijit.byId(d);if(!1==c){var n=e.isHomeItem||c,l=ec.fisa.menu.utils.obtainLabelIdVal(e,n)[1],l=new r({region:"top",baseClass:"posmenu",label:l});h.addChild(l);!0!=k.clicked&&(k.domNode.style.display="inline-block");k.onClick=function(){k.domNode.style.display="none";k.clicked=!0;ec.fisa.menu.utils.dynamicMenuCurrentLevel-=1;0>ec.fisa.menu.utils.dynamicMenuCurrentLevel&&(ec.fisa.menu.utils.dynamicMenuCurrentLevel=0);0==ec.fisa.menu.utils.dynamicMenuCurrentLevel&&(n=!0);ec.fisa.menu.utils.backwardAnimate(a,
advChilds,d,e,n)}}else k.domNode.style.display="none",!0==g&&(ec.fisa.menu.utils.dynamicMenuCurrentLevel=0,ec.fisa.menu.utils.levelsItemMap={});!0==g&&(ec.fisa.menu.utils.levelsItemMap[ec.fisa.menu.utils.dynamicMenuCurrentLevel]=b,ec.fisa.menu.utils.levelBackParentItem[ec.fisa.menu.utils.dynamicMenuCurrentLevel]=e);f.forEach(b,function(b,e){!0==c&&(b.isHomeItem=!0);var g=ec.fisa.menu.utils.obtainLabelIdVal(b,c),g=new r({region:"top",baseClass:"menulevel",label:g[1],id:g[0],onClick:function(){ec.fisa.menu.utils.menuDynamicNavigate(a,
b,d,c)}});h.addChild(g)});h.connect(h,"startup",function(){!0===k.clicked&&(k.clicked=!1,k.domNode.style.display=!1==c?"block":"none")});h.startup()},menuDynamicNavigate:function(a,b,d,c){(c=ec.fisa.menu.utils.obtainChildrenItems(c,b))?ec.fisa.menu.utils.forwardAnimate(a,c,d,b):ec.fisa.menu.utils.loadMenuTabContainer(b)},forwardAnimate:function(a,b,d,c){var e=p.slideBy({node:a,duration:50,left:-f.position(a).w,onEnd:function(){ec.fisa.menu.utils.dynamicMenuCurrentLevel+=1;ec.fisa.menu.utils.loadItems(a,
b,d,!1,c,!0)}}),g=p.slideBy({node:a,duration:1,left:2*f.position(a).w}),h=p.slideBy({node:a,duration:200,left:0});w.chain([e,g,h]).play()},backwardAnimate:function(a,b,d,c,e){b=p.slideBy({node:a,duration:50,left:f.position(a).w,onEnd:function(){ec.fisa.menu.utils.loadItems(a,ec.fisa.menu.utils.levelsItemMap[ec.fisa.menu.utils.dynamicMenuCurrentLevel],d,e,ec.fisa.menu.utils.levelBackParentItem[ec.fisa.menu.utils.dynamicMenuCurrentLevel],!1)}});c=p.slideBy({node:a,duration:1,left:2*-f.position(a).w});
var g=p.slideBy({node:a,duration:200,left:0});w.chain([b,c,g]).play()},obtainChildrenItems:function(a,b){return advChilds=b.childrenItems},obtainLabelIdVal:function(a,b){var d="",c="",d=a.name,c=a.id;return[c,d]},updateSubMenuTree:function(){if(this.advChilds){var a=new f.store.Memory({data:this.advChilds});a.idProperty="id";var a=new f.data.ObjectStore({objectStore:a,labelProperty:"name"}),a=new dijit.tree.ForestStoreModel({store:a,rootId:"id",rootLabel:"name",childrenAttrs:["childrenItems"]}),b=
f.create("div",null,this.domNode),a=new dijit.Tree({model:a,showRoot:!1,openOnClick:!0,getLabelClass:function(a,b){var e="fisaMenuLevel",g=a.id.match(/_/g);null!=g&&0<=g.length&&(e+=g.length);return e}},b);delete this.advChilds;a.connect(a,"onClick",ec.fisa.menu.utils.menuTreeOnClick)}},closeTab:function(){var a=dijit.byId("tabContainer");if(a.getChildren()&&1==a.getChildren().length)if("inicio"!=a.getChildren()[0].id){var b=f.byId("homeIconLink");if(void 0!=b&&null!=b&&null!=b._home)ec.fisa.menu.utils.loadMenuTabContainer(b._home,
!0);else if(!0!=a.selectedChildWidget.removedTabToUpdate){b={preload:!0};b.title=f.config.fisaHomeLabel;b.closable=!0;b.nested=!0;1==f.config.fisaTabMaxNumber&&(b.title=item.name,b.closable=!1);b.id="inicio";b.onClose=ec.fisa.menu.utils.closeTab;var b=new dijit.layout.TabContainer(b),d=new dijit.layout.ContentPane({title:f.config.fisaHomeLabel,itemType:"EMPTY_TAB",closable:!0});d.onClose=function(){return ec.fisa.menu.utils.closeTab()};b.addChild(d);a.addChild(b);a.selectChild(b)}}else return!1;return!0},
addEmptyTab:function(a){var b=dijit.byId("tabContainer");if(b.getChildren().length>=f.config.fisaTabMaxNumber)return!1;a=new dijit.layout.ContentPane({title:a,itemType:"EMPTY_TAB",closable:!0});a.onClose=function(){return ec.fisa.menu.utils.closeTab()};b.addChild(a);b.selectChild(a)},addEmptyTabAllClosed:function(a){var b=dijit.byId("tabContainer");if(1<=b.getChildren().length)return!1;a=new dijit.layout.ContentPane({title:a,itemType:"EMPTY_TAB",closable:!0});a.onClose=function(){return ec.fisa.menu.utils.closeTab()};
b.addChild(a);b.selectChild(a)},verifyAgendaTab:function(a,b){for(var d=!1,c=a.getChildren(),e=c.length,g=0;g<e;g++){var f=c[g].params.fisaId;if(f&&f==b){d=!0;break}}return d},menuTreeOnClick:function(a,b){try{null!=a&&(!b||!b.isExpandable)&&ec.fisa.menu.utils.loadMenuTabContainer(a,!1)}catch(d){alert(d)}},loadMenuTabContainer:function(a,b,d,c,e){if(void 0==d||null==d)d="tabContainer";if(void 0==c||null==c)c="inicio";d=dijit.byId(d);var g=null,g=b?dijit.byId(c):d.selectedChildWidget,h=0;g&&(h=d.getIndexOfChild(g));
var l=a.fisaId;l&&this.verifyAgendaTab(d,l);var k={};k.fromPlataforma=e;k.preload=!0;e={};k.title=b?f.config.fisaHomeLabel:a.name;k.closable=!0;k.nested=!0;1==f.config.fisaTabMaxNumber&&(k.title=a.name,k.closable=!1);l&&(k.fisaId=l);b&&(k.id=c);b=null;g&&(g.onClose&&(g.removedTabToUpdate=!0,g.onClose()),d.removeChild(g),g.destroyRecursive());b=new dijit.layout.TabContainer(k);d.addChild(b,h);b.startup();b.appendable=a.notAppendable?!0:!1;d.selectChild(b);b.callObj={callbackScope:this,callback:function(){}};
b.onClose=function(){var a=this.getChildren(),b={};null!=a&&f.forEach(a,function(a){null!=a.tabId&&(""!=a.tabId&&null==b[a.tabId])&&(b[a.tabId]="",EventActionDWR.closeTab(a.tabId,this.callObj))},this);return!0!=this.fromPlataforma&&!ec.fisa.menu.utils.closeTab()?!1:!0};e.title=a.name;e.iconClass="breadcrumbIcon";e.preventCache=!0;c=null;"DIRECT_LINK"==a.itemType?(e.href=a.relatedUrl,e.href&&(c=new ec.fisa.layout.ContentPane(e))):"EXTERNAL_URL"!=a.itemType?(c="",d=!0,"BUSINESS_TEMPLATE_CUSTOMIZED"==
a.itemType?(c=f.config.fisaContextPath,c=c+"/"+a.itemType,c+="/",c+=a.relatedUrl,void 0!=a.FISATabId&&(c+="/parentFisaTabId/",c+=a.FISATabId),void 0!=a.FisaPageScopeId&&(c+="/parentFisaPageScopeId/",c+=a.FisaPageScopeId),a.hasChildren&&(c+="?SubMenuItemId\x3d"+a.realId),d=!1):"BUSINESS_TEMPLATE_CUSTOMIZED_URL"==a.itemType&&null!=a.realUrl?(c=f.config.fisaContextPath,c+=a.realUrl,d=!1):(c=f.config.fisaContextPath,c+="/",c+=a.itemType,c+="/",c+=a.relatedUrl),a.relatedParameter&&(c+="/actionMode/",c+=
a.relatedParameter),d&&(c+="/index.jsp"),a.lockInsert&&(d={},d.content={lockInsert:a.lockInsert},e.ioArgs=d),"ITEM_QUERY_TEMPLATE"==a.itemType&&null!=a.qtParameters&&(c=c+"?initialQtParamValues\x3d"+a.qtParameters),this.verifyMenuRoutine(c,e,a,b)):"EXTERNAL_URL"==a.itemType&&(e.src=a.relatedUrl,e.width="100%",e.height="100%",a.invokeClass?this._callExternalUrlMenuRoutine(e,a,b):(c=new ec.fisa.widget.IFrame(e),b.addChild(c)));a={};a.title=f.config.fisaHomeLabel;a.iconClass="breadcrumbIcon";a.isHome=
!0;a=new ec.fisa.layout.ContentPane(a);b.addChild(a,0);a.controlButton.set("disabled",!0);a.controlButton.onClick=function(){}},verifyMenuRoutine:function(a,b,d,c){d.customParam?this.callMenuRoutine(a,b,d,c):(b.href=a,a=new ec.fisa.layout.ContentPane(b),null!=a&&c.addChild(a))},callMenuRoutine:function(a,b,d,c){var e={};e.callbackScope={controller:this,newSubTabPaneArg:b,newTabPane:c};e.errorHandler=f.hitch(this,this.errorHandler);e.callback=this._callMenuRoutineCallBack;var g={};dojox.lang.functional.forIn(d,
function(a,b){g[b]=""+a});EventActionDWR.callMenuRoutine(a,g,e)},_callMenuRoutineCallBack:function(a){"refresh"==a.wAxn?(this.newSubTabPaneArg.href=a.msg,a=new ec.fisa.layout.ContentPane(this.newSubTabPaneArg),null!=a&&(f.forEach(this.newTabPane.getChildren(),f.hitch(this,function(a){this.newTabPane.removeChild(a)})),this.newTabPane.addChild(a))):"error"==a.wAxn&&ec.fisa.controller.utils.getPageController(a.FISATabId,a.FisaPageScopeId).updateMsgsPanel(a.aMsgs)},_callExternalUrlMenuRoutine:function(a,
b,d){var c={};c.callbackScope={controller:this,newSubTabPaneArg:a,newTabPane:d};c.errorHandler=f.hitch(this,this.errorHandler);c.callback=this._callExternalUrlMenuRoutineCallBack;var e={};dojox.lang.functional.forIn(b,function(a,b){e[b]=""+a});EventActionDWR.callExternalUrlRoutine(e,c)},_callExternalUrlMenuRoutineCallBack:function(a){a.goForIt&&!0===a.goForIt?(this.newSubTabPaneArg.href=a.msg,a=new ec.fisa.widget.IFrame(this.newSubTabPaneArg),null!=a&&(f.forEach(this.newTabPane.getChildren(),f.hitch(this,
function(a){this.newTabPane.removeChild(a)})),this.newTabPane.addChild(a))):(a.aMsgs&&(this.newSubTabPaneArg.href=f.config.fisaContextPath+"/pages/schedule-errors.jsp",this.newSubTabPaneArg.ioArgs={content:{SCHEDULE_ERROR_SUMMARY:encodeURIComponent(a.aMsgs[0].summary),SCHEDULE_ERROR_DETAIL:encodeURIComponent(a.aMsgs[0].summary),ERROR_LEVEL:"INFO"}},a=new ec.fisa.layout.ContentPane(this.newSubTabPaneArg),null!=a&&(f.forEach(this.newTabPane.getChildren(),f.hitch(this,function(a){this.newTabPane.removeChild(a)})),
this.newTabPane.addChild(a))),window.open(this.newSubTabPaneArg.src,"_blank"))},showHideLeftMenu:function(){ec.fisa.menu.utils.hideMenus("slidepanelleftDiv","brdCntrLeft",f.config.fisaStandbyId,!0,!0)},showHideRightMenu:function(a){ec.fisa.menu.utils.hideMenus("slidepanelrightDiv","brdCntrRight",f.config.fisaStandbyId,!1,a)},hideMenus:function(a,b,d,c,e){var g=dijit.byId(b),h={};null==g.isHidden||!1==g.isHidden?(g.prevWidth=f.position(b).w,g.isHidden=!0,e?(h=p.wipeTo({node:b,duration:2,width:1}).play(),
t(h,"End",function(){dijit.byId(d).resize();var b=f.byId(a);!0==c?b.style.left="1px":b.style.right="1px"})):(b=f.byId(b),q.set(b,"width",0),dijit.byId(d).resize())):(g.isHidden=!1,e&&(b=p.wipeTo({node:b,duration:2,width:g.prevWidth}).play(),t(b,"End",function(){dijit.byId(d).resize();var b=f.byId(a);!0==c?b.style.left=g.prevWidth+"px":b.style.right=g.prevWidth+"px"})))},updateHorizontalMenu:function(a,b,d,c){var e=c||!1;b=dijit.byId(b);var g=dijit.byId(d);null!=g&&g.destroyRecursive(!1);var g=new dijit.MenuBar({id:d,
name:"topMenu"},f.create("div",null,b.domNode)),h=new dijit.PopupMenuBarItem({label:"\x3e",id:d+"menu_more_options",popup:new dijit.Menu({parentMenu:g,baseClass:"dijitHorizontalSubMenu"}),baseClass:"dijitHorizontalSubMenuItem"});g.addChild(h);var l=u.position(h.domNode).y,k=!1;f.forEach(a,function(a,b){if(k)this.addHorizontalMenuItems(h.popup,[this.getMenuItem(a)]);else{var c=new dijit.Menu({parentMenu:g,baseClass:"dijitHorizontalSubMenu"}),d=new dijit.PopupMenuBarItem({label:a.name,id:a.id,popup:c,
baseClass:"dijitHorizontalSubMenuItem",hotKey:a.hotKey});g.addChild(d,b);var f=u.position(h.domNode);!1==e&&f.y!=l?(k=!0,g.removeChild(d),d.destroyRecursive(!1),this.addHorizontalMenuItems(h.popup,[this.getMenuItem(a)])):this.addHorizontalMenuItems(c,a.childrenItems)}},this);k||(g.removeChild(h),h.destroyRecursive(!1))},addHorizontalMenuItems:function(a,b){null!=b&&f.forEach(b,function(b){if(null!=b.childrenItems){var c=new dijit.Menu({parentMenu:a,baseClass:"dijitHorizontalSubMenu"}),e=new dijit.PopupMenuItem({label:b.name,
popup:c,baseClass:"dijitHorizontalSubMenuItem"});a.addChild(e);q.set(e.arrowWrapper,"visibility","");this.addHorizontalMenuItems(c,b.childrenItems)}else c={onClick:function(){ec.fisa.menu.utils.menuTreeOnClick(this,null)}},y.mixin(c,b),c.label=b.name,c.baseClass="dijitHorizontalMenuItem",a.addChild(new dijit.MenuItem(c))},this)},getMenuItem:function(a){var b={};b.name=a.name;b.id=a.id;b.childrenItems=a.childrenItems;return b},updateHomeTab:function(a){var b=f.byId("homeIconLink");null!=a&&"name"in
a?(null!=b&&(q.set(b,"visibility",""),q.set(b,"display",""),b._home=a,null!=b._connection&&(b._connection.remove(),b._connection=null),b._connection=t(b,"click",function(){ec.fisa.navigation.utils.closeCurrentTab();ec.fisa.menu.utils.loadMenuTabContainer(this._home,!0)})),ec.fisa.menu.utils.loadMenuTabContainer(a,!0)):null!=b&&(q.set(b,"visibility","hidden"),q.set(b,"display","none"))},doResponsive:function(a){ec.fisa.menu.utils.menuItems&&(800>z.getBox().w?ec.fisa.menu.utils.menuLoad({items:[{id:"parent_menu_0000",
name:"Tablets Menu",childrenItems:ec.fisa.menu.utils.menuItems}]},a,!1,"leftMenuCntPn"):ec.fisa.menu.utils.menuLoad({items:ec.fisa.menu.utils.menuItems},a,!1,"leftMenuCntPn"))}});v.utils=new s;ec.fisa.menu.utils=v.utils;return s});
//@ sourceMappingURL=Utils.js.map