//>>built
require({cache:{"url:ec/fisa/widget/security/templates/Keyboard.html":'\x3cdiv\x3e\n\t\x3ctable cellpadding\x3d"0" cellspacing\x3d"0" border\x3d"0" class\x3d"keyboardImage"\x3e\n\t\t\x3ctbody data-dojo-attach-point\x3d"_tBodyNode"\x3e\x3c/tbody\x3e\n\t\x3c/table\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/security/Keyboard","dojo/_base/declare dojo/text!./templates/Keyboard.html ec/fisa/widget/Utils dojo/dom-construct dojo/dom-class dojo/dom-style dojo/_base/sniff dijit/_Widget dijit/_Templated dijit/form/Button dijit/focus ./_base".split(" "),function(l,m,s,h,f,g,n,p,q,r,k){return l("ec.fisa.widget.security.Keyboard",[p,q],{tabId:"",pageScopeId:"",_fStarted:!0,baseClass:"",widgetsInTemplate:!0,_type:"",options:[],alphOptions:[],allOptions:[],selectedValue:"",context:null,templateString:m,
_tBodyNode:null,multipleSelectedVals:{},currentId:null,lowerUpper:{},isUpperCase:!1,actualAlphStyle:"lowercase",lastULSelectedBtn:null,lastACSelectedBtn:null,charTrList:[],alphTrList:[],isLogin:!1,data:{},postMixInProperties:function(){this.inherited(arguments)},postCreate:function(){this.inherited(arguments)},responseHandler:function(a){this.lowerUpper=a.lowerUpper;if(a.msg){var b=null;dojo.forEach(a.msg,function(c,d){if(0==d%a.maxCols&&(b=h.create("tr",{},this._tBodyNode),null!=c))if("CHAR"==c.type)this.charTrList.push(b),
g.set(b,"display","none");else if("ALPH"==c.type||"NUM"==c.type)this.alphTrList.push(b);else if("SPECIAL"==c.type){var e={align:"left"};n("ie")?e.colSpan=a.maxCols:e.colspan=a.maxCols;e=h.create("td",e,b);b=null;e=h.create("table",{border:"0",cellpadding:"0",cellspacing:"0"},e);e=h.create("tbody",{},e);b=h.create("tr",{},e)}e=null;e=h.create("td",{},b);null!=c?"SPECIAL"!=c.type?this._addImageComponent(c,e):this._addButtonComponent(c,e):this._addImageComponent(c,e)},this)}},_addImageComponent:function(a,
b){var c=h.create("span",{"class":"fisaKeyBtn"},b),d="",e=null,d=null;null!=a&&(null!=a.url&&""!=a.url)&&(d=a.url,e=a.type,d=h.create("span",{style:{backgroundImage:'url("'+d+'")'}},c));null!=d?(null!=e&&"ALPH"==e?(f.add(d,"lowercase"),this.alphOptions.push(d)):f.add(d,"number"),null!=a&&null!=a.url&&(this.connect(d,"onclick",function(b){this.onClick(c,a,b)}),this.connect(d,"onmouseover",dojo.hitch(this,this.onMouseOver,d,a)),this.connect(d,"onmouseout",dojo.hitch(this,this.onMouseOut,d,a)),this.options.push(c),
this.allOptions.push(d))):(d=h.create("div",{width:"5px"},b),b.width="10px")},_addButtonComponent:function(a,b){var c=a.label,d=a.value;"LOWERCASE"==d?(g.set(b,"display","none"),this.lastULSelectedBtn=b):"LETTERS"==d&&(g.set(b,"display","none"),this.lastACSelectedBtn=b);var e=h.create("div",{width:"64px",height:"32px"},b),c=new r({label:c,value:d},e);c.connect(c,"onClick",dojo.hitch(this,this.onClickSpecialBtn,b,d))},onClick:function(a,b,c){a=b.value;dojo.forEach(this.options,function(a,b){f.remove(a,
"selected")},this);b=a;if(!0==this.isUpperCase&&(b=this.lowerUpper[a],null==b||""==b))b=a;this.selectedValue+=b;this.multipleSelectedVals[this.currentId]=this.selectedValue;dojo.stopEvent(c)},onClickSpecialBtn:function(a,b){"LOWERCASE"==b?(dojo.forEach(this.alphOptions,function(a,b){f.remove(a,"uppercase");f.add(a,"lowercase")},this),this.isUpperCase=!1,this.actualAlphStyle="lowercase"):"UPPERCASE"==b?(dojo.forEach(this.alphOptions,function(a,b){f.remove(a,"lowercase");f.add(a,"uppercase")},this),
this.isUpperCase=!0,this.actualAlphStyle="uppercase"):"SPECIALCHARS"==b?(dojo.forEach(this.charTrList,function(a,b){g.set(a,"display","")},this),dojo.forEach(this.alphTrList,function(a,b){g.set(a,"display","none")},this)):"LETTERS"==b&&(dojo.forEach(this.charTrList,function(a,b){g.set(a,"display","none")},this),dojo.forEach(this.alphTrList,function(a,b){g.set(a,"display","")},this));if("LOWERCASE"==b||"UPPERCASE"==b)k.curNode&&k.curNode.blur(),null!=this.lastULSelectedBtn&&(g.set(this.lastULSelectedBtn,
"display",""),k.focus(this.lastULSelectedBtn)),g.set(a,"display","none"),this.lastULSelectedBtn=a;else if("LETTERS"==b||"SPECIALCHARS"==b)k.curNode&&k.curNode.blur(),null!=this.lastACSelectedBtn&&(g.set(this.lastACSelectedBtn,"display",""),k.focus(this.lastACSelectedBtn)),g.set(a,"display","none"),this.lastACSelectedBtn=a},onMouseOver:function(a,b){var c=b.type;null!=c&&"ALPH"==c?(f.remove(a,this.actualAlphStyle),f.add(a,this.actualAlphStyle+"hover")):(f.remove(a,"number"),f.add(a,"numberhover"))},
onMouseOut:function(a,b){var c=b.type;null!=c&&"ALPH"==c?(f.remove(a,this.actualAlphStyle+"hover"),f.add(a,this.actualAlphStyle)):(f.remove(a,"numberhover"),f.add(a,"number"))},_getValueAttr:function(){return this.selectedValue},_setValueAttr:function(a,b,c){this.selectedValue=a},_getContext:function(){return this.context},registrySelectedValue:function(a){this.multipleSelectedVals[a]=""},onChangeSelectedValue:function(a){this.selectedValue=this.multipleSelectedVals[a];this.currentId=a},getSelectedValueById:function(a){return this.multipleSelectedVals[a]},
setSelectedValueById:function(a,b){for(var c in this.multipleSelectedVals);this.multipleSelectedVals[a]=b},startup:function(){!0==this.isLogin&&this.responseHandler(this.data)}})});
//@ sourceMappingURL=Keyboard.js.map