//>>built
require({cache:{"url:ec/fisa/widget/security/templates/Keyboard.html":'\x3cdiv\x3e\n\t\x3ctable cellpadding\x3d"0" cellspacing\x3d"0" border\x3d"0" class\x3d"keyboardImage"\x3e\n\t\t\x3ctbody data-dojo-attach-point\x3d"_tBodyNode"\x3e\x3c/tbody\x3e\n\t\x3c/table\x3e\n\x3c/div\x3e'}});
define("ec/fisa/widget/security/KeyboardLogin","dojo/_base/declare ec/fisa/widget/Utils dojo/dom-construct dojo/dom-class dojo/dom-style dijit/_Widget dijit/_Templated dijit/form/Button dojo/text!ec/fisa/widget/security/templates/Keyboard.html ./_base".split(" "),function(h,p,g,d,f,k,l,m,n){return h("ec.fisa.widget.security.KeyboardLogin",[k,l],{tabId:"",pageScopeId:"",_fStarted:!0,baseClass:"",widgetsInTemplate:!0,_type:"",options:[],alphOptions:[],allOptions:[],selectedValue:"",context:null,templateString:n,
_tBodyNode:null,multipleSelectedVals:{},currentId:null,lowerUpper:{},isUpperCase:!1,actualAlphStyle:"lowercase",lastULSelectedBtn:null,lastACSelectedBtn:null,charTrList:[],alphTrList:[],isLogin:!1,data:{},postMixInProperties:function(){this.inherited(arguments)},postCreate:function(){this.inherited(arguments)},responseHandler:function(a){this.lowerUpper=a.lowerUpper;if(a.msg){var b=null;dojo.forEach(a.msg,function(c,e){0==e%a.maxCols&&(b=g.create("tr"),g.place(b,this._tBodyNode),null!=c&&("CHAR"==
c.type?(this.charTrList.push(b),f.set(b,"display","none")):("ALPH"==c.type||"NUM"==c.type)&&this.alphTrList.push(b)));var d=null,d=null!=c&&null!=c.specialProperties?g.create("td",{colspan:c.specialProperties.colspan}):g.create("td");null!=c?"SPECIAL"!=c.type?this._addImageComponent(c,d):this._addButtonComponent(c,d):this._addImageComponent(c,d);g.place(d,b)},this)}},_addImageComponent:function(a,b){var c=g.create("span",{"class":"link"}),e="",f=null;null!=a&&null!=a.url&&(e=a.url,f=a.type);e=g.create("img",
{src:e});null!=f&&"ALPH"==f?(d.add(e,"lowercase"),this.alphOptions.push(e)):d.add(e,"number");null!=a&&null!=a.url&&(this.connect(e,"onclick",function(b){this.onClick(c,a,b)}),this.connect(e,"onmouseover",dojo.hitch(this,this.onMouseOver,e,a)),this.connect(e,"onmouseout",dojo.hitch(this,this.onMouseOut,e,a)),this.options.push(c),this.allOptions.push(e));g.place(e,c);g.place(c,b)},_addButtonComponent:function(a,b){var c=a.label,e=a.value;"LOWERCASE"==e?(f.set(b,"display","none"),this.lastULSelectedBtn=
b):"LETTERS"==e&&(f.set(b,"display","none"),this.lastACSelectedBtn=b);var d=g.create("div",{width:"64px",height:"32px"},b),c=new m({label:c,value:e},d);this.connect(c,"onClick",dojo.hitch(this,this.onClickSpecialBtn,b,e))},onClick:function(a,b,c){a=b.value;dojo.forEach(this.options,function(a,c){d.remove(a,"selected")},this);b=a;if(!0==this.isUpperCase&&(b=this.lowerUpper[a],null==b||""==b))b=a;this.selectedValue+=b;this.multipleSelectedVals[this.currentId]=this.selectedValue;dojo.stopEvent(c)},onClickSpecialBtn:function(a,
b){"LOWERCASE"==b?(dojo.forEach(this.alphOptions,function(a,b){d.remove(a,"uppercase");d.add(a,"lowercase")},this),this.isUpperCase=!1,this.actualAlphStyle="lowercase"):"UPPERCASE"==b?(dojo.forEach(this.alphOptions,function(a,b){d.remove(a,"lowercase");d.add(a,"uppercase")},this),this.isUpperCase=!0,this.actualAlphStyle="uppercase"):"SPECIALCHARS"==b?(dojo.forEach(this.charTrList,function(a,b){f.set(a,"display","")},this),dojo.forEach(this.alphTrList,function(a,b){f.set(a,"display","none")},this)):
"LETTERS"==b&&(dojo.forEach(this.charTrList,function(a,b){f.set(a,"display","none")},this),dojo.forEach(this.alphTrList,function(a,b){f.set(a,"display","")},this));if("LOWERCASE"==b||"UPPERCASE"==b)f.set(a,"display","none"),null!=this.lastULSelectedBtn&&f.set(this.lastULSelectedBtn,"display",""),this.lastULSelectedBtn=a;else if("LETTERS"==b||"SPECIALCHARS"==b)f.set(a,"display","none"),null!=this.lastACSelectedBtn&&f.set(this.lastACSelectedBtn,"display",""),this.lastACSelectedBtn=a},onMouseOver:function(a,
b){var c=b.type;null!=c&&"ALPH"==c?(d.remove(a,this.actualAlphStyle),d.add(a,this.actualAlphStyle+"hover")):(d.remove(a,"number"),d.add(a,"numberhover"))},onMouseOut:function(a,b){var c=b.type;null!=c&&"ALPH"==c?(d.remove(a,this.actualAlphStyle+"hover"),d.add(a,this.actualAlphStyle)):(d.remove(a,"numberhover"),d.add(a,"number"))},_getValueAttr:function(){return this.selectedValue},_setValueAttr:function(a,b,c){this.selectedValue=a},_getContext:function(){return this.context},registrySelectedValue:function(a){this.multipleSelectedVals[a]=
""},onChangeSelectedValue:function(a){this.selectedValue=this.multipleSelectedVals[a];this.currentId=a},getSelectedValueById:function(a){return this.multipleSelectedVals[a]},setSelectedValueById:function(a,b){return this.multipleSelectedVals[a]=b},startup:function(){!0==this.isLogin&&this.responseHandler(this.data)}})});
//@ sourceMappingURL=KeyboardLogin.js.map