//>>built
define("ec/fisa/controller/tsc/authorization/AuthorizationRuleController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/controller/custom/CustomBtController ec/fisa/format/Utils ec/fisa/navigation/Utils dojo/dom-construct dojox/mvc dojox/mvc/StatefulModel ec/fisa/mvc/StatefulModel dojo/dom-style dojo/dom-geometry dijit/tree/ForestStoreModel dojox/grid/TreeGrid dojo/data/ItemFileWriteStore dijit/form/CheckBox ec/fisa/widget/tsc/MixedCheckBox ec/fisa/dwr/Store".split(" "),
function(e,g,r,s,n,t,u,v,w,x,p,f,q){return g("ec.fisa.controller.tsc.AuthorizationRuleController",n,{tabId:null,pageScopeId:null,model:null,modelDestinatario:null,data:{},breadcrumbId:null,icons:null,labelsData:null,requiredFieldMessage:null,priorityId:null,nextId:null,isFirstPanel:!0,generalPanelId:null,gridPanelId:null,userPanelId:null,rulePanelId:null,checkRuleId:null,checkAlwaysId:null,checkOneId:null,checkAllId:null,listUserDataGrid:null,listAppDataGrid:null,userStore:null,selectUsers:null,contentLovAplication:null,
textBtId:null,textAppDesc:null,actionId:null,actionMode:null,sequence:null,buttonAdd:null,textAppSearchId:null,authorizationRuleId:null,rule:null,ruleCondition:null,selectData:null,tempUserGrid:null,panelInit:!1,appId:null,validBtId:!0,validBtMessages:null,btnBackId:null,btnNextId:null,btnSaveId:null,constructor:function(a,b,c){this.labelsData=this.initLabels;this.icons=c.icons;this.tempUserGrid=[];this.initData=c;void 0==c.aMsgs&&(this.model={},this.modelDestinatario={},this.appId="",this.userStore=
new ec.fisa.dwr.Store("AuthorizationRuleControllerDWR","viewDataUsers",this.tabId,this.pageScopeId,[],null),this.init(c))},init:function(a){this.selectUsers=a.selectUsers;this.actionMode=a.actionMode;this.sequence=a.sequence;this.rule=a.rule;this.ruleCondition=a.ruleCondition;this.selectData=a.selectData;this.requiredFieldMessage=a.requiredFieldMessage;this.textBtId=a.textBtId;delete a.selectUsers;delete a.actionMode;delete a.sequence;delete a.rule;delete a.ruleCondition;delete a.selectData;delete a.requiredFieldMessage;
delete a.textBtId;this.data=a;this.id_lov;this.model=dojox.mvc.newStatefulModel({data:{}});this.modelDestinatario=new p({data:{}})},handleWindowAction:function(a){dijit.byId(this.messagesPanelId).clearAllMessages();"cnfrm"==a.wAxn?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(a.respBtLabels[0],a.aMsgs,this.breadcrumbId,this.tabId,this.pageId,null,null,!1):void 0!=a.wAxn&&"close"==a.wAxn?ec.fisa.navigation.utils.closeCurrentBreadCrumb(this.breadcrumbId):void 0!=a.aMsgs&&this.updateMsgsPanel(a.aMsgs)},
bindToModel:function(a,b,c){var d=this.data[b];if(void 0===d||null==d)d="";d=new dojox.mvc.StatefulModel({data:d});this.model.add(b,d);a.set("ref",this.model[b]);a.set("disabled","true"===c)},processValue:function(a,b){},sendInfoToServer:function(){},validateBtInfo:function(a){var b=this.requiredFieldMessage.I18N_REQUIRED_FIELDS,c="",d=null,h=null,f=this.textBtId,k=this.validateFields([{field:"AUT_MAIN_TRANS",value:f}]);if(null!=k&&"error"==k.wAxn)return a.aMsgs=k.aMsgs,a.wAxn=k.wAxn,a;var l=e.byId(this.checkAlwaysId).checked,
g=e.byId(this.checkAllId).checked,m=k=!1;if("DE"!=this.actionMode)if(l){if(k=!0,d=this.listUserDataGrid.selection.getSelected(),null==d||!(0<d.length))b=b+" ["+this.labelsData.AUT_APPROVES+"] ",c=c+"** "+this.requiredFieldMessage.I18N_REQUIRED_FIELDS+"["+this.labelsData.AUT_APPROVES+"]",m=!0}else if(h=dijit.byId(this.authorizationRuleId).get("value"),null==h||!(0<h.group.length))b=b+" ["+this.labelsData.AUT_BT_TITTLE+"] ",c=c+"** "+this.requiredFieldMessage.I18N_REQUIRED_FIELDS+"["+this.labelsData.AUT_BT_TITTLE+
"]",m=!0;l=!1;g&&(l=!0);b=this.generateMsg(b,c,4E4);m?(a.aMsgs=b,a.wAxn="error"):(a.wAxn="cnfrm",a.data={},a.data.isAlwaysRule=k,a.data.btId=f,a.data.isAll=l,a.data.selectionUserGrid=d,a.data.authorizationRule=h);return a},save:function(a){a=a.data;var b={callbackScope:this};b.callback=this.handleWindowAction;b.errorHandler=this.errorHandler;AuthorizationRuleControllerDWR.saveUserRolInformation(this.tabId,this.pageScopeId,this._addNotificationValData(),[a.isAlwaysRule,a.isAll],a.btId,a.selectionUserGrid,
a.authorizationRule,this.appId,b)},remove:function(a){(new ec.fisa.widget.ConfirmDialog({acceptDialogLabel:this.labelsData.yesLabel,cancelDialogLabel:this.labelsData.noLabel,title:this.labelsData.deleteMenuLabel,content:this.labelsData.deleteWarnLabel,acceptAction:e.hitch(this,function(){var a={callbackScope:this};a.callback=this.handleWindowAction;a.errorHandler=this.errorHandler;AuthorizationRuleControllerDWR.deleteUserRoleInfo(this.tabId,this.pageScopeId,a)})})).show()},cancel:function(){var a=
{callbackScope:this};a.callback=this.handleCancelAction;a.errorHandler=this.errorHandler;AuthorizationRuleControllerDWR.cancelUserRoleImpl(this.tabId,this.pageScopeId,a)},validateFields:function(a){var b={},c=this.requiredFieldMessage.I18N_REQUIRED_FIELDS,d="";e.forEach(a,function(a){if("undefined"===typeof a.value||""==a.value||"-1"==a.value)c=c+" ["+this.labelsData[a.field]+"] ",d=d+"** "+this.requiredFieldMessage.I18N_REQUIRED_FIELDS+"["+this.labelsData[a.field]+"]"},this);a=this.generateMsg(c,
d,4E4);void 0!=a[0].detail&&""!=a[0].detail?(b.aMsgs=a,b.wAxn="error",this.addToolTipRequiredField(this.id_lov)):b.wAxn="cnfrm";return b},addParamToModel:function(a){var b=a["bt-id"],c=a["field-id"],d=null;this.data&&(this.data[b]&&this.data[b].dataMessage)&&(d=this.data[b].dataMessage.fields[c]);null==d?(d={value:"",complement:null},a._fStarted=!0):null==d.value&&(a._fStarted=!0);this.disabled&&(a.set("disabled",this.disabled),d.enabled=!1);if(this.modelDestinatario.contains(b))this.modelDestinatario.contains([b,
"dataMessage","fields",c])&&this.modelDestinatario.setValue([b,"dataMessage","fields",c,"value"],d.value);else{var e=null;a instanceof ec.fisa.widget.DateTextBox&&(e=ec.fisa.format.utils.formatLongDate);this.modelDestinatario.appendObject([b,"dataMessage","fields",c,"value"],d.value,a.id,"value",e,!0);e=null;void 0!=d.enabled&&(e=d.enabled);this.modelDestinatario.appendObject([b,"dataMessage","fields",c,"enabled"],e,a.id,"enabled",null,!1);a.hasCompl&&this.modelDestinatario.appendObject([b,"dataMessage",
"fields",c,"complement"],d.complement,a.id,"complement",null,!1)}},containsFieldModel:function(a,b){return this.modelDestinatario.contains([a,"dataMessage","fields",b,"value"])},getFieldModel:function(a,b){return this.modelDestinatario.getValue([a,"dataMessage","fields",b,"value"])},setFieldModelValue:function(a,b,c){this.modelDestinatario.setValue([a,"dataMessage","fields",b,"value"],c)},setFieldModelEnabled:function(a,b,c){this.modelDestinatario.setValue([a,"dataMessage","fields",b,"enabled"],c)},
setFieldModelComplement:function(a,b,c){this.modelDestinatario.setValue([a,"dataMessage","fields",b,"complement"],c)},getFieldModelComplement:function(a,b){return this.modelDestinatario.getValue([a,"dataMessage","fields",b,"complement"])},logger:function(a){},_setVisiblePanel:function(a){a.style.display="block";f.set(a,"display","block")},_setNotVisiblePanel:function(a){f.set(a,"display","none")},next:function(){var a=dijit.byId(this.notificationAdditionalsWdgId),b={field:"AUT_MAIN_TRANS",value:this.textBtId};
if(this.validBtId)if(b=this.validateFields([b]),null!=b&&"error"==b.wAxn)a=b.aMsgs,void 0!=a&&null!=a&&(void 0!=a[0]&&null!=a[0])&&(a=this.generateMsg(a[0].summary,a[0].detail,4E4),this.clearPanelMessage(),this.updateMsgsPanel(a));else{var b=e.byId(this.userPanelId),c=e.byId(this.generalPanelId),d=null,h=e.byId(this.checkRuleId).checked,d=h?e.byId(this.rulePanelId):e.byId(this.gridPanelId);if(this.isFirstPanel){this._setVisiblePanel(d);this._setNotVisiblePanel(c);var c=dijit.byId(this.btnNextId),
d=dijit.byId(this.btnBackId),g=dijit.byId(this.btnSaveId);this._setVisible(d);this._setVisible(g);this._setNotVisible(c);e.forEach(a,function(a){a=dijit.byId(a.notifWdgId);this._setNotVisible(a.getParent())},this);h?this.initPanel():(f.set(b,"display","block"),b.style.display="block",f.set(this.listUserDataGrid,"display","block"),this.listUserDataGrid.render(),this.listUserDataGrid.resize());this.isFirstPanel=!1}else this._setVisiblePanel(c),this._setNotVisiblePanel(d),c=dijit.byId(this.btnNextId),
d=dijit.byId(this.btnBackId),g=dijit.byId(this.btnSaveId),this._setNotVisible(d),this._setNotVisible(g),this._setVisible(c),e.forEach(a,function(a){a=dijit.byId(a.notifWdgId);this._setVisiblePanel(a.getParent(),"block")},this),this.isFirstPanel=!0}else dijit.byId(this.messagesPanelId).clearAllMessages(),this.updateMsgsPanel(this.validBtMessages)},openLovAplication:function(){if(!(this.disabled||"IN"!=this.actionMode)){this.clearPanelMessage();this.appStore=new ec.fisa.dwr.Store("AuthorizationRuleControllerDWR",
"viewApplications",this.tabId,this.pageScopeId,[],null);var a=ec.fisa.controller.utils.getGlobalModalSize(0.8);this.contentLovAplication=new dojox.widget.DialogSimple({title:"Aplicaciones",href:"./static/tsc/authorization_rule/fragment/lovApplication.jsp",ioArgs:{content:{FISATabId:this.tabId,FisaPageScopeId:this.pageScopeId}},ioMethod:e.xhrPost,style:"height:"+a.h+"px;width:"+a.w+"px;"});this.contentLovAplication.resizeContainerNode=this.resizeNode;this.contentLovAplication.show();this.resizeNode(this.contentLovAplication,
a)}},closeLovAplication:function(){this.contentLovAplication.destroy();this.clearPanelMessage()},saveLovAplication:function(){this.clearPanelMessage();var a=this.listAppDataGrid.selection.getSelected(),b="",c="";if(null!=a&&(void 0!=a[0]||null!=a[0]))this.appId=a[0],b=this.listAppDataGrid.store.getValue(this.appId,"appName"),c=this.listAppDataGrid.store.getValue(this.appId,"btId");this.textBtId=c;dijit.byId(this.textAppDesc).set("value",b);this.contentLovAplication.destroy();this.removeToolTipRequiredField(this.id_lov);
this.initSecondPanel(c,b)},updateLovAplication:function(a){if("IN"==a){this.clearPanelMessage();var b=dijit.byId(this.textAppDesc).get("value"),c=null;a={callbackScope:this,callback:function(a){void 0!=a.btId?(c=a.btId,this.appId=a.id,b=a.appName,c=a.btId,this.initSecondPanel(c,b),this.textBtId=c):this.handleWindowAction(a)}};a.errorHandler=this.errorHandler;AuthorizationRuleControllerDWR.getApplicationItem(this.tabId,this.pageScopeId,[b],a)}},initSecondPanel:function(a,b){var c={callbackScope:this,
callback:function(a){this.validBtId=a.validBtId;this.validBtId||(this.validBtMessages=a.aMsgs,dijit.byId(this.messagesPanelId).clearAllMessages(),this.updateMsgsPanel(a.aMsgs),this.addToolTipRequiredField(this.id_lov));this.clearAuthorization()}};c.errorHandler=this.errorHandler;AuthorizationRuleControllerDWR.initializeBT(this.tabId,this.pageScopeId,a,b,c)},setRuleChange:function(){var a=dijit.byId(this.checkAlwaysId),b=dijit.byId(this.checkRuleId);null==a||null==b||(b.checked?a.set("value",!1,!1):
a.set("value",!0,!1))},setAlwaysChange:function(){var a=dijit.byId(this.checkAlwaysId),b=dijit.byId(this.checkRuleId);null==a||null==b||(a.checked?b.set("checked",!1,!1):b.set("checked",!0,!1))},setOneChange:function(){var a=dijit.byId(this.checkOneId),b=dijit.byId(this.checkAllId);null==a||null==b||(a.checked?b.set("value",!1,!1):b.set("value",!0,!1))},setAllChange:function(){var a=dijit.byId(this.checkOneId),b=dijit.byId(this.checkAllId);null==b||null==a||(b.checked?a.set("checked",!1,!1):a.set("checked",
!0,!1))},update:function(){var a=e.byId(this.textAppSearchId).value;this.appStore=new ec.fisa.dwr.Store("AuthorizationRuleControllerDWR","viewApplications",this.tabId,this.pageScopeId,[a],null);this.listAppDataGrid.setStore(this.appStore)},setAuthorizationRule:function(a){this.authorizationRuleId=a.id;null!=this.rule&&(void 0!=this.ruleCondition&&void 0!=this.selectData)&&a.set("value",[this.rule,this.ruleCondition,this.selectData])},initPanel:function(){this.panelInit=!0;dijit.byId(this.authorizationRuleId).relatedFieldBt=
this.textBtId;e.forEach(this.tempUserGrid,function(a,b){var c=e.byId(a.getParent().id);f.set(c,"display","block");c.style.display="block";f.set(a,"display","block");a.render();a.resize()},this);delete this.tempUserGrid},resizeNode:function(a,b){var c=q.getMarginBox(a.titleNode);f.set(a.containerNode,"height",b.h-c.h-4*c.t+"px");f.set(a.containerNode,"display","block");f.set(a.containerNode,"overflowY","auto");f.set(a.containerNode,"overflowX","auto")},addToolTipRequiredField:function(a){ec.fisa.format.utils.addToFieldError(a,
"El Campo es requerido.",{level:4E4},null)},removeToolTipRequiredField:function(a){ec.fisa.format.utils.removeFieldError(a)},clearAuthorization:function(){}})});
//@ sourceMappingURL=AuthorizationRuleController.js.map