//>>built
define("ec/fisa/mobile/grid/Utils",["dojo/_base/kernel","dojo/_base/declare","dojo/dom-construct","ec/fisa/mvc/StatefulModel","ec/fisa/mobile/grid/_base"],function(l,t,u,r,s){l=t("ec.fisa.mobile.grid.Utils",null,{_formatcolumn:function(k,f,a,d,c,g,n){return d.hasLink?(a=c,0!=d.format&&(a=ec.fisa.mobile.format.utils.formatQtColumn(d.format,d.formatPattern,c)),this.formatLink(d.btId,d.fieldId,k,f,d.actionMode,d.entityId,d.tabIndex,a,g,n)):ec.fisa.grid.utils.obtainMultiRegisterFormatValue(d,c)},getMRComponentDirect:function(k,
f,a,d,c,g,n,p,b,h,m){if(null==a.grid.model||void 0==a.grid.model)a.grid.model=[];if(null==a.grid.complementModel||void 0==a.grid.complementModel)a.grid.complementModel=[];void 0==a.grid.model[f]&&(a.grid.model[f]=new r);void 0==a.grid.complementModel[f]&&(a.grid.complementModel[f]=new r);if(!("QY"==b.actionMode||"DE"==b.actionMode))return this.getMRComponentEditable(k,f,a,d,c,g,n,p,b,!0,h,m)},getMRComponentEditable:function(k,f,a,d,c,g,n,p,b,h,m,q){var l=a.grid.store.getValue(q,"rowSts"),e=null;1<
l.length&&(e=l.charAt(l.length-2));1==e?e="IN":2==e&&(e="UP");null==e&&!0==h&&(e=b.actionMode);q=a.grid.store.getValue(q,a.field);if("ec.fisa.mobile.widget.FormGrid"===a.grid.declaredClass&&0===b.columnIndex)return c=u.create("span",{"class":"fisaLabel",innerHTML:q});d=7==d?1:d;if(1==d)return 1==b.multiLanguage?(c={"bt-id":a.bt,fisatabid:c,fisapageid:g,fieldId:a.field,"field-id":a.field,defaultLanguage:b.currentLanguage,supportedLanguages:b.supportedLanguages,tapdFieldLenght:b.tapdFieldLenght,requestedAction:b.requestedAction,
parentEditableGrid:!0,"notify-combo-id":b.notifyComboId,tdParentWidth:b.tdParentWidth,gridId:p,gridSelectedRowIndex:f,entityMrId:b.entityId,tabIndexField:m,parentType:a.ptype},null!=b.visualSize&&(c.visualSize=b.visualSize),c=new ec.fisa.widget.i18n.I18nTextBox(c)):(c={"bt-id":a.bt,fieldId:a.field,"field-id":a.field,maxLength:b.tapdFieldLenght,requestedAction:b.requestedAction,btId:b.btId,gridSelectedRowIndex:f,"notify-combo-id":b.notifyComboId,tdParentWidth:b.tdParentWidth,parentEditableGrid:!0,
fisatabid:c,fisapageid:g,entityMrId:b.entityId,gridId:p,format:b.format,tabIndexField:m},null!=b.visualSize&&(c.visualSize=b.visualSize),c=new ec.fisa.mobile.widget.TextBox(c),g=!0,"IN"==e?g=b.ftmDisabledIn:"UP"==e&&(g=b.ftmDisabledUp),b.insertAllowed=!0!=g,b.updateAllowed=!0!=g,this._defineReadOnly(c,e,b.insertAllowed,b.updateAllowed)),d=[a.field],e=null,!1==h&&(e=a.grid.model.getValue(d)),this._setInitValFromModel(a,h,f,e,k,c.id,f),c;if(3==d)return d=[a.field],e=!1==h?a.grid.model.getValue(d):k,
c={qtId:n,"qt-id":n,fieldId:a.field,value:e,fisatabid:c,fisapageid:g,parentEditableGrid:!0,entityMrId:b.entityId,"notify-combo-id":b.notifyComboId,parentGridId:p,tdParentWidth:b.tdParentWidth,"field-id":a.field,gridRealRowIndex:f,tabIndexField:m,"bt-id":a.bt},null!=b.visualSize&&(c.visualSize=b.visualSize),c=new ec.fisa.mobile.widget.Select(c),this._setInitValFromModel(a,h,f,e,k,c.id,f),c;if(5==d)return c={fieldId:a.field,fisaFormat:b.format,fisaFormatPattern:b.formatPattern,fisatabid:c,fisapageid:g,
"field-id":a.field,"bt-id":a.bt,parentEditableGrid:!0,entityMrId:b.entityId,"notify-combo-id":b.notifyComboId,tdParentWidth:b.tdParentWidth,gridRealRowIndex:f,tabIndexField:m,baseClass:"dijitTextBox dijitComboBox dijitDateTextBox",inputInvalidLabel:b.inputInvalidLabel},null!=b.visualSize&&(c.visualSize=b.visualSize),c=new ec.fisa.mobile.widget.DatePicker(c),d=[a.field],e=null,!1==h&&(e=a.grid.model.getValue(d)),this._setInitValFromModel(a,h,f,e,k,c.id,f),c;if(8==d)return c={fieldId:a.field,fisatabid:c,
fisapageid:g,"field-id":a.field,"bt-id":a.bt,parentEditableGrid:!0,"notify-combo-id":b.notifyComboId,tdParentWidth:b.tdParentWidth,gridRealRowIndex:f,tabIndex:m,inputInvalidLabel:b.inputInvalidLabel},c=new dojox.mobile.CheckBox(c),this._defineReadOnly(c,e,b.insertAllowed,b.updateAllowed),d=[a.field],e=null,!1==h&&(e=a.grid.model.getValue(d)),this._setInitValFromModel(a,h,f,e,k,c.id,f),c;if(0==d)return c=new ec.fisa.mobile.widget.OutputText({fieldId:a.field}),e=k,""===e||(null==e||"undefined"===typeof e)||
c.set("value",e),this._setInitValFromModel(a,h,f,e,k,c.id,f),c}});s.utils=new l;ec.fisa.mobile.grid.utils=s.utils;return l});
//@ sourceMappingURL=Utils.js.map