//>>built
define("ec/fisa/controller/payments/MultiplePaymentsController","dojo/_base/kernel dojo/_base/declare dojo/_base/lang ec/fisa/controller/BaseController ec/fisa/controller/custom/CustomBtController dojo/dom-construct dijit/form/CheckBox dojo/dom-geometry dojo/dom-style ec/fisa/widget/SANotificationGridUser ec/fisa/format/Utils ec/fisa/navigation/Utils".split(" "),function(m,n,r,s,p,t,u,q,l){return n("ec.fisa.controller.transfers.MultiplePaymentsController",p,{listUserDataGridId:null,tXMDinamicGridId:null,
selectedUsers:null,selectedProds:null,breadcrumbId:null,icons:null,additionalSucessCheckBoxList:[],additionalUnSucessCheckBoxList:[],urlToAdditionalUserPage:null,disableVal:null,breadCrumbAdditionalUser:null,parentBtId:null,additionalUserGridId:null,productSelectValues:null,contentPanelProperties:null,priorityId:null,listSelectFrecuency:{},ownAccountsData:null,listGridData:null,btnBackId:null,btnNextId:null,btnSaveId:null,btnCloseId:null,btnCancelId:null,btnPrintId:null,_fci:{id:0,transactionType:1,
transactionName:2,companyName:3,serviceName:4,outAccount:5,monto_aux:6,desc:7,descRead:8,monto:9,charge:10,totalAmount:11,summary:12,summarySave:13},montoId:"monto",montoIdAux:"monto_aux",descId:"desc",montoReadId:"montoRead",descReadId:"descRead",accountId:null,accountAmountId:"accountAmount",resumePanelId:null,inputDisabled:null,montoReadId:"montoRead",descReadId:"descRead",chargeId:"charge",totalAmountId:"totalAmount",summaryId:"summary",summarySaveId:"summarySave",contractId:"contract",contractReadId:"contractReadId",
disabledId:"disabledId",isSuccess:"totalSuccess",constructor:function(a,b,c){this.listGridData={};this.inputDisabled=!1;void 0==c.aMsgs&&(this.selectedUsers=c.selectedUsers,this.selectedProds=c.selectedProds,this.disableVal=c.disableVal,this.parentBtId=c.parentBtId,this.priorityId=c.priorityId,this.ownAccountsData=c.ownAccountsData);delete c.selectedUsers;delete c.selectedProds;delete c.disableVal;delete c.parentBtId;delete c.priorityId;delete c.ownAccountsData},getSelectedUsers:function(){return this.selectedUsers},
getSelectedProds:function(){return this.selectedProds},setTxMDinamicGridId:function(a){this.tXMDinamicGridId=a},getTxMDinamicGrid:function(){return dijit.byId(this.tXMDinamicGridId)},setListProdDataGridId:function(a){this.listProdDataGridId=a.id},_getSelectedUsers:function(){return this._getSelectedValues(this.listUserDataGridId)},_getSelectedProducts:function(){return this._getSelectedValues(this.listProdDataGridId)},_getSelectedProductsLine:function(){return this._getSelectedValuesProducts(this.listProdDataGridId)},
_getSelectedValuesProducts:function(a){a=dijit.byId(gridId);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],m.forEach(a.fisaChecks,function(a){dijit.byId(a).checked&&b.push(null)},this));return b},_getSelectedValues:function(a){a=dijit.byId(a);var b=null;null!=a&&null!=a.fisaChecks&&(b=[],m.forEach(a.fisaChecks,function(a){a=dijit.byId(a);a.checked&&b.push(a.fval)},this));return b},_getSelectedAllProducts:function(){return this._getAllValues(this.listProdDataGridId)},_getAllValues:function(a){a=dijit.byId(a);
var b=null;null!=a&&null!=a.fisaChecks&&(b=[],m.forEach(a.fisaChecks,function(a){a=dijit.byId(a);b.push(a.fval)},this));return b},validateBtInfo:function(a){this.clearPanelMessage();for(var b=!1,c="",e=this.getTxMDinamicGrid().store.getResults(),h=!1,f=0;f<e.length;f++){var d=e[f].data,g=d.id;this.listGridData[g]&&this.listGridData[g][this.montoId]&&(d[this.montoId]=this.listGridData[g][this.montoId]);if("true"===this.listGridData[g][this.isSuccess]&&(h=!0,!(0<d[this.montoId]))){b=!0;c=this.initLabels.warning2;
break}}h||(b=!0,c=this.initLabels.warning5);b?(b=this.generateMsg(c,"",4E4),a.aMsgs=b,a.wAxn="error"):a.wAxn="cnfrm";return a},cancel:function(){EventActionDWR.executeCommandButtonCancel(this.tabId,this.pageScopeId,this.btId,{callbackScope:this,callback:this.handleCancelAction})},remove:function(a){},handleAdditionalSaveAction:function(a){this.contentPanelProperties.destroy()},handleConfirmationBt:function(a){var b=a.respBtLabels[0],c=a.aMsgs,e=a.postBtId,h=a.pBtId,f=a.postBtIdDataKey,d=a.principalPostBtIdDataKey,
g=a.parentBtInAuthorization,k=a.showReportModule;a=a.showReportAuto;dijit.byId(this.messagesPanelId).clearAllMessages();null==e?ec.fisa.navigation.utils.showNewBreadCrumbConfirmation(b,c,this.breadcrumbId,this.tabId,this.pageScopeId,this.btIdescIdd,this.btActionMode,this.isSequence,k,a):(b=dijit.byId(this.breadcrumbId),ec.fisa.navigation.utils.showPostBtBreadCrumb(b.params.title,c,this.tabId,this.pageScopeId,e,h,this.btContentPaneId,f,d,this.isSequence,k,a,g,!1))},setUrlToAdditionalUserPage:function(a){this.urlToAdditionalUserPage=
a},openAdditionalUsersSelection:function(){var a=ec.fisa.controller.utils.getPageController(this.tabId,this.pageScopeId);a.productSelectValues=a._getSelectedProducts();var b={},c=ec.fisa.controller.utils.getGlobalModalSize(0.8);b.href=m.config.fisaContextPath+this.urlToAdditionalUserPage;b.ioArgs={content:{FISATabId:this.tabId,FISAParentPageScopeId:this.pageScopeId,isSelect:this.rowData.checked,rowId:this.rowData.fval,componentId:this.parentBtId,height:c.h}};b.ioMethod=m.xhrPost;b.style="height:"+
c.h+"px;width:700px;overflow: auto;";b.splitter="true";a.contentPanelProperties=new dojox.widget.DialogSimple(b);a.contentPanelProperties.resizeContainerNode=this.resizeNode;a.contentPanelProperties.show();a.resizeNode(a.contentPanelProperties,c)},resizeNode:function(a,b){var c=q.getMarginBox(a.titleNode);l.set(a.containerNode,"height",b.h-c.h-4*c.t+"px");l.set(a.containerNode,"display","block");l.set(a.containerNode,"overflowY","auto");l.set(a.containerNode,"overflowX","auto")},save:function(a){this.clearPanelMessage();
this.listGridData;a={callbackScope:this,callback:this.handleSaveAction};var b=this._addNotificationValData();MultiplePaymentsControllerDWR.save(this.listGridData,b,this.tabId,this.pageScopeId,a)},next:function(a){this.clearPanelMessage();a=!1;var b="",c=dijit.byId(this.accountId).get("value");c&&"-1"==c&&(a=!0,b=this.initLabels.warning3);var e=this.getTxMDinamicGrid().store.getResults();if(!a)for(var h=0;h<e.length;h++){var f=e[h].data,d=f.id;this.listGridData[d]&&this.listGridData[d][this.descId]&&
(f[this.descId]=this.listGridData[d][this.descId],f[this.montoReadId]=this.listGridData[d][this.montoIdAux],f[this.montoIdAux]=f[this.montoReadId]);if(void 0==f[this.descId]||0==f[this.descId].length){a=!0;b=this.initLabels.warning4;break}}a?this.showErrorValidation(b):MultiplePaymentsControllerDWR.next(this.listGridData,c,this.tabId,this.pageScopeId,{callbackScope:this,callback:this.handleNextAction})},back:function(a){this.clearPanelMessage();MultiplePaymentsControllerDWR.back(this.listGridData,
this.tabId,this.pageScopeId,{callbackScope:this,callback:this.handleBackAction})},handleBackAction:function(a){this.inputDisabled=!1;dijit.byId(this.accountId).set("disabled",this.inputDisabled);a=this.getTxMDinamicGrid();a.isSortable=!0;a.layout.setColumnVisibility(this._fci[this.montoIdAux],!0);a.layout.setColumnVisibility(this._fci[this.descId],!0);a.layout.setColumnVisibility(this._fci[this.descReadId],!1);a.layout.setColumnVisibility(this._fci[this.montoId],!1);a.layout.setColumnVisibility(this._fci[this.chargeId],
!1);a.layout.setColumnVisibility(this._fci[this.totalAmountId],!1);a=dijit.byId(this.resumePanelId);var b=dijit.byId(this.btnNextId),c=dijit.byId(this.btnBackId),e=dijit.byId(this.btnSaveId);this._setNotVisible(a);this._setNotVisible(c);this._setVisible(b);this._setNotVisible(e);a=dijit.byId(this.notificationAdditionalsWdgId);m.forEach(a,function(a){a=dijit.byId(a.notifWdgId);this._setVisiblePanel(a.getParent(),"block")},this)},handleNextAction:function(a){this.inputDisabled=!0;dijit.byId(this.accountId).set("disabled",
this.inputDisabled);var b=a.errorList,c=a.mapTxM;a=a.totalTxn;var e=this.getTxMDinamicGrid();e.isSortable=!1;for(var h=e.store.getResults(),f=0;f<h.length;f++){var d=h[f].data.id;if(c[d]&&(this.listGridData[d]&&(this.listGridData[d][this.isSuccess]=c[d][this.isSuccess],this.listGridData[d][this.montoId]=c[d][this.montoIdAux],this.listGridData[d][this.montoIdAux]=c[d][this.montoIdAux],this.listGridData[d][this.contractReadId]=c[d][this.contractId],this.listGridData[d][this.totalAmountId]=c[d][this.totalAmountId],
this.listGridData[d][this.descId]=c[d][this.descId],this.listGridData[d][this.descReadId]=c[d][this.descId],this.listGridData[d][this.chargeId]=c[d][this.chargeId],this.listGridData[d][this.summaryId]=""),b[d])){for(var g="",k=0;k<b[d].length;k++)b[d][k][this.summaryId]&&(g=g+"**"+b[d][k][this.summaryId]);this.listGridData[d]&&(this.listGridData[d][this.summaryId]=g)}}a&&this.setValuesResumePanel(a.accountAmount,a.totalCharge,a.totalDebit);e.layout.setColumnVisibility(this._fci[this.montoIdAux],!1);
e.layout.setColumnVisibility(this._fci[this.descId],!1);e.layout.setColumnVisibility(this._fci[this.descReadId],!0);e.layout.setColumnVisibility(this._fci[this.montoId],!0);e.layout.setColumnVisibility(this._fci[this.chargeId],!0);e.layout.setColumnVisibility(this._fci[this.totalAmountId],!0);e.layout.setColumnVisibility(this._fci[this.summaryId],!0);b=dijit.byId(this.resumePanelId);c=dijit.byId(this.btnNextId);a=dijit.byId(this.btnBackId);e=dijit.byId(this.btnSaveId);this._setVisiblePanel(b);this._setNotVisible(c);
this._setVisible(a);this._setVisible(e);b=dijit.byId(this.notificationAdditionalsWdgId);m.forEach(b,function(a){a=dijit.byId(a.notifWdgId);this._setNotVisible(a.getParent())},this)},handleQueryServicesAction:function(a){a=a.mapTxAmounts;var b=this.getTxMDinamicGrid();b.isSortable=!1;for(var c=b.store.getResults(),e=0;e<c.length;e++){var h=c[e].data,f=h.id;a[f]&&this.listGridData[f]&&(h[this.montoIdAux]=a[f],this.listGridData[f][this.montoIdAux]=a[f])}b.layout.setColumnVisibility(this._fci[this.montoIdAux],
!1)},handleSaveAction:function(a){var b=a.mapTxM,c=a.errorList,e=this.getTxMDinamicGrid(),h=e.store.getResults();a=a.totalTxn;for(var f=0;f<h.length;f++){var d=h[f].data,g=d.id,k="";if(c[g])for(var k="",l=0;l<c[g].length;l++)c[g][l][this.summaryId]&&(k=k+"**"+c[g][l][this.summaryId]);else b[g]&&b[g][this.summaryId]&&(k=b[g][this.summaryId]);d[this.summarySaveId]=k;this.listGridData[g]&&(this.listGridData[g][this.disabledId]="true",this.listGridData[g][this.summarySaveId]=k,this.listGridData[g][this.summaryId]=
k)}a&&this.setValuesResumePanel(a.accountAmount,a.totalCharge,a.totalDebit);e.layout.setColumnVisibility(this._fci[this.totalAmountId],!0);e.layout.setColumnVisibility(this._fci[this.summaryId],!1);b=dijit.byId(this.btnNextId);c=dijit.byId(this.btnBackId);e=dijit.byId(this.btnSaveId);h=dijit.byId(this.btnCloseId);a=dijit.byId(this.btnCancelId);f=dijit.byId(this.btnPrintId);this._setNotVisible(a);this._setNotVisible(b);this._setNotVisible(c);this._setNotVisible(e);this._setVisible(f);this._setVisible(h);
setTimeout(m.hitch(this,"brokenGlass"),50)},brokenGlass:function(){this.getTxMDinamicGrid().layout.setColumnVisibility(this._fci[this.summaryId],!0)},setValuesResumePanel:function(a,b,c){this.model.accountAmount.set("value",a);this.model.totalCharge.set("value",b);this.model.totalDebit.set("value",c)},showErrorValidation:function(a){this.clearPanelMessage();a=this.generateMsg(a,"",4E4);this.updateMsgsPanel(a)},_setVisiblePanel:function(a){a.style="min-width:98%; display: inline-block";l.set(a.domNode,
"display","inline-block");a.resize()}})});
//@ sourceMappingURL=MultiplePaymentsController.js.map